EALib: PVMinterface.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
PVMinterface.cpp File Reference
This file serves as a dummy interface for the use of PVM with the EALib.
#include <EALib/PVMinterface.h>
#include <SharkDefs.h>
Functions
int pvm_joingroup (char *group)
int pvm_mytid ()
int pvm_gettid (char *group, int inum)
int pvm_initsend (int encoding)
int pvm_send (int tid, int msgtag)
int pvm_recv (int tid, int msgtag)
int pvm_pkdouble (double *dp, int nitem, int stride)
int pvm_pkuint (unsigned int *up, int nitem, int stride)
int pvm_pkint (int *ip, int nitem, int stride)
int pvm_pkbyte (char *xp, int nitem, int stride)
int pvm_upkdouble (double *dp, int nitem, int stride)
int pvm_upkuint (unsigned int *up, int nitem, int stride)
int pvm_upkint (int *ip, int nitem, int stride)
int pvm_upkbyte (char *xp, int nitem, int stride)
int pvm_probe (int tid, int msgtag)
int pvm_barrier (char *group, int count)
int pvm_exit ()
int pvm_getinst (char *group, int tid)
int pvm_bufinfo (int bufid, int *bytes, int *mstag, int *tid)
Detailed Description
This file serves as a dummy interface for the use of PVM with the EALib.
Exceptions:
SharkException
Author:
S. Wiegand
Copyright (c) 1999-2003:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
EALib
This file is part of EALib. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file PVMinterface.cpp.
Function Documentation
int pvm_barrier (char * group, int count)
Examples:
pvmSphereGA.cpp.
Definition at line 140 of file PVMinterface.cpp.
int pvm_bufinfo (int bufid, int * bytes, int * mstag, int * tid)
Examples:
pvmSphereGA.cpp.
Definition at line 158 of file PVMinterface.cpp.
int pvm_exit ()
Examples:
pvmSphereGA.cpp.
Definition at line 146 of file PVMinterface.cpp.
int pvm_getinst (char * group, int tid)
Definition at line 152 of file PVMinterface.cpp.
int pvm_gettid (char * group, int inum)
Examples:
pvmSphereGA.cpp.
Definition at line 62 of file PVMinterface.cpp.
int pvm_initsend (int encoding)
Examples:
pvmSphereGA.cpp.
Definition at line 68 of file PVMinterface.cpp.
int pvm_joingroup (char * group)
Examples:
pvmSphereGA.cpp.
Definition at line 50 of file PVMinterface.cpp.
int pvm_mytid ()
Examples:
pvmSphereGA.cpp.
Definition at line 56 of file PVMinterface.cpp.
int pvm_pkbyte (char * xp, int nitem, int stride)
Definition at line 104 of file PVMinterface.cpp.
Referenced by ChromosomeT< char >::pvm_pkchrom().
int pvm_pkdouble (double * dp, int nitem, int stride)
Definition at line 86 of file PVMinterface.cpp.
Referenced by ChromosomeT< double >::pvm_pkchrom(), ChromosomeCMA::pvm_pkchrom(), and Individual::pvm_pkind().
int pvm_pkint (int * ip, int nitem, int stride)
Definition at line 98 of file PVMinterface.cpp.
Referenced by ChromosomeT< int >::pvm_pkchrom().
int pvm_pkuint (unsigned int * up, int nitem, int stride)
Definition at line 92 of file PVMinterface.cpp.
Referenced by ChromosomeT< bool >::pvm_pkchrom(), ChromosomeT< int >::pvm_pkchrom(), ChromosomeT< char >::pvm_pkchrom(), ChromosomeT< double >::pvm_pkchrom(), ChromosomeCMA::pvm_pkchrom(), Individual::pvm_pkind(), Population::pvm_pkpop(), and ChromosomeCMA::pvm_upkchrom().
int pvm_probe (int tid, int msgtag)
Examples:
pvmSphereGA.cpp.
Definition at line 134 of file PVMinterface.cpp.
int pvm_recv (int tid, int msgtag)
Examples:
pvmSphereGA.cpp.
Definition at line 80 of file PVMinterface.cpp.
int pvm_send (int tid, int msgtag)
Examples:
pvmSphereGA.cpp.
Definition at line 74 of file PVMinterface.cpp.
int pvm_upkbyte (char * xp, int nitem, int stride)
Definition at line 128 of file PVMinterface.cpp.
Referenced by ChromosomeT< char >::pvm_upkchrom().
int pvm_upkdouble (double * dp, int nitem, int stride)
Definition at line 110 of file PVMinterface.cpp.
Referenced by ChromosomeT< double >::pvm_upkchrom(), ChromosomeCMA::pvm_upkchrom(), and Individual::pvm_upkind().
int pvm_upkint (int * ip, int nitem, int stride)
Definition at line 122 of file PVMinterface.cpp.
Referenced by ChromosomeT< int >::pvm_upkchrom().
int pvm_upkuint (unsigned int * up, int nitem, int stride)
Definition at line 116 of file PVMinterface.cpp.
Referenced by ChromosomeT< bool >::pvm_upkchrom(), ChromosomeT< int >::pvm_upkchrom(), ChromosomeT< char >::pvm_upkchrom(), ChromosomeT< double >::pvm_upkchrom(), Individual::pvm_upkind(), and Population::pvm_upkpop().