EALib: PVMinterface.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
PVMinterface.h File Reference
This file serves as a dummy interface for the use of PVM with the EALib.
#include <stdlib.h>
#include <iostream>
Defines
#define PvmDataDefault 0
Typedefs
typedef unsigned uint
Functions
int pvm_joingroup (char *)
int pvm_mytid ()
int pvm_gettid (char *, int)
int pvm_initsend (int)
int pvm_send (int, int)
int pvm_recv (int, int)
int pvm_pkdouble (double *, int, int)
int pvm_pkuint (uint *, int, int)
int pvm_pkint (int *, int, int)
int pvm_pkbyte (char *, int, int)
int pvm_upkdouble (double *, int, int)
int pvm_upkuint (uint *, int, int)
int pvm_upkint (int *, int, int)
int pvm_upkbyte (char *, int, int)
int pvm_probe (int, int)
int pvm_barrier (char *, int)
int pvm_exit ()
int pvm_getinst (char *, int)
int pvm_bufinfo (int, int *, int *, int *)
Detailed Description
This file serves as a dummy interface for the use of PVM with the EALib.
Author:
S. Wiegand
Date:
2003-01-01
Copyright (c) 1999-2003:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
EALib
This file is part of EALib. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file PVMinterface.h.
Define Documentation
#define PvmDataDefault 0
Examples:
pvmSphereGA.cpp.
Definition at line 47 of file PVMinterface.h.
Typedef Documentation
typedef unsigned uint
This file serves as a dummy interface for the use of PVM with the EALib. It reimplements basic PVM methods with default return error values due to calls implemented in Individual.h.
Definition at line 54 of file PVMinterface.h.
Function Documentation
int pvm_barrier (char * , int)
Definition at line 140 of file PVMinterface.cpp.
int pvm_bufinfo (int , int * , int * , int *)
Definition at line 158 of file PVMinterface.cpp.
int pvm_exit ()
Definition at line 146 of file PVMinterface.cpp.
int pvm_getinst (char * , int)
Definition at line 152 of file PVMinterface.cpp.
int pvm_gettid (char * , int)
Definition at line 62 of file PVMinterface.cpp.
int pvm_initsend (int)
Definition at line 68 of file PVMinterface.cpp.
int pvm_joingroup (char *)
Definition at line 50 of file PVMinterface.cpp.
int pvm_mytid ()
Definition at line 56 of file PVMinterface.cpp.
int pvm_pkbyte (char * , int , int)
Definition at line 104 of file PVMinterface.cpp.
Referenced by ChromosomeT< char >::pvm_pkchrom().
int pvm_pkdouble (double * , int , int)
Definition at line 86 of file PVMinterface.cpp.
Referenced by ChromosomeT< double >::pvm_pkchrom(), ChromosomeCMA::pvm_pkchrom(), and Individual::pvm_pkind().
int pvm_pkint (int * , int , int)
Definition at line 98 of file PVMinterface.cpp.
Referenced by ChromosomeT< int >::pvm_pkchrom().
int pvm_pkuint (uint * , int , int)
int pvm_probe (int , int)
Definition at line 134 of file PVMinterface.cpp.
int pvm_recv (int , int)
Definition at line 80 of file PVMinterface.cpp.
int pvm_send (int , int)
Definition at line 74 of file PVMinterface.cpp.
int pvm_upkbyte (char * , int , int)
Definition at line 128 of file PVMinterface.cpp.
Referenced by ChromosomeT< char >::pvm_upkchrom().
int pvm_upkdouble (double * , int , int)
Definition at line 110 of file PVMinterface.cpp.
Referenced by ChromosomeT< double >::pvm_upkchrom(), ChromosomeCMA::pvm_upkchrom(), and Individual::pvm_upkind().
int pvm_upkint (int * , int , int)
Definition at line 122 of file PVMinterface.cpp.
Referenced by ChromosomeT< int >::pvm_upkchrom().
int pvm_upkuint (uint * , int , int)