EALib: UncertaintyQuantification.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
UncertaintyQuantification.h File Reference
Uncertainty quantification for rank-based selection.
#include <SharkDefs.h>
#include <Array/Array.h>
#include <EALib/Population.h>
Classes
class NoisyFitnessFunction
Wrapper class, which allows to reevaluate objective functions and which counts the number of evaluations.
Functions
double UncertaintyQuantification (Population &p, NoisyFitnessFunction &f, double theta=0.2, double r_l=0.)
compute uncertainty level s
Detailed Description
Uncertainty quantification for rank-based selection.
Author:
T. Glasmachers, based on code by C. Igel
Date:
2008
based on
"A Method for Handling Uncertainty in Evolutionary Optimization with an Application to Feedback Control in Combustion" N. Hansen, A.S.P. Niederberger, L. Guzzella, and P. Koumoutsakos
Copyright (c) 2008:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
EALib
This file is part of ReClaM. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file UncertaintyQuantification.h.
Function Documentation
double UncertaintyQuantification (Population & p, NoisyFitnessFunction & f, double theta = 0.2, double r_l = 0.)
compute uncertainty level s
Definition at line 102 of file UncertaintyQuantification.cpp.
References deltaLimTheta(), NoisyFitnessFunction::fitness(), rankingObjectLessFitnessNew(), rankingObjectLessFitnessOld(), and Population::size().