EALib: UncertaintyQuantification.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
UncertaintyQuantification.cpp File Reference
Uncertainty quantification for rank-based selection.
#include <iomanip>
#include <vector>
#include <EALib/UncertaintyQuantification.h>
Classes
struct RankingObject
Functions
template<class T >
double percentile (std::vector< T > v, double p=.25)
bool rankingObjectLessFitnessOld (const RankingObject &x, const RankingObject &y)
bool rankingObjectLessFitnessNew (const RankingObject &x, const RankingObject &y)
double deltaLimTheta (unsigned R, unsigned l, double theta)
double UncertaintyQuantification (Population &p, NoisyFitnessFunction &f, double theta, double r_l)
compute uncertainty level s
Detailed Description
Uncertainty quantification for rank-based selection.
Author:
T. Glasmachers, based on code by C. Igel
Date:
2008
based on
"A Method for Handling Uncertainty in Evolutionary Optimization with an Application to Feedback Control in Combustion" N. Hansen, A.S.P. Niederberger, L. Guzzella, and P. Koumoutsakos
Copyright (c) 2008:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
EALib
This file is part of ReClaM. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file UncertaintyQuantification.cpp.
Function Documentation
double deltaLimTheta (unsigned R, unsigned l, double theta)
Definition at line 93 of file UncertaintyQuantification.cpp.
References percentile().
Referenced by UncertaintyQuantification().
template<class T > double percentile (std::vector< T > v, double p = .25)
Definition at line 56 of file UncertaintyQuantification.cpp.
Referenced by deltaLimTheta().
bool rankingObjectLessFitnessNew (const RankingObject & x, const RankingObject & y)
Definition at line 87 of file UncertaintyQuantification.cpp.
References RankingObject::fitnessNew.
Referenced by UncertaintyQuantification().
bool rankingObjectLessFitnessOld (const RankingObject & x, const RankingObject & y)
Definition at line 83 of file UncertaintyQuantification.cpp.
References RankingObject::fitnessOld.
Referenced by UncertaintyQuantification().
double UncertaintyQuantification (Population & p, NoisyFitnessFunction & f, double theta, double r_l)
compute uncertainty level s
Definition at line 102 of file UncertaintyQuantification.cpp.
References deltaLimTheta(), NoisyFitnessFunction::fitness(), rankingObjectLessFitnessNew(), rankingObjectLessFitnessOld(), and Population::size().