EALib: Interval Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Interval Class Reference
Interval [a, b] of the real numbers.
#include <Interval.h>
Public Member Functions
Interval ()
default constructor
Interval (double lo)
Constructor.
Interval (double lo, double hi)
Constructor.
double lowerBound () const
return lower interval end
double upperBound () const
return upper interval end
double width () const
return interval width
Detailed Description
Interval [a, b] of the real numbers.
Examples:
ackleyES.cpp, countingOnes.cpp, integerES.cpp, pvmSphereGA.cpp, sphereGA.cpp, and steadyState.cpp.
Definition at line 50 of file Interval.h.
Constructor & Destructor Documentation
Interval::Interval () [inline]
default constructor
Definition at line 61 of file Interval.h.
Interval::Interval (double lo) [inline]
Constructor.
Definition at line 67 of file Interval.h.
Interval::Interval (double lo, double hi) [inline]
Constructor.
Definition at line 73 of file Interval.h.
Member Function Documentation
double Interval::lowerBound () const [inline]
return lower interval end
Definition at line 79 of file Interval.h.
Referenced by ChromosomeT< bool >::decode(), ChromosomeT< double >::decodeBinary(), ChromosomeT< bool >::encode(), and ChromosomeT< bool >::encodeBinary().
double Interval::upperBound () const [inline]
return upper interval end
Definition at line 85 of file Interval.h.
double Interval::width () const [inline]
return interval width
Definition at line 91 of file Interval.h.
Referenced by ChromosomeT< bool >::decode(), ChromosomeT< double >::decodeBinary(), ChromosomeT< bool >::encode(), and ChromosomeT< bool >::encodeBinary().
The documentation for this class was generated from the following file:
Interval.h