EALib: ElitistCMA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ElitistCMA Class Reference
Implements the elitist version of the CMA-ES.
#include <ElitistCMA.h>
Static Public Member Functions
static void init (IndividualCT< ChromosomeCMA > &parent, double sigma, int lambda=1)
initialization of the elitist CMA
static void init (IndividualCT< ChromosomeCMA > &parent, const Array< double > &sigma, int lambda=1)
initialization of the elitist CMA with individual step sizes
static void Mutate (IndividualCT< ChromosomeCMA > &parent, PopulationCT< ChromosomeCMA > &offspring)
Overwrite the offspring population with mutations of the parent.
static void SelectAndUpdateStrategyParameters (IndividualCT< ChromosomeCMA > &parent, PopulationCT< ChromosomeCMA > &offspring)
Update of the CMA search strategy.
Detailed Description
Implements the elitist version of the CMA-ES.
The ElitistCMA class is a simple implementation of the elitist CMA. However, Most of the work is done by the ChromosomeCMA class.
Definition at line 51 of file ElitistCMA.h.
Member Function Documentation
void ElitistCMA::init (IndividualCT< ChromosomeCMA > & parent, double sigma, int lambda = 1) [static]
initialization of the elitist CMA
Parameters:
parent parent individual with ChromosoleCMA as its first chromosome
sigma initial step width
lambda size of the offspring population
Definition at line 42 of file ElitistCMA.cpp.
void ElitistCMA::init (IndividualCT< ChromosomeCMA > & parent, const Array< double > & sigma, int lambda = 1) [static]
initialization of the elitist CMA with individual step sizes
Parameters:
parent parent individual with ChromosoleCMA as its first chromosome
sigma initial step width for each coordinate
lambda size of the offspring population
Definition at line 50 of file ElitistCMA.cpp.
References Individual::size().
void ElitistCMA::Mutate (IndividualCT< ChromosomeCMA > & parent, PopulationCT< ChromosomeCMA > & offspring) [static]
Overwrite the offspring population with mutations of the parent.
Parameters:
parent parent individual
offspring population of new offspring
Definition at line 60 of file ElitistCMA.cpp.
References Population::size().
void ElitistCMA::SelectAndUpdateStrategyParameters (IndividualCT< ChromosomeCMA > & parent, PopulationCT< ChromosomeCMA > & offspring) [static]
Update of the CMA search strategy.
It is assumed that all individuals, that is, parent and offspring, have a valid fitness value.
Parameters:
parent parent individual
offspring offspring population
Definition at line 71 of file ElitistCMA.cpp.
References Individual::getFitness(), and Population::size().
The documentation for this class was generated from the following files:
ElitistCMA.h
ElitistCMA.cpp