EALib: PopulationCT< CT > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
PopulationCT< CT > Class Template Reference
Population with uniform chromosome type CT.
#include <PopulationT.h>
Public Member Functions
PopulationCT ()
PopulationCT (unsigned n)
PopulationCT (unsigned n, unsigned m)
create a population of n individuals with m chromosomes each
PopulationCT (const IndividualCT< CT > &ind)
PopulationCT (unsigned n, const IndividualCT< CT > &ind)
PopulationCT (unsigned n, const CT &c0)
PopulationCT (unsigned n, const CT &c0, const CT &c1)
PopulationCT (unsigned n, const std::vector< CT * > &v)
PopulationCT (const PopulationCT< CT > &pop)
PopulationCT (const std::vector< IndividualCT< CT > * > &v)
~PopulationCT ()
IndividualCT< CT > & operator[] (unsigned i)
const IndividualCT< CT > & operator[] (unsigned i) const
PopulationCT< CT > operator() (unsigned from, unsigned to) const
PopulationCT< CT > & operator= (const IndividualCT< CT > &ind)
PopulationCT< CT > & operator= (const PopulationCT< CT > &pop)
IndividualCT< CT > & oneOfBest ()
const IndividualCT< CT > & oneOfBest () const
IndividualCT< CT > & best ()
const IndividualCT< CT > & best () const
IndividualCT< CT > & worst ()
const IndividualCT< CT > & worst () const
IndividualCT< CT > & random ()
const IndividualCT< CT > & random () const
IndividualCT< CT > & selectOneIndividual ()
Detailed Description
template<typename CT>
class PopulationCT< CT >
Population with uniform chromosome type CT.
Definition at line 51 of file PopulationT.h.
Constructor & Destructor Documentation
template<typename CT> PopulationCT< CT >::PopulationCT () [inline]
Definition at line 54 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (unsigned n) [inline, explicit]
Definition at line 57 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (unsigned n, unsigned m) [inline]
create a population of n individuals with m chromosomes each
Definition at line 66 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (const IndividualCT< CT > & ind) [inline]
Definition at line 72 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (unsigned n, const IndividualCT< CT > & ind) [inline]
Definition at line 77 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (unsigned n, const CT & c0) [inline]
Definition at line 83 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (unsigned n, const CT & c0, const CT & c1) [inline]
Definition at line 89 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (unsigned n, const std::vector< CT * > & v) [inline]
Definition at line 96 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (const PopulationCT< CT > & pop) [inline]
Definition at line 102 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::PopulationCT (const std::vector< IndividualCT< CT > * > & v) [inline]
Definition at line 110 of file PopulationT.h.
template<typename CT> PopulationCT< CT >::~PopulationCT () [inline]
Definition at line 118 of file PopulationT.h.
Member Function Documentation
template<typename CT> IndividualCT<CT>& PopulationCT< CT >::best () [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 159 of file PopulationT.h.
Referenced by PopulationCT< ChromosomeT< T > >::best().
template<typename CT> const IndividualCT<CT>& PopulationCT< CT >::best () const [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 163 of file PopulationT.h.
template<typename CT> IndividualCT<CT>& PopulationCT< CT >::oneOfBest () [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 149 of file PopulationT.h.
Referenced by PopulationCT< ChromosomeT< T > >::oneOfBest().
template<typename CT> const IndividualCT<CT>& PopulationCT< CT >::oneOfBest () const [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 154 of file PopulationT.h.
template<typename CT> PopulationCT<CT> PopulationCT< CT >::operator() (unsigned from, unsigned to) const [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 130 of file PopulationT.h.
template<typename CT> PopulationCT<CT>& PopulationCT< CT >::operator= (const IndividualCT< CT > & ind) [inline]
Definition at line 137 of file PopulationT.h.
Referenced by PopulationCT< ChromosomeT< T > >::operator=().
template<typename CT> PopulationCT<CT>& PopulationCT< CT >::operator= (const PopulationCT< CT > & pop) [inline]
Definition at line 143 of file PopulationT.h.
template<typename CT> const IndividualCT<CT>& PopulationCT< CT >::operator[] (unsigned i) const [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 126 of file PopulationT.h.
template<typename CT> IndividualCT<CT>& PopulationCT< CT >::operator[] (unsigned i) [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 121 of file PopulationT.h.
template<typename CT> const IndividualCT<CT>& PopulationCT< CT >::random () const [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 181 of file PopulationT.h.
template<typename CT> IndividualCT<CT>& PopulationCT< CT >::random () [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 177 of file PopulationT.h.
Referenced by PopulationCT< ChromosomeT< T > >::random().
template<typename CT> IndividualCT<CT>& PopulationCT< CT >::selectOneIndividual () [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 186 of file PopulationT.h.
Referenced by PopulationCT< ChromosomeT< T > >::selectOneIndividual().
template<typename CT> IndividualCT<CT>& PopulationCT< CT >::worst () [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 168 of file PopulationT.h.
Referenced by PopulationCT< ChromosomeT< T > >::worst().
template<typename CT> const IndividualCT<CT>& PopulationCT< CT >::worst () const [inline]
Reimplemented from Population.
Reimplemented in PopulationT< T >, and PopulationT< double >.
Definition at line 172 of file PopulationT.h.
The documentation for this class was generated from the following file:
PopulationT.h