EALib: CMSASearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CMSASearch Class Reference
Non-elitist CMSA-ES implementing the interface EvolutionaryAlgorithm.
#include <CMSA.h>
Public Member Functions
CMSASearch ()
~CMSASearch ()
CMSA & getCMSA ()
const CMSA & getCMSA () const
const PopulationT< double > * parents () const
const PopulationT< double > * offspring () const
void init (ObjectiveFunctionVS< double > &fitness, unsigned lambda=0, CMSA::RecombType recomb=CMSA::equal)
void init (ObjectiveFunctionVS< double > &fitness, const Array< double > &start, double stepsize, unsigned lambda=0, CMSA::RecombType recomb=CMSA::equal)
void run ()
main interface: perform one iteration of the search algorithm
void bestSolutions (std::vector< double * > &points)
return the current set of pareto-optimal solutions
void bestSolutionsFitness (Array< double > &fitness)
Return a two-dimensional array of fitness values.
Protected Attributes
CMSA m_cma
ObjectiveFunctionVS< double > * m_fitness
PopulationT< double > * m_parents
PopulationT< double > * m_offspring
Detailed Description
Non-elitist CMSA-ES implementing the interface EvolutionaryAlgorithm.
Examples:
SchwefelEllipsoidCMSA.cpp.
Definition at line 112 of file CMSA.h.
Constructor & Destructor Documentation
CMSASearch::CMSASearch ()
Definition at line 241 of file CMSA.cpp.
References SearchAlgorithmBase::m_name, m_offspring, and m_parents.
CMSASearch::~CMSASearch ()
Definition at line 249 of file CMSA.cpp.
References m_offspring, and m_parents.
Member Function Documentation
void CMSASearch::bestSolutions (std::vector< double * > & points) [virtual]
return the current set of pareto-optimal solutions
Implements SearchAlgorithm< double * >.
Definition at line 350 of file CMSA.cpp.
void CMSASearch::bestSolutionsFitness (Array< double > & fitness) [virtual]
Return a two-dimensional array of fitness values.
The first dimension corresponds to the solution, while the second dimension corresponds to the objective.
Implements SearchAlgorithm< double * >.
Definition at line 356 of file CMSA.cpp.
const CMSA& CMSASearch::getCMSA () const [inline]
Definition at line 119 of file CMSA.h.
References m_cma.
CMSA& CMSASearch::getCMSA () [inline]
Definition at line 118 of file CMSA.h.
References m_cma.
void CMSASearch::init (ObjectiveFunctionVS< double > & fitness, unsigned lambda = 0, CMSA::RecombType recomb = CMSA::equal)
Examples:
SchwefelEllipsoidCMSA.cpp.
Definition at line 256 of file CMSA.cpp.
References ObjectiveFunctionVS< T >::dimension(), CMSA::init(), EvolutionaryAlgorithm< double * >::lambda(), m_cma, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, ObjectiveFunctionVS< T >::ProposeStartingPoint(), Population::setMinimize(), CMSA::suggestLambda(), and CMSA::suggestMu().
void CMSASearch::init (ObjectiveFunctionVS< double > & fitness, const Array< double > & start, double stepsize, unsigned lambda = 0, CMSA::RecombType recomb = CMSA::equal)
Definition at line 300 of file CMSA.cpp.
References ObjectiveFunctionVS< T >::dimension(), CMSA::init(), EvolutionaryAlgorithm< double * >::lambda(), m_cma, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, Population::setMinimize(), CMSA::suggestLambda(), and CMSA::suggestMu().
const PopulationT<double>* CMSASearch::offspring () const [inline]
Definition at line 121 of file CMSA.h.
References m_offspring.
const PopulationT<double>* CMSASearch::parents () const [inline]
Definition at line 120 of file CMSA.h.
References m_parents.
void CMSASearch::run () [virtual]
main interface: perform one iteration of the search algorithm
Reimplemented from SearchAlgorithm< double * >.
Examples:
SchwefelEllipsoidCMSA.cpp.
Definition at line 329 of file CMSA.cpp.
References ObjectiveFunctionVS< T >::closestFeasible(), CMSA::create(), ObjectiveFunctionVS< T >::isFeasible(), m_cma, m_fitness, m_offspring, m_parents, Population::selectMuLambda(), Population::size(), and CMSA::updateStrategyParameters().
Member Data Documentation
CMSA CMSASearch::m_cma [protected]
Definition at line 130 of file CMSA.h.
Referenced by getCMSA(), init(), and run().
ObjectiveFunctionVS<double>* CMSASearch::m_fitness [protected]
Definition at line 131 of file CMSA.h.
Referenced by init(), and run().
PopulationT<double>* CMSASearch::m_offspring [protected]
Definition at line 133 of file CMSA.h.
Referenced by CMSASearch(), init(), offspring(), run(), and ~CMSASearch().
PopulationT<double>* CMSASearch::m_parents [protected]
Definition at line 132 of file CMSA.h.
Referenced by CMSASearch(), init(), parents(), run(), and ~CMSASearch().
The documentation for this class was generated from the following files:
CMSA.h
CMSA.cpp