EALib: SearchAlgorithm< T > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SearchAlgorithm< T > Class Template Reference
Search algorithm template with flexible search space.
#include <SearchAlgorithm.h>
Public Member Functions
SearchAlgorithm ()
Constructor.
~SearchAlgorithm ()
Destructor.
virtual void run ()
main interface: perform one iteration of the search algorithm
void runN (unsigned int iter)
perform #iter iterations by calling Run() #iter times
virtual void bestSolutions (std::vector< T > &points)=0
return the current set of pareto-optimal solutions
virtual void bestSolutionsFitness (Array< double > &fitness)=0
Return a two-dimensional array of fitness values.
T bestSolution ()
return the best solution (for a single-objective task)
double bestSolutionFitness ()
return the best fitness (for a single-objective task)
Detailed Description
template<class T>
class SearchAlgorithm< T >
Search algorithm template with flexible search space.
The SearchAlgorithm template class represents an abstract search algorithm for search on the space represented by the template type T. The search is guided by a single- or multi- objective fitness function, defined on this space.
Definition at line 84 of file SearchAlgorithm.h.
Constructor & Destructor Documentation
template<class T> SearchAlgorithm< T >::SearchAlgorithm () [inline]
Constructor.
Definition at line 88 of file SearchAlgorithm.h.
template<class T> SearchAlgorithm< T >::~SearchAlgorithm () [inline]
Destructor.
Definition at line 91 of file SearchAlgorithm.h.
Member Function Documentation
template<class T> T SearchAlgorithm< T >::bestSolution () [inline]
return the best solution (for a single-objective task)
Definition at line 112 of file SearchAlgorithm.h.
template<class T> double SearchAlgorithm< T >::bestSolutionFitness () [inline]
return the best fitness (for a single-objective task)
Definition at line 120 of file SearchAlgorithm.h.
template<class T> virtual void SearchAlgorithm< T >::bestSolutions (std::vector< T > & points) [pure virtual]
return the current set of pareto-optimal solutions
Implemented in CMASearch, CMSASearch, CMAElitistSearch, and OnePlusOneES.
Referenced by SearchAlgorithm< double * >::bestSolution().
template<class T> virtual void SearchAlgorithm< T >::bestSolutionsFitness (Array< double > & fitness) [pure virtual]
Return a two-dimensional array of fitness values.
The first dimension corresponds to the solution, while the second dimension corresponds to the objective.
Implemented in CMASearch, CMSASearch, CMAElitistSearch, and OnePlusOneES.
Referenced by SearchAlgorithm< double * >::bestSolutionFitness().
template<class T> virtual void SearchAlgorithm< T >::run () [inline, virtual]
main interface: perform one iteration of the search algorithm
Reimplemented in CMASearch, CMSASearch, CMAElitistSearch, and OnePlusOneES.
Definition at line 95 of file SearchAlgorithm.h.
Referenced by SearchAlgorithm< double * >::runN().
template<class T> void SearchAlgorithm< T >::runN (unsigned int iter) [inline]
perform #iter iterations by calling Run() #iter times
Definition at line 98 of file SearchAlgorithm.h.
The documentation for this class was generated from the following file:
SearchAlgorithm.h