EALib: ChromosomeT< double > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ChromosomeT< double > Class Template Reference
chromosome based on double numbers
#include <ChromosomeT.h>
Public Member Functions
ChromosomeT ()
ChromosomeT (unsigned l)
ChromosomeT (unsigned l, const double &v)
ChromosomeT (const std::vector< double > &v)
~ChromosomeT ()
void initializeRotate (const ChromosomeT< double > &)
void initializeRotate (const std::vector< double > &)
void initializeRotate (double, double)
void showRotate ()
void decodeBinary (const Chromosome &chrom, const Interval &range, unsigned nbits, bool useGray=false)
void accumulate (const std::vector< double > &, double)
void accumulate (const Chromosome &, double)
void mutateCauchy (double scale)
void mutateCauchy (const std::vector< double > &scale, bool=false)
void mutateCauchy (const Chromosome &scale, bool=false)
void mutateCauchy (const ChromosomeT< double > &scale, bool=false)
void mutateNormal (double variance)
void mutateNormal (const std::vector< double > &variances, bool=false)
void mutateNormal (const Chromosome &variances, bool=false)
void mutateNormal (const ChromosomeT< double > &variances, bool=false)
void mutateNormalRotAngles (const std::vector< double > &, const std::vector< double > &)
void mutateNormalRotAngles (const Chromosome &, const Chromosome &)
void mutateLogNormal (double, double)
void mutateMSR (double)
void mutateRotate (ChromosomeT< double > &)
void mutateRotate (ChromosomeT< double > &, double, double, double, int, double)
void recombineIntermediate (const Chromosome &, const Chromosome &)
void recombineGenIntermediate (const Chromosome &, const Chromosome &)
void recombineGeomIntermediate (const Chromosome &, const Chromosome &)
void recombineIntermediate (Chromosome &)
void recombineGenIntermediate (Chromosome &)
void recombineGeomIntermediate (Chromosome &)
void SBX (ChromosomeT< double > &, double, double=.5)
void SBX (ChromosomeT< double > &, double, double, double, double=.5, double=1.E-12)
void SBX (ChromosomeT< double > &, std::vector< double > &, std::vector< double > &, double, double=.5, double=1.E-12)
void simpleMutatePolynomial (double, double, double, double)
void simpleMutatePolynomial (std::vector< double > &, std::vector< double > &, double, double)
void mutatePolynomial (double, double, double, double)
void mutatePolynomial (std::vector< double > &, std::vector< double > &, double, double)
Protected Member Functions
Chromosome * clone () const
Chromosome * empty () const
int pvm_pkchrom ()
int pvm_upkchrom ()
void writeTo (std::ostream &os) const
void readFrom (std::istream &is)
Detailed Description
template<>
class ChromosomeT< double >
chromosome based on double numbers
Examples:
ackleyES.cpp, integerES.cpp, pvmSphereGA.cpp, sphereGA.cpp, and steadyState.cpp.
Definition at line 1182 of file ChromosomeT.h.
Constructor & Destructor Documentation
ChromosomeT< double >::ChromosomeT () [inline]
Definition at line 1185 of file ChromosomeT.h.
ChromosomeT< double >::ChromosomeT (unsigned l) [inline, explicit]
Definition at line 1187 of file ChromosomeT.h.
ChromosomeT< double >::ChromosomeT (unsigned l, const double & v) [inline]
Definition at line 1190 of file ChromosomeT.h.
ChromosomeT< double >::ChromosomeT (const std::vector< double > & v) [inline]
Definition at line 1193 of file ChromosomeT.h.
ChromosomeT< double >::~ChromosomeT ()
Definition at line 48 of file ChromosomeT_double.cpp.
Member Function Documentation
void ChromosomeT< double >::accumulate (const std::vector< double > & acc, double c)
Definition at line 88 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::accumulate (const Chromosome & acc, double c)
Definition at line 98 of file ChromosomeT_double.cpp.
Chromosome* ChromosomeT< double >::clone () const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< double >.
Reimplemented in ChromosomeCMA, and ChromosomeCMACholesky.
Definition at line 1250 of file ChromosomeT.h.
void ChromosomeT< double >::decodeBinary (const Chromosome & chrom, const Interval & range, unsigned nbits, bool useGray = false)
Examples:
pvmSphereGA.cpp, sphereGA.cpp, and steadyState.cpp.
Definition at line 58 of file ChromosomeT_double.cpp.
References Interval::lowerBound(), pow2(), ChromosomeT_base< T >::resize(), ChromosomeT_base< T >::size(), Chromosome::size(), and Interval::width().
Chromosome* ChromosomeT< double >::empty () const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< double >.
Reimplemented in ChromosomeCMA, and ChromosomeCMACholesky.
Definition at line 1254 of file ChromosomeT.h.
void ChromosomeT< double >::initializeRotate (const ChromosomeT< double > & sigma)
Definition at line 438 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::initializeRotate (const std::vector< double > & sigma)
Definition at line 447 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::initializeRotate (double SigmaMin, double SigmaMax)
Definition at line 421 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::mutateCauchy (double scale)
Definition at line 139 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateCauchy (const std::vector< double > & scale, bool cycle = false)
Definition at line 147 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateCauchy (const Chromosome & scale, bool cycle = false)
Definition at line 166 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::mutateCauchy (const ChromosomeT< double > & scale, bool cycle = false)
Definition at line 158 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::mutateLogNormal (double overallVariance, double indivVariance)
Definition at line 224 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateMSR (double xi_prob)
Definition at line 485 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateNormal (double variance)
Definition at line 105 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateNormal (const std::vector< double > & variances, bool cycle = false)
Definition at line 113 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateNormal (const Chromosome & variances, bool cycle = false)
Definition at line 131 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::mutateNormal (const ChromosomeT< double > & variances, bool cycle = false)
Definition at line 123 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::mutateNormalRotAngles (const std::vector< double > & sigma_sqr, const std::vector< double > & alpha)
Definition at line 184 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateNormalRotAngles (const Chromosome & sigma, const Chromosome & alpha)
Definition at line 174 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::mutatePolynomial (double lower, double upper, double nm, double p)
Definition at line 723 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutatePolynomial (std::vector< double > & lower, std::vector< double > & upper, double nm, double p)
Definition at line 771 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateRotate (ChromosomeT< double > & sigma)
Definition at line 337 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::mutateRotate (ChromosomeT< double > & sigma_sqr, double tau1, double tau2, double beta, int sigmaCheck, double epsi)
Definition at line 352 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
int ChromosomeT< double >::pvm_pkchrom () [inline, protected, virtual]
Part of PVM-send routine for type double Chromosomes
Reimplemented from Chromosome.
Reimplemented in ChromosomeCMA.
Definition at line 1261 of file ChromosomeT.h.
References pvm_pkdouble(), pvm_pkuint(), and ChromosomeT_base< T >::size().
int ChromosomeT< double >::pvm_upkchrom () [inline, protected, virtual]
Part of PVM-receive routine for type double Chromosomes
Reimplemented from Chromosome.
Reimplemented in ChromosomeCMA.
Definition at line 1282 of file ChromosomeT.h.
References pvm_upkdouble(), pvm_upkuint(), and ChromosomeT_base< T >::size().
void ChromosomeT< double >::readFrom (std::istream & is) [inline, protected, virtual]
Reimplemented from ChromosomeT_base< double >.
Definition at line 1314 of file ChromosomeT.h.
References ChromosomeT_base< T >::resize(), and ChromosomeT_base< T >::size().
void ChromosomeT< double >::recombineGenIntermediate (const Chromosome & dadChrom, const Chromosome & momChrom)
Definition at line 255 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::resize(), ChromosomeT_base< T >::size(), and Chromosome::size().
void ChromosomeT< double >::recombineGenIntermediate (Chromosome & mate)
Definition at line 305 of file ChromosomeT_double.cpp.
References Chromosome::size(), and ChromosomeT_base< T >::size().
void ChromosomeT< double >::recombineGeomIntermediate (const Chromosome & dadChrom, const Chromosome & momChrom)
Definition at line 274 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::resize(), ChromosomeT_base< T >::size(), and Chromosome::size().
void ChromosomeT< double >::recombineGeomIntermediate (Chromosome & mate)
Definition at line 324 of file ChromosomeT_double.cpp.
References Chromosome::size(), and ChromosomeT_base< T >::size().
void ChromosomeT< double >::recombineIntermediate (Chromosome & mate)
Definition at line 290 of file ChromosomeT_double.cpp.
References Chromosome::size(), and ChromosomeT_base< T >::size().
void ChromosomeT< double >::recombineIntermediate (const Chromosome & dadChrom, const Chromosome & momChrom)
Definition at line 236 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::resize(), ChromosomeT_base< T >::size(), and Chromosome::size().
void ChromosomeT< double >::SBX (ChromosomeT< double > & mate, std::vector< double > & lower, std::vector< double > & upper, double nc, double p = .5, double epsilon = 1.E-12)
Definition at line 607 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::SBX (ChromosomeT< double > & mate, double nc, double p = .5)
Definition at line 502 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::SBX (ChromosomeT< double > & mate, double lower, double upper, double nc, double p = .5, double epsilon = 1.E-12)
Definition at line 530 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::showRotate ()
Definition at line 459 of file ChromosomeT_double.cpp.
void ChromosomeT< double >::simpleMutatePolynomial (double lower, double upper, double nm, double p)
Definition at line 686 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::simpleMutatePolynomial (std::vector< double > & lower, std::vector< double > & upper, double nm, double p)
Definition at line 704 of file ChromosomeT_double.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< double >::writeTo (std::ostream & os) const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< double >.
Definition at line 1303 of file ChromosomeT.h.
References ChromosomeT_base< T >::size().
The documentation for this class was generated from the following files:
ChromosomeT.h
ChromosomeT_double.cpp