EALib: CMAElitistSearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CMAElitistSearch Class Reference
Elitist CMA-ES that implements the interface EvolutionaryAlgorithm.
#include <ElitistCMA.h>
Public Member Functions
CMAElitistSearch ()
~CMAElitistSearch ()
const PopulationCT
< ChromosomeCMA > * parents () const
const PopulationCT
< ChromosomeCMA > * offspring () const
void init (ObjectiveFunctionVS< double > &fitness, unsigned int lambda=1)
void init (ObjectiveFunctionVS< double > &fitness, const Array< double > &start, double stepsize, unsigned int lambda=1)
void run ()
main interface: perform one iteration of the search algorithm
void bestSolutions (std::vector< double * > &points)
return the current set of pareto-optimal solutions
void bestSolutionsFitness (Array< double > &fitness)
Return a two-dimensional array of fitness values.
Protected Attributes
ObjectiveFunctionVS< double > * m_fitness
PopulationCT< ChromosomeCMA > * m_parents
PopulationCT< ChromosomeCMA > * m_offspring
bool m_bIsParentFitnessValid
Detailed Description
Elitist CMA-ES that implements the interface EvolutionaryAlgorithm.
Definition at line 93 of file ElitistCMA.h.
Constructor & Destructor Documentation
CMAElitistSearch::CMAElitistSearch ()
Definition at line 101 of file ElitistCMA.cpp.
References SearchAlgorithmBase::m_name, m_offspring, and m_parents.
CMAElitistSearch::~CMAElitistSearch ()
Definition at line 109 of file ElitistCMA.cpp.
References m_offspring, and m_parents.
Member Function Documentation
void CMAElitistSearch::bestSolutions (std::vector< double * > & points) [virtual]
return the current set of pareto-optimal solutions
Implements SearchAlgorithm< double * >.
Definition at line 222 of file ElitistCMA.cpp.
void CMAElitistSearch::bestSolutionsFitness (Array< double > & fitness) [virtual]
Return a two-dimensional array of fitness values.
The first dimension corresponds to the solution, while the second dimension corresponds to the objective.
Implements SearchAlgorithm< double * >.
Definition at line 228 of file ElitistCMA.cpp.
void CMAElitistSearch::init (ObjectiveFunctionVS< double > & fitness, const Array< double > & start, double stepsize, unsigned int lambda = 1)
Definition at line 155 of file ElitistCMA.cpp.
References ObjectiveFunctionVS< T >::dimension(), EvolutionaryAlgorithm< double * >::lambda(), m_bIsParentFitnessValid, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, and Population::setMinimize().
void CMAElitistSearch::init (ObjectiveFunctionVS< double > & fitness, unsigned int lambda = 1)
Definition at line 116 of file ElitistCMA.cpp.
References ObjectiveFunctionVS< T >::dimension(), EvolutionaryAlgorithm< double * >::lambda(), m_bIsParentFitnessValid, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, ObjectiveFunctionVS< T >::ProposeStartingPoint(), and Population::setMinimize().
const PopulationCT<ChromosomeCMA>* CMAElitistSearch::offspring () const [inline]
Definition at line 100 of file ElitistCMA.h.
References m_offspring.
const PopulationCT<ChromosomeCMA>* CMAElitistSearch::parents () const [inline]
Definition at line 99 of file ElitistCMA.h.
References m_parents.
void CMAElitistSearch::run () [virtual]
main interface: perform one iteration of the search algorithm
Reimplemented from SearchAlgorithm< double * >.
Definition at line 186 of file ElitistCMA.cpp.
References Individual::getFitness(), ObjectiveFunctionVS< T >::isFeasible(), m_bIsParentFitnessValid, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, m_offspring, m_parents, ObjectiveFunctionVS< T >::ProposeStartingPoint(), and Individual::setFitness().
Member Data Documentation
bool CMAElitistSearch::m_bIsParentFitnessValid [protected]
Definition at line 112 of file ElitistCMA.h.
Referenced by init(), and run().
ObjectiveFunctionVS<double>* CMAElitistSearch::m_fitness [protected]
Definition at line 109 of file ElitistCMA.h.
Referenced by init(), and run().
PopulationCT<ChromosomeCMA>* CMAElitistSearch::m_offspring [protected]
Definition at line 111 of file ElitistCMA.h.
Referenced by CMAElitistSearch(), init(), offspring(), run(), and ~CMAElitistSearch().
PopulationCT<ChromosomeCMA>* CMAElitistSearch::m_parents [protected]
Definition at line 110 of file ElitistCMA.h.
Referenced by CMAElitistSearch(), init(), parents(), run(), and ~CMAElitistSearch().
The documentation for this class was generated from the following files:
ElitistCMA.h
ElitistCMA.cpp