EALib: ELLI2 Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ELLI2 Class Reference
multi-objective problem ELLI2
#include <MultiObjectiveFunctions.h>
Public Member Functions
ELLI2 (unsigned d=10, double a=1000)
Constructor.
~ELLI2 ()
Destructor.
unsigned int objectives () const
return the number of objectives to optimize
void result (double *const &point, std::vector< double > &value)
objective function evaluation
bool ProposeStartingPoint (double *&point) const
For a BoxConstraintHandler we can automatically propose a starting point.
void initRandomRotation ()
Create a random orthogonal transformation.
Protected Member Functions
void transform_1 (const double *in, std::vector< double > &out) const
transform #in with m_Transformation_1, resulting in #out
void transform_2 (const double *in, std::vector< double > &out) const
transform #in with m_Transformation_2, resulting in #out
Protected Attributes
double m_a
Matrix m_Transformation_1
transformation matrix for the first objective function
Matrix m_Transformation_2
transformation matrix for the secound objective function
Detailed Description
multi-objective problem ELLI2
where y and z are defined by:
where and are arbitrary orthogonal rotation matrices and usually and
Definition at line 1602 of file MultiObjectiveFunctions.h.
Constructor & Destructor Documentation
ELLI2::ELLI2 (unsigned d = 10, double a = 1000)
Constructor.
Definition at line 2645 of file MultiObjectiveFunctions.cpp.
References initRandomRotation(), m_a, and ObjectiveFunction::m_name.
ELLI2::~ELLI2 ()
Destructor.
Definition at line 2652 of file MultiObjectiveFunctions.cpp.
Member Function Documentation
void ELLI2::initRandomRotation ()
Create a random orthogonal transformation.
Definition at line 2697 of file MultiObjectiveFunctions.cpp.
References ObjectiveFunctionVS< double >::m_dimension, m_Transformation_1, and m_Transformation_2.
Referenced by ELLI2().
unsigned int ELLI2::objectives () const [virtual]
return the number of objectives to optimize
Implements ObjectiveFunction.
Definition at line 2656 of file MultiObjectiveFunctions.cpp.
bool ELLI2::ProposeStartingPoint (double *& point) const [virtual]
For a BoxConstraintHandler we can automatically propose a starting point.
Reimplemented from ObjectiveFunctionVS< double >.
Definition at line 2688 of file MultiObjectiveFunctions.cpp.
References ObjectiveFunctionVS< double >::m_dimension.
void ELLI2::result (double *const & point, std::vector< double > & value) [virtual]
objective function evaluation
Implements ObjectiveFunctionT< double * >.
Definition at line 2661 of file MultiObjectiveFunctions.cpp.
References m_a, ObjectiveFunctionVS< double >::m_dimension, ObjectiveFunction::m_timesCalled, transform_1(), and transform_2().
void ELLI2::transform_1 (const double * in, std::vector< double > & out) const [protected]
transform #in with m_Transformation_1, resulting in #out
Definition at line 2740 of file MultiObjectiveFunctions.cpp.
References ObjectiveFunctionVS< double >::m_dimension, and m_Transformation_1.
Referenced by result().
void ELLI2::transform_2 (const double * in, std::vector< double > & out) const [protected]
transform #in with m_Transformation_2, resulting in #out
Definition at line 2752 of file MultiObjectiveFunctions.cpp.
References ObjectiveFunctionVS< double >::m_dimension, and m_Transformation_2.
Referenced by result().
Member Data Documentation
double ELLI2::m_a [protected]
Definition at line 1624 of file MultiObjectiveFunctions.h.
Referenced by ELLI2(), and result().
Matrix ELLI2::m_Transformation_1 [protected]
transformation matrix for the first objective function
Definition at line 1626 of file MultiObjectiveFunctions.h.
Referenced by initRandomRotation(), and transform_1().
Matrix ELLI2::m_Transformation_2 [protected]
transformation matrix for the secound objective function
Definition at line 1628 of file MultiObjectiveFunctions.h.
Referenced by initRandomRotation(), and transform_2().
The documentation for this class was generated from the following files:
MultiObjectiveFunctions.h
MultiObjectiveFunctions.cpp