EALib: ChromosomeCMA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ChromosomeCMA Class Reference
Elitist CMA evolution strategy.
#include <ChromosomeCMA.h>
Public Member Functions
ChromosomeCMA ()
ChromosomeCMA (unsigned l)
ChromosomeCMA (unsigned l, const double &v)
ChromosomeCMA (const std::vector< double > &v)
~ChromosomeCMA ()
void init (unsigned dimension, std::vector< double > stdv, double initialSigma, ChromosomeT< double > &MinInit, ChromosomeT< double > &MaxInit, int noOffspring=1, double lower=0.)
void init (unsigned dimension, double initialSigma, double MinInit, double MaxInit, int lambda=1)
void mutate ()
void updateGlobalStepsize ()
void updateLambdaSucc (bool better)
void updateGlobalStepsize (double nsucc)
void updateCovariance (Individual &parent)
void updateCovariance ()
const Array< double > & getC () const
double getSigma () const
double getCondition () const
void setLower (double lower)
bool covarianceUpdateNeeded ()
Protected Member Functions
Chromosome * clone () const
Chromosome * empty () const
int pvm_pkchrom ()
int pvm_upkchrom ()
Detailed Description
Elitist CMA evolution strategy.
Definition at line 67 of file ChromosomeCMA.h.
Constructor & Destructor Documentation
ChromosomeCMA::ChromosomeCMA () [inline]
Definition at line 70 of file ChromosomeCMA.h.
Referenced by clone(), and empty().
ChromosomeCMA::ChromosomeCMA (unsigned l) [inline, explicit]
Definition at line 72 of file ChromosomeCMA.h.
ChromosomeCMA::ChromosomeCMA (unsigned l, const double & v) [inline]
Definition at line 74 of file ChromosomeCMA.h.
ChromosomeCMA::ChromosomeCMA (const std::vector< double > & v) [inline]
Definition at line 76 of file ChromosomeCMA.h.
ChromosomeCMA::~ChromosomeCMA () [inline]
Definition at line 78 of file ChromosomeCMA.h.
Member Function Documentation
Chromosome* ChromosomeCMA::clone () const [inline, protected, virtual]
Reimplemented from ChromosomeT< double >.
Definition at line 267 of file ChromosomeCMA.h.
References ChromosomeCMA().
bool ChromosomeCMA::covarianceUpdateNeeded () [inline]
Definition at line 261 of file ChromosomeCMA.h.
Chromosome* ChromosomeCMA::empty () const [inline, protected, virtual]
Reimplemented from ChromosomeT< double >.
Definition at line 271 of file ChromosomeCMA.h.
References ChromosomeCMA().
const Array<double>& ChromosomeCMA::getC () const [inline]
Definition at line 241 of file ChromosomeCMA.h.
double ChromosomeCMA::getCondition () const [inline]
Definition at line 251 of file ChromosomeCMA.h.
double ChromosomeCMA::getSigma () const [inline]
Definition at line 246 of file ChromosomeCMA.h.
void ChromosomeCMA::init (unsigned dimension, double initialSigma, double MinInit, double MaxInit, int lambda = 1) [inline]
Definition at line 136 of file ChromosomeCMA.h.
References Chromosome::init().
void ChromosomeCMA::init (unsigned dimension, std::vector< double > stdv, double initialSigma, ChromosomeT< double > & MinInit, ChromosomeT< double > & MaxInit, int noOffspring = 1, double lower = 0.) [inline]
Definition at line 81 of file ChromosomeCMA.h.
References ChromosomeT_num< double >::initialize().
void ChromosomeCMA::mutate () [inline, virtual]
Chromosomes externally defined from the EALib shall 'know' how to mutate themselves.
Reimplemented from Chromosome.
Definition at line 153 of file ChromosomeCMA.h.
int ChromosomeCMA::pvm_pkchrom () [inline, protected, virtual]
Part of PVM-send routine for type double Chromosomes
Reimplemented from ChromosomeT< double >.
Definition at line 276 of file ChromosomeCMA.h.
References pvm_pkdouble(), and pvm_pkuint().
int ChromosomeCMA::pvm_upkchrom () [inline, protected, virtual]
Part of PVM-receive routine for type double Chromosomes
Reimplemented from ChromosomeT< double >.
Definition at line 316 of file ChromosomeCMA.h.
References pvm_pkuint(), pvm_upkdouble(), ChromosomeT_base< double >::resize(), and ChromosomeT_base< double >::size().
void ChromosomeCMA::setLower (double lower) [inline]
Definition at line 256 of file ChromosomeCMA.h.
void ChromosomeCMA::updateCovariance () [inline]
Definition at line 218 of file ChromosomeCMA.h.
void ChromosomeCMA::updateCovariance (Individual & parent) [inline]
Definition at line 193 of file ChromosomeCMA.h.
void ChromosomeCMA::updateGlobalStepsize (double nsucc) [inline]
Definition at line 183 of file ChromosomeCMA.h.
void ChromosomeCMA::updateGlobalStepsize () [inline]
Definition at line 170 of file ChromosomeCMA.h.
void ChromosomeCMA::updateLambdaSucc (bool better) [inline]
Definition at line 177 of file ChromosomeCMA.h.
The documentation for this class was generated from the following file:
ChromosomeCMA.h