EALib: ChromosomeCMACholesky Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ChromosomeCMACholesky Class Reference
Elitist CMA evolution strategy with "Cholesky Update".
#include <ChromosomeCMACholesky.h>
Public Member Functions
ChromosomeCMACholesky ()
ChromosomeCMACholesky (unsigned l)
ChromosomeCMACholesky (unsigned l, const double &v)
ChromosomeCMACholesky (const std::vector< double > &v)
~ChromosomeCMACholesky ()
void init (unsigned dimension, std::vector< double > stdv, double initialSigma, ChromosomeT< double > &MinInit, ChromosomeT< double > &MaxInit, int noOffspring=1)
void init (unsigned dimension, double initialSigma, double MinInit, double MaxInit, int lambda=1)
void init (unsigned dimension, std::vector< double > &stdv, double initialSigma, double MinInit, double MaxInit, int lambda=1)
void mutate ()
void updateGlobalStepsize (double nsucc)
void updateCovariance ()
void updateGlobalStepsize ()
void updateLambdaSucc (bool better)
bool covarianceUpdateNeeded ()
const Array< double > & getB ()
double getSigma ()
double getCondition ()
double getPath ()
Protected Member Functions
void rankOneUpdate (Array< double > &A, const Array< double > &v, double alpha, double beta)
Chromosome * clone () const
Chromosome * empty () const
Detailed Description
Elitist CMA evolution strategy with "Cholesky Update".
Definition at line 63 of file ChromosomeCMACholesky.h.
Constructor & Destructor Documentation
ChromosomeCMACholesky::ChromosomeCMACholesky () [inline]
Definition at line 66 of file ChromosomeCMACholesky.h.
Referenced by clone(), and empty().
ChromosomeCMACholesky::ChromosomeCMACholesky (unsigned l) [inline, explicit]
Definition at line 68 of file ChromosomeCMACholesky.h.
ChromosomeCMACholesky::ChromosomeCMACholesky (unsigned l, const double & v) [inline]
Definition at line 70 of file ChromosomeCMACholesky.h.
ChromosomeCMACholesky::ChromosomeCMACholesky (const std::vector< double > & v) [inline]
Definition at line 72 of file ChromosomeCMACholesky.h.
ChromosomeCMACholesky::~ChromosomeCMACholesky () [inline]
Definition at line 74 of file ChromosomeCMACholesky.h.
Member Function Documentation
Chromosome* ChromosomeCMACholesky::clone () const [inline, protected, virtual]
Reimplemented from ChromosomeT< double >.
Definition at line 233 of file ChromosomeCMACholesky.h.
References ChromosomeCMACholesky().
bool ChromosomeCMACholesky::covarianceUpdateNeeded () [inline]
Definition at line 195 of file ChromosomeCMACholesky.h.
Chromosome* ChromosomeCMACholesky::empty () const [inline, protected, virtual]
Reimplemented from ChromosomeT< double >.
Definition at line 237 of file ChromosomeCMACholesky.h.
References ChromosomeCMACholesky().
const Array<double>& ChromosomeCMACholesky::getB () [inline]
Definition at line 200 of file ChromosomeCMACholesky.h.
double ChromosomeCMACholesky::getCondition () [inline]
Definition at line 210 of file ChromosomeCMACholesky.h.
double ChromosomeCMACholesky::getPath () [inline]
Definition at line 215 of file ChromosomeCMACholesky.h.
double ChromosomeCMACholesky::getSigma () [inline]
Definition at line 205 of file ChromosomeCMACholesky.h.
void ChromosomeCMACholesky::init (unsigned dimension, double initialSigma, double MinInit, double MaxInit, int lambda = 1) [inline]
Definition at line 120 of file ChromosomeCMACholesky.h.
References Chromosome::init().
void ChromosomeCMACholesky::init (unsigned dimension, std::vector< double > stdv, double initialSigma, ChromosomeT< double > & MinInit, ChromosomeT< double > & MaxInit, int noOffspring = 1) [inline]
Definition at line 77 of file ChromosomeCMACholesky.h.
References ChromosomeT_num< double >::initialize().
void ChromosomeCMACholesky::init (unsigned dimension, std::vector< double > & stdv, double initialSigma, double MinInit, double MaxInit, int lambda = 1) [inline]
Definition at line 137 of file ChromosomeCMACholesky.h.
References Chromosome::init().
void ChromosomeCMACholesky::mutate () [inline, virtual]
Chromosomes externally defined from the EALib shall 'know' how to mutate themselves.
Reimplemented from Chromosome.
Definition at line 153 of file ChromosomeCMACholesky.h.
void ChromosomeCMACholesky::rankOneUpdate (Array< double > & A, const Array< double > & v, double alpha, double beta) [inline, protected]
Definition at line 222 of file ChromosomeCMACholesky.h.
Referenced by updateCovariance().
void ChromosomeCMACholesky::updateCovariance () [inline]
Definition at line 173 of file ChromosomeCMACholesky.h.
References rankOneUpdate().
void ChromosomeCMACholesky::updateGlobalStepsize () [inline]
Definition at line 182 of file ChromosomeCMACholesky.h.
void ChromosomeCMACholesky::updateGlobalStepsize (double nsucc) [inline]
Definition at line 166 of file ChromosomeCMACholesky.h.
void ChromosomeCMACholesky::updateLambdaSucc (bool better) [inline]
Definition at line 189 of file ChromosomeCMACholesky.h.
The documentation for this class was generated from the following file:
ChromosomeCMACholesky.h