EALib: CMASearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CMASearch Class Reference
Non-elitist CMA-ES implementing the interface EvolutionaryAlgorithm.
#include <CMA.h>
Public Member Functions
CMASearch ()
~CMASearch ()
CMA & getCMA ()
const CMA & getCMA () const
const PopulationT< double > * parents () const
const PopulationT< double > * offspring () const
void init (ObjectiveFunctionVS< double > &fitness, CMA::RecombType recomb=CMA::superlinear, CMA::UpdateType cupdate=CMA::rankmu)
void init (ObjectiveFunctionVS< double > &fitness, const Array< double > &start, double stepsize, CMA::RecombType recomb=CMA::superlinear, CMA::UpdateType cupdate=CMA::rankmu)
void init (ObjectiveFunctionVS< double > &fitness, unsigned int mu, unsigned int lambda, const Array< double > &start, double stepsize, CMA::RecombType recomb=CMA::superlinear, CMA::UpdateType cupdate=CMA::rankmu)
void init (ObjectiveFunctionVS< double > &fitness, unsigned int mu, unsigned int lambda, const Array< double > &start, const Array< double > &stepsize, CMA::RecombType recomb=CMA::superlinear, CMA::UpdateType cupdate=CMA::rankmu)
void run ()
main interface: perform one iteration of the search algorithm
void bestSolutions (std::vector< double * > &points)
return the current set of pareto-optimal solutions
void bestSolutionsFitness (Array< double > &fitness)
Return a two-dimensional array of fitness values.
Protected Attributes
CMA m_cma
ObjectiveFunctionVS< double > * m_fitness
PopulationT< double > * m_parents
PopulationT< double > * m_offspring
Friends
std::ostream & operator<< (std::ostream &stream, const CMASearch &search)
std::istream & operator>> (std::istream &stream, CMASearch &search)
Detailed Description
Non-elitist CMA-ES implementing the interface EvolutionaryAlgorithm.
Examples:
paraboloidCMA.cpp.
Definition at line 142 of file CMA.h.
Constructor & Destructor Documentation
CMASearch::CMASearch ()
Definition at line 362 of file CMA.cpp.
References SearchAlgorithmBase::m_name, m_offspring, and m_parents.
CMASearch::~CMASearch ()
Definition at line 370 of file CMA.cpp.
References m_offspring, and m_parents.
Member Function Documentation
void CMASearch::bestSolutions (std::vector< double * > & points) [virtual]
return the current set of pareto-optimal solutions
Implements SearchAlgorithm< double * >.
Definition at line 506 of file CMA.cpp.
void CMASearch::bestSolutionsFitness (Array< double > & fitness) [virtual]
Return a two-dimensional array of fitness values.
The first dimension corresponds to the solution, while the second dimension corresponds to the objective.
Implements SearchAlgorithm< double * >.
Definition at line 512 of file CMA.cpp.
const CMA& CMASearch::getCMA () const [inline]
Definition at line 149 of file CMA.h.
References m_cma.
CMA& CMASearch::getCMA () [inline]
Definition at line 148 of file CMA.h.
References m_cma.
void CMASearch::init (ObjectiveFunctionVS< double > & fitness, unsigned int mu, unsigned int lambda, const Array< double > & start, const Array< double > & stepsize, CMA::RecombType recomb = CMA::superlinear, CMA::UpdateType cupdate = CMA::rankmu)
Definition at line 460 of file CMA.cpp.
References ObjectiveFunctionVS< T >::dimension(), CMA::init(), EvolutionaryAlgorithm< double * >::lambda(), m_cma, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, EvolutionaryAlgorithm< double * >::mu(), and Population::setMinimize().
void CMASearch::init (ObjectiveFunctionVS< double > & fitness, unsigned int mu, unsigned int lambda, const Array< double > & start, double stepsize, CMA::RecombType recomb = CMA::superlinear, CMA::UpdateType cupdate = CMA::rankmu)
Definition at line 438 of file CMA.cpp.
References ObjectiveFunctionVS< T >::dimension(), CMA::init(), EvolutionaryAlgorithm< double * >::lambda(), m_cma, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, EvolutionaryAlgorithm< double * >::mu(), and Population::setMinimize().
void CMASearch::init (ObjectiveFunctionVS< double > & fitness, CMA::RecombType recomb = CMA::superlinear, CMA::UpdateType cupdate = CMA::rankmu)
Examples:
paraboloidCMA.cpp.
Definition at line 377 of file CMA.cpp.
References ObjectiveFunctionVS< T >::dimension(), CMA::init(), m_cma, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, ObjectiveFunctionVS< T >::ProposeStartingPoint(), Population::setMinimize(), CMA::suggestLambda(), and CMA::suggestMu().
void CMASearch::init (ObjectiveFunctionVS< double > & fitness, const Array< double > & start, double stepsize, CMA::RecombType recomb = CMA::superlinear, CMA::UpdateType cupdate = CMA::rankmu)
Definition at line 416 of file CMA.cpp.
References ObjectiveFunctionVS< T >::dimension(), CMA::init(), m_cma, m_fitness, EvolutionaryAlgorithm< double * >::m_lambda, EvolutionaryAlgorithm< double * >::m_mu, m_offspring, m_parents, Population::setMinimize(), CMA::suggestLambda(), and CMA::suggestMu().
const PopulationT<double>* CMASearch::offspring () const [inline]
Definition at line 151 of file CMA.h.
References m_offspring.
const PopulationT<double>* CMASearch::parents () const [inline]
Definition at line 150 of file CMA.h.
References m_parents.
void CMASearch::run () [virtual]
main interface: perform one iteration of the search algorithm
Reimplemented from SearchAlgorithm< double * >.
Examples:
paraboloidCMA.cpp.
Definition at line 486 of file CMA.cpp.
References ObjectiveFunctionVS< T >::closestFeasible(), CMA::create(), ObjectiveFunctionVS< T >::isFeasible(), m_cma, m_fitness, m_offspring, m_parents, Population::selectMuLambda(), Population::size(), and CMA::updateStrategyParameters().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const CMASearch & search) [friend]
Definition at line 518 of file CMA.cpp.
std::istream& operator>> (std::istream & stream, CMASearch & search) [friend]
Definition at line 527 of file CMA.cpp.
Member Data Documentation
CMA CMASearch::m_cma [protected]
Definition at line 165 of file CMA.h.
Referenced by getCMA(), init(), operator<<(), operator>>(), and run().
ObjectiveFunctionVS<double>* CMASearch::m_fitness [protected]
Definition at line 166 of file CMA.h.
Referenced by init(), and run().
PopulationT<double>* CMASearch::m_offspring [protected]
Definition at line 168 of file CMA.h.
Referenced by CMASearch(), init(), offspring(), operator<<(), operator>>(), run(), and ~CMASearch().
PopulationT<double>* CMASearch::m_parents [protected]
Definition at line 167 of file CMA.h.
Referenced by CMASearch(), init(), operator<<(), operator>>(), parents(), run(), and ~CMASearch().
The documentation for this class was generated from the following files:
CMA.h
CMA.cpp