EALib: ChromosomeT< int > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ChromosomeT< int > Class Template Reference
chromosome based on integers
#include <ChromosomeT.h>
Public Member Functions
ChromosomeT ()
ChromosomeT (unsigned l)
ChromosomeT (unsigned l, const int &v)
ChromosomeT (const std::vector< int > &v)
void mutateDiffGeom (double s)
void mutateDiffGeom (const std::vector< double > &s, bool=false)
void mutateDiffGeom (const Chromosome &s, bool=false)
void mutateDiffGeom (const ChromosomeT< double > &s, bool=false)
Protected Member Functions
Chromosome * clone () const
Chromosome * empty () const
int pvm_pkchrom ()
int pvm_upkchrom ()
void writeTo (std::ostream &os) const
void readFrom (std::istream &is)
Detailed Description
template<>
class ChromosomeT< int >
chromosome based on integers
Examples:
integerES.cpp.
Definition at line 1461 of file ChromosomeT.h.
Constructor & Destructor Documentation
ChromosomeT< int >::ChromosomeT () [inline]
Definition at line 1464 of file ChromosomeT.h.
ChromosomeT< int >::ChromosomeT (unsigned l) [inline, explicit]
Definition at line 1466 of file ChromosomeT.h.
ChromosomeT< int >::ChromosomeT (unsigned l, const int & v) [inline]
Definition at line 1469 of file ChromosomeT.h.
ChromosomeT< int >::ChromosomeT (const std::vector< int > & v) [inline]
Definition at line 1472 of file ChromosomeT.h.
Member Function Documentation
Chromosome* ChromosomeT< int >::clone () const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< int >.
Definition at line 1482 of file ChromosomeT.h.
Chromosome* ChromosomeT< int >::empty () const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< int >.
Definition at line 1486 of file ChromosomeT.h.
void ChromosomeT< int >::mutateDiffGeom (double s)
Examples:
integerES.cpp.
Definition at line 48 of file ChromosomeT_int.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< int >::mutateDiffGeom (const ChromosomeT< double > & s, bool cycle = false)
Definition at line 71 of file ChromosomeT_int.cpp.
void ChromosomeT< int >::mutateDiffGeom (const std::vector< double > & s, bool cycle = false)
Definition at line 58 of file ChromosomeT_int.cpp.
References ChromosomeT_base< T >::size().
void ChromosomeT< int >::mutateDiffGeom (const Chromosome & s, bool cycle = false)
Definition at line 79 of file ChromosomeT_int.cpp.
int ChromosomeT< int >::pvm_pkchrom () [inline, protected, virtual]
Part of PVM-send routine for type int Chromosomes
Reimplemented from Chromosome.
Definition at line 1494 of file ChromosomeT.h.
References pvm_pkint(), pvm_pkuint(), and ChromosomeT_base< T >::size().
int ChromosomeT< int >::pvm_upkchrom () [inline, protected, virtual]
Part of PVM-receive routine for type int Chromosomes
Reimplemented from Chromosome.
Definition at line 1516 of file ChromosomeT.h.
References pvm_upkint(), pvm_upkuint(), and ChromosomeT_base< T >::size().
void ChromosomeT< int >::readFrom (std::istream & is) [inline, protected, virtual]
Reimplemented from ChromosomeT_base< int >.
Definition at line 1548 of file ChromosomeT.h.
References ChromosomeT_base< T >::resize(), and ChromosomeT_base< T >::size().
void ChromosomeT< int >::writeTo (std::ostream & os) const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< int >.
Definition at line 1537 of file ChromosomeT.h.
References ChromosomeT_base< T >::size().
The documentation for this class was generated from the following files:
ChromosomeT.h
ChromosomeT_int.cpp