EALib: ChromosomeT< char > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ChromosomeT< char > Class Template Reference
chromosome based on characters
#include <ChromosomeT.h>
Public Member Functions
ChromosomeT ()
ChromosomeT (unsigned l)
ChromosomeT (unsigned l, const char &v)
ChromosomeT (const std::vector< char > &v)
Protected Member Functions
Chromosome * clone () const
Chromosome * empty () const
int pvm_pkchrom ()
int pvm_upkchrom ()
void writeTo (std::ostream &os) const
void readFrom (std::istream &is)
Detailed Description
template<>
class ChromosomeT< char >
chromosome based on characters
Definition at line 1349 of file ChromosomeT.h.
Constructor & Destructor Documentation
ChromosomeT< char >::ChromosomeT () [inline]
Definition at line 1352 of file ChromosomeT.h.
ChromosomeT< char >::ChromosomeT (unsigned l) [inline, explicit]
Definition at line 1354 of file ChromosomeT.h.
ChromosomeT< char >::ChromosomeT (unsigned l, const char & v) [inline]
Definition at line 1357 of file ChromosomeT.h.
ChromosomeT< char >::ChromosomeT (const std::vector< char > & v) [inline]
Definition at line 1360 of file ChromosomeT.h.
Member Function Documentation
Chromosome* ChromosomeT< char >::clone () const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< char >.
Definition at line 1365 of file ChromosomeT.h.
Chromosome* ChromosomeT< char >::empty () const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< char >.
Definition at line 1369 of file ChromosomeT.h.
int ChromosomeT< char >::pvm_pkchrom () [inline, protected, virtual]
Part of PVM-send routine for type char Chromosomes
Reimplemented from Chromosome.
Definition at line 1376 of file ChromosomeT.h.
References pvm_pkbyte(), pvm_pkuint(), and ChromosomeT_base< T >::size().
int ChromosomeT< char >::pvm_upkchrom () [inline, protected, virtual]
Part of PVM-receive routine for type char Chromosomes
Reimplemented from Chromosome.
Definition at line 1398 of file ChromosomeT.h.
References pvm_upkbyte(), pvm_upkuint(), and ChromosomeT_base< T >::size().
void ChromosomeT< char >::readFrom (std::istream & is) [inline, protected, virtual]
Reimplemented from ChromosomeT_base< char >.
Definition at line 1426 of file ChromosomeT.h.
References ChromosomeT_base< T >::resize(), and ChromosomeT_base< T >::size().
void ChromosomeT< char >::writeTo (std::ostream & os) const [inline, protected, virtual]
Reimplemented from ChromosomeT_base< char >.
Definition at line 1418 of file ChromosomeT.h.
References ChromosomeT_base< T >::size().
The documentation for this class was generated from the following file:
ChromosomeT.h