Fuzzy: BellLT Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
BellLT Class Reference
LinguisticTerm with a bell-shaped (Gaussian) membership function.
#include <BellLT.h>
Public Member Functions
BellLT (const std::string name, const RCPtr< LinguisticVariable > &parent, double sigma, double offset, double scale=1)
Constructor.
double defuzzify (double errRel=ERR_RELATIVE, int recursionMax=RECURSION_MAX) const
Defuzzifies the set by returning the Bell's offset if the support is not bounded by the associated linguistic variable, and by dertermination of the center of gravity otherwise.
double getMin () const
Returns the lower boundary of the support.
double getMax () const
Returns the upper boundary of the support.
Detailed Description
LinguisticTerm with a bell-shaped (Gaussian) membership function.
This class implements a LinguisticTerm with membership function:
Definition at line 50 of file BellLT.h.
Constructor & Destructor Documentation
BellLT::BellLT (const std::string name, const RCPtr< LinguisticVariable > & parent, double sigma, double offset, double scale = 1)
Constructor.
Parameters:
name the name
parent the associated linguistic variable
sigma controlls the width of the Gaussian
offset position of the center of the peak
scale scales the whole function
Definition at line 28 of file BellLT.cpp.
Member Function Documentation
double BellLT::defuzzify (double errRel = ERR_RELATIVE, int recursionMax = RECURSION_MAX) const
Defuzzifies the set by returning the Bell's offset if the support is not bounded by the associated linguistic variable, and by dertermination of the center of gravity otherwise.
Parameters:
errRel relative approximation error that is tollerated during numerical integration
recursionMax max. depth of recursion during numerical integration (i.e. max. steps)
Reimplemented from LinguisticTerm.
Definition at line 35 of file BellLT.cpp.
References FuzzySet::defuzzify(), BellFS::defuzzify(), BellFS::getMax(), and BellFS::getMin().
double BellLT::getMax () const [inline, virtual]
Returns the upper boundary of the support.
Returns:
the max. value for which the FuzzySet is nonzero (or exceeds a given threshold)
Reimplemented from BellFS.
Definition at line 96 of file BellLT.h.
References BellFS::getMax().
double BellLT::getMin () const [inline, virtual]
Returns the lower boundary of the support.
Returns:
the min. value for which the FuzzySet is nonzero (or exceeds a given threshold)
Reimplemented from BellFS.
Definition at line 86 of file BellLT.h.
References BellFS::getMin().
The documentation for this class was generated from the following files:
BellLT.h
BellLT.cpp