Fuzzy: SugenoIM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SugenoIM Class Reference
A Sugeno inference machine.
#include <SugenoIM.h>
Public Member Functions
SugenoIM (RuleBase *rb=0)
Constructor.
virtual ~SugenoIM ()
Destructor.
double computeSugenoInference (const InputType inputType) const
Computes the Sugeno inference.
double computeSugenoInference (double a, double b) const
Computes the Sugeno inference.
double computeSugenoInference (double a, double b, double c) const
Computes the Sugeno inference.
double computeSugenoInference (double a, double b, double c, double d) const
Computes the Sugeno inference.
Detailed Description
A Sugeno inference machine.
Definition at line 37 of file SugenoIM.h.
Constructor & Destructor Documentation
SugenoIM::SugenoIM (RuleBase * rb = 0)
Constructor.
Parameters:
rb the associated rulebase
Definition at line 31 of file SugenoIM.cpp.
SugenoIM::~SugenoIM () [virtual]
Destructor.
Definition at line 34 of file SugenoIM.cpp.
Member Function Documentation
double SugenoIM::computeSugenoInference (const InputType inputType) const
Computes the Sugeno inference.
Parameters:
inputType a vector of crisp values (an InputType)
Returns:
the inference
Definition at line 38 of file SugenoIM.cpp.
References Rule::Activation(), and SugenoRule::calculateConsequence().
Referenced by computeSugenoInference().
double SugenoIM::computeSugenoInference (double a, double b, double c, double d) const
Computes the Sugeno inference.
Parameters:
a the first crisp value
b the second crisp value
c the third crisp value
d the fourth crisp value
Returns:
the inference
Definition at line 75 of file SugenoIM.cpp.
References computeSugenoInference().
double SugenoIM::computeSugenoInference (double a, double b, double c) const
Computes the Sugeno inference.
Parameters:
a the first crisp value
b the second crisp value
c the third crisp value
Returns:
the inference
Definition at line 68 of file SugenoIM.cpp.
References computeSugenoInference().
double SugenoIM::computeSugenoInference (double a, double b) const
Computes the Sugeno inference.
Parameters:
a the first crisp value
b the second crisp value
Returns:
the inference
Definition at line 61 of file SugenoIM.cpp.
References computeSugenoInference().
The documentation for this class was generated from the following files:
SugenoIM.h
SugenoIM.cpp