Fuzzy: RuleBase Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
RuleBase Class Reference
A composite of rules.
#include <RuleBase.h>
Public Types
typedef std::list< RCPtr
< LinguisticVariable > > inputTemplate
typedef std::list< RCPtr
< LinguisticVariable > > outputTemplate
typedef RuleSet::const_iterator BaseIterator
typedef
inputTemplate::const_iterator FormatIterator
typedef
outputTemplate::const_iterator ConclIt
Public Member Functions
RuleBase ()
~RuleBase ()
void addRule (const RCPtr< Rule > &rule)
Add a rule to the rulebase.
void removeRule (const RCPtr< Rule > &rule)
Remove a rule from the rulbase.
int getNumberOfRules ()
Return the number of rules in the rulebase.
const std::string print () const
Return a string with the all the rules of the rulabase.
const RCPtr< Rule > getRule (int whichone)
Return a certain rule of the rulebase.
BaseIterator getFirstIterator () const
BaseIterator getLastIterator () const
FormatIterator getFirstFormatIterator () const
FormatIterator getLastFormatIterator () const
FormatIterator getFirstConclIt () const
FormatIterator getLastConclIt () const
void setInputFormat (inputTemplate &in)
Sets the Input Format.
void addToInputFormat (const RCPtr< LinguisticVariable > &lv)
Adds a liniguistic variable to the Imput Format.
void addToInputFormat (const RCPtr< LinguisticVariable > &lv1, const RCPtr< LinguisticVariable > &lv2)
Adds two liniguistic variables to the Imput Format.
void addToInputFormat (const RCPtr< LinguisticVariable > &lv1, const RCPtr< LinguisticVariable > &lv2, const RCPtr< LinguisticVariable > &lv3)
Adds three liniguistic variables to the Imput Format.
void addToInputFormat (const RCPtr< LinguisticVariable > &lv1, const RCPtr< LinguisticVariable > &lv2, const RCPtr< LinguisticVariable > &lv3, const RCPtr< LinguisticVariable > &lv4)
Adds four liniguistic variable to the Imput Format.
void addToOutputFormat (const RCPtr< LinguisticVariable > &lv)
Adds a liniguistic variable to the Ouput Format.
void addToOutputFormat (const RCPtr< LinguisticVariable > &lv1, const RCPtr< LinguisticVariable > &lv2)
Adds two liniguistic variables to the Ouput Format.
void removeFromInputFormat (const RCPtr< LinguisticVariable > &lv)
Removes a liniguistic variable from the Imput Format.
unsigned int getNumberOfInputs () const
Returns the number of linguistic variables in the Input Format.
Detailed Description
A composite of rules.
A rulebase combines several rules.
Definition at line 45 of file RuleBase.h.
Member Typedef Documentation
typedef RuleSet::const_iterator RuleBase::BaseIterator
Definition at line 95 of file RuleBase.h.
typedef outputTemplate::const_iterator RuleBase::ConclIt
Definition at line 113 of file RuleBase.h.
typedef inputTemplate::const_iterator RuleBase::FormatIterator
Definition at line 103 of file RuleBase.h.
typedef std::list< RCPtr<LinguisticVariable> > RuleBase::inputTemplate
Definition at line 52 of file RuleBase.h.
typedef std::list< RCPtr<LinguisticVariable> > RuleBase::outputTemplate
Definition at line 53 of file RuleBase.h.
Constructor & Destructor Documentation
RuleBase::RuleBase ()
Definition at line 39 of file RuleBase.cpp.
RuleBase::~RuleBase ()
Definition at line 31 of file RuleBase.cpp.
Member Function Documentation
void RuleBase::addRule (const RCPtr< Rule > & rule)
Add a rule to the rulebase.
Parameters:
rule the rule to be added
Definition at line 43 of file RuleBase.cpp.
Referenced by Rule::Rule().
void RuleBase::addToInputFormat (const RCPtr< LinguisticVariable > & lv1, const RCPtr< LinguisticVariable > & lv2, const RCPtr< LinguisticVariable > & lv3, const RCPtr< LinguisticVariable > & lv4)
Adds four liniguistic variable to the Imput Format.
The linguistic variables must be added in the correct order with respect to the corresponding positions in the input vector.
Parameters:
lv1 the first linguistic variable to be added
lv2 the secound linguistic variable to be added
lv3 the third linguitic variable to be added
lv4 the fourth linguitic variable to be added
Definition at line 119 of file RuleBase.cpp.
References addToInputFormat().
void RuleBase::addToInputFormat (const RCPtr< LinguisticVariable > & lv)
Adds a liniguistic variable to the Imput Format.
The linguistic variables must be added in the correct order with respect to the corresponding positions in the input vector.
Parameters:
lv the linguistic variable to be added
Definition at line 75 of file RuleBase.cpp.
Referenced by addToInputFormat().
void RuleBase::addToInputFormat (const RCPtr< LinguisticVariable > & lv1, const RCPtr< LinguisticVariable > & lv2)
Adds two liniguistic variables to the Imput Format.
The linguistic variables must be added in the correct order with respect to the corresponding positions in the input vector.
Parameters:
lv1 the first linguistic variable to be added
lv2 the secound linguistic variable to be added
Definition at line 105 of file RuleBase.cpp.
References addToInputFormat().
void RuleBase::addToInputFormat (const RCPtr< LinguisticVariable > & lv1, const RCPtr< LinguisticVariable > & lv2, const RCPtr< LinguisticVariable > & lv3)
Adds three liniguistic variables to the Imput Format.
The linguistic variables must be added in the correct order with respect to the corresponding positions in the input vector.
Parameters:
lv1 the first linguistic variable to be added
lv2 the secound linguistic variable to be added
lv3 the third linguitic variable to be added
Definition at line 111 of file RuleBase.cpp.
References addToInputFormat().
void RuleBase::addToOutputFormat (const RCPtr< LinguisticVariable > & lv)
Adds a liniguistic variable to the Ouput Format.
The linguistic variables must be added in the correct order with respect to the corresponding positions in the input vector.
Parameters:
lv the linguistic variable to be added
Definition at line 80 of file RuleBase.cpp.
Referenced by addToOutputFormat().
void RuleBase::addToOutputFormat (const RCPtr< LinguisticVariable > & lv1, const RCPtr< LinguisticVariable > & lv2)
Adds two liniguistic variables to the Ouput Format.
The linguistic variables must be added in the correct order with respect to the corresponding positions in the input vector.
Parameters:
lv1 the firs linguistic variable to be added
lv2 the secound linguistic variable to be added
Definition at line 130 of file RuleBase.cpp.
References addToOutputFormat().
FormatIterator RuleBase::getFirstConclIt () const [inline]
Definition at line 117 of file RuleBase.h.
Referenced by InferenceMachine::computeInference().
FormatIterator RuleBase::getFirstFormatIterator () const [inline]
Definition at line 107 of file RuleBase.h.
Referenced by Rule::addPremise(), and InferenceMachine::characteristicCurve().
BaseIterator RuleBase::getFirstIterator () const [inline]
Definition at line 97 of file RuleBase.h.
Referenced by InferenceMachine::computeInference().
FormatIterator RuleBase::getLastConclIt () const [inline]
Definition at line 121 of file RuleBase.h.
Referenced by InferenceMachine::computeInference().
FormatIterator RuleBase::getLastFormatIterator () const [inline]
Definition at line 111 of file RuleBase.h.
BaseIterator RuleBase::getLastIterator () const [inline]
Definition at line 101 of file RuleBase.h.
unsigned int RuleBase::getNumberOfInputs () const [inline]
Returns the number of linguistic variables in the Input Format.
@ return, the number of linguistic variables in the Input Format
Definition at line 221 of file RuleBase.h.
Referenced by SugenoRule::calculateConsequence(), InferenceMachine::characteristicCurve(), and SugenoRule::setConclusion().
int RuleBase::getNumberOfRules () [inline]
Return the number of rules in the rulebase.
Definition at line 73 of file RuleBase.h.
Referenced by InferenceMachine::computeInference(), and getRule().
const RCPtr< Rule > RuleBase::getRule (int whichone)
Return a certain rule of the rulebase.
Parameters:
whichone the number of the rule that shall be returned
Definition at line 61 of file RuleBase.cpp.
References getNumberOfRules().
const std::string RuleBase::print () const
Return a string with the all the rules of the rulabase.
Returns:
, the rulebase as a string
Definition at line 92 of file RuleBase.cpp.
void RuleBase::removeFromInputFormat (const RCPtr< LinguisticVariable > & lv)
Removes a liniguistic variable from the Imput Format.
Parameters:
lv the linguistic variable to be removed
Definition at line 84 of file RuleBase.cpp.
void RuleBase::removeRule (const RCPtr< Rule > & rule)
Remove a rule from the rulbase.
Parameters:
rule the rule to be added
Definition at line 47 of file RuleBase.cpp.
void RuleBase::setInputFormat (inputTemplate & in)
Sets the Input Format.
Parameters:
in the InputTemplate (list of linguistic vaiables)
Definition at line 88 of file RuleBase.cpp.
The documentation for this class was generated from the following files:
RuleBase.h
RuleBase.cpp