Fuzzy: Operators Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Operators Class Reference
Operators and connective functions.
#include <Operators.h>
Static Public Member Functions
static RCPtr< ComposedFS > max (const RCPtr< FuzzySet > &f1, const RCPtr< FuzzySet > &f2)
Connects two fuzzy sets via the maximum function and returns the resulting fuzzy set.
static RCPtr< FuzzySet > min (const RCPtr< FuzzySet > &f1, const RCPtr< FuzzySet > &f2)
Connects two fuzzy sets via the minimum function and returns the resulting fuzzy set.
static RCPtr< ComposedNDimFS > supMinComp (const std::vector< double > &input, Implication *imp)
Sup-min composition of an implication and a vector of singeltons.
static double minimum (double a, double b)
The minimum function.
static double maximum (double a, double b)
The maximum function.
static double prod (double a, double b)
The PROD function.
static double probor (double a, double b)
The PROBOR function.
Detailed Description
Operators and connective functions.
This class implements operators needed to do some calculations on fuzzy sets and the connective functions MINIMUM, MAXIMUM, PROD and PRODOR.
Definition at line 45 of file Operators.h.
Member Function Documentation
RCPtr< ComposedFS > Operators::max (const RCPtr< FuzzySet > & f1, const RCPtr< FuzzySet > & f2) [static]
Connects two fuzzy sets via the maximum function and returns the resulting fuzzy set.
Parameters:
f1 the first fuzzy set
f2 the second fuzzy set
Returns:
the resulting composed fuzzy set
Definition at line 29 of file Operators.cpp.
References ComposedFS::MAX.
static double Operators::maximum (double a, double b) [inline, static]
The maximum function.
Parameters:
a first input value
b second input value retrun the maximum of a and b
Definition at line 114 of file Operators.h.
Referenced by Rule::setConnective().
RCPtr< FuzzySet > Operators::min (const RCPtr< FuzzySet > & f1, const RCPtr< FuzzySet > & f2) [static]
Connects two fuzzy sets via the minimum function and returns the resulting fuzzy set.
Parameters:
f1 the first fuzzy set
f2 the second fuzzy set
Returns:
the resulting composed fuzzy set
Definition at line 50 of file Operators.cpp.
References ComposedFS::MIN.
static double Operators::minimum (double a, double b) [inline, static]
The minimum function.
Parameters:
a first input value
b second input value retrun the minimum of a and b
Definition at line 103 of file Operators.h.
Referenced by Rule::setConnective().
static double Operators::probor (double a, double b) [inline, static]
The PROBOR function.
Parameters:
a first input value
b second input value retrun PROBOR(a,b)= a+b-a*b
Definition at line 137 of file Operators.h.
Referenced by Rule::setConnective().
static double Operators::prod (double a, double b) [inline, static]
The PROD function.
Parameters:
a first input value
b second input value retrun the product of a and b (a*b)
Definition at line 125 of file Operators.h.
Referenced by Rule::setConnective().
RCPtr< ComposedNDimFS > Operators::supMinComp (const std::vector< double > & input, Implication * imp) [static]
Sup-min composition of an implication and a vector of singeltons.
where is the implication function and is the current input, in our case a vector of singletons, which simplifies this to
Parameters:
input the input vector (vector of singeltons)
imp the implication
Returns:
the resulting composed n-dimensional fuzzy set
Definition at line 70 of file Operators.cpp.
References FuzzyRelation::Y.
The documentation for this class was generated from the following files:
Operators.h
Operators.cpp