Fuzzy: Rule Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Rule Class Reference
A rule which is composed of premise and conclusion.
#include <Rule.h>
Public Types
typedef std::vector< RCPtr
< FuzzySet > > IORuleType
typedef std::vector< RCPtr
< FuzzySet > > ConclusionType
Public Member Functions
Rule (Connective c=AND, RuleBase *belongsTo=NULL, double _weight=1.0)
Default constructor.
Rule (std::string ruleText, RuleBase *belongsTo, double _weight=1.0)
Constructor.
virtual ~Rule ()
double Activation (const std::vector< double > &inputs) const
Returns the activation of the premise of the rule for a given input vector.
double Activation (double input) const
Returns the activation of the premise of the rule for a given single imput value.
void setConnective (Connective con)
Sets the connective, that shell be used in the premise.
std::string printRule () const
Returns the rule given by a string.
virtual void addPremise (const RCPtr< LinguisticTerm > &lt)
Adds a linguistic therm to the premise.
virtual void addPremise (const RCPtr< LinguisticTerm > &lt1, const RCPtr< LinguisticTerm > &lt2)
Adds two linguistic therms to the premise.
virtual void addPremise (const RCPtr< LinguisticTerm > &lt1, const RCPtr< LinguisticTerm > &lt2, const RCPtr< LinguisticTerm > &lt3)
Adds three linguistic therms to the premise.
virtual void addPremise (const RCPtr< LinguisticTerm > &lt1, const RCPtr< LinguisticTerm > &lt2, const RCPtr< LinguisticTerm > &lt3, const RCPtr< LinguisticTerm > &lt4)
Adds four linguistic therms to the premise.
virtual void addConclusion (const RCPtr< LinguisticTerm > &lt)
Adds a linguistic therm to the conclusion.
NDimFS * getPremise ()
Returns the premise of a rule.
const ConclusionType & getConclusion () const
Returns the conclusion of a rule.
double getWeight () const
Returns the weight of a rule.
Protected Attributes
RuleBase * ruleBasePtr
Detailed Description
A rule which is composed of premise and conclusion.
The premise is composed of linguistic terms which are linked with one connective (AND, OR, PROD or PROBOR). AND is the minimum function, OR the maximum function, PROD the product, and PROBOR(x,y)= x+y-xy. There is always used solely one kind of connective for all connections in one permise.
Definition at line 63 of file Rule.h.
Member Typedef Documentation
typedef std::vector< RCPtr<FuzzySet> > Rule::ConclusionType
Reimplemented in SugenoRule.
Definition at line 66 of file Rule.h.
typedef std::vector< RCPtr<FuzzySet> > Rule::IORuleType
Definition at line 65 of file Rule.h.
Constructor & Destructor Documentation
Rule::Rule (Connective c = AND, RuleBase * belongsTo = NULL, double _weight = 1.0)
Default constructor.
Definition at line 49 of file Rule.cpp.
References RuleBase::addRule(), and setConnective().
Rule::Rule (std::string ruleText, RuleBase * belongsTo, double _weight = 1.0)
Constructor.
Constructor for rules given by a string of the form
  IF LinguisticVariable1 = LinguisticTermA AND/OR
     LinguisticVariable2 = LinguisticTermB AND/OR ...
  THEN
     LinguisticVariable3 = LinguisticTermC
     LinguisticVariable4 = LinguisticTermD ...
where LinguisticVariable/Term in this example stands for their names, which can be obtained by their getName() methods.
Parameters:
ruleText the rule given by a string
belongsTo the RuleBase the rule belongs to
_weight the weight of a rule
Definition at line 58 of file Rule.cpp.
References addConclusion(), addPremise(), RuleBase::addRule(), AND, LinguisticVariable::findLT(), LinguisticVariable::getLV(), OR, PROBOR, PROD, and setConnective().
Rule::~Rule () [virtual]
Definition at line 47 of file Rule.cpp.
Member Function Documentation
double Rule::Activation (const std::vector< double > & inputs) const
Returns the activation of the premise of the rule for a given input vector.
This method returns the activation of the premise of the rule. In this case the methods accepts crisp inputs. Thus it is sufficient to calculate the value of the MF at the input points. Input is a vector of singletons
Parameters:
inputs input vector with values of the type double
Definition at line 163 of file Rule.cpp.
Referenced by Activation(), and SugenoIM::computeSugenoInference().
double Rule::Activation (double input) const [inline]
Returns the activation of the premise of the rule for a given single imput value.
This method returns the activation of the premise of the rule. In this case the methods accepts crisp inputs. Thus it is sufficient to calculate the value of the MF at the input points. Input is a vector of singletons
Parameters:
input single input value
Definition at line 383 of file Rule.cpp.
References Activation().
void Rule::addConclusion (const RCPtr< LinguisticTerm > & lt) [virtual]
Adds a linguistic therm to the conclusion.
Parameters:
lt the linguisic Term to be added
Definition at line 275 of file Rule.cpp.
Referenced by Rule().
void Rule::addPremise (const RCPtr< LinguisticTerm > & lt1, const RCPtr< LinguisticTerm > & lt2, const RCPtr< LinguisticTerm > & lt3, const RCPtr< LinguisticTerm > & lt4) [virtual]
Adds four linguistic therms to the premise.
Parameters:
lt1 the first linguisic term to be added
lt2 the secound linguistic term to be added
lt3 the third linguistic term to be added
lt4 the fourth linguistic term to be added
Definition at line 403 of file Rule.cpp.
References addPremise().
void Rule::addPremise (const RCPtr< LinguisticTerm > & lt) [virtual]
Adds a linguistic therm to the premise.
Parameters:
lt the linguisic Term to be added
Definition at line 197 of file Rule.cpp.
References AND, RuleBase::getFirstFormatIterator(), ComposedFS::MAX, ComposedFS::MIN, OR, PROBOR, ComposedFS::PROD, PROD, and ruleBasePtr.
Referenced by addPremise(), and Rule().
void Rule::addPremise (const RCPtr< LinguisticTerm > & lt1, const RCPtr< LinguisticTerm > & lt2) [virtual]
Adds two linguistic therms to the premise.
Parameters:
lt1 the first linguisic term to be added
lt2 the secound linguistic term to be added
Definition at line 389 of file Rule.cpp.
References addPremise().
void Rule::addPremise (const RCPtr< LinguisticTerm > & lt1, const RCPtr< LinguisticTerm > & lt2, const RCPtr< LinguisticTerm > & lt3) [virtual]
Adds three linguistic therms to the premise.
Parameters:
lt1 the first linguisic term to be added
lt2 the secound linguistic term to be added
lt3 the third linguistic term to be added
Definition at line 395 of file Rule.cpp.
References addPremise().
const ConclusionType& Rule::getConclusion () const [inline]
Returns the conclusion of a rule.
Returns:
the conclusion of he rule
Definition at line 216 of file Rule.h.
NDimFS * Rule::getPremise ()
Returns the premise of a rule.
Returns:
the premise of the rule
Definition at line 378 of file Rule.cpp.
double Rule::getWeight () const [inline]
Returns the weight of a rule.
Returns:
the weight of he rule
Definition at line 226 of file Rule.h.
std::string Rule::printRule () const
Returns the rule given by a string.
Returns:
string, that gives the rule
Definition at line 279 of file Rule.cpp.
References AND, LinguisticTerm::getLinguisticVariable(), LinguisticTerm::getName(), OR, PROBOR, and PROD.
void Rule::setConnective (Connective con)
Sets the connective, that shell be used in the premise.
Parameters:
con the Connective (AND, OR, PROD, or PROBOR) to be unsed in the premise
Definition at line 358 of file Rule.cpp.
References AND, Operators::maximum(), Operators::minimum(), OR, Operators::probor(), PROBOR, Operators::prod(), and PROD.
Referenced by Rule().
Member Data Documentation
RuleBase* Rule::ruleBasePtr [protected]
Definition at line 228 of file Rule.h.
Referenced by addPremise(), SugenoRule::calculateConsequence(), and SugenoRule::setConclusion().
The documentation for this class was generated from the following files:
Rule.h
Rule.cpp