Fuzzy: BellFS Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
BellFS Class Reference
FuzzySet with a bell-shaped (Gaussian) membership function.
#include <BellFS.h>
Public Member Functions
BellFS (double sigma, double offset, double scale=1)
Constructor.
virtual double defuzzify () const
Defuzzifies the set by returning the Bell's offset.
virtual double getMin () const
Returns the lower boundary of the support.
virtual double getMax () const
Returns the upper boundary of the support.
double getThreshold () const
Returns the theshold under which values of the function are set to be zero.
void setThreshold (double thresh)
Sets the theshold under which values of the function are set to be zero.
void setParams (double sigma, double offset, double scale=1)
Sets the parameters of the fuzzy set.
Detailed Description
FuzzySet with a bell-shaped (Gaussian) membership function.
This class implements a FuzzySet with membership function:
Definition at line 48 of file BellFS.h.
Constructor & Destructor Documentation
BellFS::BellFS (double sigma, double offset, double scale = 1)
Constructor.
Parameters:
sigma controlls the width of the Gaussian
offset position of the center of the peak
scale scales the whole function
Definition at line 30 of file BellFS.cpp.
Member Function Documentation
virtual double BellFS::defuzzify () const [inline, virtual]
Defuzzifies the set by returning the Bell's offset.
Definition at line 70 of file BellFS.h.
Referenced by BellLT::defuzzify().
virtual double BellFS::getMax () const [inline, virtual]
Returns the upper boundary of the support.
Returns:
the max. value for which the membership function is nonzero (or exceeds a given threshold)
Implements FuzzySet.
Reimplemented in BellLT.
Definition at line 90 of file BellFS.h.
Referenced by BellLT::defuzzify(), and BellLT::getMax().
virtual double BellFS::getMin () const [inline, virtual]
Returns the lower boundary of the support.
Returns:
the min. value for which the membership function is nonzero (or exceeds a given threshold)
Implements FuzzySet.
Reimplemented in BellLT.
Definition at line 80 of file BellFS.h.
Referenced by BellLT::defuzzify(), and BellLT::getMin().
double BellFS::getThreshold () const [inline]
Returns the theshold under which values of the function are set to be zero.
Returns:
the theshold
Definition at line 99 of file BellFS.h.
void BellFS::setParams (double sigma, double offset, double scale = 1)
Sets the parameters of the fuzzy set.
Parameters:
sigma controlls the width of the Gaussian
offset position of the center of the peak
scale scales the whole function
Definition at line 46 of file BellFS.cpp.
void BellFS::setThreshold (double thresh)
Sets the theshold under which values of the function are set to be zero.
Parameters:
thresh the theshold
Definition at line 40 of file BellFS.cpp.
The documentation for this class was generated from the following files:
BellFS.h
BellFS.cpp