TimeSeries: Embedding< T > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Embedding< T > Class Template Reference
#include <Embedding.h>
Public Member Functions
Embedding (const Generator< T > &gen, unsigned d, unsigned l, unsigned bufsize=100)
Embedding (const Generator< T > &gen, const Array< unsigned > &lagvec, unsigned bufsize=100)
Embedding (const Embedding< T > &embed)
~Embedding ()
unsigned dim () const
void setDim (unsigned d)
void setLag (unsigned l)
void setEmbedding (unsigned d, unsigned l)
void setEmbedding (const Array< unsigned > &lagvec)
void readahead ()
void reset ()
Array< T > operator() ()
Protected Member Functions
Generator< Array< T > > * clone () const
Protected Attributes
Generator< T > * generator
Array< unsigned > lag
Array< T > buf
unsigned step
Detailed Description
template<class T>
class Embedding< T >
Definition at line 57 of file Embedding.h.
Constructor & Destructor Documentation
template<class T> Embedding< T >::Embedding (const Generator< T > & gen, unsigned d, unsigned l, unsigned bufsize = 100) [inline]
Definition at line 60 of file Embedding.h.
References Embedding< T >::setEmbedding().
template<class T> Embedding< T >::Embedding (const Generator< T > & gen, const Array< unsigned > & lagvec, unsigned bufsize = 100) [inline]
Definition at line 71 of file Embedding.h.
References Embedding< T >::setEmbedding().
template<class T> Embedding< T >::Embedding (const Embedding< T > & embed) [inline]
Definition at line 81 of file Embedding.h.
template<class T> Embedding< T >::~Embedding () [inline]
Definition at line 88 of file Embedding.h.
References Embedding< T >::generator.
Member Function Documentation
template<class T> Generator< Array< T > >* Embedding< T >::clone () const [inline, protected, virtual]
Implements Generator< Array< T > >.
Definition at line 156 of file Embedding.h.
template<class T> unsigned Embedding< T >::dim () const [inline]
Definition at line 93 of file Embedding.h.
References Embedding< T >::lag.
Referenced by Embedding< T >::operator()(), and Embedding< T >::setLag().
template<class T> Array< T > Embedding< T >::operator() () [inline, virtual]
Implements Generator< Array< T > >.
Definition at line 134 of file Embedding.h.
References Embedding< T >::buf, Embedding< T >::dim(), Embedding< T >::generator, Embedding< T >::lag, and Embedding< T >::step.
template<class T> void Embedding< T >::readahead () [inline]
Definition at line 121 of file Embedding.h.
References Embedding< T >::buf, Embedding< T >::generator, Embedding< T >::lag, and Embedding< T >::step.
Referenced by Embedding< T >::setEmbedding().
template<class T> void Embedding< T >::reset () [inline, virtual]
Reimplemented from Generator< Array< T > >.
Definition at line 128 of file Embedding.h.
References Embedding< T >::generator, and Embedding< T >::step.
template<class T> void Embedding< T >::setDim (unsigned d) [inline]
Definition at line 98 of file Embedding.h.
References Embedding< T >::setEmbedding().
template<class T> void Embedding< T >::setEmbedding (unsigned d, unsigned l) [inline]
Definition at line 108 of file Embedding.h.
References Embedding< T >::lag, and Embedding< T >::readahead().
Referenced by Embedding< T >::Embedding(), Embedding< T >::setDim(), and Embedding< T >::setLag().
template<class T> void Embedding< T >::setEmbedding (const Array< unsigned > & lagvec) [inline]
Definition at line 115 of file Embedding.h.
References Embedding< T >::lag, and Embedding< T >::readahead().
template<class T> void Embedding< T >::setLag (unsigned l) [inline]
Definition at line 103 of file Embedding.h.
References Embedding< T >::dim(), and Embedding< T >::setEmbedding().
Member Data Documentation
template<class T> Array< T > Embedding< T >::buf [protected]
Definition at line 153 of file Embedding.h.
Referenced by Embedding< T >::operator()(), and Embedding< T >::readahead().
template<class T> Generator< T >* Embedding< T >::generator [protected]
Definition at line 151 of file Embedding.h.
Referenced by Embedding< T >::operator()(), Embedding< T >::readahead(), Embedding< T >::reset(), and Embedding< T >::~Embedding().
template<class T> Array< unsigned > Embedding< T >::lag [protected]
Definition at line 152 of file Embedding.h.
Referenced by Embedding< T >::dim(), Embedding< T >::operator()(), Embedding< T >::readahead(), and Embedding< T >::setEmbedding().
template<class T> unsigned Embedding< T >::step [protected]
Definition at line 154 of file Embedding.h.
Referenced by Embedding< T >::operator()(), Embedding< T >::readahead(), and Embedding< T >::reset().
The documentation for this class was generated from the following file:
Embedding.h