Array: ArraySort.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ArraySort.h File Reference
Iterative implementation of the quicksort algorithm for one-dimensional arrays with support of index arrays.
#include <climits>
#include <SharkDefs.h>
#include <Array/Array.h>
Defines
#define PIVOT
If this flag is defined, then a pivot value is determined by random.
#define myRandom(num) (rand() % (num))
Returns a random number between 0 and num - 1.
#define pivot(L, R) (L + myRandom(R - L))
Returns a pivot value as random number between L and R - 1.
Functions
template<class T >
void sort (Array< T > &value, Array< unsigned > &index)
Performs a quicksort on the one-dimensional array "value" and will also return the index array "index" of "value".
template<class T >
void sort2DBy1st (Array< T > &value)
Performs a quicksort on the rows of the two-dimensional array "value" by the values of the first column.
Detailed Description
Iterative implementation of the quicksort algorithm for one-dimensional arrays with support of index arrays.
Author:
M. Kreutz
Date:
1995-11-03
Copyright (c) 1995-2000:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
Array
This file is part of Array. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file ArraySort.h.
Define Documentation
#define myRandom (num) (rand() % (num))
Returns a random number between 0 and num - 1.
This preprocessor operation is only defined, if the pivot flag is set.
Parameters:
num defines the upper bound for the returned random number
Returns:
a random number between 0 and num - 1
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 85 of file ArraySort.h.
#define pivot (L, R) (L + myRandom(R - L))
Returns a pivot value as random number between L and R - 1.
The pivot value is only set as random value if the pivot flag above is set.
The pivot value is used for the partitioning step of the quicksort algorithm implementation in function sort.
Parameters:
L defines the lower bound for the returned random number
R defines the upper bound for the returned random number
Returns:
a pivot value between L and R - 1
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 113 of file ArraySort.h.
Referenced by sort(), and sort2DBy1st().
#define PIVOT
If this flag is defined, then a pivot value is determined by random.
Otherwise it is determined by bit operations.
Definition at line 60 of file ArraySort.h.
Function Documentation
template<class T > void sort (Array< T > & value, Array< unsigned > & index)
Performs a quicksort on the one-dimensional array "value" and will also return the index array "index" of "value".
This method implements the famous quicksort algorithm not in a recursive but in an iterative way.
Furthermore an index array is returned, corresponding to the elements of the value array in their original order and sorted in the same way as the values of the value array. This index array can be used especially for the functions "ArrayIndex operator&&(ArrayIndex& a, ArrayIndex& b)" and "ArrayIndex operator||(ArrayIndex& a, ArrayIndex& b)".
By defining/undefining the flag pivot, it can be determined, whether the initial pivot point for the first partition step is a random value or a value calculated by bit operations.
Parameters:
value the one-dimensional array with the values that will be sorted. After the method call, the values in this array are in ascending order
index will contain the indices of the elements of array value as given before sorting and in the same order as the corresponding elements in value after the sort
Returns:
none
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 186 of file ArraySort.h.
References Array< T >::elem(), ArrayBase::nelem(), pivot, and ArrayBase::resize().
Referenced by Array< T * >::remove_cols().
template<class T > void sort2DBy1st (Array< T > & value)
Performs a quicksort on the rows of the two-dimensional array "value" by the values of the first column.
This method implements the famous quicksort algorithm not in a recursive but in an iterative way.
The sorting is performed by the values of the first column. All elements of the second column are sorted in the same way as the corresponding values of the first column belonging to the same row.
By defining/undefining the flag pivot, it can be determined, whether the initial pivot point for the first partition step is a random value or a value calculated by bit operations.
Parameters:
value the two-dimensional array with the values that will be sorted. After the method call, the values of the first column of this array are in ascending order
Returns:
none
Author:
C. Igel
Date:
2005
Changes
none
Status
stable
Definition at line 333 of file ArraySort.h.
References ArrayBase::dim(), Array< T >::elem(), pivot, and ArrayBase::resize().