Array: ReadArray.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ReadArray.cpp File Reference
Contains functions for reading the content of an array from a given input stream.
#include <cmath>
#include <iostream>
#include <list>
#include <algorithm>
#include <SharkDefs.h>
#include <Array/ArrayOp.h>
#include <Array/ArrayIo.h>
Functions
int readArray (Array< double > &arr, istream &is, bool seek, const string beginRecord, const string endRecord, const string beginComment, const string endComment, const string separator, const vector< unsigned > dimensions)
Reads the content for array "arr" from input stream "is".
Detailed Description
Contains functions for reading the content of an array from a given input stream.
Author:
M. Kreutz
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
Array
This file is part of Array. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file ReadArray.cpp.
Function Documentation
int readArray (Array< double > & arr, istream & is, bool seek, const string beginRecord, const string endRecord, const string beginComment, const string endComment, const string separator, const vector< unsigned > dimensions)
Reads the content for array "arr" from input stream "is".
You have several possibilities of reading data from is.
For all possibilities holds, that you can also use the "values" (for not a number), or (for positive infinity) and (for negative infinity) in your input data. It is also possible to use comments (enclosed in the strings beginComment and endComment) at any position of your data and several separators for the single array values at once (each character in the separator string represents one single separator).
If the preprocessor flag __ARRAY_NO_GENERIC_IOSTREAM in file "Array.h" is not defined and you have set seek to "true", you can read data in the following format:
Array<type>(list of dimension sizes)
list of all array elements
Please notice that there are no whitespaces allowed in the list of dimension sizes and between the parentheses and the list, otherwise the method will exit with an exception.
Example
From is the following data is read:
Array<double>(3,2)
1. 2. 3. 4. 5. 6.
So the array arr will be a array of type "double" with content
You can also explicitly give the dimension sizes, by using parameter dimensions. In this case you only have to list the single array values:
Example
  #include "Array/ArrayIo.h"
  void main()
  {
    vector< unsigned > dim_vec;
    Array< double > arr;
    dim_vec.push_back(3);
    dim_vec.push_back(2);
    readArray( arr, cin, true, "", "\n", ";", "\n", " ,", dim_vec );
  }
Given the code above, the data read from the input stream "cin", must be something like:
And you will get the same array again.
If you set the first value of dimension to zero, this functions as wildcard. After the reading of the data, the function will determine the final size of the array by itself. Guess, we will replace the first "push_back"-instruction in the code above by "dim_vec.push_back(0)". Then given as input again, we will get the same array as in the two previous examples.
If you use neither the specification of the array type and dimensions in the input data nor the specification of the dimensions in the function call, all input is interpreted as unformatted.
You must then use the beginRecord and endRecord strings to mark the several dimensions of the array data. If you use the default strings (no beginRecord string and a newline as endRecord string), it is obvious that you can only read in data for one-dimensional arrays (one line of values ended by a newline character) or 2-dimensional arrays (each line contains the values for one array row).
If you want to read in data for arrays with 3 or more dimensions, then you have to use a nonempty beginRecord string.
Guess, we have set the beginRecord string to "\f$(\f$" and the endRecord string to "\f$)\f$". To read in data for a 3-dimensional array, that will match the one defined in the following code
Example
  Array< double > test( 2, 2, 4 );
  test( 0, 0, 0 ) = 1.;
  test( 0, 0, 1 ) = 2.;
  test( 0, 0, 2 ) = 3.;
  test( 0, 0, 3 ) = 4.;
  test( 0, 1, 0 ) = 5.;
  test( 0, 1, 1 ) = 6.;
  test( 0, 1, 2 ) = 7.;
  test( 0, 1, 3 ) = 8.;
  test( 1, 0, 0 ) = 9.;
  test( 1, 0, 1 ) = 10.;
  test( 1, 0, 2 ) = 11.;
  test( 1, 0, 3 ) = 12.;
  test( 1, 1, 0 ) = 13.;
  test( 1, 1, 1 ) = 14.;
  test( 1, 1, 2 ) = 15.;
  test( 1, 1, 3 ) = 16.;
the data read in must have the following format:
The function is error tolerant, i.e. if you use a separator that is not the whitespace character, then two separators without any value between them will cause the function to insert the infinity value. The same occurs if a nonempty beginRecord string is directly followed by a separator (not the whitespace character).
So using the beginRecord and the endRecord strings from above and the comma as separator, the input "\f$(,,,)\f$" will result in an one-dimensional array with the values "\f$inf\mbox{\ }inf\mbox{\ }inf\mbox{\ }inf\f$".
Different numbers of values in the same dimension and beginRecord strings not ended by endRecord strings will be recognized and bring the function to exit with a corresponding error message.
Parameters:
arr the array whose content will be read from is
seek must be set to "true" if you want to read data with the prefix "Array< type >(dimensions)"
is the input stream from which the arrays content is read
beginRecord the string that marks the beginning of a new record (= subdimension of the array). This string is empty by default (this means you can only read in one- or 2-dimensional arrays when using unformatted input data)
endRecord the string that marks the end of the data of each subdimension, the default is the newline character
beginComment marks the beginning of a comment, the default is the semicolon
endComment marks the end of a comment, the default is a newline
separator contains all single characters that will separate single array values. By default the whitspace character and the comma can be used as separators
dimensions can be used to specify the structure of the array data. Each position indicates the size of one array dimension. By default this vector is set empty and not used
Returns:
"-2" - the parameter strings are not valid, "-1" - the data read has a wrong format, "0" - data for the array was successfully read
Exceptions:
check_exception the type of the exception is "range check error" and indicates that the given dimension sizes in dimensions or the dimensions implicitly given by the data prefix "Array<...>(...)" do not correspond to the number of array values read from is
Author:
M. Kreutz
Date:
1995
Changes
2002-03-20, ra: method readArray() didn't work for seek = true, when using explicit specification of array type and dimensions - fixed!
Status
stable
Examples:
mean-var.cpp.
Definition at line 409 of file ReadArray.cpp.
References Array< T >::elem(), ArrayBase::nelem(), and ArrayBase::resize().