Array: Creating Arrays
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Creating Arrays
Operations for Arrays (Please notice the detailed description!)
Functions
ArrayReference::ArrayReference ()
Creates a new empty Array Reference object.
ArrayReference::ArrayReference (unsigned *_d, T *_e, unsigned _nd, unsigned _ne)
Creates a new Array Reference object with the structure and content given by the parameters.
ArrayTable::ArrayTable ()
Creates a new empty ArrayTable.
ArrayTable::ArrayTable (unsigned i)
Creates a new empty one-dimensional ArrayTable.
ArrayTable::ArrayTable (unsigned i, unsigned j)
Creates a new empty 2-dimensional ArrayTable.
ArrayTable::ArrayTable (unsigned i, unsigned j, unsigned k)
Creates a new empty 3-dimensional ArrayTable.
ArrayTable::ArrayTable (const ArrayTable< T > &a)
Creates a new ArrayTable as a copy of the parameter (copy constructor).
Function Documentation
template<class T> ArrayReference< T >::ArrayReference () [inline, inherited]
Creates a new empty Array Reference object.
Returns:
none
Author:
M. Kreutz
Date:
1995-01-01
Changes
none
Status
stable
Definition at line 4788 of file Array.h.
References ArrayBase::d, ArrayBase::ne, and ArrayBase::stat.
template<class T> ArrayReference< T >::ArrayReference (unsigned * _d, T * _e, unsigned _nd, unsigned _ne) [inline, inherited]
Creates a new Array Reference object with the structure and content given by the parameters.
This constructor is for internal usage only.
Parameters:
_d the one-dimensional dimension vector ArrayBase::d
_e the one-dimensional element vector Array::e
_nd the number of array dimensions ArrayBase::nd
_ne the number of array elements ArrayBase::ne
Returns:
none
Author:
M. Kreutz
Date:
1995-01-01
Changes
none
Status
stable
Definition at line 4823 of file Array.h.
References ArrayBase::d, ArrayBase::ne, and ArrayBase::stat.
template<class T> ArrayTable< T >::ArrayTable (unsigned i, unsigned j, unsigned k) [inline, inherited]
Creates a new empty 3-dimensional ArrayTable.
Parameters:
i the size of the ArrayTable in the first dimension.
j the size of the ArrayTable in the second dimension.
k the size of the ArrayTable in the third dimension.
Returns:
none
Author:
R. Alberts
Date:
2002-05-06
Changes
none
Status
stable
Definition at line 662 of file ArrayTable.h.
References ArrayTable< T >::resize().
template<class T> ArrayTable< T >::ArrayTable (unsigned i, unsigned j) [inline, inherited]
Creates a new empty 2-dimensional ArrayTable.
Parameters:
i the size of the ArrayTable in the first dimension.
j the size of the ArrayTable in the second dimension.
Returns:
none
Author:
R. Alberts
Date:
2002-05-06
Changes
none
Status
stable
Definition at line 636 of file ArrayTable.h.
References ArrayTable< T >::resize().
template<class T> ArrayTable< T >::ArrayTable (unsigned i) [inline, inherited]
Creates a new empty one-dimensional ArrayTable.
Parameters:
i the size of the ArrayTable in the first dimension.
Returns:
none
Author:
R. Alberts
Date:
2002-05-06
Changes
none
Status
stable
Definition at line 611 of file ArrayTable.h.
References ArrayTable< T >::resize().
template<class T> ArrayTable< T >::ArrayTable () [inline, inherited]
Creates a new empty ArrayTable.
Returns:
none
Author:
R. Alberts
Date:
2002-05-15
Changes
none
Status
stable
Definition at line 590 of file ArrayTable.h.
template<class T> ArrayTable< T >::ArrayTable (const ArrayTable< T > & a) [inline, inherited]
Creates a new ArrayTable as a copy of the parameter (copy constructor).
Parameters:
a the ArrayTable object to copy.
Returns:
none
Author:
T. Glasmachers, C. Igel
Date:
2004-11-16, 2009-02-11
Status
stable
Definition at line 683 of file ArrayTable.h.
References ArrayTable< T >::operator=().