Array: Input/Output of Arrays
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Input/Output of Arrays
Operations for Arrays (Please notice the detailed description!)
Functions
int readArray (Array< double > &arr, std::istream &is, bool seek=false, const std::string beginRecord="", const std::string endRecord="\n", const std::string beginComment=";", const std::string endComment="\n", const std::string separator=" ,", const std::vector< unsigned > dimensions=std::vector< unsigned >(0))
Reads the content for array "arr" from input stream "is".
template<class T >
int writeArray (const Array< T > &arr, std::ostream &os, const std::string beginRecord="", const std::string endRecord="\n", char separator= '\t', char recordSeparator= '\0')
Writes the content of array "arr" to the output stream "os".
template<class T >
bool prettyprint (std::ostream &os, const Array< T > &v, unsigned depth=0)
Output of the content of array "v" to output stream "os" in a form, where you can better see the array's structure.
Function Documentation
template<class T > bool prettyprint (std::ostream & os, const Array< T > & v, unsigned depth = 0)
Output of the content of array "v" to output stream "os" in a form, where you can better see the array's structure.
This output method works recursively and begins each new position in the current dimension with a left parenthesis and ends each single position in the current dimension with a right parenthesis.
Each single position in the last dimension will be written in its own line and indented by a number of white spaces.
Example
  #include "Array/ArrayOp.h"
  void main()
  {
      // test vector:
      Array< double > test( 2, 2, 4 );
      // Filling the test vector with content:
      test( 0, 0, 0 ) = 1.;
      test( 0, 0, 1 ) = 2.;
      test( 0, 0, 2 ) = 3.;
      test( 0, 0, 3 ) = 4.;
      test( 0, 1, 0 ) = 5.;
      test( 0, 1, 1 ) = 6.;
      test( 0, 1, 2 ) = 7.;
      test( 0, 1, 3 ) = 8.;
      test( 1, 0, 0 ) = 9.;
      test( 1, 0, 1 ) = 10.;
      test( 1, 0, 2 ) = 11.;
      test( 1, 0, 3 ) = 12.;
      test( 1, 1, 0 ) = 13.;
      test( 1, 1, 1 ) = 14.;
      test( 1, 1, 2 ) = 15.;
      test( 1, 1, 3 ) = 16.;
      // Formatted output of the test vector:
      prettyprint( cout, test );
  }
This example program will produce the output:
Parameters:
os the output stream to which the array's content will be written
v the array whose content will be written to os
depth the number of spaces, that will be used as indent. This indent will be increased by one for each subdimension (recursion), the default value at the first call is "0"
Returns:
"true" if there is another subdimension, that must be processed recursively, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 1335 of file ArrayOp.h.
References ArrayBase::dim(), Array< T >::elem(), and ArrayBase::ndim().
int readArray (Array< double > & arr, std::istream & is, bool seek = false, const std::string beginRecord = "", const std::string endRecord = "\n", const std::string beginComment = ";", const std::string endComment = "\n", const std::string separator = " ,", const std::vector< unsigned > dimensions = std::vector< unsigned >(0))
Reads the content for array "arr" from input stream "is".
template<class T > int writeArray (const Array< T > & arr, std::ostream & os, const std::string beginRecord = "", const std::string endRecord = "\n", char separator = '\t', char recordSeparator = '\0')
Writes the content of array "arr" to the output stream "os".
When writing arrays to the output stream, each array will be arranged by records. Each position of the first dimension with all its subdimensions is a single record and the records are written successively. Because all subdimensions of a position of the first dimension are processed by means of recursion, you will get a nested structure of the beginRecord and endRecord strings.
Guess, you have the following 3-dimensional array and call of the writeArray-function:
  Array< double > test( 2, 2, 4 );
  test( 0, 0, 0 ) = 1.;
  test( 0, 0, 1 ) = 2.;
  test( 0, 0, 2 ) = 3.;
  test( 0, 0, 3 ) = 4.;
  test( 0, 1, 0 ) = 5.;
  test( 0, 1, 1 ) = 6.;
  test( 0, 1, 2 ) = 7.;
  test( 0, 1, 3 ) = 8.;
  test( 1, 0, 0 ) = 9.;
  test( 1, 0, 1 ) = 10.;
  test( 1, 0, 2 ) = 11.;
  test( 1, 0, 3 ) = 12.;
  test( 1, 1, 0 ) = 13.;
  test( 1, 1, 1 ) = 14.;
  test( 1, 1, 2 ) = 15.;
  test( 1, 1, 3 ) = 16.;
  writeArray( test, cout, "<RECORD BEGIN>", "<RECORD END>", '\t', '#' );
Then you will get the following output:
<RECORD BEGIN><RECORD BEGIN><RECORD BEGIN>1 2 3 4<RECORD END><RECORD BEGIN>5 6 7 8<RECORD END><RECORD END>#<RECORD BEGIN><RECORD BEGIN>9 10 11 12<RECORD END><RECORD BEGIN>13 14 15 16<RECORD END><RECORD END><RECORD END>
Parameters:
arr the array whose content will be written to os
os the output stream to which the arrays content is written
beginRecord the string that will be written at the beginning of the output of each subdimension of a single record, the default is an empty string
endRecord the string that will be written at the end of the output of each subdimension of a single record, the default is the newline character
separator the character that will separate single array elements, the default is the tabulator character
recordSeparator the character that separates single records, the default is the null character for strings
Returns:
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 137 of file ArrayIo.h.
References ArrayBase::dim(), Array< T >::elem(), ArrayBase::ndim(), and ArrayBase::nelem().