Array: Comparing Arrays
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Comparing Arrays
Operations for Arrays (Please notice the detailed description!)
Functions
template<class T >
bool operator== (const Array< T > &v, const Array< T > &w)
Returns "true" if the two array "v" and "w" are equal.
template<class T >
bool operator== (const ArrayReference< T > v, const Array< T > &w)
Returns "true" if array reference "v" and array "w" are equal.
template<class T >
bool operator== (const Array< T > &v, const ArrayReference< T > w)
Returns "true" if array "v" and array reference "w" are equal.
template<class T >
bool operator== (const ArrayReference< T > v, const ArrayReference< T > w)
Returns "true" if array reference "v" and array reference "w" are equal.
template<class T >
bool operator< (const Array< T > &v, const Array< T > &w)
Returns "true" if array "v" is less than array "w".
template<class T >
bool operator!= (const Array< T > &v, const Array< T > &w)
Returns "true" if the two array "v" and "w" are not equal.
template<class T >
bool operator!= (const ArrayReference< T > v, const Array< T > &w)
Returns "true" if array reference "v" and array "w" are not equal.
template<class T >
bool operator!= (const Array< T > &v, const ArrayReference< T > w)
Returns "true" if array "v" and array reference "w" are not equal.
template<class T >
bool operator!= (const ArrayReference< T > v, const ArrayReference< T > w)
Returns "true" if array reference "v" and array reference "w" are not equal.
Function Documentation
template<class T > bool operator!= (const Array< T > & v, const Array< T > & w) [inline]
Returns "true" if the two array "v" and "w" are not equal.
The two arrays are not equal, if they have different dimensions or at least one element of v is different to the corresponding element of w.
Parameters:
v the first array
w the second array
Returns:
"true", when v and w are not equal, "false" otherwise
Author:
R. Alberts
Date:
2002-05-15
Changes
none
Status
stable
Definition at line 431 of file ArrayOp.h.
template<class T > bool operator!= (const Array< T > & v, const ArrayReference< T > w) [inline]
Returns "true" if array "v" and array reference "w" are not equal.
v and w are not equal, if they have different dimensions or at least one element of v is not equal to the corresponding element of w.
Parameters:
v the array
w the array reference
Returns:
"true", when v and w are not equal, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 493 of file ArrayOp.h.
template<class T > bool operator!= (const ArrayReference< T > v, const ArrayReference< T > w) [inline]
Returns "true" if array reference "v" and array reference "w" are not equal.
v and w are not equal, if they have different dimensions or at least one element of v is not equal to the corresponding element of w.
Parameters:
v the array reference
w the array reference
Returns:
"true", when v and w are not equal, "false" otherwise
Definition at line 516 of file ArrayOp.h.
template<class T > bool operator!= (const ArrayReference< T > v, const Array< T > & w) [inline]
Returns "true" if array reference "v" and array "w" are not equal.
v and w are not equal, if they have different dimensions or at least one element of v is not equal to the corresponding element of w.
Parameters:
v the array reference
w the array
Returns:
"true", when v and w are not equal, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 463 of file ArrayOp.h.
template<class T > bool operator< (const Array< T > & v, const Array< T > & w) [inline]
Returns "true" if array "v" is less than array "w".
v is less than w, if v has less elements than w or both have the same number of elements and at least one element of v is less than the corresponding element of w.
Parameters:
v the first array
w the second array
Returns:
"true", when v is less than w, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 389 of file ArrayOp.h.
References ArrayBase::nelem().
template<class T > bool operator== (const ArrayReference< T > v, const Array< T > & w) [inline]
Returns "true" if array reference "v" and array "w" are equal.
v and w are equal, if they have the same dimensions and all elements are equal.
Parameters:
v the array reference
w the array
Returns:
"true", when v and w are equal, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 288 of file ArrayOp.h.
References Array< T >::begin(), Array< T >::end(), and ArrayBase::samedim().
template<class T > bool operator== (const Array< T > & v, const Array< T > & w) [inline]
Returns "true" if the two array "v" and "w" are equal.
The two arrays are equal, if they have the same dimensions and all elements are equal.
Parameters:
v the first array
w the second array
Returns:
"true", when v and w are equal, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 251 of file ArrayOp.h.
References Array< T >::begin(), Array< T >::end(), and ArrayBase::samedim().
template<class T > bool operator== (const Array< T > & v, const ArrayReference< T > w) [inline]
Returns "true" if array "v" and array reference "w" are equal.
v and w are equal, if they have the same dimensions and all elements are equal.
Parameters:
v the array
w the array reference
Returns:
"true", when v and w are equal, "false" otherwise
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 324 of file ArrayOp.h.
References Array< T >::begin(), Array< T >::end(), and ArrayBase::samedim().
template<class T > bool operator== (const ArrayReference< T > v, const ArrayReference< T > w) [inline]
Returns "true" if array reference "v" and array reference "w" are equal.
v and w are equal, if they have the same dimensions and all elements are equal.
Parameters:
v the array reference
w the array reference
Returns:
"true", when v and w are equal, "false" otherwise
Definition at line 351 of file ArrayOp.h.
References Array< T >::begin(), Array< T >::end(), and ArrayBase::samedim().