Rng: RNG Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
RNG Class Reference
This class defines a generator for uniformally distributed pseudo random numbers of the interval (0,1).
#include <RNG.h>
Public Member Functions
virtual ~RNG ()
RNG (long s=1)
Creates a new pseudo random number instance and generates seed values for the three internal number generators.
void seed (long s=time(NULL))
Uses "s" to generate the seed values for the three internal random number generators.
void reset ()
Resets the current results of the three internal random number generators to the seed values.
long genLong ()
Returns a new discrete uniformally distributed pseudo random number from the interval (0,1).
double genDouble ()
Returns a new continuous uniformally distributed pseudo random number from the interval (0,1).
void getStatus (unsigned &x, unsigned &y, unsigned &z) const
Returns the current results of the three internal random number generators.
void setStatus (const unsigned x, const unsigned y, const unsigned z)
Sets the current results of the three internal random number generators.
virtual double operator() ()
Returns a new continuous uniformally distributed pseudo random number of the interval (0,1).
Static Public Attributes
static RNG globalRng
Global instantiation of class RNG, can be used by all random number generators in library "#Rng".
Detailed Description
This class defines a generator for uniformally distributed pseudo random numbers of the interval (0,1).
A computer can only create "pseudo-random numbers", i.e. a sequence of numbers generated in some systematic way such that its statistical properties are as close as possible to those of true random numbers, e.g. negligible correlation between consecutive numbers. The most common methods are based on the "multiplicative congruential algorithm".
This basic algorithm is defined as:
The resulting integers are then divided by to give uniformly distributed pseudo-random numbers lying in the interval (0,1).
The start number is also called the "seed".
As you can see the random numbers created are cyclic with a maximum frequency of . When choosing unintelligent numbers for and , the frequency will be further shortened.
The aim is to achieve a most possible large frequency.
Therefore, this class uses an alternative algorithm, the Wichman-Hill algorithm, that uses three generators:
From this the pseudo random numbers are generated as:
The random numbers are uniformally distributed in the interval (0,1).
By using intelligent numbers for and for a frequency of is achieved.
For more information about this algorithm please refer to the BYTE magazine, March, 1987, pp. 127-128.
There will be one static instance of this class named globalRng. This instance can be used as base for the template class RandomVar from which all random generators used in library "#Rng" are derived.
This is done, because for every distribution simulation, where the distribution is not uniform, the uniformally distributed pseudo random numbers delivered by this class are transformed to the types of the other distributions.
So, if you have the uniformally distributed random numbers you can transform them into random numbers that are distributed by the function by applying the inverse function of to :
This is also called the inverse transformation.
Author:
M. Kreutz
Date:
1998-08-17
Changes:
none
Status:
stable
Definition at line 130 of file RNG.h.
Constructor & Destructor Documentation
virtual RNG::~RNG () [inline, virtual]
Definition at line 134 of file RNG.h.
RNG::RNG (long s = 1) [inline]
Creates a new pseudo random number instance and generates seed values for the three internal number generators.
s is used as base for the generation of the seed numbers (see description of the class) for the three number generators.
Parameters:
s the base for the generation of the three seed values, by default the value "1" is taken.
Returns:
none
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 160 of file RNG.h.
References seed().
Member Function Documentation
double RNG::genDouble () [inline]
Returns a new continuous uniformally distributed pseudo random number from the interval (0,1).
Generates and returns the current random number (see description of class) in the interval (0,1). The type of the continuous random number will be "double".
Returns:
the current random number as double value
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 282 of file RNG.h.
Referenced by genLong(), and operator()().
long RNG::genLong () [inline]
Returns a new discrete uniformally distributed pseudo random number from the interval (0,1).
Generates and returns the current random number (see description of class) in the interval (0,1). The type of the random number will be "long", so the original continuous type of the random number will be transformed to a discrete type.
Returns:
the current random number as long value
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 253 of file RNG.h.
References genDouble().
void RNG::getStatus (unsigned & x, unsigned & y, unsigned & z) const [inline]
Returns the current results of the three internal random number generators.
Stores the current values of (see description of the class) in x, y and z.
Parameters:
x the current result of generator no. 1
y the current result of generator no. 2
z the current result of generator no. 3
Returns:
none
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 321 of file RNG.h.
virtual double RNG::operator() () [inline, virtual]
Returns a new continuous uniformally distributed pseudo random number of the interval (0,1).
Generates and returns the current random number (see description of the class) as continuous value of type "double".
Returns:
the current random number as double value
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 383 of file RNG.h.
References genDouble().
void RNG::reset () [inline]
Resets the current results of the three internal random number generators to the seed values.
The current results (see description of the class) for the three number generators are set to the stored seed values .
Returns:
none
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 222 of file RNG.h.
void RNG::seed (long s = time(NULL)) [inline]
Uses "s" to generate the seed values for the three internal random number generators.
s is used as base for the generation of the seed numbers (see description of the class) for the three number generators.
Parameters:
s the base for the generation of the three seed values, by default the current system clock time is taken (i.e. the number of seconds since 00:00 hours, Jan 1, 1970 UTC).
Returns:
none
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Examples:
RngTestSimple.cpp.
Definition at line 191 of file RNG.h.
Referenced by RNG(), and RandomVar< bool >::seed().
void RNG::setStatus (const unsigned x, const unsigned y, const unsigned z) [inline]
Sets the current results of the three internal random number generators.
Sets the current values of (see description of the class), that will be used as base for the generation of the next random number.
Parameters:
x the new current result of generator no. 1
y the new current result of generator no. 2
z the new current result of generator no. 3
Returns:
none
Author:
M. Kreutz
Date:
1998-08-17
Changes
none
Status
stable
Definition at line 354 of file RNG.h.
Member Data Documentation
RNG RNG::globalRng [static]
Global instantiation of class RNG, can be used by all random number generators in library "#Rng".
Global instantiation of class RNG, that can be used by all random number generators in library "#Rng".
Examples:
RngTestSimple.cpp.
Definition at line 391 of file RNG.h.
The documentation for this class was generated from the following files:
RNG.h
RNG.cpp