Rng: Dirichlet Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Dirichlet Class Reference
This class simulates a "Dirichlet" distribution.
#include <Dirichlet.h>
Public Member Functions
Dirichlet (unsigned n=3, double alpha=1)
Creates a new instance of the Dirichlet random number generator.
Dirichlet (const std::vector< double > &alpha)
Creates a new instance of the Dirichlet random number generator.
Dirichlet (unsigned n, double alpha, RNG &r)
Creates a new instance of the Dirichlet random number generator.
Dirichlet (std::vector< double > &alpha, RNG &r)
Creates a new instance of the Dirichlet random number generator.
void seed (long s)
Initializes the pseudo random number generator used by this class with value s.
void alpha (const std::vector< double > &a)
Set parameter vector.
void alpha (double a)
Set each parameter to the scalar value a.
std::vector< double > operator() (const std::vector< double > &alpha)
Samples Dirichlet distribution with parameters a.
std::vector< double > operator() (unsigned n, double alpha)
Samples Dirichlet distribution where all parameters are set to the same scalar a.
std::vector< double > operator() ()
Returns a Dirichlet distributed random number.
double p (const std::vector< double > &x) const
Returns the probability desity function evaluated at x.
Protected Attributes
std::vector< double > pAlpha
Parameter vector.
Detailed Description
This class simulates a "Dirichlet" distribution.
The Dirichlet distribution of order is an -dimensional continous distribution with positive parameters . The probability density function satisfies and the are positive and sum to one.
Author:
C. Igel
Date:
2008-11-28
Changes:
none
Status:
stable
Definition at line 73 of file Dirichlet.h.
Constructor & Destructor Documentation
Dirichlet::Dirichlet (unsigned n = 3, double alpha = 1)
Creates a new instance of the Dirichlet random number generator.
Parameters:
n length of random vector
a common parameter value
Definition at line 44 of file Dirichlet.cpp.
References pAlpha.
Dirichlet::Dirichlet (const std::vector< double > & alpha)
Creates a new instance of the Dirichlet random number generator.
Parameters:
a parameter vector
Definition at line 51 of file Dirichlet.cpp.
References alpha(), and pAlpha.
Dirichlet::Dirichlet (unsigned n, double alpha, RNG & r)
Creates a new instance of the Dirichlet random number generator.
Parameters:
n length of random vector
a common parameter value
r random number generator
Definition at line 55 of file Dirichlet.cpp.
References pAlpha.
Dirichlet::Dirichlet (std::vector< double > & alpha, RNG & r)
Creates a new instance of the Dirichlet random number generator.
Parameters:
a parameter vector
r random number generator
Definition at line 62 of file Dirichlet.cpp.
References alpha(), and pAlpha.
Member Function Documentation
void Dirichlet::alpha (const std::vector< double > & a)
Set parameter vector.
Definition at line 71 of file Dirichlet.cpp.
References pAlpha.
Referenced by Dirichlet().
void Dirichlet::alpha (double a)
Set each parameter to the scalar value a.
Definition at line 76 of file Dirichlet.cpp.
References pAlpha.
std::vector< double > Dirichlet::operator() (const std::vector< double > & alpha)
Samples Dirichlet distribution with parameters a.
The dimensionality of the random vector corresponds to the dimensionality of the parameter vector a.
Parameters:
a parameter vector
Returns:
realization of random vector
Author:
C. Igel
Date:
2008-11-28
See also:
RandomVar::seed
Definition at line 82 of file Dirichlet.cpp.
References RandomVar< std::vector< double > >::rng.
std::vector< double > Dirichlet::operator() (unsigned n, double alpha)
Samples Dirichlet distribution where all parameters are set to the same scalar a.
The dimensionality of the random vector corresponds to the parameter n
Parameters:
n length of random vector
a common parameter value
Returns:
realization of random vector
Author:
C. Igel
Date:
2008-11-28
See also:
RandomVar::seed
Definition at line 99 of file Dirichlet.cpp.
References RandomVar< std::vector< double > >::rng.
std::vector< double > Dirichlet::operator() () [virtual]
Returns a Dirichlet distributed random number.
Implements RandomVar< std::vector< double > >.
Definition at line 116 of file Dirichlet.cpp.
References pAlpha.
double Dirichlet::p (const std::vector< double > & x) const [virtual]
Returns the probability desity function evaluated at x.
Implements RandomVar< std::vector< double > >.
Definition at line 120 of file Dirichlet.cpp.
References pAlpha.
void Dirichlet::seed (long s) [virtual]
Initializes the pseudo random number generator used by this class with value s.
The pseudo random number generator as defined in class RNG is initialized by using the seed value s.
Parameters:
s initialization value for the pseudo random number generator
Returns:
none
Author:
C. Igel
Date:
2008-11-28
See also:
RandomVar::seed
Reimplemented from RandomVar< std::vector< double > >.
Definition at line 66 of file Dirichlet.cpp.
Referenced by Rng::seed().
Member Data Documentation
std::vector<double > Dirichlet::pAlpha [protected]
Parameter vector.
Definition at line 173 of file Dirichlet.h.
Referenced by alpha(), Dirichlet(), operator()(), and p().
The documentation for this class was generated from the following files:
Dirichlet.h
Dirichlet.cpp