Mixture: MixtureOfGaussians Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
MixtureOfGaussians Class Reference
Core class implementing a sum of Gaussians.
#include <MixtureOfGaussians.h>
Public Member Functions
bool isfinite () const
double A (unsigned r) const
double B (unsigned r, unsigned t) const
double E (unsigned i, unsigned j) const
double U (unsigned i, unsigned j, unsigned r) const
double V (unsigned i, unsigned j, unsigned r, unsigned t) const
double Delta1 (unsigned s, unsigned j, unsigned q) const
double Delta2 (unsigned s, unsigned j, unsigned q) const
double Delta3 (unsigned s, unsigned j, unsigned q, unsigned k) const
double Delta4 (unsigned s, unsigned j, unsigned q, unsigned k) const
double dAda (unsigned r, unsigned s) const
double dAdb (unsigned r, unsigned s) const
double dAdm (unsigned r, unsigned s, unsigned q) const
double dAds (unsigned r, unsigned s, unsigned q) const
double dBda (unsigned r, unsigned t, unsigned s) const
double dBdb (unsigned r, unsigned t, unsigned s) const
double dBdm (unsigned r, unsigned t, unsigned s, unsigned q) const
double dBds (unsigned r, unsigned t, unsigned s, unsigned q) const
void dCurve (Array< double > &db, Array< double > &dm, Array< double > &ds) const
double q (const Array< double > &x, const MixtureOfGaussians &old) const
void dq (const Array< double > &x, const MixtureOfGaussians &old, Array< double > &da, Array< double > &dm, Array< double > &ds) const
void dCurveams (Array< double > &da, Array< double > &dm, Array< double > &ds) const
double overlap (unsigned i, unsigned j) const
unsigned maxOverlap (unsigned i) const
double volume (unsigned i) const
unsigned minVolume () const
unsigned maxVolume () const
void splitDataset (const Array< double > &x, std::vector< Array< double > > &z)
void merge (unsigned i, unsigned j, std::vector< Array< double > > &z)
void split (unsigned i, std::vector< Array< double > > &z)
void splitBroadest (const Array< double > &)
void splitRandom (const Array< double > &)
void mergeSmallest (const Array< double > &)
void mergeRandom (const Array< double > &)
void splitBroadest (const Array< double > &, const Array< double > &)
void splitRandom (const Array< double > &, const Array< double > &)
void mergeSmallest (const Array< double > &, const Array< double > &)
void mergeRandom (const Array< double > &, const Array< double > &)
double p (const Array< double > &, unsigned) const
double p (const Array< double > &x) const
MixtureOfGaussians (unsigned numA=0, unsigned dimA=0)
Contructs a mixture model with given number of kernels.
virtual ~MixtureOfGaussians ()
MixtureOfGaussians (const Array< double > &alphaA, const Array< double > &muA, const Array< double > &sigmaSqrA)
Contructs a mixture model and initializes it with given parameter vectors.
double & mean (unsigned i, unsigned j)
double & var (unsigned i, unsigned j)
double mean (unsigned i, unsigned j) const
double var (unsigned i, unsigned j) const
const Array< double > & mean () const
Returns the array of mean vectors (read-only)
const Array< double > & var () const
Returns the array of variance vectors (read-only)
Array< double > & mean ()
Returns the array of mean vectors.
Array< double > & var ()
Returns the array of variance vectors.
void resize (unsigned numA, bool copyA=false)
Changes the number of Gaussian kernels.
void resize (unsigned numA, unsigned dimA, bool copyA=false)
Changes the number and dimensionality of Gaussian kernels.
void append (const MixtureOfGaussians &, bool=true)
Appends all kernels of a given mixture model to the current model.
void insertKernel (double, const Array< double > &, const Array< double > &, bool norm=true)
Inserts a new kernel initialized with given parameter vectors.
void insertKernel (const Array< double > &, const Array< double > &, bool norm=true)
void insertKernel (bool=true)
void deleteKernel (unsigned, bool=true)
void deleteKernel (unsigned, unsigned, bool=true)
void deleteInput (unsigned i)
unsigned removeDuplicates (double eps=1e-6, bool norm=true)
unsigned removeMinVar (double minv=1e-30, bool norm=true)
unsigned size () const
Returns the number of Gaussian kernels.
void initialize (const Array< double > &x)
Initializes the code book vectors with uniformly distributed numbers.
virtual void initialize (const Array< double > &x, const Array< double > &y)
Initializes the code book vectors with uniformly distributed numbers.
void estimateRadii ()
void kmc (const Array< double > &x, double prec=1e-6, unsigned maxiter=0)
Performs a k-means-clustering.
void kmc (const Array< double > &x, const Array< double > &y, double prec=1e-6, unsigned maxiter=0)
bool em (const Array< double > &x, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30, double epsilon=1, double beta=1)
void noisy_em (const Array< double > &x, const Array< double > &vx, unsigned numSamples=1000, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30, double epsilon=1, double beta=1)
void em_mask (const Array< double > &x, const Array< bool > &amask, const Array< bool > &mmask, const Array< bool > &vmask, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30)
void jack_knife_em (const Array< double > &x, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30, double beta=1)
void stochastic_em (const Array< double > &x, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30, double epsilon=1)
void annealing_em (const Array< double > &x, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30, double epsilon=1, double minBeta=0.5, double incBeta=1.2)
void em_deficient (const Array< double > &x, const Array< double > &xvar, double prec=1e-6, unsigned maxiter=1000, double minvar=1e-30, double maxvar=1e+30)
void bsom_update (const Array< double > &x, double alpha, double beta)
void bsom (const Array< double > &x, double alphai=0.5, double alphaf=0.005, double betai=1, double betaf=1, unsigned tmax=10000)
void crossover (MixtureOfGaussians &mate, bool=true)
void deleteSmallest (bool=true)
void deleteRandom (bool=true)
void insertRandom (bool=true)
double entropy2 ()
double Renyi () const
double kernelEntropy (const Array< double > &) const
double kernelEntropy (const Array< double > &, const Array< double > &) const
virtual double curvature () const
double sqrDistance (const MixtureOfGaussians &mix) const
Array< double > operator() ()
Array< double > max () const
MixtureOfGaussians condDensity (const Array< double > &x) const
MixtureOfGaussians marginalDensity (const Array< unsigned > &idx) const
MixtureOfGaussians marginalDensity (unsigned) const
MixtureOfGaussians marginalDensity (unsigned, unsigned) const
MixtureOfGaussians marginalDensity (unsigned, unsigned, unsigned) const
double mse (const Array< double > &x, const Array< double > &y) const
Computes the mean squared error of the regression based on the mixture model.
virtual void recall (const Array< double > &, Array< double > &) const
Computes the regression based on the mixture model.
Array< double > condExpectation (const Array< double > &x) const
Computes the conditional expectation.
Array< double > condExpectation (const Array< double > &x, const Array< double > &A, const Array< double > &b) const
Computes the conditional expectation under a linear transformation.
Array< double > condVariance (const Array< double > &x) const
Computes the conditional variance.
Array< double > overallExpectation () const
Computes the overall expectation of the model.
Array< double > overallVariance () const
Computes the overall variance of the model.
double RenyiLikelihood (const Array< double > &) const
double RenyiLikelihood (const Array< double > &, const Array< double > &) const
double jointLogLikelihood (const Array< double > &, const Array< double > &) const
double condLogLikelihood (const Array< double > &, const Array< double > &) const
double deficientLogLikelihood (const Array< double > &, const Array< double > &, double=1e+30) const
bool operator== (const MixtureOfGaussians &) const
bool operator< (const MixtureOfGaussians &) const
void writeMathematica (std::ostream &os) const
Writes the parameters of the mixture model to an output stream.
Static Public Member Functions
static void join (const Array< double > &x, const Array< double > &y, Array< double > &z)
Public Attributes
Array< double > v
Normal gauss
Protected Member Functions
void firstLayer (const Array< double > &x, Array< double > &y) const
double deficientP (const Array< double > &, const Array< double > &, unsigned, double=1e+30) const
double deficientP (const Array< double > &, const Array< double > &, double=1e+30) const
Friends
class RBFN
class RBFN_PTO
Detailed Description
Core class implementing a sum of Gaussians.
Definition at line 55 of file MixtureOfGaussians.h.
Constructor & Destructor Documentation
MixtureOfGaussians::MixtureOfGaussians (unsigned numA = 0, unsigned dimA = 0)
Contructs a mixture model with given number of kernels.
Definition at line 317 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, and v.
virtual MixtureOfGaussians::~MixtureOfGaussians () [inline, virtual]
Definition at line 187 of file MixtureOfGaussians.h.
MixtureOfGaussians::MixtureOfGaussians (const Array< double > & alphaA, const Array< double > & muA, const Array< double > & sigmaSqrA)
Contructs a mixture model and initializes it with given parameter vectors.
Member Function Documentation
double MixtureOfGaussians::A (unsigned r) const
Definition at line 2641 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, E(), size(), and U().
Referenced by curvature(), and dAdb().
void MixtureOfGaussians::annealing_em (const Array< double > & x, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30, double epsilon = 1, double minBeta = 0.5, double incBeta = 1.2)
Definition at line 2367 of file MixtureOfGaussians.cpp.
References em().
void MixtureOfGaussians::append (const MixtureOfGaussians & mix, bool norm = true)
Appends all kernels of a given mixture model to the current model.
Definition at line 428 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, MixtureModel< double >::normalize(), size(), and v.
double MixtureOfGaussians::B (unsigned r, unsigned t) const
Definition at line 2654 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, E(), size(), and V().
Referenced by curvature(), and dBdb().
void MixtureOfGaussians::bsom (const Array< double > & x, double alphai = 0.5, double alphaf = 0.005, double betai = 1, double betaf = 1, unsigned tmax = 10000)
Definition at line 1196 of file MixtureOfGaussians.cpp.
References bsom_update().
void MixtureOfGaussians::bsom_update (const Array< double > & x, double alpha, double beta)
Definition at line 1166 of file MixtureOfGaussians.cpp.
References MIN_VAL.
Referenced by bsom().
MixtureOfGaussians MixtureOfGaussians::condDensity (const Array< double > & x) const
Definition at line 1410 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, max(), MIN_VAL, p(), size(), and v.
Array< double > MixtureOfGaussians::condExpectation (const Array< double > & x) const
Computes the conditional expectation.
Definition at line 1546 of file MixtureOfGaussians.cpp.
References MIN_VAL.
Array< double > MixtureOfGaussians::condExpectation (const Array< double > & x, const Array< double > & A, const Array< double > & b) const
Computes the conditional expectation under a linear transformation.
Definition at line 1575 of file MixtureOfGaussians.cpp.
References LOG_MAX_VAL, and LOG_MIN_VAL.
double MixtureOfGaussians::condLogLikelihood (const Array< double > & y, const Array< double > & x) const
Definition at line 1697 of file MixtureOfGaussians.cpp.
References jointLogLikelihood(), and RandomVector< double >::logLikelihood().
Array< double > MixtureOfGaussians::condVariance (const Array< double > & x) const
Computes the conditional variance.
Definition at line 1620 of file MixtureOfGaussians.cpp.
References MIN_VAL.
void MixtureOfGaussians::crossover (MixtureOfGaussians & mate, bool norm = true)
Definition at line 1257 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, CodeBook::dim(), insertKernel(), CodeBook::m, max(), MixtureModel< T >::normalize(), MixtureModel< double >::normalize(), resize(), size(), MixtureModel< double >::uni, and v.
double MixtureOfGaussians::curvature () const [virtual]
Definition at line 2823 of file MixtureOfGaussians.cpp.
References A(), B(), and CodeBook::dim().
double MixtureOfGaussians::dAda (unsigned r, unsigned s) const
Definition at line 2728 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, E(), size(), and U().
Referenced by dCurveams().
double MixtureOfGaussians::dAdb (unsigned r, unsigned s) const
Definition at line 2738 of file MixtureOfGaussians.cpp.
References A(), MixtureModel< double >::a, E(), size(), and U().
Referenced by dCurve().
double MixtureOfGaussians::dAdm (unsigned r, unsigned s, unsigned q) const
Definition at line 2748 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, delta(), Delta1(), E(), CodeBook::m, size(), U(), and v.
Referenced by dCurve(), and dCurveams().
double MixtureOfGaussians::dAds (unsigned r, unsigned s, unsigned q) const
Definition at line 2760 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, delta(), Delta2(), E(), CodeBook::m, size(), U(), and v.
Referenced by dCurve(), and dCurveams().
double MixtureOfGaussians::dBda (unsigned r, unsigned t, unsigned s) const
Definition at line 2773 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, E(), size(), and V().
Referenced by dCurveams().
double MixtureOfGaussians::dBdb (unsigned r, unsigned t, unsigned s) const
Definition at line 2783 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, B(), E(), size(), and V().
Referenced by dCurve().
double MixtureOfGaussians::dBdm (unsigned r, unsigned t, unsigned s, unsigned q) const
Definition at line 2793 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, delta(), Delta3(), E(), CodeBook::m, size(), V(), and v.
Referenced by dCurve(), and dCurveams().
double MixtureOfGaussians::dBds (unsigned r, unsigned t, unsigned s, unsigned q) const
Definition at line 2808 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, delta(), Delta4(), E(), CodeBook::m, size(), V(), and v.
Referenced by dCurve(), and dCurveams().
void MixtureOfGaussians::dCurve (Array< double > & db, Array< double > & dm, Array< double > & ds) const
Definition at line 2858 of file MixtureOfGaussians.cpp.
References dAdb(), dAdm(), dAds(), dBdb(), dBdm(), dBds(), CodeBook::dim(), q(), and size().
void MixtureOfGaussians::dCurveams (Array< double > & da, Array< double > & dm, Array< double > & ds) const
Definition at line 2888 of file MixtureOfGaussians.cpp.
References dAda(), dAdm(), dAds(), dBda(), dBdm(), dBds(), CodeBook::dim(), q(), and size().
Referenced by RBFN::gradientCurve().
double MixtureOfGaussians::deficientLogLikelihood (const Array< double > & x, const Array< double > & xvar, double maxV = 1e+30) const
Definition at line 2504 of file MixtureOfGaussians.cpp.
References deficientP().
double MixtureOfGaussians::deficientP (const Array< double > & x, const Array< double > & xvar, double maxV = 1e+30) const [protected]
Definition at line 2490 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, deficientP(), p(), and size().
double MixtureOfGaussians::deficientP (const Array< double > & x, const Array< double > & xvar, unsigned i, double maxV = 1e+30) const [protected]
Definition at line 2461 of file MixtureOfGaussians.cpp.
References CodeBook::m, max(), MIN_VAL, SQRT_MAX_VAL, and v.
Referenced by deficientLogLikelihood(), deficientP(), and em_deficient().
void MixtureOfGaussians::deleteInput (unsigned i)
Definition at line 1433 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), CodeBook::m, resize(), size(), and v.
void MixtureOfGaussians::deleteKernel (unsigned k, bool norm = true)
Definition at line 577 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, MixtureModel< double >::normalize(), size(), and v.
Referenced by deleteKernel(), deleteRandom(), RBFN::deleteRBF(), deleteSmallest(), merge(), and split().
void MixtureOfGaussians::deleteKernel (unsigned k, unsigned l, bool norm = true)
Definition at line 611 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, deleteKernel(), CodeBook::dim(), CodeBook::m, MixtureModel< double >::normalize(), size(), and v.
void MixtureOfGaussians::deleteRandom (bool norm = true)
Definition at line 1354 of file MixtureOfGaussians.cpp.
References deleteKernel(), size(), and MixtureModel< double >::uni.
void MixtureOfGaussians::deleteSmallest (bool norm = true)
Definition at line 1347 of file MixtureOfGaussians.cpp.
References deleteKernel(), and minVolume().
double MixtureOfGaussians::Delta1 (unsigned s, unsigned j, unsigned q) const
Definition at line 2700 of file MixtureOfGaussians.cpp.
References CodeBook::m, and v.
Referenced by dAdm().
double MixtureOfGaussians::Delta2 (unsigned s, unsigned j, unsigned q) const
Definition at line 2706 of file MixtureOfGaussians.cpp.
References CodeBook::m, and v.
Referenced by dAds().
double MixtureOfGaussians::Delta3 (unsigned s, unsigned j, unsigned q, unsigned k) const
Definition at line 2714 of file MixtureOfGaussians.cpp.
References CodeBook::m, and v.
Referenced by dBdm(), and Delta4().
double MixtureOfGaussians::Delta4 (unsigned s, unsigned j, unsigned q, unsigned k) const
Definition at line 2721 of file MixtureOfGaussians.cpp.
References Delta3(), CodeBook::m, and v.
Referenced by dBds().
void MixtureOfGaussians::dq (const Array< double > & x, const MixtureOfGaussians & old, Array< double > & da, Array< double > & dm, Array< double > & ds) const
Definition at line 171 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MIN_VAL, and p().
double MixtureOfGaussians::E (unsigned i, unsigned j) const
Definition at line 2667 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), CodeBook::m, and v.
Referenced by A(), B(), dAda(), dAdb(), dAdm(), dAds(), dBda(), dBdb(), dBdm(), and dBds().
bool MixtureOfGaussians::em (const Array< double > & x, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30, double epsilon = 1, double beta = 1)
Definition at line 1993 of file MixtureOfGaussians.cpp.
References MIN_VAL.
Referenced by annealing_em(), kmc(), merge(), split(), and stochastic_em().
void MixtureOfGaussians::em_deficient (const Array< double > & x, const Array< double > & xvar, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30, double maxvar = 1e+30)
Definition at line 2520 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, deficientP(), CodeBook::dim(), CodeBook::m, MIN_VAL, MixtureModel< double >::normalize(), size(), v, and var().
void MixtureOfGaussians::em_mask (const Array< double > & x, const Array< bool > & amask, const Array< bool > & mmask, const Array< bool > & vmask, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30)
Definition at line 1879 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, max(), MIN_VAL, MixtureModel< double >::normalize(), p(), size(), and v.
double MixtureOfGaussians::entropy2 ()
Definition at line 1043 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), gauss, CodeBook::m, size(), and v.
void MixtureOfGaussians::estimateRadii ()
Definition at line 939 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::m, size(), sqrDistance(), and v.
Referenced by kmc().
void MixtureOfGaussians::firstLayer (const Array< double > & x, Array< double > & y) const [protected]
Reimplemented in RBFN.
Definition at line 216 of file MixtureOfGaussians.cpp.
void MixtureOfGaussians::initialize (const Array< double > & x)
Initializes the code book vectors with uniformly distributed numbers.
Reimplemented from CodeBook.
Reimplemented in RBFN.
Definition at line 985 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::m, max(), size(), MixtureModel< double >::uni, and v.
Referenced by merge(), and split().
void MixtureOfGaussians::initialize (const Array< double > & min, const Array< double > & max) [virtual]
Initializes the code book vectors with uniformly distributed numbers.
Reimplemented from CodeBook.
Reimplemented in RBFN.
Definition at line 1031 of file MixtureOfGaussians.cpp.
void MixtureOfGaussians::insertKernel (double _a, const Array< double > & _m, const Array< double > & _v, bool norm = true)
Inserts a new kernel initialized with given parameter vectors.
Definition at line 462 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, MixtureModel< double >::normalize(), size(), and v.
Referenced by crossover(), insertKernel(), insertRandom(), RBFN::insertRBF(), merge(), and split().
void MixtureOfGaussians::insertKernel (const Array< double > & min, const Array< double > & max, bool norm = true)
Definition at line 495 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), insertKernel(), CodeBook::m, max(), size(), sqrDistance(), and MixtureModel< double >::uni.
void MixtureOfGaussians::insertKernel (bool norm = true)
Definition at line 540 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), insertKernel(), CodeBook::m, max(), and size().
void MixtureOfGaussians::insertRandom (bool norm = true)
Definition at line 1361 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), insertKernel(), CodeBook::m, size(), MixtureModel< double >::uni, and v.
bool MixtureOfGaussians::isfinite () const
Definition at line 76 of file MixtureOfGaussians.cpp.
void MixtureOfGaussians::jack_knife_em (const Array< double > & x, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30, double beta = 1)
Definition at line 2241 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, max(), MIN_VAL, MixtureModel< double >::normalize(), p(), size(), and v.
void MixtureOfGaussians::join (const Array< double > & x, const Array< double > & y, Array< double > & z) [static]
Definition at line 93 of file MixtureOfGaussians.cpp.
Referenced by jointLogLikelihood(), kernelEntropy(), kmc(), mergeRandom(), mergeSmallest(), RenyiLikelihood(), splitBroadest(), and splitRandom().
double MixtureOfGaussians::jointLogLikelihood (const Array< double > & x, const Array< double > & y) const
Definition at line 1680 of file MixtureOfGaussians.cpp.
References join(), and RandomVector< double >::logLikelihood().
Referenced by condLogLikelihood().
double MixtureOfGaussians::kernelEntropy (const Array< double > & x) const
Definition at line 1095 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::modelEntropy(), and size().
Referenced by kernelEntropy().
double MixtureOfGaussians::kernelEntropy (const Array< double > & x, const Array< double > & y) const
Definition at line 1104 of file MixtureOfGaussians.cpp.
References join(), and kernelEntropy().
void MixtureOfGaussians::kmc (const Array< double > & x, double prec = 1e-6, unsigned maxiter = 0)
Performs a k-means-clustering.
Reimplemented from CodeBook.
Definition at line 963 of file MixtureOfGaussians.cpp.
References em(), estimateRadii(), and size().
Referenced by RBFN::initialize(), kmc(), merge(), and split().
void MixtureOfGaussians::kmc (const Array< double > & x, const Array< double > & y, double prec = 1e-6, unsigned maxiter = 0)
Definition at line 974 of file MixtureOfGaussians.cpp.
References join(), and kmc().
MixtureOfGaussians MixtureOfGaussians::marginalDensity (unsigned i, unsigned j, unsigned k) const
Definition at line 1493 of file MixtureOfGaussians.cpp.
MixtureOfGaussians MixtureOfGaussians::marginalDensity (unsigned i) const
Definition at line 1476 of file MixtureOfGaussians.cpp.
References marginalDensity().
MixtureOfGaussians MixtureOfGaussians::marginalDensity (const Array< unsigned > & idx) const
Definition at line 1460 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, MixtureModel< T >::a, CodeBook::m, size(), and v.
Referenced by marginalDensity().
MixtureOfGaussians MixtureOfGaussians::marginalDensity (unsigned i, unsigned j) const
Definition at line 1484 of file MixtureOfGaussians.cpp.
References marginalDensity().
Array< double > MixtureOfGaussians::max () const
Definition at line 1393 of file MixtureOfGaussians.cpp.
References CodeBook::m, and size().
Referenced by condDensity(), RBFN_PTO::copyFrom(), crossover(), deficientP(), em_mask(), RBFN::firstLayer(), RBFN::gradientOut(), initialize(), insertKernel(), jack_knife_em(), and RBFN::setParams().
unsigned MixtureOfGaussians::maxOverlap (unsigned i) const
Definition at line 672 of file MixtureOfGaussians.cpp.
References overlap(), p(), and size().
Referenced by mergeRandom(), and mergeSmallest().
unsigned MixtureOfGaussians::maxVolume () const
Definition at line 720 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), size(), and v.
double MixtureOfGaussians::mean (unsigned i, unsigned j) const [inline]
Definition at line 206 of file MixtureOfGaussians.h.
References CodeBook::m.
double& MixtureOfGaussians::mean (unsigned i, unsigned j) [inline]
Definition at line 198 of file MixtureOfGaussians.h.
References CodeBook::m.
const Array< double >& MixtureOfGaussians::mean () const [inline]
Returns the array of mean vectors (read-only)
Definition at line 216 of file MixtureOfGaussians.h.
References CodeBook::m.
Referenced by overallExpectation(), and overallVariance().
Array< double >& MixtureOfGaussians::mean () [inline]
Returns the array of mean vectors.
Definition at line 228 of file MixtureOfGaussians.h.
References CodeBook::m.
void MixtureOfGaussians::merge (unsigned i, unsigned j, std::vector< Array< double > > & z)
Definition at line 800 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, deleteKernel(), CodeBook::dim(), em(), initialize(), insertKernel(), kmc(), CodeBook::m, and v.
Referenced by mergeRandom(), and mergeSmallest().
void MixtureOfGaussians::mergeRandom (const Array< double > & x)
Definition at line 1856 of file MixtureOfGaussians.cpp.
References maxOverlap(), merge(), MixtureModel< double >::sampleModelUniform(), and splitDataset().
Referenced by mergeRandom().
void MixtureOfGaussians::mergeRandom (const Array< double > & x, const Array< double > & y)
Definition at line 1865 of file MixtureOfGaussians.cpp.
References join(), and mergeRandom().
void MixtureOfGaussians::mergeSmallest (const Array< double > & x)
Definition at line 1829 of file MixtureOfGaussians.cpp.
References maxOverlap(), merge(), and splitDataset().
Referenced by mergeSmallest().
void MixtureOfGaussians::mergeSmallest (const Array< double > & x, const Array< double > & y)
Definition at line 1840 of file MixtureOfGaussians.cpp.
References join(), and mergeSmallest().
unsigned MixtureOfGaussians::minVolume () const
Definition at line 700 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), size(), v, and volume().
Referenced by deleteSmallest().
double MixtureOfGaussians::mse (const Array< double > & x, const Array< double > & y) const
Computes the mean squared error of the regression based on the mixture model.
Definition at line 2921 of file MixtureOfGaussians.cpp.
Referenced by RBFN::estimateFisherInformation(), RBFN::gradientMSE(), and RBFN::overallVariance().
void MixtureOfGaussians::noisy_em (const Array< double > & x, const Array< double > & vx, unsigned numSamples = 1000, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30, double epsilon = 1, double beta = 1)
Definition at line 2115 of file MixtureOfGaussians.cpp.
References MIN_VAL.
Array< double > MixtureOfGaussians::operator() ()
Definition at line 1215 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), gauss, CodeBook::m, MixtureModel< double >::sampleModel(), and v.
bool MixtureOfGaussians::operator< (const MixtureOfGaussians &) const [inline]
Definition at line 503 of file MixtureOfGaussians.h.
bool MixtureOfGaussians::operator== (const MixtureOfGaussians & mix) const
Definition at line 121 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, CodeBook::m, and v.
Array< double > MixtureOfGaussians::overallExpectation () const
Computes the overall expectation of the model.
Definition at line 2950 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::m, mean(), and size().
Referenced by overallVariance().
Array< double > MixtureOfGaussians::overallVariance () const
Computes the overall variance of the model.
Definition at line 2967 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::m, mean(), overallExpectation(), size(), and v.
double MixtureOfGaussians::overlap (unsigned i, unsigned j) const
Definition at line 660 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), CodeBook::m, and v.
Referenced by maxOverlap().
double MixtureOfGaussians::p (const Array< double > & x) const [inline]
Reimplemented from MixtureModel< double >.
Reimplemented in KernelDensity.
Definition at line 171 of file MixtureOfGaussians.h.
References p().
double MixtureOfGaussians::p (const Array< double > & x, unsigned i) const [virtual]
Implements MixtureModel< double >.
Definition at line 885 of file MixtureOfGaussians.cpp.
References CodeBook::m, MIN_VAL, and v.
Referenced by condDensity(), deficientP(), dq(), em_mask(), jack_knife_em(), maxOverlap(), p(), and q().
double MixtureOfGaussians::q (const Array< double > & x, const MixtureOfGaussians & old) const
Definition at line 139 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MIN_VAL, and p().
Referenced by dCurve(), and dCurveams().
void MixtureOfGaussians::recall (const Array< double > & x, Array< double > & y) const [virtual]
Computes the regression based on the mixture model.
Reimplemented in RBFN.
Definition at line 1524 of file MixtureOfGaussians.cpp.
unsigned MixtureOfGaussians::removeDuplicates (double eps = 1e-6, bool norm = true)
Definition at line 349 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, MixtureModel< double >::normalize(), resize(), size(), and v.
unsigned MixtureOfGaussians::removeMinVar (double minv = 1e-30, bool norm = true)
Definition at line 393 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, MixtureModel< double >::normalize(), resize(), size(), and v.
double MixtureOfGaussians::Renyi () const
Definition at line 1068 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, size(), and v.
double MixtureOfGaussians::RenyiLikelihood (const Array< double > & x) const
Definition at line 1645 of file MixtureOfGaussians.cpp.
Referenced by RenyiLikelihood().
double MixtureOfGaussians::RenyiLikelihood (const Array< double > & x, const Array< double > & y) const
Definition at line 1663 of file MixtureOfGaussians.cpp.
References join(), and RenyiLikelihood().
void MixtureOfGaussians::resize (unsigned numA, unsigned dimA, bool copyA = false) [virtual]
Changes the number and dimensionality of Gaussian kernels.
Reimplemented from CodeBook.
Definition at line 340 of file MixtureOfGaussians.cpp.
References resize(), and v.
void MixtureOfGaussians::resize (unsigned numA, bool copyA = false) [virtual]
Changes the number of Gaussian kernels.
Reimplemented from CodeBook.
Reimplemented in RBFN.
Definition at line 331 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), and v.
Referenced by crossover(), deleteInput(), removeDuplicates(), removeMinVar(), resize(), KernelDensity::set(), and splitDataset().
unsigned MixtureOfGaussians::size () const [inline]
Returns the number of Gaussian kernels.
Reimplemented from CodeBook.
Definition at line 278 of file MixtureOfGaussians.h.
Referenced by A(), append(), B(), condDensity(), RBFN_PTO::copyFrom(), crossover(), RBFN::curvature(), dAda(), dAdb(), dAdm(), dAds(), dBda(), dBdb(), dBdm(), dBds(), dCurve(), dCurveams(), deficientP(), deleteInput(), deleteKernel(), deleteRandom(), RBFN::deleteRBF(), em_deficient(), em_mask(), entropy2(), estimateRadii(), KernelDensity::estimateVariance(), RBFN::firstLayer(), RBFN::gradientCurve(), RBFN::gradientMSE(), RBFN::gradientOut(), initialize(), insertKernel(), insertRandom(), RBFN::insertRBF(), RBFN::insertRBFData(), jack_knife_em(), KernelDensity::KernelDensity(), kernelEntropy(), kmc(), marginalDensity(), max(), maxOverlap(), maxVolume(), minVolume(), overallExpectation(), overallVariance(), KernelDensity::p(), removeDuplicates(), removeMinVar(), Renyi(), KernelDensity::sample(), KernelDensity::set(), KernelDensity::setVar(), splitDataset(), sqrDistance(), stochastic_em(), and writeMathematica().
void MixtureOfGaussians::split (unsigned i, std::vector< Array< double > > & z)
Definition at line 849 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MixtureModel< double >::a, deleteKernel(), CodeBook::dim(), em(), initialize(), insertKernel(), kmc(), CodeBook::m, and v.
Referenced by splitBroadest(), and splitRandom().
void MixtureOfGaussians::splitBroadest (const Array< double > & x, const Array< double > & y)
Definition at line 1790 of file MixtureOfGaussians.cpp.
References join(), and splitBroadest().
void MixtureOfGaussians::splitBroadest (const Array< double > & x)
Definition at line 1779 of file MixtureOfGaussians.cpp.
References split(), and splitDataset().
Referenced by splitBroadest().
void MixtureOfGaussians::splitDataset (const Array< double > & x, std::vector< Array< double > > & z)
Definition at line 765 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), resize(), MixtureModel< double >::sampleModel(), and size().
Referenced by mergeRandom(), mergeSmallest(), splitBroadest(), and splitRandom().
void MixtureOfGaussians::splitRandom (const Array< double > & x, const Array< double > & y)
Definition at line 1813 of file MixtureOfGaussians.cpp.
References join(), and splitRandom().
void MixtureOfGaussians::splitRandom (const Array< double > & x)
Definition at line 1806 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::sampleModelUniform(), split(), and splitDataset().
Referenced by splitRandom().
double MixtureOfGaussians::sqrDistance (const MixtureOfGaussians & mix) const
Definition at line 1121 of file MixtureOfGaussians.cpp.
References MixtureModel< T >::a, MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, size(), and v.
Referenced by estimateRadii(), insertKernel(), RBFN::insertRBFData(), and KernelDensity::p().
void MixtureOfGaussians::stochastic_em (const Array< double > & x, double prec = 1e-6, unsigned maxiter = 1000, double minvar = 1e-30, double epsilon = 1)
Definition at line 2381 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), em(), RandomVector< double >::logLikelihood(), CodeBook::m, MIN_VAL, MixtureModel< double >::normalize(), MixtureModel< double >::sampleModel(), size(), and v.
double MixtureOfGaussians::U (unsigned i, unsigned j, unsigned r) const
Definition at line 2679 of file MixtureOfGaussians.cpp.
References CodeBook::m, and v.
Referenced by A(), dAda(), dAdb(), dAdm(), and dAds().
double MixtureOfGaussians::V (unsigned i, unsigned j, unsigned r, unsigned t) const
Definition at line 2687 of file MixtureOfGaussians.cpp.
References CodeBook::m, and v.
Referenced by B(), dBda(), dBdb(), dBdm(), and dBds().
Array< double >& MixtureOfGaussians::var () [inline]
Returns the array of variance vectors.
Definition at line 234 of file MixtureOfGaussians.h.
References v.
const Array< double >& MixtureOfGaussians::var () const [inline]
Returns the array of variance vectors (read-only)
Definition at line 222 of file MixtureOfGaussians.h.
References v.
Referenced by em_deficient(), KernelDensity::estimateVariance(), KernelDensity::KernelDensity(), KernelDensity::p(), KernelDensity::sample(), KernelDensity::set(), KernelDensity::setVar(), and KernelDensity::variance().
double& MixtureOfGaussians::var (unsigned i, unsigned j) [inline]
Definition at line 202 of file MixtureOfGaussians.h.
References v.
double MixtureOfGaussians::var (unsigned i, unsigned j) const [inline]
Definition at line 210 of file MixtureOfGaussians.h.
References v.
double MixtureOfGaussians::volume (unsigned i) const
Definition at line 688 of file MixtureOfGaussians.cpp.
References CodeBook::dim(), and v.
Referenced by minVolume().
void MixtureOfGaussians::writeMathematica (std::ostream & os) const
Writes the parameters of the mixture model to an output stream.
Definition at line 1721 of file MixtureOfGaussians.cpp.
References MixtureModel< double >::a, CodeBook::dim(), CodeBook::m, size(), and v.
Friends And Related Function Documentation
friend class RBFN [friend]
Definition at line 91 of file MixtureOfGaussians.h.
friend class RBFN_PTO [friend]
Definition at line 92 of file MixtureOfGaussians.h.
Member Data Documentation
Normal MixtureOfGaussians::gauss
Definition at line 136 of file MixtureOfGaussians.h.
Referenced by entropy2(), operator()(), and KernelDensity::sample().
Array< double > MixtureOfGaussians::v
Definition at line 135 of file MixtureOfGaussians.h.
Referenced by append(), condDensity(), RBFN_PTO::copyFrom(), crossover(), dAdm(), dAds(), dBdm(), dBds(), deficientP(), deleteInput(), deleteKernel(), Delta1(), Delta2(), Delta3(), Delta4(), E(), em_deficient(), em_mask(), entropy2(), estimateRadii(), RBFN::firstLayer(), RBFN::getParams(), RBFN::gradientCurve(), RBFN::gradientMSE(), RBFN::gradientOut(), initialize(), insertKernel(), insertRandom(), jack_knife_em(), KernelDensity::KernelDensity(), marginalDensity(), maxVolume(), merge(), minVolume(), MixtureOfGaussians(), operator()(), operator==(), overallVariance(), overlap(), p(), removeDuplicates(), removeMinVar(), Renyi(), resize(), KernelDensity::set(), RBFN::setParams(), KernelDensity::setVar(), split(), sqrDistance(), stochastic_em(), U(), V(), var(), volume(), and writeMathematica().
The documentation for this class was generated from the following files:
MixtureOfGaussians.h
MixtureOfGaussians.cpp