Mixture: RBFN Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
RBFN Class Reference
Radial Basis Function Network.
#include <RBFN.h>
Public Member Functions
RBFN (unsigned nInputs=0, unsigned nOutputs=0, unsigned nCenters=0)
double & weight (unsigned i, unsigned j)
double & bias (unsigned i)
double weight (unsigned i, unsigned j) const
double bias (unsigned i) const
const Array< double > & weight () const
const Array< double > & bias () const
void setParams (const Array< double > &w)
void getParams (Array< double > &w) const
unsigned odim () const
void initialize (const Array< double > &x)
Initializes the code book vectors with uniformly distributed numbers.
void initialize (const Array< double > &x, const Array< double > &y)
Initializes the code book vectors with uniformly distributed numbers.
void initialize_linear (double min=-1, double max=1)
double curvature ()
void insertRBFData (const Array< double > &input, const Array< double > &output, const Array< double > &minInput, const Array< double > &maxInput)
void insertRBF (const Array< double > &, const Array< double > &, const Array< double > &)
void deleteRBF (unsigned)
void resize (unsigned, bool=false)
Changes the number of Gaussian kernels.
void resize (unsigned, unsigned, unsigned, bool=false)
void train_linear (const Array< double > &, const Array< double > &)
void recall (const Array< double > &, Array< double > &) const
Computes the regression based on the mixture model.
void estimateFisherInformation (const Array< double > &input, const Array< double > &output, Array< double > &A)
void estimateInvFisher (const Array< double > &input, const Array< double > &output, Array< double > &invA, Array< double > &transInvA, double &S2)
double estimateVariance (const Array< double > &input, const Array< double > &invA)
double estimateVarianceChange (const Array< double > &input, const Array< double > &invA, const Array< double > &transInvA, double S2)
double overallVariance (const Array< double > &input, const Array< double > &output)
Protected Member Functions
double gradientMSE (const Array< double > &in, const Array< double > &out, Array< double > &de)
void gradientOut (const Array< double > &in, Array< double > &dw)
virtual void firstLayer (const Array< double > &, Array< double > &) const
void gradientCurve (Array< double > &de)
Protected Attributes
Array< double > A
Array< double > b
Detailed Description
Radial Basis Function Network.
Examples:
rbfn-example.cpp.
Definition at line 51 of file RBFN.h.
Constructor & Destructor Documentation
RBFN::RBFN (unsigned nInputs = 0, unsigned nOutputs = 0, unsigned nCenters = 0)
Examples:
rbfn-example.cpp.
Definition at line 54 of file RBFN.cpp.
References A, b, and MixtureModel< double >::uni.
Member Function Documentation
double& RBFN::bias (unsigned i) [inline]
Definition at line 62 of file RBFN.h.
References b.
double RBFN::bias (unsigned i) const [inline]
Definition at line 70 of file RBFN.h.
References b.
const Array< double >& RBFN::bias () const [inline]
Definition at line 79 of file RBFN.h.
References b.
double RBFN::curvature ()
Definition at line 664 of file RBFN.cpp.
References A, MixtureModel< double >::a, odim(), and MixtureOfGaussians::size().
void RBFN::deleteRBF (unsigned k)
Definition at line 566 of file RBFN.cpp.
References A, MixtureOfGaussians::deleteKernel(), odim(), and MixtureOfGaussians::size().
void RBFN::estimateFisherInformation (const Array< double > & input, const Array< double > & output, Array< double > & A)
Definition at line 266 of file RBFN.cpp.
References gradientOut(), and MixtureOfGaussians::mse().
void RBFN::estimateInvFisher (const Array< double > & input, const Array< double > & output, Array< double > & invA, Array< double > & transInvA, double & S2)
Definition at line 292 of file RBFN.cpp.
double RBFN::estimateVariance (const Array< double > & input, const Array< double > & invA)
Definition at line 370 of file RBFN.cpp.
References gradientOut().
double RBFN::estimateVarianceChange (const Array< double > & input, const Array< double > & invA, const Array< double > & transInvA, double S2)
Definition at line 385 of file RBFN.cpp.
References gradientOut().
void RBFN::firstLayer (const Array< double > & x, Array< double > & ex) const [protected, virtual]
Reimplemented from MixtureOfGaussians.
Definition at line 117 of file RBFN.cpp.
References CodeBook::dim(), CodeBook::m, MixtureOfGaussians::max(), MIN_VAL, MixtureOfGaussians::size(), and MixtureOfGaussians::v.
Referenced by gradientMSE(), gradientOut(), recall(), and train_linear().
void RBFN::getParams (Array< double > & w) const
Examples:
rbfn-example.cpp.
Definition at line 92 of file RBFN.cpp.
References A, b, CodeBook::m, MIN_VAL, and MixtureOfGaussians::v.
void RBFN::gradientCurve (Array< double > & de) [protected]
Definition at line 678 of file RBFN.cpp.
References MixtureModel< double >::a, A, b, MixtureOfGaussians::dCurveams(), CodeBook::m, odim(), MixtureOfGaussians::size(), and MixtureOfGaussians::v.
double RBFN::gradientMSE (const Array< double > & in, const Array< double > & out, Array< double > & de) [protected]
Definition at line 136 of file RBFN.cpp.
References A, b, CodeBook::dim(), firstLayer(), CodeBook::m, MIN_VAL, MixtureOfGaussians::mse(), odim(), MixtureOfGaussians::size(), and MixtureOfGaussians::v.
void RBFN::gradientOut (const Array< double > & in, Array< double > & dw) [protected]
Examples:
rbfn-example.cpp.
Definition at line 225 of file RBFN.cpp.
References A, b, CodeBook::dim(), firstLayer(), CodeBook::m, MixtureOfGaussians::max(), MIN_VAL, odim(), MixtureOfGaussians::size(), and MixtureOfGaussians::v.
Referenced by estimateFisherInformation(), estimateVariance(), estimateVarianceChange(), and overallVariance().
void RBFN::initialize (const Array< double > & x) [inline]
Initializes the code book vectors with uniformly distributed numbers.
Reimplemented from MixtureOfGaussians.
Definition at line 92 of file RBFN.h.
References MixtureModel< double >::initialize().
void RBFN::initialize (const Array< double > & min, const Array< double > & max) [virtual]
Initializes the code book vectors with uniformly distributed numbers.
Reimplemented from MixtureOfGaussians.
Definition at line 399 of file RBFN.cpp.
References A, CodeBook::dim(), MixtureModel< double >::initialize(), MixtureOfGaussians::kmc(), and train_linear().
void RBFN::initialize_linear (double min = -1, double max = 1)
Definition at line 416 of file RBFN.cpp.
References A, b, and MixtureModel< double >::uni.
void RBFN::insertRBF (const Array< double > & newA, const Array< double > & newm, const Array< double > & newv)
Definition at line 544 of file RBFN.cpp.
References A, MixtureOfGaussians::insertKernel(), odim(), and MixtureOfGaussians::size().
Referenced by insertRBFData().
void RBFN::insertRBFData (const Array< double > & input, const Array< double > & output, const Array< double > & minInput, const Array< double > & maxInput)
Definition at line 455 of file RBFN.cpp.
References CodeBook::dim(), insertRBF(), CodeBook::m, recall(), MixtureOfGaussians::size(), MixtureOfGaussians::sqrDistance(), and MixtureModel< double >::uni.
unsigned RBFN::odim () const [inline]
Definition at line 87 of file RBFN.h.
References b.
Referenced by curvature(), deleteRBF(), gradientCurve(), gradientMSE(), gradientOut(), insertRBF(), and resize().
double RBFN::overallVariance (const Array< double > & input, const Array< double > & output)
Definition at line 335 of file RBFN.cpp.
References A, gradientOut(), and MixtureOfGaussians::mse().
void RBFN::recall (const Array< double > & x, Array< double > & y) const [virtual]
Computes the regression based on the mixture model.
Reimplemented from MixtureOfGaussians.
Examples:
rbfn-example.cpp.
Definition at line 643 of file RBFN.cpp.
References A, b, and firstLayer().
Referenced by insertRBFData().
void RBFN::resize (unsigned ninput, unsigned noutput, unsigned num, bool copy = false)
Definition at line 589 of file RBFN.cpp.
References A, b, and resize().
void RBFN::resize (unsigned numA, bool copyA = false) [virtual]
Changes the number of Gaussian kernels.
Reimplemented from MixtureOfGaussians.
Definition at line 596 of file RBFN.cpp.
References CodeBook::dim(), and odim().
Referenced by resize().
void RBFN::setParams (const Array< double > & w)
Examples:
rbfn-example.cpp.
Definition at line 69 of file RBFN.cpp.
References A, b, CodeBook::m, MixtureOfGaussians::max(), MIN_VAL, and MixtureOfGaussians::v.
void RBFN::train_linear (const Array< double > & x, const Array< double > & y)
Definition at line 430 of file RBFN.cpp.
References A, b, and firstLayer().
Referenced by initialize().
double& RBFN::weight (unsigned i, unsigned j) [inline]
Definition at line 58 of file RBFN.h.
References A.
double RBFN::weight (unsigned i, unsigned j) const [inline]
Definition at line 66 of file RBFN.h.
References A.
const Array< double >& RBFN::weight () const [inline]
Definition at line 75 of file RBFN.h.
References A.
Member Data Documentation
Array< double > RBFN::A [protected]
Definition at line 150 of file RBFN.h.
Referenced by RBFN_PTO::copyFrom(), curvature(), deleteRBF(), getParams(), gradientCurve(), gradientMSE(), gradientOut(), initialize(), initialize_linear(), insertRBF(), overallVariance(), RBFN(), recall(), resize(), setParams(), train_linear(), and weight().
Array< double > RBFN::b [protected]
Definition at line 151 of file RBFN.h.
Referenced by bias(), RBFN_PTO::copyFrom(), getParams(), gradientCurve(), gradientMSE(), gradientOut(), initialize_linear(), odim(), RBFN(), recall(), resize(), setParams(), and train_linear().
The documentation for this class was generated from the following files:
RBFN.h
RBFN.cpp