Mixture: RBFN_PTO Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
RBFN_PTO Class Reference
#include <RBFN-PTO.h>
Public Member Functions
RBFN_PTO (unsigned numInputs, unsigned numOutputs, unsigned numCenters, bool trainkap=false)
void copyFrom (const MixtureOfGaussians &gm)
Detailed Description
Definition at line 47 of file RBFN-PTO.h.
Constructor & Destructor Documentation
RBFN_PTO::RBFN_PTO (unsigned numInputs, unsigned numOutputs, unsigned numCenters, bool trainkap = false)
Definition at line 46 of file RBFN-PTO.cpp.
Member Function Documentation
void RBFN_PTO::copyFrom (const MixtureOfGaussians & gm)
Definition at line 128 of file RBFN-PTO.cpp.
References MixtureModel< T >::a, RBFN::A, RBFN::b, CodeBook::dim(), CodeBook::m, MixtureOfGaussians::max(), MIN_VAL, MixtureOfGaussians::size(), and MixtureOfGaussians::v.
The documentation for this class was generated from the following files:
RBFN-PTO.h
RBFN-PTO.cpp