Mixture: CodeBook Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CodeBook Class Reference
A container class for code book vectors.
#include <CodeBook.h>
Public Member Functions
CodeBook ()
Contructs an object with an empty set of code book vectors.
CodeBook (unsigned num, unsigned dim)
Contructs an object with a given number and dimension of vectors.
virtual ~CodeBook ()
Destructs the current object.
unsigned nearest (const Array< double > &x) const
Finds the index of the best matching vector in the code book.
void nearest (const Array< double > &x, Array< double > &y) const
Finds the best matching vector in the code book.
unsigned size () const
Returns the number of code book vectors.
unsigned dim () const
Returns the dimension of the code book vectors.
virtual void resize (unsigned n, bool copy=false)
Changes the number of code book vectors without affection the dimension.
virtual void resize (unsigned n, unsigned d, bool copy=false)
Changes the number and dimension of the code book vectors.
void initialize (const Array< double > &min, const Array< double > &max)
Initializes the code book vectors with uniformly distributed numbers.
void initialize (const Array< double > &x)
Initializes the code book vectors with uniformly distributed numbers.
void kmc (const Array< double > &x, double prec=1e-6, unsigned maxiter=0)
Performs a k-means-clustering.
Protected Attributes
Array< double > m
An n x d matrix that contains n code book vectors of dimension d.
Detailed Description
A container class for code book vectors.
This class implements a container for code book vectors which may be used e.g. for vector quantization. This class serves also as a base class for mixture models and kernel density estimators which use the code book vectors as centers for the models and kernels, respectively.
Author:
M. Kreutz
Date:
1995-01-01
Changes:
none
Status:
stable
Definition at line 68 of file CodeBook.h.
Constructor & Destructor Documentation
CodeBook::CodeBook () [inline]
Contructs an object with an empty set of code book vectors.
Definition at line 84 of file CodeBook.h.
CodeBook::CodeBook (unsigned num, unsigned dim)
Contructs an object with a given number and dimension of vectors.
Definition at line 50 of file CodeBook.cpp.
virtual CodeBook::~CodeBook () [inline, virtual]
Destructs the current object.
Definition at line 98 of file CodeBook.h.
Member Function Documentation
unsigned CodeBook::dim () const [inline]
Returns the dimension of the code book vectors.
Definition at line 131 of file CodeBook.h.
References m.
Referenced by MixtureOfGaussians::append(), MixtureOfGaussians::condDensity(), RBFN_PTO::copyFrom(), MixtureOfGaussians::crossover(), MixtureOfGaussians::curvature(), MixtureOfGaussians::dCurve(), MixtureOfGaussians::dCurveams(), MixtureOfGaussians::deleteInput(), MixtureOfGaussians::deleteKernel(), MixtureOfGaussians::E(), MixtureOfGaussians::em_deficient(), MixtureOfGaussians::em_mask(), MixtureOfGaussians::entropy2(), RBFN::firstLayer(), RBFN::gradientMSE(), RBFN::gradientOut(), RBFN::initialize(), MixtureOfGaussians::insertKernel(), MixtureOfGaussians::insertRandom(), RBFN::insertRBFData(), MixtureOfGaussians::jack_knife_em(), MixtureOfGaussians::maxVolume(), MixtureOfGaussians::merge(), MixtureOfGaussians::minVolume(), MixtureOfGaussians::operator()(), MixtureOfGaussians::overlap(), MixtureOfGaussians::removeDuplicates(), MixtureOfGaussians::removeMinVar(), MixtureOfGaussians::Renyi(), RBFN::resize(), MixtureOfGaussians::resize(), KernelDensity::sample(), MixtureOfGaussians::split(), MixtureOfGaussians::splitDataset(), MixtureOfGaussians::sqrDistance(), MixtureOfGaussians::stochastic_em(), MixtureOfGaussians::volume(), and MixtureOfGaussians::writeMathematica().
void CodeBook::initialize (const Array< double > & x)
Initializes the code book vectors with uniformly distributed numbers.
Reimplemented in MixtureOfGaussians, and RBFN.
Definition at line 128 of file CodeBook.cpp.
void CodeBook::initialize (const Array< double > & min, const Array< double > & max)
Initializes the code book vectors with uniformly distributed numbers.
Reimplemented in MixtureOfGaussians, and RBFN.
Definition at line 154 of file CodeBook.cpp.
void CodeBook::kmc (const Array< double > & x, double prec = 1e-6, unsigned maxiter = 0)
Performs a k-means-clustering.
Reimplemented in MixtureOfGaussians.
Definition at line 173 of file CodeBook.cpp.
unsigned CodeBook::nearest (const Array< double > & x) const
Finds the index of the best matching vector in the code book.
Definition at line 86 of file CodeBook.cpp.
void CodeBook::nearest (const Array< double > & x, Array< double > & y) const
Finds the best matching vector in the code book.
Definition at line 117 of file CodeBook.cpp.
void CodeBook::resize (unsigned n, unsigned d, bool copy = false) [virtual]
Changes the number and dimension of the code book vectors.
Reimplemented in LocalLinearRegression, and MixtureOfGaussians.
Definition at line 74 of file CodeBook.cpp.
void CodeBook::resize (unsigned n, bool copy = false) [virtual]
Changes the number of code book vectors without affection the dimension.
Reimplemented in LocalLinearRegression, MixtureOfGaussians, and RBFN.
Definition at line 65 of file CodeBook.cpp.
Referenced by LocalLinearRegression::resize().
unsigned CodeBook::size () const [inline]
Returns the number of code book vectors.
Reimplemented in MixtureOfGaussians.
Definition at line 125 of file CodeBook.h.
References m.
Referenced by LocalLinearRegression::reset(), and LocalLinearRegression::update().
Member Data Documentation
Array< double > CodeBook::m [protected]
An n x d matrix that contains n code book vectors of dimension d.
Definition at line 186 of file CodeBook.h.
Referenced by MixtureOfGaussians::append(), MixtureOfGaussians::condDensity(), RBFN_PTO::copyFrom(), MixtureOfGaussians::crossover(), MixtureOfGaussians::dAdm(), MixtureOfGaussians::dAds(), MixtureOfGaussians::dBdm(), MixtureOfGaussians::dBds(), MixtureOfGaussians::deficientP(), MixtureOfGaussians::deleteInput(), MixtureOfGaussians::deleteKernel(), MixtureOfGaussians::Delta1(), MixtureOfGaussians::Delta2(), MixtureOfGaussians::Delta3(), MixtureOfGaussians::Delta4(), dim(), MixtureOfGaussians::E(), MixtureOfGaussians::em_deficient(), MixtureOfGaussians::em_mask(), MixtureOfGaussians::entropy2(), MixtureOfGaussians::estimateRadii(), KernelDensity::estimateVariance(), RBFN::firstLayer(), RBFN::getParams(), RBFN::gradientCurve(), RBFN::gradientMSE(), RBFN::gradientOut(), MixtureOfGaussians::initialize(), MixtureOfGaussians::insertKernel(), MixtureOfGaussians::insertRandom(), RBFN::insertRBFData(), MixtureOfGaussians::jack_knife_em(), KernelDensity::KernelDensity(), MixtureOfGaussians::marginalDensity(), MixtureOfGaussians::max(), MixtureOfGaussians::mean(), MixtureOfGaussians::merge(), MixtureOfGaussians::operator()(), MixtureOfGaussians::operator==(), MixtureOfGaussians::overallExpectation(), MixtureOfGaussians::overallVariance(), MixtureOfGaussians::overlap(), MixtureOfGaussians::p(), KernelDensity::p(), MixtureOfGaussians::removeDuplicates(), MixtureOfGaussians::removeMinVar(), MixtureOfGaussians::Renyi(), KernelDensity::sample(), KernelDensity::set(), RBFN::setParams(), size(), MixtureOfGaussians::split(), MixtureOfGaussians::sqrDistance(), MixtureOfGaussians::stochastic_em(), MixtureOfGaussians::U(), MixtureOfGaussians::V(), and MixtureOfGaussians::writeMathematica().
The documentation for this class was generated from the following files:
CodeBook.h
CodeBook.cpp