Mixture: LocalLinearRegression Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LocalLinearRegression Class Reference
Abstract model of a parameterized mixture density.
#include <LocalLinearRegression.h>
Public Member Functions
LocalLinearRegression ()
LocalLinearRegression (unsigned n)
void reset ()
void clear ()
void update ()
void train (const Array< double > &, const Array< double > &)
void recall (const Array< double > &, Array< double > &)
void resize (unsigned n, bool=false)
Changes the number of code book vectors without affection the dimension.
void resize (unsigned n, unsigned d, bool=false)
Changes the number and dimension of the code book vectors.
Public Attributes
Array< MixtureLinearRegression > lr
Detailed Description
Abstract model of a parameterized mixture density.
Definition at line 55 of file LocalLinearRegression.h.
Constructor & Destructor Documentation
LocalLinearRegression::LocalLinearRegression () [inline]
Definition at line 58 of file LocalLinearRegression.h.
LocalLinearRegression::LocalLinearRegression (unsigned n)
Definition at line 47 of file LocalLinearRegression.cpp.
Member Function Documentation
void LocalLinearRegression::clear ()
void LocalLinearRegression::recall (const Array< double > & x, Array< double > & y)
Definition at line 98 of file LocalLinearRegression.cpp.
void LocalLinearRegression::reset ()
Definition at line 53 of file LocalLinearRegression.cpp.
References lr, and CodeBook::size().
void LocalLinearRegression::resize (unsigned n, unsigned d, bool copy = false) [virtual]
Changes the number and dimension of the code book vectors.
Reimplemented from CodeBook.
Definition at line 135 of file LocalLinearRegression.cpp.
References CodeBook::resize().
void LocalLinearRegression::resize (unsigned n, bool copy = false) [virtual]
Changes the number of code book vectors without affection the dimension.
Reimplemented from CodeBook.
Definition at line 125 of file LocalLinearRegression.cpp.
References CodeBook::resize().
void LocalLinearRegression::train (const Array< double > & x, const Array< double > & y)
Definition at line 72 of file LocalLinearRegression.cpp.
void LocalLinearRegression::update ()
Definition at line 62 of file LocalLinearRegression.cpp.
References lr, and CodeBook::size().
Member Data Documentation
Array< MixtureLinearRegression > LocalLinearRegression::lr
Definition at line 78 of file LocalLinearRegression.h.
Referenced by reset(), and update().
The documentation for this class was generated from the following files:
LocalLinearRegression.h
LocalLinearRegression.cpp