Mixture: KernelDensity Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
KernelDensity Class Reference
A container class for a kernel density estimator.
#include <KernelDensity.h>
Public Member Functions
KernelDensity (double va=0)
Constructs an empty kernel density estimator with a fixed variance.
KernelDensity (const Array< double > &x, double va=0)
Constructs a kernel density estimators with given data points.
void setVar (double va)
Sets the global variance of all kernels.
double variance () const
Returns the global variance.
void set (const Array< double > &x)
Sets the centers of the kernels.
Array< double > sample ()
Creates a pseudo random sample from the estimated distribution.
double p (const Array< double > &pat) const
Computes the value of the estimated pdf for a given data point.
Protected Member Functions
void estimateVariance ()
Estimates the global variance on the basis of the given data.
Detailed Description
A container class for a kernel density estimator.
This class implements a kernel density estimator with Gaussian kernels. The class is derived from MixtureOfGaussians since kernel density estimators can be viewed as special mixture models with identical models and one model centered on each data point.
Author:
M. Kreutz
Date:
1995-01-01
Changes:
none
Status:
stable
Definition at line 67 of file KernelDensity.h.
Constructor & Destructor Documentation
KernelDensity::KernelDensity (double va = 0) [inline]
Constructs an empty kernel density estimator with a fixed variance.
Definition at line 76 of file KernelDensity.h.
KernelDensity::KernelDensity (const Array< double > & x, double va = 0) [inline]
Constructs a kernel density estimators with given data points.
Definition at line 89 of file KernelDensity.h.
References MixtureModel< double >::a, estimateVariance(), CodeBook::m, MixtureOfGaussians::size(), MixtureOfGaussians::v, and MixtureOfGaussians::var().
Member Function Documentation
void KernelDensity::estimateVariance () [protected]
Estimates the global variance on the basis of the given data.
Definition at line 107 of file KernelDensity.cpp.
References CodeBook::m, MixtureOfGaussians::size(), and MixtureOfGaussians::var().
Referenced by KernelDensity(), set(), and setVar().
double KernelDensity::p (const Array< double > & pat) const
Computes the value of the estimated pdf for a given data point.
Reimplemented from MixtureOfGaussians.
Definition at line 78 of file KernelDensity.cpp.
References CodeBook::m, MixtureOfGaussians::size(), MixtureOfGaussians::sqrDistance(), and MixtureOfGaussians::var().
Array< double > KernelDensity::sample ()
Creates a pseudo random sample from the estimated distribution.
Definition at line 48 of file KernelDensity.cpp.
References CodeBook::dim(), MixtureOfGaussians::gauss, CodeBook::m, MixtureOfGaussians::size(), and MixtureOfGaussians::var().
void KernelDensity::set (const Array< double > & x) [inline]
Sets the centers of the kernels.
Definition at line 140 of file KernelDensity.h.
References MixtureModel< double >::a, estimateVariance(), CodeBook::m, MixtureOfGaussians::resize(), MixtureOfGaussians::size(), MixtureOfGaussians::v, and MixtureOfGaussians::var().
void KernelDensity::setVar (double va) [inline]
Sets the global variance of all kernels.
Definition at line 113 of file KernelDensity.h.
References estimateVariance(), MixtureOfGaussians::size(), MixtureOfGaussians::v, and MixtureOfGaussians::var().
double KernelDensity::variance () const [inline]
Returns the global variance.
Definition at line 126 of file KernelDensity.h.
References MixtureOfGaussians::var().
The documentation for this class was generated from the following files:
KernelDensity.h
KernelDensity.cpp