ReClaM: CoverTree.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CoverTree.cpp File Reference
#include <ReClaM/CoverTree.h>
Classes
union IntWiseDouble
Defines
#define POINTSCALE -1022
Functions
double i_pow2 (int exponent)
int i_log2 (double dist2)
bool cmp (const CoverTree::tNode &n1, const CoverTree::tNode &n2)
Define Documentation
#define POINTSCALE -1022
Definition at line 5 of file CoverTree.cpp.
Referenced by CoverTree::CoverTree(), and CoverTree::Insert().
Function Documentation
bool cmp (const CoverTree::tNode & n1, const CoverTree::tNode & n2)
Definition at line 218 of file CoverTree.cpp.
References CoverTree::tNode::dist.
int i_log2 (double dist2)
Definition at line 24 of file CoverTree.cpp.
References IntWiseDouble::d, and IntWiseDouble::i.
Referenced by CoverTree::Insert().
double i_pow2 (int exponent)
Definition at line 15 of file CoverTree.cpp.
References IntWiseDouble::d, and IntWiseDouble::i.
Referenced by CoverTree::KNN(), CoverTree::OneNN(), and CoverTree::SecondNN().