ReClaM: LOO Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LOO Class Reference
Leave One Out (LOO) Error for Support Vector Machines.
#include <LOO.h>
Public Member Functions
LOO ()
Constructor.
~LOO ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Compute the leave one out error for the C-SVM model.
double ComputeB (QpSvmDecomp &qp, const Array< double > &lower, const Array< double > &upper, const Array< double > &alpha)
Compute the SVM offset b.
void setMaxIterations (SharkInt64 maxiter=-1)
set the maximum number of iterations for the quadratic program solver
SharkInt64 iterations ()
return the number of iterations last used by the quadratic program solver
Protected Attributes
SharkInt64 maxIter
maximum number of QpSvmDecomp iterations
SharkInt64 iter
last number if QpSvmDecomp iterations
Detailed Description
Leave One Out (LOO) Error for Support Vector Machines.
The leave one out error is as extreme variant of the cross validation error, where all examples but one are used for training and only the left out example is used for testing. For SVM classifiers, the LOO error can be computed easily as it is known that non-support-vectors do not contribute. On the other hand, for support vectors the optimization can be started from a feasible solution near the full SVM classifier realizing fast convergence.
Examples:
KernelOptimization.cpp.
Definition at line 67 of file LOO.h.
Constructor & Destructor Documentation
LOO::LOO ()
Constructor.
Definition at line 49 of file LOO.cpp.
References maxIter.
LOO::~LOO ()
Destructor.
Definition at line 54 of file LOO.cpp.
Member Function Documentation
double LOO::ComputeB (QpSvmDecomp & qp, const Array< double > & lower, const Array< double > & upper, const Array< double > & alpha)
Compute the SVM offset b.
Definition at line 199 of file LOO.cpp.
References QpSvmDecomp::getGradient().
Referenced by error().
double LOO::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Compute the leave one out error for the C-SVM model.
Implements ErrorFunction.
Definition at line 59 of file LOO.cpp.
References ComputeB(), QpSvmDecomp::ComputeInnerProduct(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM::getKernel(), MetaSVM::getSVM(), i, C_SVM::is2norm(), iter, QpSvmDecomp::iterations(), maxIter, QpSvmDecomp::setMaxIterations(), SVM::SetTrainingData(), and QpSvmDecomp::Solve().
SharkInt64 LOO::iterations () [inline]
return the number of iterations last used by the quadratic program solver
Definition at line 89 of file LOO.h.
References iter.
void LOO::setMaxIterations (SharkInt64 maxiter = -1)
set the maximum number of iterations for the quadratic program solver
Definition at line 234 of file LOO.cpp.
References maxIter.
Member Data Documentation
SharkInt64 LOO::iter [protected]
last number if QpSvmDecomp iterations
Definition at line 99 of file LOO.h.
Referenced by error(), and iterations().
SharkInt64 LOO::maxIter [protected]
maximum number of QpSvmDecomp iterations
Definition at line 96 of file LOO.h.
Referenced by error(), LOO(), and setMaxIterations().
The documentation for this class was generated from the following files:
LOO.h
LOO.cpp