ReClaM: FFNet Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
FFNet Class Reference
Offers the functions to create and to work with a feed-forward network.
#include <FFNet.h>
Public Member Functions
void read (std::istream &is)
Reads the data for the creation of a network from an input stream.
void write (std::ostream &os) const
Writes the data of a network to an output stream.
FFNet (const std::string &filename)
Creates a feed-forward network by reading the necessary information from a file named "filename".
FFNet (const unsigned in=0, const unsigned out=0)
Creates an empty feed-forward network with "in" input neurons and "out" output neurons.
FFNet (const unsigned in, const unsigned out, const Array< int > &cmat)
Creates a feed-forward network with "in" input neurons and "out" output neurons.
FFNet (const unsigned in, const unsigned out, const Array< int > &cmat, const Array< double > &wmat)
Creates a feed-forward network with "in" input neurons and "out" output neurons.
virtual ~FFNet ()
Destructs an feed forward network object.
FFNet & operator= (const FFNet &net)
Assigns the data of network "net" to the current network.
FFNet (const FFNet &net)
Copies the values of object "net" to the current object.
double & weight (unsigned i, unsigned j)
Returns the weight value at position in the weight matrix.
int & connection (unsigned i, unsigned j)
Returns the value at position of the connection matrix.
virtual void initWeights (long seed=42, double l=-.5, double h=.5)
Initializes the random number generator and the weights of the net.
virtual void initWeights (double l=-.5, double h=.5)
Initializes the weights of the net.
void seed (long s)
Initializes the random number generator.
const Array< double > & getWeights ()
Returns the current weightMatrix.
const Array< int > & getConnections ()
Returns the current connectionMatrix.
double outputValue (unsigned i)
Returns the output value of neuron no. "i".
void model (const Array< double > &input, Array< double > &output)
Uses the input pattern(s) input for the Feed Forward Net model to produce the output vector(s) output.
void modelDerivative (const Array< double > &input, Array< double > &derivative)
Reads in one input pattern for the Feed Forward Net model and calculates the derivatives of the resulting network output with respect to the weights.
void modelDerivative (const Array< double > &input, Array< double > &output, Array< double > &derivative)
Reads in one input pattern for the Feed Forward Net model and calculates the derivatives of the resulting network output with respect to the weights.
void generalDerivative (const Array< double > &input, const Array< double > &coeffs, Array< double > &derivative)
Calculates the model's general derivative.
void readParameters ()
Reads the parameters (weight and bias values) from the parameter vector ModelInterface::w and stores them in the weightMatrix.
void writeParameters ()
Reads the parameters (weight and bias values) from the weightMatrix and writes them to the parameter vector ModelInterface::w.
void setStructure (const Array< int > &cmat)
Based on a given connectionMatrix the structure of the current network is modified.
void setStructure (const Array< double > &wmat, bool preserve=false)
Based on a given weightMatrix the structure of the current network is modified.
void setStructure (const Array< int > &cmat, const Array< double > &wmat)
Based on a given connectionMatrix and a weightMatrix the structure of the current network is modified.
void setStructure (unsigned in, unsigned hidden1, unsigned hidden2, unsigned out, bool ff_layer=true, bool ff_in_out=true, bool ff_all=true, bool bias=true)
Sets connection structure of a network with two hidden layers.
void setStructure (Array< unsigned > &layers, bool ff_layer=true, bool ff_in_out=true, bool ff_all=true, bool bias=true)
Sets connection structure of the network.
void setStructure (unsigned in, unsigned hidden, unsigned out, bool ff_layer=true, bool ff_in_out=true, bool ff_all=true, bool bias=true)
Sets connection structure of a network with a single hidden layer.
void writeSource (std::ostream &os, const char *g, const char *gOut, unsigned p=4)
Writes the network to an outout stream as plain C code.
Protected Member Functions
virtual double g (double a)
Activation function of the hidden neurons.
virtual double dg (double a)
Computes the derivative of the activation function for the hidden neurons.
virtual double gOutput (double a)
Activation function of the output neurons.
virtual double dgOutput (double a)
Computes the derivative of the activation function for the output neurons.
virtual void resize ()
Reserves memory for all internal net data structures.
void activate (const Array< double > &in)
The input pattern "in" is used to activate the neurons of the net and produce some result at the output neurons.
void backprop (Array< double > &derivative)
Performs a backpropagation to calculate the derivatives of the outputs with respect to the parameters of the network.
void replaceInString (const std::string &str, std::string &newString, const std::string &token, const std::string &newToken1, int newToken2, const std::string &newToken3)
Auxiliary function for writeSource.
Protected Attributes
unsigned numberOfNeurons
Number of all network neurons.
unsigned bias
Index of bias weight in the weight matrix.
unsigned firstOutputNeuron
Index of the first output neuron.
Array< int > connectionMatrix
Matrix that identifies the connection status between all neurons.
Array< double > weightMatrix
Corresponding to the connectionMatrix, this matrix defines the weight of the considered connection.
double * z
Used to store the current results of the activation function for all neurons for the input pattern .
Array< double > d
Used for temporary storage for the local gradient delta values for all output neurons.
Array< double > delta
Detailed Description
Offers the functions to create and to work with a feed-forward network.
Together with an error measure and an optimization algorithm class you can use this feed-forward network class to produce your own optimization tool.
Author:
C. Igel
Date:
1999
Changes:
none
Status:
stable
Definition at line 84 of file FFNet.h.
Constructor & Destructor Documentation
FFNet::FFNet (const std::string & filename)
Creates a feed-forward network by reading the necessary information from a file named "filename".
FFNet::FFNet (const unsigned in = 0, const unsigned out = 0)
Creates an empty feed-forward network with "in" input neurons and "out" output neurons.
Constructor no. 1
Only the input and output dimensions are set, but the network will contain no neurons.
Parameters:
in Dimension of the input (no. of input neurons).
out Dimension of the output (no. of output neurons).
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 660 of file FFNet.cpp.
FFNet::FFNet (const unsigned in, const unsigned out, const Array< int > & cmat)
Creates a feed-forward network with "in" input neurons and "out" output neurons.
Creates a feed-forward network with "in" input neurons and "out" output neurons. Additionally, the array "cmat" determines the topology (i.e., number of neurons and their connections).
Additionally, the array "cmat" determines the topology (i.e., number of neurons and their connections).
Constructor no. 2
A network with the given connections will be created, memory for the weightMatrix reserved, but the weights for all connections will be set to zero.
Parameters:
in Dimension of the input (no. of input neurons).
out Dimension of the output (no. of output neurons).
cmat The connectionMatrix.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
2002-01-09, ci
Memory leackage removed.
Status
stable
Definition at line 702 of file FFNet.cpp.
FFNet::FFNet (const unsigned in, const unsigned out, const Array< int > & cmat, const Array< double > & wmat)
Creates a feed-forward network with "in" input neurons and "out" output neurons.
Creates a feed-forward network with "in" input neurons and "out" output neurons. Additionally, the arrays "cmat" and "wmat" determine the topology (i.e., number of neurons and their connections) as well as the connection weights.
Additionally, the arrays "cmat" and "wmat" determine the topology (i.e., number of neurons and their connections) as well as the connection weights.
Constructor no. 3
A network with the given connections and weights will be created.
Parameters:
in Dimension of the input (no. of input neurons).
out Dimension of the output (no. of output neurons).
cmat The connectionMatrix.
wmat The weightMatrix.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
2002-01-09, ci
Memory leackage removed.
Status
stable
Definition at line 760 of file FFNet.cpp.
FFNet::~FFNet () [virtual]
Destructs an feed forward network object.
Destructor.
Warning:
none
Bug:
none
Changes
none
Status
none
Definition at line 67 of file FFNet.cpp.
FFNet::FFNet (const FFNet & net) [inline]
Copies the values of object "net" to the current object.
This operator is defined in order to prevent the implicit definition by the compiler (which would result in unwanted behavior, e.g. if the object contains pointer members).
Parameters:
net Object, which values are copied.
Returns:
A reference to the current object (after the copy process).
Author:
C. Igel
Date:
2001
Changes
2002-01-08: ci
Constructor totally changed to remove memory leackage that lead to crashes, too.
Status
stable
Definition at line 188 of file FFNet.h.
References z.
Member Function Documentation
void FFNet::activate (const Array< double > & in) [inline, protected]
The input pattern "in" is used to activate the neurons of the net and produce some result at the output neurons.
The input vector in contains a pattern given to the input neurons. The input will be propagated through the network and produce some "reaction" at the output neurons, depending one the weights of the single connections. The activation of the input neurons is done by
so the input neurons only propagate the input values. For the further propagation of the input values through the hidden to the output neurons, sigmoid activation functions given by the methods g and gOutput are used.
Parameters:
in The input pattern.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 444 of file FFNet.h.
References bias, connectionMatrix, firstOutputNeuron, g(), gOutput(), i, Model::inputDimension, numberOfNeurons, weight(), and z.
Referenced by LMSEFFNet::errorDerivative().
void FFNet::backprop (Array< double > & derivative) [inline, protected]
Performs a backpropagation to calculate the derivatives of the outputs with respect to the parameters of the network.
Performs backpropagation to calculate the derivatives of the outputs with respect to the parameters of the network.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 375 of file FFNet.cpp.
References i.
int& FFNet::connection (unsigned i, unsigned j) [inline]
Returns the value at position of the connection matrix.
If a connection exists from neuron no. to neuron no. with , then the function will return "1". If there is no connection or if then the function will return zero.
If you have a matrix , then for will indicate the status of the connection between the neuron no. and the bias value. For all input neurons, this status value is always zero.
Parameters:
i Connection end point.
j Connection start point.
Returns:
Status of connection .
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 254 of file FFNet.h.
References connectionMatrix.
Referenced by LMSEFFNet::errorDerivative().
double FFNet::dg (double ga) [protected, virtual]
Computes the derivative of the activation function for the hidden neurons.
Computes the derivative of the activation function for the hidden neurons given .
The derivative function is defined as
Parameters:
ga The value of .
Returns:
The result of
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
g
Reimplemented in ProbenBNet, and TanhNet.
Definition at line 144 of file FFNet.cpp.
Referenced by LMSEFFNet::errorDerivative().
double FFNet::dgOutput (double ga) [protected, virtual]
Computes the derivative of the activation function for the output neurons.
The derivative function is defined as
Parameters:
ga The value of .
Returns:
The result of
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
gOutput, dg
Reimplemented in LinOutFFNet, LinOutMSEBFFNet, and TanhNet.
Definition at line 223 of file FFNet.cpp.
Referenced by LMSEFFNet::errorDerivative().
double FFNet::g (double a) [protected, virtual]
Activation function of the hidden neurons.
The activation function is used for the propagation of the input through the network. Given a network with neurons, including input neurons and output neurons, the sigmoid activation function for the hidden neuron with index is given by
where as the propagated result of the input for the previous neurons is calculated as
and denotes the bias term.
Parameters:
a Input for the activation function, see above.
Returns:
.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
gOutput
Reimplemented in ProbenBNet, and TanhNet.
Definition at line 111 of file FFNet.cpp.
Referenced by activate().
void FFNet::generalDerivative (const Array< double > & input, const Array< double > & coefficient, Array< double > & derivative) [virtual]
Calculates the model's general derivative.
After a call of model, generalDerivative calculates the gradient and stores it in derivative. Here is some input pattern, and denotes the parameter vector of the model and its th component. The index indicates the th output. The coefficients can be chosen freely.
The point of this function is that for many models, the complexity of calculating this linear combination of gradients is the same as of calculating a single output gradient
Via the chain rule, the gradient of _any_ (e.g., error) functional can be calculated.
Example 1: Let , then
is the parameter gradient of an MSE with respect to target values As above, the index runs over the outputs.
Example 2: Let , then the gradients of only the th output will be calculated:
and
The default implementation is the computationally inefficient usage of modelDerivative.
Parameters:
input the corefficients in the formula above.
coefficient the corefficients in the formula above.
derivative the calculated model's general derivative.
Returns:
None.
Author:
M. Toussaint, C. Igel
Date:
2002
Reimplemented from Model.
Definition at line 495 of file FFNet.cpp.
References i.
const Array< int > & FFNet::getConnections ()
Returns the current connectionMatrix.
Returns:
The connectionMatrix.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 1461 of file FFNet.cpp.
const Array< double > & FFNet::getWeights ()
Returns the current weightMatrix.
The weight values are read from the parameter vector Model::parameter and stored in the weightMatrix, then the matrix is returned.
Returns:
The weightMatrix.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 1439 of file FFNet.cpp.
double FFNet::gOutput (double a) [protected, virtual]
Activation function of the output neurons.
The activation function is used for the propagation of the input through the network. Given a network with neurons, including input neurons and output neurons, the sigmoid activation function for the output neuron with index is given as
where as the propagated result of the input for the previous neurons is calculated as
and denotes the bias term.
Parameters:
a Input for the activation function, see above.
Returns:
.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
g
Reimplemented in LinOutFFNet, LinOutMSEBFFNet, and TanhNet.
Definition at line 190 of file FFNet.cpp.
Referenced by activate().
void FFNet::initWeights (long seed = 42, double l = -.5, double h = .5) [virtual]
Initializes the random number generator and the weights of the net.
After initializing the random number generator with a seed value, the weight values of the network are initialized with uniformly distributed random numbers.
Parameters:
seed Initialization value for random number generator, default value is "42".
l Lower bound for weight random numbers, default value is "-0.5".
h Upper bound for weight random numbers, default value is "0.5".
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 254 of file FFNet.cpp.
References i.
void FFNet::initWeights (double l = -.5, double h = .5) [inline, virtual]
Initializes the weights of the net.
The weight values of the network are initialized with uniformly distributed random numbers.
Parameters:
l Lower bound for weight random numbers, default value is "-0.5".
h Upper bound for weight random numbers, default value is "0.5".
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
initWeights(long seed, double l, double h)
Definition at line 292 of file FFNet.cpp.
References i.
void FFNet::model (const Array< double > & input, Array< double > & output) [inline, virtual]
Uses the input pattern(s) input for the Feed Forward Net model to produce the output vector(s) output.
Uses the input pattern(s) "in" for the Feed Forward Net model to produce the output vector(s) "output".
The given input pattern(s) in input are propagated forward through the net by using the activate function for all patterns sequentially. After each propagation the result in the output neurons is stored in the output vector(s) output.
Parameters:
input Input pattern(s) for the model.
output Output vector(s).
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
activate
Implements Model.
Examples:
simpleFFNet.cpp.
Definition at line 330 of file FFNet.cpp.
References i.
void FFNet::modelDerivative (const Array< double > & input, Array< double > & derivative) [virtual]
Reads in one input pattern for the Feed Forward Net model and calculates the derivatives of the resulting network output with respect to the weights.
The single input pattern in is used to activate the neurons of the network. The results, given in the output neurons are then used to calculate the derivatives of the output with respect to the weights of the network.
Parameters:
input The single input pattern. If more than one pattern is given, the method exits with an exception.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
See also:
backprop
Reimplemented from Model.
Reimplemented in MSEFFNet.
Definition at line 566 of file FFNet.cpp.
void FFNet::modelDerivative (const Array< double > & input, Array< double > & output, Array< double > & derivative) [virtual]
Reads in one input pattern for the Feed Forward Net model and calculates the derivatives of the resulting network output with respect to the weights.
Reads in one input pattern for the Feed Forward Net model and calculates the derivatives of the resulting network output with respect to the weights. Furthermore, the network output is given back.
Furthermore, the network output is given back.
Equal to method #modelDerivative(const Array<double> &input), but here the output of the network is not only used for the calculation, but also stored in output.
Parameters:
input Input pattern for the model.
output Output for the input pattern.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Reimplemented from Model.
Reimplemented in MSEFFNet.
Definition at line 457 of file FFNet.cpp.
References i.
FFNet& FFNet::operator= (const FFNet & net) [inline]
Assigns the data of network "net" to the current network.
This operator is defined in order to prevent the implicit definition by the compiler, because a feed forward network includes dynamic structures, that must be properly assigned.
Parameters:
net Second network, whose data is assigned to the current network.
Returns:
A reference to the current network (after assignment).
Author:
C. Igel
Date:
1999
Changes
2002-01-08, ci:
Added some commands to remove memory leackage that lead crashes, too.
Status
stable
Definition at line 143 of file FFNet.h.
References bias, connectionMatrix, d, delta, firstOutputNeuron, Model::getInputDimension(), Model::getOutputDimension(), Model::inputDimension, numberOfNeurons, Model::outputDimension, Model::parameter, weightMatrix, and z.
double FFNet::outputValue (unsigned i) [inline]
Returns the output value of neuron no. "i".
Given an index i, the function returns the value, that was calculated by the activation function for the neuron no. i for the last given input pattern.
Parameters:
i Index of the neuron.
Returns:
Output value of the neuron.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 320 of file FFNet.h.
References i, and z.
void FFNet::read (std::istream & is) [virtual]
Reads the data for the creation of a network from an input stream.
Reimplemented from Model.
void FFNet::readParameters ()
Reads the parameters (weight and bias values) from the parameter vector ModelInterface::w and stores them in the weightMatrix.
Reads the parameters (weights) from the parameter vector Model::parameter and stores them in the weightMatrix.
In feed forward networks connections and the corresponding weights can exist only from neurons with no. to neurons with no. with . So to save space, the parameters, i.e. the values for the connection weights are internally stored in a vector. But a matrix offers a more concise view so this function reads in the parameter vector Model::parameter and writes the values to the weightMatrix.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 1395 of file FFNet.cpp.
References i.
Referenced by LMSEFFNet::errorDerivative().
void FFNet::replaceInString (const std::string & str, std::string & newString, const std::string & token, const std::string & newToken1, int newToken2, const std::string & newToken3) [protected]
Auxiliary function for writeSource.
Definition at line 1617 of file FFNet.cpp.
void FFNet::resize () [protected, virtual]
Reserves memory for all internal net data structures.
For the internal administration of a network several dynamic data structures are used. Based on the size of the connectionMatrix and the values of Model::inputDimension and ModelInterface::outputDimension, the memory for all other data is reserved.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
2002-01-08, ci
Some commands added to remove memory leackage, that lead to crashes.
Status
stable
Reimplemented in MSEFFNet.
Definition at line 612 of file FFNet.cpp.
References i.
void FFNet::seed (long s) [inline]
Initializes the random number generator.
Parameters:
s The init (seed) value for the random number generator.
Returns:
None.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 285 of file FFNet.h.
void FFNet::setStructure (Array< unsigned > & layers, bool ff_layer = true, bool ff_in_out = true, bool ff_all = true, bool bias = true)
Sets connection structure of the network.
Creates a connection matrix for a network.
Automatically creates a connection matrix with several layers, with the numbers of neurons for each layer defined by layers and (standard) connections defined by ff_layer, ff_in_out, ff_all and bias.
Parameters:
layers contains the numbers of neurons for each layer of the network.
ff_layer if set to true, connections from each neuron of layer to each neuron of layer will be set for all layers.
ff_in_out if set to true, connections from all input neurons to all output neurons will be set.
ff_all if set to true, connections from all neurons of layer to all neurons of layers with will be set for all layers .
bias if set to true, connections from all neurons (except the input neurons) to the bias will be set.
Returns:
none
Author:
C. Igel, M. Hüsken
Date:
2002
Changes
none
Status
stable
Definition at line 957 of file FFNet.cpp.
void FFNet::setStructure (const Array< int > & cmat)
Based on a given connectionMatrix the structure of the current network is modified.
This function will use the information in the given connectionMatrix cmat to modify the network. The weights for all neurons of the new connectionMatrix are initialized by zero.
Parameters:
cmat The connectionMatrix that provides the basis information for the creation of the network.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 1180 of file FFNet.cpp.
void FFNet::setStructure (const Array< int > & cmat, const Array< double > & wmat)
Based on a given connectionMatrix and a weightMatrix the structure of the current network is modified.
This function will use the information in the given connectionMatrix cmat and the weightMatrix wmat to modify the network.
Parameters:
cmat The connectionMatrix that provides the basis information for the modification of the network.
wmat The weightMatrix that provides the basis information for the modification of the network.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 893 of file FFNet.cpp.
void FFNet::setStructure (const Array< double > & wmat, bool preserve = false)
Based on a given weightMatrix the structure of the current network is modified.
This function will use the values of ModelInterface::inputDimension, ModelInterface::outputDimension and the information in the given weightMatrix wmat to change the structure of the network. An existing connection matrix (that is compatible to the the new weightMatrix wmat) can be adopted or a new one will be created with the data of the weightMatrix.
Parameters:
wmat The weightMatrix that provides the basis information for the modification of the network.
preserve If set to "true", the existing connectionMatrix will be kept. In case of inconsistency between the weightMatrix and the connectionMatrix the function will exit with an exception.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
2002-01-08, ci
Added some commands to remove memory leackage, that lead to crashes, too.
Status
stable
Definition at line 1239 of file FFNet.cpp.
References i.
void FFNet::setStructure (unsigned in, unsigned hidden, unsigned out, bool ff_layer = true, bool ff_in_out = true, bool ff_all = true, bool bias = true)
Sets connection structure of a network with a single hidden layer.
Creates a connection matrix for a network with a single hidden layer.
Automatically creates a connection matrix for a network with three different layers: An input layer with in input neurons, an output layer with out output neurons and a single hidden layer with hidden hidden neurons. (Standard) connections can be defined by ff_layer, ff_in_out, ff_all and bias.
Parameters:
in number of input neurons.
hidden number of neurons of the single hidden layer.
out number of output neurons.
ff_layer if set to true, connections from each neuron of layer to each neuron of layer will be set for all layers.
ff_in_out if set to true, connections from all input neurons to all output neurons will be set.
ff_all if set to true, connections from all neurons of layer to all neurons of layers with will be set for all layers .
bias if set to true, connections from all neurons (except the input neurons) to the bias will be set.
Returns:
none
Author:
C. Igel, M. Hüsken
Date:
2002
Changes
none
Status
stable
Definition at line 1086 of file FFNet.cpp.
void FFNet::setStructure (unsigned in, unsigned hidden1, unsigned hidden2, unsigned out, bool ff_layer = true, bool ff_in_out = true, bool ff_all = true, bool bias = true)
Sets connection structure of a network with two hidden layers.
Creates a connection matrix for a network with two hidden layers.
Automatically creates a connection matrix for a network with four different layers: An input layer with in input neurons, an output layer with out output neurons and two hidden layers with hidden1 and hidden2 hidden neurons, respectively. (Standard) connections can be defined by ff_layer, ff_in_out, ff_all and bias.
Parameters:
in number of input neurons.
hidden1 number of neurons of the first hidden layer.
hidden2 number of neurons of the second hidden layer.
out number of output neurons.
ff_layer if set to true, connections from each neuron of layer to each neuron of layer will be set for all layers.
ff_in_out if set to true, connections from all input neurons to all output neurons will be set.
ff_all if set to true, connections from all neurons of layer to all neurons of layers with will be set for all layers .
bias if set to true, connections from all neurons (except the input neurons) to the bias will be set.
Returns:
none
Author:
C. Igel, M. Hüsken
Date:
2002
Changes
none
Status
stable
Definition at line 1141 of file FFNet.cpp.
double& FFNet::weight (unsigned i, unsigned j) [inline]
Returns the weight value at position in the weight matrix.
The weight matrix corresponds to the connection matrix. If a connection exists from neuron no. to neuron no. with , then the function will return a weight value greater than zero for this connection. If there is no connection or if then the function will return zero.
If you have a matrix , then for will give the weight of the connection between the neuron no. and the bias value.
Parameters:
i Connection end point.
j Connection start point.
Returns:
The weight of the connection .
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 223 of file FFNet.h.
References weightMatrix.
Referenced by activate(), and LMSEFFNet::errorDerivative().
void FFNet::write (std::ostream & os) const [virtual]
Writes the data of a network to an output stream.
Reimplemented from Model.
void FFNet::writeParameters ()
Reads the parameters (weight and bias values) from the weightMatrix and writes them to the parameter vector ModelInterface::w.
Reads the parameters (weights) from the weightMatrix and writes them to the parameter vector Model::parameter.
In feed forward networks connections and the corresponding weights can exist only from neurons with no. to neurons with no. with . So to save space, the parameters, i.e. the values for the connection weights are internally stored in a vector. But a matrix offers a more concise view so this function reads in the original (extended) weightMatrix and stores the values in the parameter vector Model::parameter.
Returns:
None.
Author:
C. Igel
Date:
2002
Changes
none
Status
stable
Definition at line 1346 of file FFNet.cpp.
References i.
void FFNet::writeSource (std::ostream & os, const char * g, const char * gOut, unsigned p = 4)
Writes the network to an outout stream as plain C code.
Definition at line 1635 of file FFNet.cpp.
References i.
Member Data Documentation
unsigned FFNet::bias [protected]
Index of bias weight in the weight matrix.
The bias term can be considered as an extra input neuron , whose activation is permanently set to . The index is used for direct access of the weight for the bias connection in the weight matrix.
See also:
weightMatrix
Definition at line 498 of file FFNet.h.
Referenced by activate(), LMSEFFNet::errorDerivative(), and operator=().
Array< int > FFNet::connectionMatrix [protected]
Matrix that identifies the connection status between all neurons.
If the network consists of neurons, this is a matrix where a value of "1" at position denotes a connection between neuron to neuron with , a value of zero means no connection.
The last column of the matrix indicates the connection of the current neuron (given by the row number) to the bias value.
For all input neurons, this value is always zero.
See also:
weightMatrix
Definition at line 536 of file FFNet.h.
Referenced by activate(), connection(), and operator=().
Array< double > FFNet::d [protected]
Used for temporary storage for the local gradient delta values for all output neurons.
Given a network with neurons, including input and output neurons, is a Array. The delta values for each output neuron are calculated in a backwards pass, starting with the output neurons. The delta values for output neuron are then given as:
for and
for . Taken these values as base, the delta values for the hidden neurons with index are calculated as:
where is the weight of an existing connection from neuron no. to neuron no. . These temporary values are then used for the calculation of the partial derivatives of the outputs with respect to the parameters as performed in backprop.
See also:
dg, dgOutput, backprop
Definition at line 630 of file FFNet.h.
Referenced by LMSEFFNet::errorDerivative(), MSEFFNet::MSEFFNet(), operator=(), and MSEFFNet::resize().
Array< double > FFNet::delta [protected]
Definition at line 633 of file FFNet.h.
Referenced by operator=().
unsigned FFNet::firstOutputNeuron [protected]
Index of the first output neuron.
This value is used for direct access of the output neurons, especially when working with the list z of activation results for all neurons.
Definition at line 509 of file FFNet.h.
Referenced by activate(), LMSEFFNet::errorDerivative(), and operator=().
unsigned FFNet::numberOfNeurons [protected]
Number of all network neurons.
This is the total number of neurons in the network, i.e. input, hidden and output neurons.
Definition at line 484 of file FFNet.h.
Referenced by activate(), LMSEFFNet::errorDerivative(), MSEFFNet::MSEFFNet(), operator=(), and MSEFFNet::resize().
Array< double > FFNet::weightMatrix [protected]
Corresponding to the connectionMatrix, this matrix defines the weight of the considered connection.
If the network consists of neurons, this is a matrix where a value of at position denotes, that the connection between neuron to neuron with has a weight of . If in the connectionMatrix, then . For each neuron there is also a so-called bias term at the last position of each matrix row:
See also:
connectionMatrix
Definition at line 566 of file FFNet.h.
Referenced by operator=(), and weight().
double* FFNet::z [protected]
Used to store the current results of the activation function for all neurons for the input pattern .
Given a network with neurons, including input and output neurons the single values for are given as:
See also:
g, gOutput
Definition at line 586 of file FFNet.h.
Referenced by activate(), LMSEFFNet::errorDerivative(), FFNet(), operator=(), and outputValue().
The documentation for this class was generated from the following files:
FFNet.h
FFNet.cpp