ReClaM: NoisySvmLikelihood Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
NoisySvmLikelihood Class Reference
model selection objective for SVMs
#include <NoisySvmLikelihood.h>
Public Member Functions
NoisySvmLikelihood (double trainFraction=0.8)
Constructor.
~NoisySvmLikelihood ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
computation of the negative log likelihood
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
computation of the negative log likelihood and its derivatives w.r.t.
Protected Attributes
double trainFraction
fraction of the data used for training
Detailed Description
model selection objective for SVMs
Definition at line 54 of file NoisySvmLikelihood.h.
Constructor & Destructor Documentation
NoisySvmLikelihood::NoisySvmLikelihood (double trainFraction = 0.8)
Constructor.
Parameters:
trainFraction fraction of the data used for SVM training
Definition at line 68 of file NoisySvmLikelihood.cpp.
References trainFraction.
NoisySvmLikelihood::~NoisySvmLikelihood ()
Destructor.
Definition at line 75 of file NoisySvmLikelihood.cpp.
Member Function Documentation
double NoisySvmLikelihood::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
computation of the negative log likelihood
Implements ErrorFunction.
Definition at line 80 of file NoisySvmLikelihood.cpp.
References NegativeLogLikelihood::error(), Model::getParameter(), i, IRpropPlus::init(), SVM_Optimizer::init(), SVM::model(), IRpropPlus::optimize(), SVM_Optimizer::optimize(), Model::setParameter(), and trainFraction.
double NoisySvmLikelihood::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
computation of the negative log likelihood and its derivatives w.r.t.
the model parameters
Reimplemented from ErrorFunction.
Definition at line 155 of file NoisySvmLikelihood.cpp.
References NegativeLogLikelihood::error(), Model::getParameter(), i, IRpropPlus::init(), SVM_Optimizer::init(), SimpleSigmoidModel::model(), SVM::model(), IRpropPlus::optimize(), SVM_Optimizer::optimize(), Model::setParameter(), and trainFraction.
Member Data Documentation
double NoisySvmLikelihood::trainFraction [protected]
fraction of the data used for training
Definition at line 74 of file NoisySvmLikelihood.h.
Referenced by error(), errorDerivative(), and NoisySvmLikelihood().
The documentation for this class was generated from the following files:
NoisySvmLikelihood.h
NoisySvmLikelihood.cpp