ReClaM: LinearRegression Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LinearRegression Class Reference
Linear Regression.
#include <LinearRegression.h>
Public Member Functions
LinearRegression ()
~LinearRegression ()
void init (Model &model)
basic initialization with default parameters
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Performes one optimization step, for example a gradient descent step or an evolution cycle.
double optimize (AffineLinearMap &model, const Array< double > &input, const Array< double > &target)
Detailed Description
Linear Regression.
Linear Regression builds an affine linear model minimizing the squared error from a dataset of pairs of vectors (x, y). That is, the error is minimized. The solution to this problem is found analytically.
Examples:
LinearRegressionTest.cpp.
Definition at line 68 of file LinearRegression.h.
Constructor & Destructor Documentation
LinearRegression::LinearRegression ()
Definition at line 52 of file LinearRegression.cpp.
LinearRegression::~LinearRegression ()
Definition at line 56 of file LinearRegression.cpp.
Member Function Documentation
void LinearRegression::init (Model & model) [virtual]
basic initialization with default parameters
Implements Optimizer.
Examples:
LinearRegressionTest.cpp.
Definition at line 61 of file LinearRegression.cpp.
double LinearRegression::optimize (AffineLinearMap & model, const Array< double > & input, const Array< double > & target)
Definition at line 74 of file LinearRegression.cpp.
References Model::getInputDimension(), Model::getOutputDimension(), i, and Model::setParameter().
double LinearRegression::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Performes one optimization step, for example a gradient descent step or an evolution cycle.
Parameters:
model Model to use for the computation.
errorfunction ErrorFunction on which decisions are based.
input Vector of input values.
target Vector of output values.
Returns:
The error E returned by the ErrorFunction.
Implements Optimizer.
Examples:
LinearRegressionTest.cpp.
Definition at line 67 of file LinearRegression.cpp.
The documentation for this class was generated from the following files:
LinearRegression.h
LinearRegression.cpp