ReClaM: CachedMatrix Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CachedMatrix Class Reference
Efficient quadratic matrix cache.
#include <KernelMatrices.h>
Classes
struct tCacheEntry
Public Member Functions
CachedMatrix (QPMatrix *base, unsigned int cachesize=0x4000000)
Constructor.
~CachedMatrix ()
Destructor.
float * Row (unsigned int k, unsigned int begin, unsigned int end, bool temp=false, bool keep=false)
Return a subset of a matrix row.
float Entry (unsigned int i, unsigned int j)
overriden virtual function
void FlipColumnsAndRows (unsigned int i, unsigned int j)
Exchange the rows i and j and the columns i and j.
unsigned int getMaxCacheSize () const
unsigned int getCacheSize () const
unsigned int getCacheRowSize (unsigned int k)
void Clear ()
void CacheRowResize (unsigned int k, unsigned int newsize)
void CacheRowRelease (unsigned int k)
SharkInt64 getBaseMatrixKernelEvals ()
get number of kernel evaluations
void resetBaseMatrixKernelEvals ()
set kernel evaluation counter to zero
Protected Member Functions
void cacheAppend (int var)
append the entry to the ordered list
void cacheRemove (int var)
remove the entry from the ordered list
void cacheAdd (int var, unsigned int length)
add an entry to the cache and append it to the ordered list
void cacheDelete (int var)
remove an entry from the cache and the ordered list
void cacheResize (int var, unsigned int newlength)
resize a cache entry
void cacheClear ()
completely clear the cache
Protected Attributes
QPMatrix * baseMatrix
matrix to be cached
unsigned int cacheSize
unsigned int cacheMaxSize
std::vector< tCacheEntry > cacheEntry
std::vector< float > cacheTemp
int cacheNewest
int cacheOldest
Detailed Description
Efficient quadratic matrix cache.
The access operations of the CachedMatrix class are specially tuned towards the iterative solution of quadratic programs resulting in sparse solutions.
In contrast to the QPMatrix base class, the desired access operation is Row. Algorithms should try to rely on the Row method for retreiving matrix values because the Entry method does not cache its computations.
Definition at line 297 of file KernelMatrices.h.
Constructor & Destructor Documentation
CachedMatrix::CachedMatrix (QPMatrix * base, unsigned int cachesize = 0x4000000)
Constructor.
Parameters:
base Matrix to cache
cachesize Main memory to use as a kernel cache, in floats. Default is 256MB
Definition at line 231 of file KernelMatrices.cpp.
References baseMatrix, cacheEntry, cacheMaxSize, cacheNewest, cacheOldest, cacheSize, i, and QPMatrix::matrixsize.
CachedMatrix::~CachedMatrix ()
Destructor.
Definition at line 254 of file KernelMatrices.cpp.
References cacheClear().
Member Function Documentation
void CachedMatrix::cacheAdd (int var, unsigned int length) [protected]
add an entry to the cache and append it to the ordered list
Definition at line 420 of file KernelMatrices.cpp.
References cacheAppend(), cacheEntry, and cacheSize.
Referenced by CacheRowResize(), and Row().
void CachedMatrix::cacheAppend (int var) [protected]
append the entry to the ordered list
Definition at line 386 of file KernelMatrices.cpp.
References cacheEntry, cacheNewest, and cacheOldest.
Referenced by cacheAdd(), and Row().
void CachedMatrix::cacheClear () [protected]
completely clear the cache
Definition at line 451 of file KernelMatrices.cpp.
References cacheEntry, cacheNewest, cacheOldest, and cacheSize.
Referenced by Clear(), and ~CachedMatrix().
void CachedMatrix::cacheDelete (int var) [protected]
remove an entry from the cache and the ordered list
Definition at line 430 of file KernelMatrices.cpp.
References cacheEntry, cacheRemove(), and cacheSize.
Referenced by CacheRowRelease(), and Row().
void CachedMatrix::cacheRemove (int var) [protected]
remove the entry from the ordered list
Definition at line 404 of file KernelMatrices.cpp.
References cacheEntry, cacheNewest, and cacheOldest.
Referenced by cacheDelete(), and Row().
void CachedMatrix::cacheResize (int var, unsigned int newlength) [protected]
resize a cache entry
Definition at line 441 of file KernelMatrices.cpp.
References cacheEntry, and cacheSize.
Referenced by CacheRowResize(), and Row().
void CachedMatrix::CacheRowRelease (unsigned int k)
Definition at line 381 of file KernelMatrices.cpp.
References cacheDelete(), and cacheEntry.
Referenced by QpMcStzDecomp::DeactivateExample(), QpMcDecomp::DeactivateExample(), QpEbCsDecomp::deactivateExample(), QpEbCsDecomp::performSmoStep(), QpSvmDecomp::Shrink(), QpBoxDecomp::Shrink(), and QpEbCsDecomp::Solve().
void CachedMatrix::CacheRowResize (unsigned int k, unsigned int newsize)
Definition at line 375 of file KernelMatrices.cpp.
References cacheAdd(), cacheEntry, and cacheResize().
Referenced by QpSvmDecomp::Shrink(), QpMcStzDecomp::Shrink(), QpMcDecomp::Shrink(), and QpBoxDecomp::Shrink().
void CachedMatrix::Clear () [inline]
Definition at line 356 of file KernelMatrices.h.
References cacheClear().
float CachedMatrix::Entry (unsigned int i, unsigned int j) [virtual]
overriden virtual function
Implements QPMatrix.
Definition at line 324 of file KernelMatrices.cpp.
References baseMatrix, and QPMatrix::Entry().
Referenced by QpSvmDecomp::ComputeInnerProduct(), QpBoxDecomp::QpBoxDecomp(), QpEbCsDecomp::QpEbCsDecomp(), QpSvmDecomp::QpSvmDecomp(), QpMcStzDecomp::Solve(), and QpMcDecomp::Solve().
void CachedMatrix::FlipColumnsAndRows (unsigned int i, unsigned int j) [virtual]
Exchange the rows i and j and the columns i and j.
W.l.o.g. it is assumed that . It may be advantageous for caching to reorganize the column order. In order to keep symmetric matrices symmetric the rows are swapped, too.
Parameters:
i first row/column index
j second row/column index
Implements QPMatrix.
Definition at line 329 of file KernelMatrices.cpp.
References baseMatrix, cacheEntry, cacheNewest, cacheOldest, QPMatrix::Entry(), QPMatrix::FlipColumnsAndRows(), i, QPMatrix::matrixsize, and XCHG_V.
Referenced by QpMcStzDecomp::DeactivateExample(), QpMcDecomp::DeactivateExample(), QpEbCsDecomp::flipAll(), QpSvmDecomp::FlipCoordinates(), and QpBoxDecomp::FlipCoordinates().
SharkInt64 CachedMatrix::getBaseMatrixKernelEvals () [inline]
get number of kernel evaluations
Definition at line 363 of file KernelMatrices.h.
References baseMatrix, and QPMatrix::getAccessCount().
Referenced by QpEbCsDecomp::getKernelEvals().
unsigned int CachedMatrix::getCacheRowSize (unsigned int k) [inline]
Definition at line 351 of file KernelMatrices.h.
References cacheEntry.
Referenced by QpSvmDecomp::ComputeInnerProduct(), QpSvmDecomp::Shrink(), QpMcStzDecomp::Shrink(), QpMcDecomp::Shrink(), and QpBoxDecomp::Shrink().
unsigned int CachedMatrix::getCacheSize () const [inline]
Definition at line 346 of file KernelMatrices.h.
References cacheSize.
unsigned int CachedMatrix::getMaxCacheSize () const [inline]
Definition at line 341 of file KernelMatrices.h.
References cacheMaxSize.
Referenced by QpSvmDecomp::SelectWSS(), and QpEbCsDecomp::Solve().
void CachedMatrix::resetBaseMatrixKernelEvals () [inline]
set kernel evaluation counter to zero
Definition at line 369 of file KernelMatrices.h.
References baseMatrix, and QPMatrix::resetAccessCount().
Referenced by QpEbCsDecomp::resetKernelEvals().
float * CachedMatrix::Row (unsigned int k, unsigned int begin, unsigned int end, bool temp = false, bool keep = false)
Return a subset of a matrix row.
This method returns an array of float with at least the entries in the interval [begin, end[ filled in. If #temp is set to true, the computed values are not stored in the cache.
Parameters:
k matrix row
begin first column to be filled in
end last column to be filled in +1
temp are the return values temporary or should they be cached?
keep if there are more entries stored than requested, and cache is not full, keep them?
Definition at line 260 of file KernelMatrices.cpp.
References baseMatrix, cacheAdd(), cacheAppend(), cacheDelete(), cacheEntry, cacheMaxSize, cacheNewest, cacheOldest, cacheRemove(), cacheResize(), cacheSize, cacheTemp, and QPMatrix::Entry().
Referenced by QpEbCsDecomp::calcPrimal(), QpSvmDecomp::ComputeInnerProduct(), QpSvmDecomp::HMG(), QpSvmDecomp::Libsvm28(), QpBoxDecomp::Loop(), QpEbCsDecomp::performSmoStep(), QpMcDecomp::SelectWorkingSet(), QpEbCsDecomp::selectWorkingSet(), QpBoxDecomp::SelectWorkingSet(), QpSvmDecomp::Solve(), QpMcStzDecomp::Solve(), QpMcDecomp::Solve(), QpBoxDecomp::Solve(), QpSvmDecomp::Unshrink(), QpMcStzDecomp::Unshrink(), QpMcDecomp::Unshrink(), and QpBoxDecomp::Unshrink().
Member Data Documentation
QPMatrix* CachedMatrix::baseMatrix [protected]
matrix to be cached
Definition at line 376 of file KernelMatrices.h.
Referenced by CachedMatrix(), Entry(), FlipColumnsAndRows(), getBaseMatrixKernelEvals(), resetBaseMatrixKernelEvals(), and Row().
std::vector<tCacheEntry> CachedMatrix::cacheEntry [protected]
Definition at line 388 of file KernelMatrices.h.
Referenced by cacheAdd(), cacheAppend(), cacheClear(), cacheDelete(), CachedMatrix(), cacheRemove(), cacheResize(), CacheRowRelease(), CacheRowResize(), FlipColumnsAndRows(), getCacheRowSize(), and Row().
unsigned int CachedMatrix::cacheMaxSize [protected]
Definition at line 380 of file KernelMatrices.h.
Referenced by CachedMatrix(), getMaxCacheSize(), and Row().
int CachedMatrix::cacheNewest [protected]
Definition at line 390 of file KernelMatrices.h.
Referenced by cacheAppend(), cacheClear(), CachedMatrix(), cacheRemove(), FlipColumnsAndRows(), and Row().
int CachedMatrix::cacheOldest [protected]
Definition at line 391 of file KernelMatrices.h.
Referenced by cacheAppend(), cacheClear(), CachedMatrix(), cacheRemove(), FlipColumnsAndRows(), and Row().
unsigned int CachedMatrix::cacheSize [protected]
Definition at line 379 of file KernelMatrices.h.
Referenced by cacheAdd(), cacheClear(), cacheDelete(), CachedMatrix(), cacheResize(), getCacheSize(), and Row().
std::vector<float> CachedMatrix::cacheTemp [protected]
Definition at line 389 of file KernelMatrices.h.
Referenced by Row().
The documentation for this class was generated from the following files:
KernelMatrices.h
KernelMatrices.cpp