ReClaM: QpEbCsDecomp Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
QpEbCsDecomp Class Reference
Epoch-based quadratic program approximator for Crammer-Singer type multi-class machines.
#include <QpEbCsDecomp.h>
Classes
struct sCardinalities
envelope for convenience cardinalities of important sets
struct sIntrospection
envelope for variables about the current state of the solver
struct sLogVars
struct sStopCrit
envelope for stopping criterion.
struct sStrategy
envelope for current overall strategy
struct sTmpData
envelope for caching intermediate results
struct tClassInversionCandidateList
Public Member Functions
QpEbCsDecomp (CachedMatrix &kernel, const Array< double > &y, unsigned int classes, unsigned int w=0, unsigned int r=0, SvmStatesCollection *states=NULL)
Constructor.
~QpEbCsDecomp ()
Destructor.
void setStoppingConditions (double a, int e=1, double d=-1.0)
set the stopping conditions for the solver.
void Solve (Array< double > &solutionVector, double regC)
solve the quadratic program.
long getKernelEvals ()
get number of kernel evaluations
void resetKernelEvals ()
set kernel evaluation counter to zero
void setVerbose (bool verbose=false)
set verbosity mode. 0=quiet, 1=python-compatible arrays (one row per epoch)
Protected Types
enum eFlipVariants {
fDeactivate, fRemove_first, fRemove_second, fInsert_first,
fInsert_second
}
List of possible configurations that can occur when flipping two examples.
enum eWsVariants { wRandom, wClassInversion, wSS_MAX }
List of variants of the WSS algorithm, i.e., among which set of samples is MVP-WSS carried out.
enum eNextProc { nNew, nOld, nOpt, nMAX }
List of possible actions for the next processing step.
enum eReprocessRules { rOrig, rMAX }
List of possible rules how many and which reprocess steps (nOld or nOpt) to be done after one nNew.
enum eShrinkingModes { sNever, sBook, sAgressive }
List of possible shrinking modes.
enum eStopReason {
sNone, sEndEpochSoon, sEND_MARKER, sEndEpochNow,
sQUIT_MARKER, sEpochs, sDualAim
}
helper enum: list of possible stopping conditions
typedef std::set< unsigned int > tActiveClasses
Typedef for convenience.
Protected Member Functions
void selectNextProcessingStep ()
select next processing step
bool selectNextPattern ()
find the next pattern to work on. return true if there are now unseen samples left.
double selectWorkingSet ()
Choose working set according to current strategy. return corresponding KKT violation.
double performSmoStep ()
do the actual update on the working set, return the gain achieved
double calcPrimal ()
return the current value of the primal, and also store in introsp.primal
void init ()
reset all variables that are valid for one epoch only
void shuffleSamples ()
randomly reorder the lottery vector defining the iteration through the dataset
void deactivateVariable (unsigned int v, unsigned int e, unsigned int c)
exclude a variable from getting its gradient updated and from being considered in wss
unsigned int deactivateExample (unsigned int e)
freeze an entire example: exclude it from wss and all its gradients from being updated
void flipAll (unsigned int i, unsigned int j, eFlipVariants f)
exchange all data corresponding to two samples, both in internal arrays and in the cachedMatrix Important note: flipAll inherits the assumption that i < j, i.e.
bool canIncrease (unsigned int index, double extra=0.0)
one central place to account for numerical inaccuracies when determining upper-boundedness this defines the parameter kappa of the original paper param index which component of alpha should be tested for boundedness via corresponding component of boxMax param extra for determining whether extra is bounded
bool isSC (unsigned int i)
With respect to a fixed pattern, determine whether a class is a support class This should be identical to #inSCs, unless in the middle of insertion, etc.
unsigned int safe_discrete (unsigned int upper, unsigned int subtract_upper, unsigned int lower=0)
Protected Attributes
Array< double > alpha
solution candidate
Array< double > boxMax
box constraint upper bound, that is, maximal variable value.
CachedMatrix & kernelMatrix
quadratic part, kernel matrix cache
Array< unsigned int > label
for each example, store the class label (between 0 and classes-1)
Array< double > diagonal
diagonal matrix entries
Array< double > gradient
gradient
Array< unsigned int > origIndex
i-th element gives the original index of the current i-th sample
Array< unsigned int > curIndex
i-th element gives the current index of the originally i-th sample
Array< unsigned int > lottery
In each epoch, pre-define how to traverse through the samples.
Array< tActiveClasses > ninaClasses
For each pattern, maintain a set of the corresponding support vectors.
Array< tActiveClasses > asClasses
Array< tActiveClasses > activeGlobalSCs
For each class, maintain a set of the corresponding support patterns.
Array< tActiveClasses > dormantGlobalSCs
sLogVars log
sStrategy strat
envelope for overall strategy
sCardinalities cardi
envelope for convenience cardinalities of important sets
sIntrospection introsp
envelope for variables about the current state of the solver
sTmpData temp
envelope for caching intermediate results
sStopCrit stopCrit
Stopping criterion. The last one greater zero is considered active in addition to accuracy.
tClassInversionCandidateList cicl
SvmStatesCollection * mep_historian
Array< double > m_dummyClosureDouble
Detailed Description
Epoch-based quadratic program approximator for Crammer-Singer type multi-class machines.
This algorithm implements an epoch-based approach to solving the optimization problem occuring in a Crammer-Singer multi-class machine.
One epoch is understood as the solver in a perceptron-like manner looking at all training examples once, possibly carrying out intermediate optimization steps on variables corresponding to known examples in-between.
Note the following conventions that are used in the documentation and underlie the code: A destinction is made between support vectors (SVs), support classes (SCs), and support patterns (SPs). An SV is a combined pair of input pattern i and potential class label c for which the corresponding coefficient is non-zero. An SC is any label c that makes an input pattern an SV. An SP is any pattern that has at least one SC.
Definition at line 78 of file QpEbCsDecomp.h.
Member Typedef Documentation
typedef std::set<unsigned int> QpEbCsDecomp::tActiveClasses [protected]
Typedef for convenience.
Definition at line 166 of file QpEbCsDecomp.h.
Member Enumeration Documentation
enum QpEbCsDecomp::eFlipVariants [protected]
List of possible configurations that can occur when flipping two examples.
Enumerator:
fDeactivate
fRemove_first
fRemove_second
fInsert_first
fInsert_second
Definition at line 188 of file QpEbCsDecomp.h.
enum QpEbCsDecomp::eNextProc [protected]
List of possible actions for the next processing step.
Enumerator:
nNew
nOld
nOpt
nMAX
Definition at line 206 of file QpEbCsDecomp.h.
enum QpEbCsDecomp::eReprocessRules [protected]
List of possible rules how many and which reprocess steps (nOld or nOpt) to be done after one nNew.
Enumerator:
rOrig
rMAX
Definition at line 215 of file QpEbCsDecomp.h.
enum QpEbCsDecomp::eShrinkingModes [protected]
List of possible shrinking modes.
Enumerator:
sNever
sBook
sAgressive
Definition at line 222 of file QpEbCsDecomp.h.
enum QpEbCsDecomp::eStopReason [protected]
helper enum: list of possible stopping conditions
Enumerator:
sNone
sEndEpochSoon
sEND_MARKER
sEndEpochNow
sQUIT_MARKER
sEpochs
sDualAim
Definition at line 289 of file QpEbCsDecomp.h.
enum QpEbCsDecomp::eWsVariants [protected]
List of variants of the WSS algorithm, i.e., among which set of samples is MVP-WSS carried out.
Enumerator:
wRandom
wClassInversion
wSS_MAX
Definition at line 198 of file QpEbCsDecomp.h.
Constructor & Destructor Documentation
QpEbCsDecomp::QpEbCsDecomp (CachedMatrix & kernel, const Array< double > & y, unsigned int classes, unsigned int w = 0, unsigned int r = 0, SvmStatesCollection * states = NULL)
Constructor.
Parameters:
kernel kernel matrix cache
y classification targets
classes number of classes
w working set selection preference. 0=mvpOnOneSample 1=mvpAmongLargestGrad-Samples 2=mvpAmongAllSamples. see documentation below
r reprocess alternation rule preference. see eReprocessRules for documentation
states pointer to instance of record-keeping class SvmStatesCollection, for storing intermediate states of the solver
Definition at line 57 of file QpEbCsDecomp.cpp.
References QpEbCsDecomp::sStopCrit::accuracy, activeGlobalSCs, QpEbCsDecomp::sCardinalities::activePatterns, alpha, asClasses, boxMax, QpEbCsDecomp::tClassInversionCandidateList::candidate, cardi, cicl, QpEbCsDecomp::sCardinalities::classes, QpEbCsDecomp::sIntrospection::curGainRate, curIndex, SvmStatesCollection::declareIntentions(), QpEbCsDecomp::tClassInversionCandidateList::desired_noof_hits, diagonal, dormantGlobalSCs, QpEbCsDecomp::sIntrospection::dual, QpEbCsDecomp::sStopCrit::dualAim, CachedMatrix::Entry(), QpEbCsDecomp::sCardinalities::epochs, QpEbCsDecomp::sCardinalities::examples, QpEbCsDecomp::tClassInversionCandidateList::fallback_mode, QPMatrix::getMatrixSize(), gradient, QpEbCsDecomp::sStrategy::guaranteeFraction, QpEbCsDecomp::tClassInversionCandidateList::i, i, introsp, QpEbCsDecomp::tClassInversionCandidateList::j, QpEbCsDecomp::sLogVars::kernel_lookups, kernelMatrix, label, log, lottery, m_dummyClosureDouble, QpEbCsDecomp::tClassInversionCandidateList::max_priority, QpEbCsDecomp::tClassInversionCandidateList::max_witness, QpEbCsDecomp::sStopCrit::maxEpochs, QpEbCsDecomp::sLogVars::measurements_per_epoch, mep_historian, MT_COUNT_KERNEL_LOOKUPS, ninaClasses, nMAX, nNew, QpEbCsDecomp::sStrategy::numMultipl, origIndex, QpEbCsDecomp::sLogVars::overall_noof_measurements, QpEbCsDecomp::sCardinalities::planned_steps, QpEbCsDecomp::sIntrospection::primal, QpEbCsDecomp::sStrategy::probability, QpEbCsDecomp::sStrategy::probAdaptationRate, QpEbCsDecomp::sStrategy::probSum, QpEbCsDecomp::sStrategy::proc, QpEbCsDecomp::sTmpData::q, QpEbCsDecomp::sTmpData::reprocGradients, QpEbCsDecomp::sStrategy::reRu, rOrig, QpEbCsDecomp::sCardinalities::seenEx, QpEbCsDecomp::sStrategy::shrinkCritFraction, QpEbCsDecomp::sStrategy::shrinkEqualFraction, QpEbCsDecomp::sStrategy::shrinkMode, sNone, QpEbCsDecomp::sCardinalities::sPatterns, QpEbCsDecomp::sStopCrit::stop, stopCrit, strat, temp, QpEbCsDecomp::sStrategy::tryMultipl, QpEbCsDecomp::sStrategy::useClippedAsWitness, QpEbCsDecomp::sStrategy::useClippedInReproc, QpEbCsDecomp::sCardinalities::variables, wClassInversion, QpEbCsDecomp::sLogVars::writeDualEvery, QpEbCsDecomp::sLogVars::writeDualModuland, QpEbCsDecomp::sStrategy::wss, and wSS_MAX.
QpEbCsDecomp::~QpEbCsDecomp ()
Destructor.
Definition at line 214 of file QpEbCsDecomp.cpp.
Member Function Documentation
double QpEbCsDecomp::calcPrimal () [protected]
return the current value of the primal, and also store in introsp.primal
Definition at line 1230 of file QpEbCsDecomp.cpp.
References activeGlobalSCs, alpha, asClasses, cardi, QpEbCsDecomp::sCardinalities::classes, QpEbCsDecomp::sStrategy::creg, dormantGlobalSCs, QpEbCsDecomp::sCardinalities::examples, gradient, i, introsp, isSC(), QpEbCsDecomp::sLogVars::kernel_lookups, kernelMatrix, label, log, MT_COUNT_KERNEL_LOOKUPS, QpEbCsDecomp::sIntrospection::primal, CachedMatrix::Row(), QpEbCsDecomp::sStrategy::shrinkMode, sNever, QpEbCsDecomp::sCardinalities::sPatterns, and strat.
Referenced by Solve().
bool QpEbCsDecomp::canIncrease (unsigned int index, double extra = 0.0) [inline, protected]
one central place to account for numerical inaccuracies when determining upper-boundedness this defines the parameter kappa of the original paper param index which component of alpha should be tested for boundedness via corresponding component of boxMax param extra for determining whether extra is bounded
Definition at line 419 of file QpEbCsDecomp.h.
References alpha, and boxMax.
Referenced by performSmoStep(), and selectWorkingSet().
unsigned int QpEbCsDecomp::deactivateExample (unsigned int e) [protected]
freeze an entire example: exclude it from wss and all its gradients from being updated
Definition at line 1220 of file QpEbCsDecomp.cpp.
References QpEbCsDecomp::sCardinalities::activePatterns, asClasses, CachedMatrix::CacheRowRelease(), cardi, fDeactivate, flipAll(), kernelMatrix, and ninaClasses.
Referenced by performSmoStep().
void QpEbCsDecomp::deactivateVariable (unsigned int v, unsigned int e, unsigned int c) [protected]
exclude a variable from getting its gradient updated and from being considered in wss
Definition at line 1203 of file QpEbCsDecomp.cpp.
References activeGlobalSCs, asClasses, dormantGlobalSCs, isSC(), and ninaClasses.
Referenced by performSmoStep(), and selectWorkingSet().
void QpEbCsDecomp::flipAll (unsigned int i, unsigned int j, eFlipVariants f) [protected]
exchange all data corresponding to two samples, both in internal arrays and in the cachedMatrix Important note: flipAll inherits the assumption that i < j, i.e.
firstArgument < secondArgument, from #CachedMatrix::FlipColumnsAndRows
Definition at line 1108 of file QpEbCsDecomp.cpp.
References activeGlobalSCs, alpha, asClasses, boxMax, cardi, QpEbCsDecomp::sCardinalities::classes, curIndex, diagonal, dormantGlobalSCs, fDeactivate, fInsert_first, fInsert_second, CachedMatrix::FlipColumnsAndRows(), fRemove_first, fRemove_second, gradient, i, isSC(), kernelMatrix, label, ninaClasses, origIndex, and XCHG_A.
Referenced by deactivateExample(), and performSmoStep().
long QpEbCsDecomp::getKernelEvals () [inline]
get number of kernel evaluations
Definition at line 111 of file QpEbCsDecomp.h.
References CachedMatrix::getBaseMatrixKernelEvals(), and kernelMatrix.
Referenced by Solve().
void QpEbCsDecomp::init () [protected]
reset all variables that are valid for one epoch only
Definition at line 217 of file QpEbCsDecomp.cpp.
References cardi, QpEbCsDecomp::sCardinalities::seenEx, shuffleSamples(), sNone, QpEbCsDecomp::sStopCrit::stop, and stopCrit.
Referenced by Solve().
bool QpEbCsDecomp::isSC (unsigned int i) [inline, protected]
With respect to a fixed pattern, determine whether a class is a support class This should be identical to #inSCs, unless in the middle of insertion, etc.
Accounts for numerical inaccuracies in one fixed location Attention: for convenience, i is index directly into alpha, i.e. sample*cardi.classes + (relative class number) param i index directly into alpha
Definition at line 429 of file QpEbCsDecomp.h.
References alpha.
Referenced by calcPrimal(), deactivateVariable(), flipAll(), performSmoStep(), and selectWorkingSet().
double QpEbCsDecomp::performSmoStep () [protected]
do the actual update on the working set, return the gain achieved
Definition at line 698 of file QpEbCsDecomp.cpp.
References activeGlobalSCs, QpEbCsDecomp::sCardinalities::activePatterns, alpha, QpEbCsDecomp::tClassInversionCandidateList::asc_size_current, QpEbCsDecomp::tClassInversionCandidateList::asc_size_third, asClasses, boxMax, CachedMatrix::CacheRowRelease(), QpEbCsDecomp::tClassInversionCandidateList::candidate, canIncrease(), cardi, cicl, QpEbCsDecomp::sCardinalities::classes, QpEbCsDecomp::tClassInversionCandidateList::counter_index, QpEbCsDecomp::tClassInversionCandidateList::cur_priority, QpEbCsDecomp::tClassInversionCandidateList::cur_witness, deactivateExample(), deactivateVariable(), QpEbCsDecomp::tClassInversionCandidateList::delta_g, QpEbCsDecomp::tClassInversionCandidateList::desired_noof_hits, diagonal, QpEbCsDecomp::sIntrospection::dual, QpEbCsDecomp::tClassInversionCandidateList::e, QpEbCsDecomp::tClassInversionCandidateList::fallback_mode, fInsert_first, fInsert_second, flipAll(), fRemove_first, fRemove_second, QpEbCsDecomp::tClassInversionCandidateList::g, QpEbCsDecomp::sTmpData::gMinus, QpEbCsDecomp::sTmpData::gPlus, gradient, QpEbCsDecomp::tClassInversionCandidateList::hits_so_far, QpEbCsDecomp::tClassInversionCandidateList::i, i, introsp, isSC(), QpEbCsDecomp::tClassInversionCandidateList::j, QpEbCsDecomp::sLogVars::kernel_lookups, kernelMatrix, label, QpEbCsDecomp::tClassInversionCandidateList::lit, log, QpEbCsDecomp::tClassInversionCandidateList::max_priority, QpEbCsDecomp::tClassInversionCandidateList::max_witness, MT_COUNT_KERNEL_LOOKUPS, QpEbCsDecomp::tClassInversionCandidateList::mu_test, QpEbCsDecomp::sStrategy::nextI, QpEbCsDecomp::sStrategy::nextJ, QpEbCsDecomp::sStrategy::nextPat, ninaClasses, nOld, QpEbCsDecomp::sStrategy::proc, QpEbCsDecomp::sTmpData::q, CachedMatrix::Row(), safe_discrete(), sAgressive, QpEbCsDecomp::sStrategy::shrinkCritFraction, QpEbCsDecomp::sStrategy::shrinkEqualFraction, QpEbCsDecomp::sStrategy::shrinkMode, sNever, QpEbCsDecomp::sCardinalities::sPatterns, QpEbCsDecomp::tClassInversionCandidateList::start_index, strat, QpEbCsDecomp::tClassInversionCandidateList::t, temp, QpEbCsDecomp::sStrategy::thirdClass, QpEbCsDecomp::sStrategy::useClippedAsWitness, wClassInversion, and QpEbCsDecomp::sStrategy::wss.
Referenced by Solve().
void QpEbCsDecomp::resetKernelEvals () [inline]
set kernel evaluation counter to zero
Definition at line 117 of file QpEbCsDecomp.h.
References kernelMatrix, and CachedMatrix::resetBaseMatrixKernelEvals().
unsigned int QpEbCsDecomp::safe_discrete (unsigned int upper, unsigned int subtract_upper, unsigned int lower = 0) [inline, protected]
Definition at line 434 of file QpEbCsDecomp.h.
Referenced by performSmoStep(), and selectNextPattern().
bool QpEbCsDecomp::selectNextPattern () [protected]
find the next pattern to work on. return true if there are now unseen samples left.
Definition at line 435 of file QpEbCsDecomp.cpp.
References QpEbCsDecomp::sCardinalities::activePatterns, alpha, QpEbCsDecomp::tClassInversionCandidateList::candidate, cardi, cicl, curIndex, QpEbCsDecomp::sIntrospection::dual, QpEbCsDecomp::sCardinalities::epochs, QpEbCsDecomp::sCardinalities::examples, QpEbCsDecomp::tClassInversionCandidateList::fallback_mode, introsp, log, lottery, m_dummyClosureDouble, QpEbCsDecomp::sLogVars::measurements_per_epoch, mep_historian, QpEbCsDecomp::sStrategy::nextPat, nNew, nOld, nOpt, origIndex, QpEbCsDecomp::sLogVars::overall_timer, QpEbCsDecomp::sStrategy::proc, SvmStatesCollection::pushSnapShot(), safe_discrete(), QpEbCsDecomp::sCardinalities::seenEx, sEndEpochNow, sEndEpochSoon, QpEbCsDecomp::sCardinalities::sPatterns, QpEbCsDecomp::sStopCrit::stop, stopCrit, SvmStatesCollection::storeDirectly(), strat, sWallTimer::toc(), wClassInversion, QpEbCsDecomp::sLogVars::writeDualEvery, QpEbCsDecomp::sLogVars::writeDualModuland, and QpEbCsDecomp::sStrategy::wss.
Referenced by Solve().
void QpEbCsDecomp::selectNextProcessingStep () [protected]
select next processing step
Definition at line 382 of file QpEbCsDecomp.cpp.
References QpEbCsDecomp::sCardinalities::activePatterns, cardi, QpEbCsDecomp::sIntrospection::curGainRate, QpEbCsDecomp::sStrategy::guaranteeFraction, i, introsp, nMAX, nNew, QpEbCsDecomp::sCardinalities::planned_steps, QpEbCsDecomp::sStrategy::probability, QpEbCsDecomp::sStrategy::probAdaptationRate, QpEbCsDecomp::sStrategy::probSum, QpEbCsDecomp::sStrategy::proc, QpEbCsDecomp::sStrategy::reRu, rOrig, sEndEpochNow, sEndEpochSoon, QpEbCsDecomp::sStopCrit::stop, stopCrit, and strat.
Referenced by Solve().
double QpEbCsDecomp::selectWorkingSet () [protected]
Choose working set according to current strategy. return corresponding KKT violation.
Definition at line 503 of file QpEbCsDecomp.cpp.
References activeGlobalSCs, alpha, asClasses, boxMax, canIncrease(), cardi, cicl, QpEbCsDecomp::sCardinalities::classes, deactivateVariable(), diagonal, dormantGlobalSCs, QpEbCsDecomp::tClassInversionCandidateList::fallback_mode, QpEbCsDecomp::sTmpData::gMinus, QpEbCsDecomp::sTmpData::gPlus, gradient, QpEbCsDecomp::tClassInversionCandidateList::i, i, isSC(), QpEbCsDecomp::tClassInversionCandidateList::j, QpEbCsDecomp::sLogVars::kernel_lookups, kernelMatrix, label, log, MT_COUNT_KERNEL_LOOKUPS, QpEbCsDecomp::sStrategy::nextI, QpEbCsDecomp::sStrategy::nextJ, QpEbCsDecomp::sStrategy::nextPat, ninaClasses, nNew, nOld, nOpt, QpEbCsDecomp::sStrategy::proc, QpEbCsDecomp::sTmpData::q, QpEbCsDecomp::sTmpData::reprocGradients, CachedMatrix::Row(), QpEbCsDecomp::sStrategy::shrinkCritFraction, QpEbCsDecomp::sStrategy::shrinkMode, sNever, QpEbCsDecomp::sCardinalities::sPatterns, strat, temp, QpEbCsDecomp::sStrategy::useClippedInReproc, wClassInversion, and QpEbCsDecomp::sStrategy::wss.
Referenced by Solve().
void QpEbCsDecomp::setStoppingConditions (double a, int e = 1, double d = -1.0)
set the stopping conditions for the solver.
The last one greater zero is considered active in addition to accuracy.
Parameters:
a accuracy, this is always active (as in exact solvers)
e maximal number of epochs, negative to set inactive
d desired duality gap, negative to set inactive
Definition at line 225 of file QpEbCsDecomp.cpp.
References QpEbCsDecomp::sStopCrit::accuracy, cardi, SvmStatesCollection::declareIntentions(), QpEbCsDecomp::sStopCrit::dualAim, QpEbCsDecomp::sCardinalities::examples, log, m_dummyClosureDouble, MAX_EPOCHS_HARD_BOUNDARY, QpEbCsDecomp::sStopCrit::maxEpochs, QpEbCsDecomp::sLogVars::measurements_per_epoch, mep_historian, QpEbCsDecomp::sLogVars::overall_noof_measurements, stopCrit, QpEbCsDecomp::sCardinalities::variables, QpEbCsDecomp::sLogVars::writeDualEvery, and QpEbCsDecomp::sLogVars::writeDualModuland.
Referenced by SVM_Optimizer::optimize().
void QpEbCsDecomp::setVerbose (bool verbose = false) [inline]
set verbosity mode. 0=quiet, 1=python-compatible arrays (one row per epoch)
Definition at line 123 of file QpEbCsDecomp.h.
References introsp, and QpEbCsDecomp::sIntrospection::verbosity.
Referenced by SVM_Optimizer::optimize().
void QpEbCsDecomp::shuffleSamples () [protected]
randomly reorder the lottery vector defining the iteration through the dataset
Definition at line 1097 of file QpEbCsDecomp.cpp.
References cardi, QpEbCsDecomp::sCardinalities::examples, i, lottery, and XCHG_A.
Referenced by init().
void QpEbCsDecomp::Solve (Array< double > & solutionVector, double regC)
solve the quadratic program.
unlike the solve method of other solvers, we here do not accept a custom initialization for the soluction vector, instead set it to zero no matter what is passed in (being an online algorithm, we rely on the concept of "unseen" samples for which the coefficents are supposed do be zero, i.e. wich are non-SPs)
Parameters:
solutionVector input: initial feasible vector ; output: solution
regC regularization constant C
Definition at line 267 of file QpEbCsDecomp.cpp.
References SvmStatesCollection::accessDirectly(), QpEbCsDecomp::sStopCrit::accuracy, QpEbCsDecomp::sCardinalities::activePatterns, alpha, boxMax, CachedMatrix::CacheRowRelease(), calcPrimal(), cardi, cicl, QpEbCsDecomp::sCardinalities::classes, QpEbCsDecomp::sStrategy::creg, QpEbCsDecomp::sIntrospection::curGainRate, QpEbCsDecomp::sIntrospection::dual, QpEbCsDecomp::sStopCrit::dualAim, QpEbCsDecomp::sCardinalities::epochs, QpEbCsDecomp::sCardinalities::examples, QpEbCsDecomp::tClassInversionCandidateList::fallback_mode, getKernelEvals(), CachedMatrix::getMaxCacheSize(), i, init(), introsp, QpEbCsDecomp::sLogVars::kernel_lookups, kernelMatrix, label, log, m_dummyClosureDouble, QpEbCsDecomp::sStopCrit::maxEpochs, QpEbCsDecomp::sLogVars::measurements_per_epoch, mep_historian, QpEbCsDecomp::sStrategy::nextPat, nNew, QpEbCsDecomp::sStrategy::numMultipl, origIndex, QpEbCsDecomp::sLogVars::overall_noof_measurements, QpEbCsDecomp::sLogVars::overall_timer, performSmoStep(), QpEbCsDecomp::sCardinalities::planned_steps, QpEbCsDecomp::sStrategy::proc, SvmStatesCollection::pushSnapShot(), QpEbCsDecomp::sIntrospection::rolex, sDualAim, selectNextPattern(), selectNextProcessingStep(), selectWorkingSet(), sEND_MARKER, sEndEpochSoon, sEpochs, QpEbCsDecomp::sCardinalities::sPatterns, sQUIT_MARKER, QpEbCsDecomp::sStopCrit::stop, stopCrit, SvmStatesCollection::storeDirectly(), strat, sWallTimer::tic(), sWallTimer::toc(), QpEbCsDecomp::sStrategy::tryMultipl, QpEbCsDecomp::sCardinalities::variables, QpEbCsDecomp::sIntrospection::verbosity, wClassInversion, and QpEbCsDecomp::sStrategy::wss.
Referenced by SVM_Optimizer::optimize().
Member Data Documentation
Array<tActiveClasses> QpEbCsDecomp::activeGlobalSCs [protected]
For each class, maintain a set of the corresponding support patterns.
value i in the j-th set denotes that alpha(i) is an SC for class j (not that class j is an SC for the i-th sample).
Definition at line 179 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), deactivateVariable(), flipAll(), performSmoStep(), QpEbCsDecomp(), and selectWorkingSet().
Array<double> QpEbCsDecomp::alpha [protected]
solution candidate
Definition at line 133 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), canIncrease(), flipAll(), isSC(), performSmoStep(), QpEbCsDecomp(), selectNextPattern(), selectWorkingSet(), and Solve().
Array<tActiveClasses> QpEbCsDecomp::asClasses [protected]
Definition at line 172 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), deactivateExample(), deactivateVariable(), flipAll(), performSmoStep(), QpEbCsDecomp(), and selectWorkingSet().
Array<double> QpEbCsDecomp::boxMax [protected]
box constraint upper bound, that is, maximal variable value.
Definition at line 136 of file QpEbCsDecomp.h.
Referenced by canIncrease(), flipAll(), performSmoStep(), QpEbCsDecomp(), selectWorkingSet(), and Solve().
sCardinalities QpEbCsDecomp::cardi [protected]
envelope for convenience cardinalities of important sets
Definition at line 325 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), deactivateExample(), flipAll(), init(), performSmoStep(), QpEbCsDecomp(), selectNextPattern(), selectNextProcessingStep(), selectWorkingSet(), setStoppingConditions(), shuffleSamples(), and Solve().
tClassInversionCandidateList QpEbCsDecomp::cicl [protected]
Definition at line 378 of file QpEbCsDecomp.h.
Referenced by performSmoStep(), QpEbCsDecomp(), selectNextPattern(), selectWorkingSet(), and Solve().
Array<unsigned int> QpEbCsDecomp::curIndex [protected]
i-th element gives the current index of the originally i-th sample
Definition at line 156 of file QpEbCsDecomp.h.
Referenced by flipAll(), QpEbCsDecomp(), and selectNextPattern().
Array<double> QpEbCsDecomp::diagonal [protected]
diagonal matrix entries
Definition at line 147 of file QpEbCsDecomp.h.
Referenced by flipAll(), performSmoStep(), QpEbCsDecomp(), and selectWorkingSet().
Array<tActiveClasses> QpEbCsDecomp::dormantGlobalSCs [protected]
Definition at line 183 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), deactivateVariable(), flipAll(), QpEbCsDecomp(), and selectWorkingSet().
Array<double> QpEbCsDecomp::gradient [protected]
gradient
Definition at line 150 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), flipAll(), performSmoStep(), QpEbCsDecomp(), and selectWorkingSet().
sIntrospection QpEbCsDecomp::introsp [protected]
envelope for variables about the current state of the solver
Definition at line 328 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), performSmoStep(), QpEbCsDecomp(), selectNextPattern(), selectNextProcessingStep(), setVerbose(), and Solve().
CachedMatrix& QpEbCsDecomp::kernelMatrix [protected]
quadratic part, kernel matrix cache
Definition at line 139 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), deactivateExample(), flipAll(), getKernelEvals(), performSmoStep(), QpEbCsDecomp(), resetKernelEvals(), selectWorkingSet(), and Solve().
Array<unsigned int> QpEbCsDecomp::label [protected]
for each example, store the class label (between 0 and classes-1)
Definition at line 144 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), flipAll(), performSmoStep(), QpEbCsDecomp(), selectWorkingSet(), and Solve().
sLogVars QpEbCsDecomp::log [protected]
Definition at line 319 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), performSmoStep(), QpEbCsDecomp(), selectNextPattern(), selectWorkingSet(), setStoppingConditions(), and Solve().
Array<unsigned int> QpEbCsDecomp::lottery [protected]
In each epoch, pre-define how to traverse through the samples.
Definition at line 159 of file QpEbCsDecomp.h.
Referenced by QpEbCsDecomp(), selectNextPattern(), and shuffleSamples().
Array< double > QpEbCsDecomp::m_dummyClosureDouble [protected]
Definition at line 445 of file QpEbCsDecomp.h.
Referenced by QpEbCsDecomp(), selectNextPattern(), setStoppingConditions(), and Solve().
SvmStatesCollection* QpEbCsDecomp::mep_historian [protected]
Definition at line 443 of file QpEbCsDecomp.h.
Referenced by QpEbCsDecomp(), selectNextPattern(), setStoppingConditions(), and Solve().
Array<tActiveClasses> QpEbCsDecomp::ninaClasses [protected]
For each pattern, maintain a set of the corresponding support vectors.
An element of the set of value i corresponds to the i-th class
Definition at line 170 of file QpEbCsDecomp.h.
Referenced by deactivateExample(), deactivateVariable(), flipAll(), performSmoStep(), QpEbCsDecomp(), and selectWorkingSet().
Array<unsigned int> QpEbCsDecomp::origIndex [protected]
i-th element gives the original index of the current i-th sample
Definition at line 153 of file QpEbCsDecomp.h.
Referenced by flipAll(), QpEbCsDecomp(), selectNextPattern(), and Solve().
sStopCrit QpEbCsDecomp::stopCrit [protected]
Stopping criterion. The last one greater zero is considered active in addition to accuracy.
Definition at line 334 of file QpEbCsDecomp.h.
Referenced by init(), QpEbCsDecomp(), selectNextPattern(), selectNextProcessingStep(), setStoppingConditions(), and Solve().
sStrategy QpEbCsDecomp::strat [protected]
envelope for overall strategy
Definition at line 322 of file QpEbCsDecomp.h.
Referenced by calcPrimal(), performSmoStep(), QpEbCsDecomp(), selectNextPattern(), selectNextProcessingStep(), selectWorkingSet(), and Solve().
sTmpData QpEbCsDecomp::temp [protected]
envelope for caching intermediate results
Definition at line 331 of file QpEbCsDecomp.h.
Referenced by performSmoStep(), QpEbCsDecomp(), and selectWorkingSet().
The documentation for this class was generated from the following files:
QpEbCsDecomp.h
QpEbCsDecomp.cpp