ReClaM: LMSEFFNet Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LMSEFFNet Class Reference
Offers the functions to create and to work with a feed-forward network with explicit defined neuron-to-bias connections. The network is combined with the mean squared error measure. This combination is created due to computational efficiency.
#include <LMSEFFNet.h>
Public Member Functions
LMSEFFNet (const unsigned in=0, const unsigned out=0, double min=0., double max=1.)
Creates an empty MSE Bias feed-forward network with "in" input neurons and "out" output neurons.
LMSEFFNet (const unsigned in, const unsigned out, const Array< int > &cmat, double min=0., double max=1.)
Creates a MSE Bias feed-forward network with "in" input neurons and "out" output neurons.
LMSEFFNet (const unsigned in, const unsigned out, const Array< int > &cmat, const Array< double > &wmat, double min=0., double max=1.)
Creates a MSE Bias feed-forward network with "in" input neurons and "out" output neurons.
LMSEFFNet (const std::string &name, double min=0., double max=1.)
Creates a MSE Bias feed-forward network by reading the necessary information from a file named "filename".
virtual ~LMSEFFNet ()
Destructs an MSE Bias Feed Forward Network object.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Calculates the mean squared error of the model output, compared to the target values.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Calculates the mean squared Error of the model output, compared to the target values, and the derivative of the mean squared error with respect to the weights.
Public Attributes
double tmin
double tmax
Detailed Description
Offers the functions to create and to work with a feed-forward network with explicit defined neuron-to-bias connections. The network is combined with the mean squared error measure. This combination is created due to computational efficiency.
When you are using the classes FFNet or MSEFFNet it is assumed, that each neuron is connected with the (B)ias value. These classes are a specialization of this class, where you have the free choice to connect each neuron to the bias value or not.
Author:
C. Igel
Date:
1999
Changes:
none
Status:
stable
Definition at line 77 of file LMSEFFNet.h.
Constructor & Destructor Documentation
LMSEFFNet::LMSEFFNet (const unsigned in = 0, const unsigned out = 0, double min = 0., double max = 1.) [inline]
Creates an empty MSE Bias feed-forward network with "in" input neurons and "out" output neurons.
Definition at line 83 of file LMSEFFNet.h.
References tmax, and tmin.
LMSEFFNet::LMSEFFNet (const unsigned in, const unsigned out, const Array< int > & cmat, double min = 0., double max = 1.) [inline]
Creates a MSE Bias feed-forward network with "in" input neurons and "out" output neurons.
Additionally, the array "cmat" determines the topology (i.e., number of neurons and their connections).
Definition at line 92 of file LMSEFFNet.h.
References tmax, and tmin.
LMSEFFNet::LMSEFFNet (const unsigned in, const unsigned out, const Array< int > & cmat, const Array< double > & wmat, double min = 0., double max = 1.) [inline]
Creates a MSE Bias feed-forward network with "in" input neurons and "out" output neurons.
Additionally, the arrays "cmat" and "wmat" determine the topology (i.e., number of neurons and their connections) as well as the connection weights.
Definition at line 103 of file LMSEFFNet.h.
References tmax, and tmin.
LMSEFFNet::LMSEFFNet (const std::string & name, double min = 0., double max = 1.) [inline]
Creates a MSE Bias feed-forward network by reading the necessary information from a file named "filename".
Definition at line 111 of file LMSEFFNet.h.
References tmax, and tmin.
virtual LMSEFFNet::~LMSEFFNet () [inline, virtual]
Destructs an MSE Bias Feed Forward Network object.
Definition at line 118 of file LMSEFFNet.h.
Member Function Documentation
double LMSEFFNet::error (Model & model, const Array< double > & input, const Array< double > & target) [inline, virtual]
Calculates the mean squared error of the model output, compared to the target values.
Reimplemented from MSEFFNet.
Definition at line 124 of file LMSEFFNet.h.
References Model::model(), tmax, and tmin.
double LMSEFFNet::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [inline, virtual]
Calculates the mean squared Error of the model output, compared to the target values, and the derivative of the mean squared error with respect to the weights.
Reimplemented from MSEFFNet.
Definition at line 161 of file LMSEFFNet.h.
References FFNet::activate(), FFNet::bias, FFNet::connection(), FFNet::d, FFNet::dg(), FFNet::dgOutput(), FFNet::firstOutputNeuron, Model::getParameterDimension(), i, Model::inputDimension, FFNet::numberOfNeurons, FFNet::readParameters(), tmax, tmin, FFNet::weight(), and FFNet::z.
Member Data Documentation
double LMSEFFNet::tmax
Definition at line 313 of file LMSEFFNet.h.
Referenced by error(), errorDerivative(), and LMSEFFNet().
double LMSEFFNet::tmin
Definition at line 310 of file LMSEFFNet.h.
Referenced by error(), errorDerivative(), and LMSEFFNet().
The documentation for this class was generated from the following file:
LMSEFFNet.h