ReClaM: QPMatrix Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
QPMatrix Class Reference
encapsulation of a quadratic matrix for quadratic programming
#include <KernelMatrices.h>
Public Member Functions
QPMatrix (unsigned int size)
Constructor.
virtual ~QPMatrix ()
Destructor.
virtual float Entry (unsigned int i, unsigned int j)=0
Return a single matrix element.
virtual void FlipColumnsAndRows (unsigned int i, unsigned int j)=0
Exchange the rows i and j and the columns i and j.
unsigned int getMatrixSize () const
return the size of the quadratic matrix
SharkInt64 getAccessCount () const
get number of times Entry was called
void resetAccessCount ()
set accessCount to zero
Protected Attributes
unsigned int matrixsize
length of each edge of the quadratic matrix
SharkInt64 accessCount
entry access counter
Detailed Description
encapsulation of a quadratic matrix for quadratic programming
A QPMatrix has two properties: It provides access to its single entries and it is able to swap any of its rows and columns. In particular, this interface does not require the matrix to fit into working memory.
Definition at line 73 of file KernelMatrices.h.
Constructor & Destructor Documentation
QPMatrix::QPMatrix (unsigned int size)
Constructor.
Definition at line 73 of file KernelMatrices.cpp.
QPMatrix::~QPMatrix () [virtual]
Destructor.
Definition at line 79 of file KernelMatrices.cpp.
Member Function Documentation
virtual float QPMatrix::Entry (unsigned int i, unsigned int j) [pure virtual]
Return a single matrix element.
This method returns a single matrix element.
Parameters:
i matrix row
j matrix column
Implemented in KernelMatrix, PrecomputedKernelMatrix, RegularizedKernelMatrix, QPMatrix2, and CachedMatrix.
Referenced by CachedMatrix::Entry(), QPMatrix2::Entry(), CachedMatrix::FlipColumnsAndRows(), and CachedMatrix::Row().
virtual void QPMatrix::FlipColumnsAndRows (unsigned int i, unsigned int j) [pure virtual]
Exchange the rows i and j and the columns i and j.
W.l.o.g. it is assumed that . It may be advantageous for caching to reorganize the column order. In order to keep symmetric matrices symmetric the rows are swapped, too.
Parameters:
i first row/column index
j second row/column index
Implemented in KernelMatrix, PrecomputedKernelMatrix, RegularizedKernelMatrix, QPMatrix2, and CachedMatrix.
Referenced by CachedMatrix::FlipColumnsAndRows().
SharkInt64 QPMatrix::getAccessCount () const [inline]
get number of times Entry was called
Definition at line 112 of file KernelMatrices.h.
References accessCount.
Referenced by CachedMatrix::getBaseMatrixKernelEvals().
unsigned int QPMatrix::getMatrixSize () const [inline]
return the size of the quadratic matrix
Definition at line 106 of file KernelMatrices.h.
References matrixsize.
Referenced by QpBoxDecomp::QpBoxDecomp(), QpEbCsDecomp::QpEbCsDecomp(), QPMatrix2::QPMatrix2(), QpMcDecomp::QpMcDecomp(), QpMcStzDecomp::QpMcStzDecomp(), and QpSvmDecomp::QpSvmDecomp().
void QPMatrix::resetAccessCount () [inline]
set accessCount to zero
Definition at line 118 of file KernelMatrices.h.
References accessCount.
Referenced by CachedMatrix::resetBaseMatrixKernelEvals().
Member Data Documentation
SharkInt64 QPMatrix::accessCount [protected]
entry access counter
Definition at line 128 of file KernelMatrices.h.
Referenced by KernelMatrix::Entry(), getAccessCount(), and resetAccessCount().
unsigned int QPMatrix::matrixsize [protected]
length of each edge of the quadratic matrix
Definition at line 125 of file KernelMatrices.h.
Referenced by CachedMatrix::CachedMatrix(), CachedMatrix::FlipColumnsAndRows(), getMatrixSize(), KernelMatrix::KernelMatrix(), QPMatrix2::QPMatrix2(), and KernelMatrix::~KernelMatrix().
The documentation for this class was generated from the following files:
KernelMatrices.h
KernelMatrices.cpp