ReClaM: SvmStatesCollection Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SvmStatesCollection Class Reference
Utility class for storing snapshots of SVM states.
#include <Utilities.h>
Public Member Functions
SvmStatesCollection (unsigned int classes, KernelFunction *in_kernel, const Array< double > &train_inputs)
Constructor.
~SvmStatesCollection ()
void declareIntentions (unsigned int noof_shots, unsigned int raw_param_length, unsigned int raw_closure_length_double, unsigned int raw_closure_length_unsigned, unsigned int noof_measures)
initialization method for resizing of the internal arrays.
void pushSnapShot (const Array< double > &param, const Array< double > &closure_double, const Array< unsigned int > &closure_unsigned)
true svm training should be influenced as little as possible, and the influence should be constant.
void makeHistorySparse (unsigned int svm_variant)
true svm training should be influenced as little as possible, and the influence should be constant.
void storePrimal (unsigned int svm_variant, unsigned int target_index, const Array< double > &train_targets, double regC)
using the sparsified history, calculate and store the primal of each snapshot
void storeTestErr (unsigned int svm_variant, unsigned int target_index, const Array< double > &test_inputs, const Array< double > &test_targets)
using the sparsified history, calculate and store the test error of each snapshot
void storeDirectly (double what, unsigned int target_index, unsigned int shot_number)
auxiliary methods for direct access to #m_performanceMeasures
double accessDirectly (unsigned int target_index, unsigned int shot_number)
auxiliary methods for direct access to #m_performanceMeasures
void printPerformanceMeasureAsNumPyArray (unsigned int target_index)
pretty-print the performance measuring array
Detailed Description
Utility class for storing snapshots of SVM states.
When training an SVM (solving its QpProgram), it can be interesting to analyze the intermittant solver states and thereby its learning curve. An SvmStatesCollection instance provides storage to which the relevant parameters can be pushed during training. The parameter copy procedure is non-sparse, so that copy time is constant during model buildup. All stored model snapshots can be sparsified after the optimization run. The storeXXX methods allow triggering calculations of more resource-intensive measures after training and sparsification, while the XXXdirectly methods are for quick direct storage of cheaply obtainable measures from within the solver.
Definition at line 189 of file Utilities.h.
Constructor & Destructor Documentation
SvmStatesCollection::SvmStatesCollection (unsigned int classes, KernelFunction * in_kernel, const Array< double > & train_inputs)
Constructor.
Parameters:
classes number of classes
in_kernel pointer to kernel function
train_inputs training data
Definition at line 40 of file Utilities.cpp.
SvmStatesCollection::~SvmStatesCollection ()
Definition at line 50 of file Utilities.cpp.
Member Function Documentation
double SvmStatesCollection::accessDirectly (unsigned int target_index, unsigned int shot_number)
auxiliary methods for direct access to #m_performanceMeasures
Parameters:
target_index query what row of the performance-measuring array?
shot_number query what column of the performance-measuring array?
Definition at line 282 of file Utilities.cpp.
Referenced by QpEbCsDecomp::Solve().
void SvmStatesCollection::declareIntentions (unsigned int noof_shots, unsigned int raw_param_length, unsigned int raw_closure_length_double, unsigned int raw_closure_length_unsigned, unsigned int noof_measures)
initialization method for resizing of the internal arrays.
Parameters:
noof_shots how many snapshots do i want to take?
raw_param_length of what size will the parameter array be?
raw_closure_length_double how many doubles will accompany the parameter array as closure-information?
raw_closure_length_unsigned how many unsigned ints as closure-information?
noof_measures how many performance indicators will i later want to derive for each shot
Definition at line 53 of file Utilities.cpp.
Referenced by QpEbCsDecomp::QpEbCsDecomp(), and QpEbCsDecomp::setStoppingConditions().
void SvmStatesCollection::makeHistorySparse (unsigned int svm_variant)
true svm training should be influenced as little as possible, and the influence should be constant.
hence, here construct sparse versions of all snapshots recorded
Parameters:
svm_variant to which SVM variant do my stored snapshots correspond?
Definition at line 86 of file Utilities.cpp.
References eEBCS, and i.
void SvmStatesCollection::printPerformanceMeasureAsNumPyArray (unsigned int target_index)
pretty-print the performance measuring array
Parameters:
target_index query what row of the performance-measuring array?
Definition at line 288 of file Utilities.cpp.
References i.
void SvmStatesCollection::pushSnapShot (const Array< double > & param, const Array< double > & closure_double, const Array< unsigned int > & closure_unsigned)
true svm training should be influenced as little as possible, and the influence should be constant.
hence, here push a direct snapshot of the parameter vector only, along with necessary closure information to reconstruct the corresponding true sparse solution later
Parameters:
param the model parameter array
closure_double necessary closure information of type double
closure_unsigned necessary closure information of type unsigned (e.g., the permutation of param)
Definition at line 73 of file Utilities.cpp.
Referenced by QpEbCsDecomp::selectNextPattern(), and QpEbCsDecomp::Solve().
void SvmStatesCollection::storeDirectly (double what, unsigned int target_index, unsigned int shot_number)
auxiliary methods for direct access to #m_performanceMeasures
Parameters:
what the value to store
target_index store in what row of the performance-measuring array?
shot_number store in what column of the performance-measuring array?
Definition at line 276 of file Utilities.cpp.
Referenced by QpEbCsDecomp::selectNextPattern(), and QpEbCsDecomp::Solve().
void SvmStatesCollection::storePrimal (unsigned int svm_variant, unsigned int target_index, const Array< double > & train_targets, double regC)
using the sparsified history, calculate and store the primal of each snapshot
Parameters:
svm_variant to which SVM variant do my stored snapshots correspond?
target_index store in what row of the performance-measuring array?
train_targets label array of the training data
regC regularization constant
Definition at line 123 of file Utilities.cpp.
References eEBCS, KernelFunction::eval(), and i.
void SvmStatesCollection::storeTestErr (unsigned int svm_variant, unsigned int target_index, const Array< double > & test_inputs, const Array< double > & test_targets)
using the sparsified history, calculate and store the test error of each snapshot
Parameters:
svm_variant to which SVM variant do my stored snapshots correspond?
target_index store in what row of the performance-measuring array?
test_inputs test data
test_targets test labels
Definition at line 211 of file Utilities.cpp.
References eEBCS, KernelFunction::eval(), and i.
The documentation for this class was generated from the following files:
Utilities.h
Utilities.cpp