ReClaM: MetaSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
MetaSVM Class Reference
Base class of all meta models for SVM training.
#include <Svm.h>
Public Member Functions
MetaSVM (SVM *pSVM, unsigned int numberOfHyperParameters)
Constructor.
MetaSVM (MultiClassSVM *pSVM, unsigned int numberOfHyperParameters)
Constructor.
~MetaSVM ()
Descructor.
SVM * getSVM ()
return the underlying SVM model
MultiClassSVM * getMultiClassSVM ()
return the underlying MultiClassSVM model
void model (const Array< double > &input, Array< double > &output)
Just calls the underlying SVM.
void setParameter (unsigned int index, double value)
overloaded version of Model::setParameter
bool isFeasible ()
ensure the kernel is feasible
Protected Attributes
Model * svm
pointer to the underlying SVM model
KernelFunction * kernel
pointer to the kernel function object
unsigned int hyperparameters
number of hyperparameters of the SVM training scheme
Detailed Description
Base class of all meta models for SVM training.
The MetaSVM is the base class of all SVM training schemes. It stores the hyperparameters as its model parameters. These usually include the kernel parameters and at least one complexity control parameter.
Author:
T. Glasmachers
Date:
2007
Definition at line 557 of file Svm.h.
Constructor & Destructor Documentation
MetaSVM::MetaSVM (SVM * pSVM, unsigned int numberOfHyperParameters)
Constructor.
Parameters:
pSVM Pointer to the SVM to be optimized.
numberOfHyperParameters number of hyperparameters additional to the kernel parameters
Definition at line 955 of file Svm.cpp.
References SVM::getKernel(), and Model::getParameterDimension().
MetaSVM::MetaSVM (MultiClassSVM * pSVM, unsigned int numberOfHyperParameters)
Constructor.
Parameters:
pSVM Pointer to the MultiClassSVM to be optimized.
numberOfHyperParameters number of hyperparameters additional to the kernel parameters
Definition at line 967 of file Svm.cpp.
References MultiClassSVM::getKernel(), and Model::getParameterDimension().
MetaSVM::~MetaSVM ()
Descructor.
Definition at line 979 of file Svm.cpp.
Member Function Documentation
MultiClassSVM* MetaSVM::getMultiClassSVM () [inline]
return the underlying MultiClassSVM model
Definition at line 583 of file Svm.h.
References svm.
Referenced by AllInOneMcSVM::modelDerivative(), SVM_Optimizer::optimize(), and AllInOneMcSVM::PrepareDerivative().
SVM* MetaSVM::getSVM () [inline]
return the underlying SVM model
Definition at line 577 of file Svm.h.
References svm.
Referenced by SpanBound1::bound(), SpanBound1::boundDerivative(), GaussianProcessEvidence::dEvidenceDTheta(), SpanBoundA::error(), SpanBound2::error(), SpanBound1::error(), RadiusMargin::error(), NegativePolarization::error(), LOO::error(), NegativeBKTA::error(), GaussianProcessVariance::error(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), RadiusMargin::errorDerivative(), NegativePolarization::errorDerivative(), NegativeBKTA::errorDerivative(), GaussianProcessEvidence::evidence(), C_SVM::modelDerivative(), GaussianProcess::operator()(), SVM_Optimizer::optimize(), C_SVM::PrepareDerivative(), and GaussianProcess::train().
bool MetaSVM::isFeasible () [virtual]
ensure the kernel is feasible
Reimplemented from Model.
Reimplemented in GaussianProcess, C_SVM, Epsilon_SVM, OneClassSVM, RegularizationNetwork, AllInOneMcSVM, CrammerSingerMcSVM, LLWMcSVM, DGIMcSVM, OVAMcSVM, OCCMcSVM, and EpochBasedCsMcSvm.
Definition at line 999 of file Svm.cpp.
Referenced by OCCMcSVM::isFeasible(), OVAMcSVM::isFeasible(), AllInOneMcSVM::isFeasible(), RegularizationNetwork::isFeasible(), Epsilon_SVM::isFeasible(), OneClassSVM::isFeasible(), and C_SVM::isFeasible().
void MetaSVM::model (const Array< double > & input, Array< double > & output) [virtual]
Just calls the underlying SVM.
Implements Model.
Definition at line 984 of file Svm.cpp.
void MetaSVM::setParameter (unsigned int index, double value) [virtual]
overloaded version of Model::setParameter
Reimplemented from Model.
Reimplemented in C_SVM, Epsilon_SVM, and OneClassSVM.
Definition at line 989 of file Svm.cpp.
References Model::setParameter().
Referenced by EpochBasedCsMcSvm::set_C(), OCCMcSVM::set_C(), OVAMcSVM::set_C(), DGIMcSVM::set_C(), LLWMcSVM::set_C(), CrammerSingerMcSVM::set_C(), AllInOneMcSVM::set_C(), RegularizationNetwork::set_gamma(), GaussianProcess::setBetaInv(), and GaussianProcess::setSigma().
Member Data Documentation
unsigned int MetaSVM::hyperparameters [protected]
number of hyperparameters of the SVM training scheme
Definition at line 605 of file Svm.h.
Referenced by Epsilon_SVM::setParameter().
KernelFunction* MetaSVM::kernel [protected]
pointer to the kernel function object
Definition at line 602 of file Svm.h.
Referenced by AllInOneMcSVM::modelDerivative(), C_SVM::modelDerivative(), AllInOneMcSVM::PrepareDerivative(), and C_SVM::PrepareDerivative().
Model* MetaSVM::svm [protected]
pointer to the underlying SVM model
Definition at line 599 of file Svm.h.
Referenced by getMultiClassSVM(), getSVM(), AllInOneMcSVM::modelDerivative(), C_SVM::modelDerivative(), AllInOneMcSVM::PrepareDerivative(), C_SVM::PrepareDerivative(), and GaussianProcess::train().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp