ReClaM: KernelNearestNeighborRegression Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
KernelNearestNeighborRegression Class Reference
The kernel nearest neighbor classifier is parameter free, that is, it does not require training.
#include <KernelNearestNeighborRegression.h>
Public Member Functions
KernelNearestNeighborRegression (KernelFunction *kernelfunction, int k)
Constructor.
KernelNearestNeighborRegression (const Array< double > &input, const Array< double > &target, KernelFunction *kernelfunction, int k)
Constructor.
~KernelNearestNeighborRegression ()
Destructor.
void model (const Array< double > &input, Array< double > &output)
The model method does the regression.
void doRegression (int i, Array< double > &output)
Predict i-th pattern using the others, allows efficient LOO error computation.
Protected Member Functions
void doRegression (const Array< double > &pattern, Array< double > &output)
Do regression.
Detailed Description
The kernel nearest neighbor classifier is parameter free, that is, it does not require training.
Definition at line 53 of file KernelNearestNeighborRegression.h.
Constructor & Destructor Documentation
KernelNearestNeighborRegression::KernelNearestNeighborRegression (KernelFunction * kernelfunction, int k)
Constructor.
Parameters:
kernelfunction kernel function
k number of neighbors to consider
Definition at line 46 of file KernelNearestNeighborRegression.cpp.
References Model::inputDimension, and Model::outputDimension.
KernelNearestNeighborRegression::KernelNearestNeighborRegression (const Array< double > & input, const Array< double > & target, KernelFunction * kernelfunction, int k)
Constructor.
Parameters:
input input patterns
target input labels
kernelfunction kernel function
k number of neighbors to consider
Definition at line 52 of file KernelNearestNeighborRegression.cpp.
KernelNearestNeighborRegression::~KernelNearestNeighborRegression ()
Destructor.
Definition at line 56 of file KernelNearestNeighborRegression.cpp.
Member Function Documentation
void KernelNearestNeighborRegression::doRegression (int i, Array< double > & output)
Predict i-th pattern using the others, allows efficient LOO error computation.
Definition at line 131 of file KernelNearestNeighborRegression.cpp.
References KernelNearestNeighbor::diag, KernelFunction::eval(), i, KernelNearestNeighbor::kernel, KernelNearestNeighbor::numberOfNeighbors, KernelNearestNeighbor::training_input, and KernelNearestNeighbor::training_target.
Referenced by model().
void KernelNearestNeighborRegression::doRegression (const Array< double > & pattern, Array< double > & output) [protected]
Do regression.
Definition at line 85 of file KernelNearestNeighborRegression.cpp.
References KernelNearestNeighbor::diag, KernelFunction::eval(), i, KernelNearestNeighbor::kernel, KernelNearestNeighbor::numberOfNeighbors, KernelNearestNeighbor::training_input, and KernelNearestNeighbor::training_target.
void KernelNearestNeighborRegression::model (const Array< double > & input, Array< double > & output) [virtual]
The model method does the regression.
Reimplemented from KernelNearestNeighbor.
Definition at line 61 of file KernelNearestNeighborRegression.cpp.
References KernelNearestNeighbor::bMustRecalc, doRegression(), Model::inputDimension, Model::outputDimension, and KernelNearestNeighbor::Recalc().
The documentation for this class was generated from the following files:
KernelNearestNeighborRegression.h
KernelNearestNeighborRegression.cpp