ReClaM: DGIMcSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
DGIMcSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
DGIMcSVM (MultiClassSVM *pSVM, double C, bool unconstrained=false)
Constructor.
~DGIMcSVM ()
Destructor.
double get_C ()
get the regularization constant
void set_C (double C)
set the regularization constant
bool isUnconstrained ()
return true if the exponential function is used to parameterize C
bool isFeasible ()
ensure C is positive
Protected Attributes
bool exponential
is C stored as log(C)?
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2010
Meta model for the multi class SVM proposed by Dogan, Glasmachers and Igel
Examples:
McSvm.cpp.
Definition at line 1061 of file Svm.h.
Constructor & Destructor Documentation
DGIMcSVM::DGIMcSVM (MultiClassSVM * pSVM, double C, bool unconstrained = false)
Constructor.
Definition at line 1659 of file Svm.cpp.
References exponential, and set_C().
DGIMcSVM::~DGIMcSVM ()
Destructor.
Definition at line 1666 of file Svm.cpp.
Member Function Documentation
double DGIMcSVM::get_C () [inline]
get the regularization constant
Definition at line 1072 of file Svm.h.
References exponential, and Model::parameter.
Referenced by SVM_Optimizer::init().
bool DGIMcSVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1671 of file Svm.cpp.
References exponential, and Model::parameter.
bool DGIMcSVM::isUnconstrained () [inline]
return true if the exponential function is used to parameterize C
Definition at line 1086 of file Svm.h.
References exponential.
void DGIMcSVM::set_C (double C) [inline]
set the regularization constant
Definition at line 1079 of file Svm.h.
References exponential, and MetaSVM::setParameter().
Referenced by DGIMcSVM().
Member Data Documentation
bool DGIMcSVM::exponential [protected]
is C stored as log(C)?
Definition at line 1096 of file Svm.h.
Referenced by DGIMcSVM(), get_C(), isFeasible(), isUnconstrained(), and set_C().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp