ReClaM: KernelKMeans Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
KernelKMeans Class Reference
Kernel k-means clustering.
#include <KernelKMeans.h>
Public Member Functions
KernelKMeans (KernelFunction *pKernel, const Array< double > &input, std::vector< int > &indexListForClustering, unsigned noClusters)
~KernelKMeans ()
void updateFandG ()
std::vector< int > * clusterVectors ()
const Array< double > & getPoints ()
Detailed Description
Kernel k-means clustering.
Definition at line 54 of file KernelKMeans.h.
Constructor & Destructor Documentation
KernelKMeans::KernelKMeans (KernelFunction * pKernel, const Array< double > & input, std::vector< int > & indexListForClustering, unsigned noClusters)
Definition at line 48 of file KernelKMeans.cpp.
KernelKMeans::~KernelKMeans ()
Definition at line 69 of file KernelKMeans.cpp.
Member Function Documentation
std::vector< int > * KernelKMeans::clusterVectors ()
Definition at line 124 of file KernelKMeans.cpp.
References KernelFunction::eval(), getPoints(), i, and updateFandG().
Referenced by SvmApproximation::createIndexListWithKMeans().
const Array<double>& KernelKMeans::getPoints () [inline]
Definition at line 64 of file KernelKMeans.h.
Referenced by clusterVectors(), and updateFandG().
void KernelKMeans::updateFandG ()
Definition at line 78 of file KernelKMeans.cpp.
References KernelFunction::eval(), getPoints(), and i.
Referenced by clusterVectors().
The documentation for this class was generated from the following files:
KernelKMeans.h
KernelKMeans.cpp