ReClaM: EpochBasedCsMcSvm Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
EpochBasedCsMcSvm Class Reference
Meta model (training scheme) for on-line Crammer-Singer multiclass learning.
#include <Svm.h>
Public Member Functions
EpochBasedCsMcSvm (MultiClassSVM *pSVM, double C, bool unconst=false, bool countKernels=false, unsigned int wss=0, unsigned int reru=0, SvmStatesCollection *states=NULL, int epochs=1, double dual=-1.0)
Constructor.
~EpochBasedCsMcSvm ()
Destructor.
double get_C ()
get the regularization constant
void set_C (double C)
set the regularization constant
bool isUnconstrained ()
return true if the exponential function is used to parameterize C
bool get_countPreference ()
return if number of kernel evals is being counted
unsigned int get_wssMode ()
return working set selection preference
unsigned int get_reruMode ()
return reprocess alternation rule preference
int get_epochLim ()
get the maximum number of epochs. negative for inactive
double get_dualAim ()
get the desired duality gap. negative for inactive
SvmStatesCollection * get_historian ()
get the desired duality gap. negative for inactive
bool isFeasible ()
is C positive, and the underlying MetaSVM feasible?
Protected Attributes
bool exponential
is C stored as log(C)?
bool count
count number of kernel evals?
unsigned int wssMode
working set selection preference. 0=mvpOnOneSample 1=mvpAmongLargestGrad-Samples 2=mvpAmongAllSamples.
unsigned int reruMode
reprocess alternation rule preference. see #eReprocessRules in QuadraticProgram.h for documentation.
int epochLim
number of epochs: how many iterations through the training set?
double dualAim
Desired duality gap as stopping criterion. Alternative to epochLim.
SvmStatesCollection * mep_historian
pointer to statesCollection class. use to take snapshots of your svm during training.
Detailed Description
Meta model (training scheme) for on-line Crammer-Singer multiclass learning.
Author:
M. Tuma
Date:
2010
This algorithm implements an epoch-based approach to solving the optimization problem occuring in a Crammer-Singer multi-class machine.
One epoch is understood as the solver in a perceptron-like manner looking at all training examples once, possibly carrying out intermediate optimization steps on variables corresponding to known examples in-between.
Examples:
McSvm.cpp.
Definition at line 1177 of file Svm.h.
Constructor & Destructor Documentation
EpochBasedCsMcSvm::EpochBasedCsMcSvm (MultiClassSVM * pSVM, double C, bool unconst = false, bool countKernels = false, unsigned int wss = 0, unsigned int reru = 0, SvmStatesCollection * states = NULL, int epochs = 1, double dual = -1.0)
Constructor.
Parameters:
pSVM Pointer to the SVM to be optimized.
C Value for the regularization parameter C
unconst True if C is represented as , allowing for unconstrained optimization.
wss working set selection strategy used by solver. 0=mvpOnOneSample 1=mvpAmongLargestGrad-Samples 2=mvpAmongAllSamples.
reru reprocess alternation rule preference. see #eReprocessRules in QuadraticProgram.h for documentation
count should the number of kernel evals be counted
epochs Number of runs through the training set. Often, 1 is used.
dual Desired duality gap. When greater than 0, used instead of epochLim.
Definition at line 1721 of file Svm.cpp.
References count, dualAim, epochLim, exponential, mep_historian, reruMode, set_C(), and wssMode.
EpochBasedCsMcSvm::~EpochBasedCsMcSvm ()
Destructor.
Definition at line 1736 of file Svm.cpp.
Member Function Documentation
double EpochBasedCsMcSvm::get_C () [inline]
get the regularization constant
Definition at line 1198 of file Svm.h.
References exponential, and Model::parameter.
Referenced by SVM_Optimizer::init().
bool EpochBasedCsMcSvm::get_countPreference () [inline]
return if number of kernel evals is being counted
Definition at line 1218 of file Svm.h.
References count.
Referenced by SVM_Optimizer::init().
double EpochBasedCsMcSvm::get_dualAim () [inline]
get the desired duality gap. negative for inactive
Definition at line 1242 of file Svm.h.
References dualAim.
Referenced by SVM_Optimizer::init().
int EpochBasedCsMcSvm::get_epochLim () [inline]
get the maximum number of epochs. negative for inactive
Definition at line 1236 of file Svm.h.
References epochLim.
Referenced by SVM_Optimizer::init().
SvmStatesCollection* EpochBasedCsMcSvm::get_historian () [inline]
get the desired duality gap. negative for inactive
Definition at line 1248 of file Svm.h.
References mep_historian.
Referenced by SVM_Optimizer::init().
unsigned int EpochBasedCsMcSvm::get_reruMode () [inline]
return reprocess alternation rule preference
Definition at line 1230 of file Svm.h.
References reruMode.
Referenced by SVM_Optimizer::init().
unsigned int EpochBasedCsMcSvm::get_wssMode () [inline]
return working set selection preference
Definition at line 1224 of file Svm.h.
References wssMode.
Referenced by SVM_Optimizer::init().
bool EpochBasedCsMcSvm::isFeasible () [virtual]
is C positive, and the underlying MetaSVM feasible?
Reimplemented from MetaSVM.
Definition at line 1739 of file Svm.cpp.
References exponential, and Model::parameter.
bool EpochBasedCsMcSvm::isUnconstrained () [inline]
return true if the exponential function is used to parameterize C
Definition at line 1212 of file Svm.h.
References exponential.
void EpochBasedCsMcSvm::set_C (double C) [inline]
set the regularization constant
Definition at line 1205 of file Svm.h.
References exponential, and MetaSVM::setParameter().
Referenced by EpochBasedCsMcSvm().
Member Data Documentation
bool EpochBasedCsMcSvm::count [protected]
count number of kernel evals?
Definition at line 1261 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), and get_countPreference().
double EpochBasedCsMcSvm::dualAim [protected]
Desired duality gap as stopping criterion. Alternative to epochLim.
Definition at line 1273 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), and get_dualAim().
int EpochBasedCsMcSvm::epochLim [protected]
number of epochs: how many iterations through the training set?
Definition at line 1270 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), and get_epochLim().
bool EpochBasedCsMcSvm::exponential [protected]
is C stored as log(C)?
Definition at line 1258 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), get_C(), isFeasible(), isUnconstrained(), and set_C().
SvmStatesCollection* EpochBasedCsMcSvm::mep_historian [protected]
pointer to statesCollection class. use to take snapshots of your svm during training.
Definition at line 1276 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), and get_historian().
unsigned int EpochBasedCsMcSvm::reruMode [protected]
reprocess alternation rule preference. see #eReprocessRules in QuadraticProgram.h for documentation.
Definition at line 1267 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), and get_reruMode().
unsigned int EpochBasedCsMcSvm::wssMode [protected]
working set selection preference. 0=mvpOnOneSample 1=mvpAmongLargestGrad-Samples 2=mvpAmongAllSamples.
Definition at line 1264 of file Svm.h.
Referenced by EpochBasedCsMcSvm(), and get_wssMode().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp