ReClaM: SigmoidFit Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SigmoidFit Class Reference
Optimize a sigmoid after SVM outputs to turn them into probability estimates.
#include <SigmoidFit.h>
Public Member Functions
SigmoidFit ()
Constructor.
~SigmoidFit ()
Destructor.
void init (Model &model)
The init method does nothing usefull but fulfills the base class interface.
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target)
Don't call the optimize member more than once, as the SigmoidFit optimizer is not iterative.
double mylog (double x)
Compute the maximum of -200 and the logarithm of x.
Detailed Description
Optimize a sigmoid after SVM outputs to turn them into probability estimates.
The SigmoidFit class implements a non-iterative optimizer. It optimizes a sigmoid to fit the posterior probability for positive class given SVM outputs. Although the optimizer is iterative in its nature, it is more convenient to implement it in one single step. As a side effect, Platt's original and very heuristic stopping conditions are kept.
The method was presented by John Platt in 1999, see
Probabilistic Outputs for Support Vector Machines and Comparisons to Regularized Likelyhood Methods, Advances in Large Margin Classifiers, pp. 61-74, MIT Press, (1999).
The full paper can be downloaded from
http://www.research.microsoft.com/~jplatt
--- pseudo-code is given in the paper.
Definition at line 74 of file SigmoidFit.h.
Constructor & Destructor Documentation
SigmoidFit::SigmoidFit ()
Constructor.
Definition at line 48 of file SigmoidFit.cpp.
SigmoidFit::~SigmoidFit ()
Destructor.
Definition at line 52 of file SigmoidFit.cpp.
Member Function Documentation
void SigmoidFit::init (Model & model)
The init method does nothing usefull but fulfills the base class interface.
Definition at line 57 of file SigmoidFit.cpp.
double SigmoidFit::mylog (double x)
Compute the maximum of -200 and the logarithm of x.
Definition at line 157 of file SigmoidFit.cpp.
Referenced by optimize().
double SigmoidFit::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target)
Don't call the optimize member more than once, as the SigmoidFit optimizer is not iterative.
Parameters:
model reference to the SigmoidModel object to train
errorfunction unused - can be set to #SVM_Optimizer::dummyError.
input SVM output, real-valued
target binary labels +1 or -1
Definition at line 61 of file SigmoidFit.cpp.
References i, mylog(), and Model::setParameter().
The documentation for this class was generated from the following files:
SigmoidFit.h
SigmoidFit.cpp