ReClaM: JointKernelFunction Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
JointKernelFunction Class Reference
Joint kernel for input and label space.
#include <KernelFunction.h>
Public Member Functions
JointKernelFunction (KernelFunction &inputkernel, KernelFunction &labelkernel)
Constructor.
~JointKernelFunction ()
Destructor.
double eval (const Array< double > &x1, const Array< double > &y1, const Array< double > &x2, const Array< double > &y2) const
Evaluates the kernel function on a const object.
double evalDerivative (const Array< double > &x1, const Array< double > &y1, const Array< double > &x2, const Array< double > &y2, Array< double > &derivative) const
Evaluates the kernel function and computes its derivatives w.r.t.
void model (const Array< double > &input, Array< double > &output)
undefined; just throws an exception
void setParameter (unsigned int index, double value)
set a parameter of either input or label kernel
Protected Attributes
KernelFunction & m_inputkernel
input space kernel
KernelFunction & m_labelkernel
label/output space kernel
Detailed Description
Joint kernel for input and label space.
The JointKernelFunction class basically computes a kernel on where X is the input space and Y is the output space of a model. The computation is done as
The JointKernelFunction class holds the parameters of both (input and label) kernel objects.
Definition at line 436 of file KernelFunction.h.
Constructor & Destructor Documentation
JointKernelFunction::JointKernelFunction (KernelFunction & inputkernel, KernelFunction & labelkernel)
Constructor.
Definition at line 1124 of file KernelFunction.cpp.
References Model::getParameter(), Model::getParameterDimension(), i, and Model::parameter.
JointKernelFunction::~JointKernelFunction ()
Destructor.
Definition at line 1140 of file KernelFunction.cpp.
Member Function Documentation
double JointKernelFunction::eval (const Array< double > & x1, const Array< double > & y1, const Array< double > & x2, const Array< double > & y2) const
Evaluates the kernel function on a const object.
Definition at line 1145 of file KernelFunction.cpp.
References KernelFunction::eval(), m_inputkernel, and m_labelkernel.
Referenced by NegativeKTA::error().
double JointKernelFunction::evalDerivative (const Array< double > & x1, const Array< double > & y1, const Array< double > & x2, const Array< double > & y2, Array< double > & derivative) const
Evaluates the kernel function and computes its derivatives w.r.t.
the kernel parameters.
Definition at line 1152 of file KernelFunction.cpp.
References KernelFunction::evalDerivative(), Model::getParameterDimension(), i, m_inputkernel, and m_labelkernel.
Referenced by NegativeKTA::errorDerivative().
void JointKernelFunction::model (const Array< double > & input, Array< double > & output) [virtual]
undefined; just throws an exception
Implements Model.
Definition at line 1169 of file KernelFunction.cpp.
void JointKernelFunction::setParameter (unsigned int index, double value) [virtual]
set a parameter of either input or label kernel
Reimplemented from Model.
Definition at line 1174 of file KernelFunction.cpp.
References Model::getParameterDimension(), m_inputkernel, m_labelkernel, and Model::setParameter().
Member Data Documentation
KernelFunction& JointKernelFunction::m_inputkernel [protected]
input space kernel
Definition at line 461 of file KernelFunction.h.
Referenced by eval(), evalDerivative(), and setParameter().
KernelFunction& JointKernelFunction::m_labelkernel [protected]
label/output space kernel
Definition at line 464 of file KernelFunction.h.
Referenced by eval(), evalDerivative(), and setParameter().
The documentation for this class was generated from the following files:
KernelFunction.h
KernelFunction.cpp