ReClaM: StochasticGradientDescent Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
StochasticGradientDescent Class Reference
Learning strategies based on SteepestDescent, but with randomly chosen patterns.
#include <StochasticGradientDescent.h>
Public Member Functions
void init ()
void initStochasticGradientDescent (double lr=0.1, double mu=0.3, bool fast=false)
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Iterative update of weights, patterns are randomly chosen, each pattern only once.
void clearMemory ()
Clears the array of momentum values.
Detailed Description
Learning strategies based on SteepestDescent, but with randomly chosen patterns.
Similar to the most simple learning strategy SteepestDescent, the weights of the network are iteratively updated to minimize the error. When working with more than one pattern and gradient descent, all patterns are sequentially presented to the network and the weight update takes place after every pattern. Here you will find two methods that work on the base of SteepestDescent, but that will chose the next pattern for presentation by random.
Author:
P. Stagge
Date:
1999
Changes:
none
Status:
stable
Definition at line 86 of file StochasticGradientDescent.h.
Member Function Documentation
void StochasticGradientDescent::clearMemory () [inline]
Clears the array of momentum values.
The momentum values are the values that are added to the weights for updating.
Returns:
None.
Author:
P. Stagge
Date:
1999
Changes
none
Status
stable
Definition at line 228 of file StochasticGradientDescent.h.
void StochasticGradientDescent::init () [inline]
Definition at line 89 of file StochasticGradientDescent.h.
References initStochasticGradientDescent().
void StochasticGradientDescent::initStochasticGradientDescent (double lr = 0.1, double mu = 0.3, bool fast = false) [inline]
Definition at line 94 of file StochasticGradientDescent.h.
Referenced by init().
double StochasticGradientDescent::optimize (Model & model, ErrorFunction & error, const Array< double > & input, const Array< double > & target) [inline, virtual]
Iterative update of weights, patterns are randomly chosen, each pattern only once.
Similar to SteepestDescent, where the weights are iteratively updated by moving a short distance in the direction of the greatest decrease of the error, i.e. in the direction of the negative gradient by using the error derivatives. Additionally a momentum term is added to the gradient descent to deal with the problem of widely differing eigenvalues. The update of a weight at time to a weight at time is then given as
In contrast to SteepestDescent the weights for more than one pattern are not updated by choosing the patterns sequentially, but randomly. Compared to #learnfast a pattern can not be chosen more than once.
Parameters:
in Input vector for the model.
target Target vector.
lr Learning rate .
mu Momentum parameter .
Returns:
None.
Author:
P. Stagge
Date:
1999
Changes
none
Status
stable
Implements Optimizer.
Definition at line 141 of file StochasticGradientDescent.h.
References ErrorFunction::errorDerivative(), and i.
The documentation for this class was generated from the following file:
StochasticGradientDescent.h