ReClaM: WTA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
WTA Class Reference
Winner-takes-all error function.
#include <WTA.h>
Public Member Functions
double error (Model &model, const Array< double > &input, const Array< double > &target)
Caculates the error based on "the winner takes it all" strategy.
Protected Member Functions
void takeAll (Array< double > &a)
First searches for the best (maximum) output value, then sets this value to 1 and all others to 0.
Detailed Description
Winner-takes-all error function.
Examples:
LinearClassifierTest.cpp.
Definition at line 46 of file WTA.h.
Member Function Documentation
double WTA::error (Model & model, const Array< double > & input, const Array< double > & target) [inline, virtual]
Caculates the error based on "the winner takes it all" strategy.
This error measure is used for classification problems. For each pattern only the output neuron with the best (maximum) value is considered and set to 1, all other output neurons are set to zero. This result is compared with the target vectors and then the number of different vectors (= errors) is counted. Finally, the number of errors is normalized with the number of patterns.
Parameters:
model The model used for prediction
input Input vector for the model.
target Target vector.
Returns:
The number of errors, normalized with the number of patterns.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Implements ErrorFunction.
Examples:
LinearClassifierTest.cpp.
Definition at line 74 of file WTA.h.
References i, Model::model(), and takeAll().
void WTA::takeAll (Array< double > & a) [inline, protected]
First searches for the best (maximum) output value, then sets this value to 1 and all others to 0.
Definition at line 108 of file WTA.h.
References i.
Referenced by error().
The documentation for this class was generated from the following file:
WTA.h