ReClaM: CrammerSingerMcSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CrammerSingerMcSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
CrammerSingerMcSVM (MultiClassSVM *pSVM, double C, bool unconstrained=false)
Constructor.
~CrammerSingerMcSVM ()
Destructor.
double get_C ()
get the regularization constant
void set_C (double C)
set the regularization constant
bool isUnconstrained ()
return true if the exponential function is used to parameterize C
bool isFeasible ()
ensure C is positive
Protected Attributes
bool exponential
is C stored as log(C)?
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2008
Meta model for the multi class SVM proposed by Crammer and Singer.
Examples:
McSvm.cpp.
Definition at line 963 of file Svm.h.
Constructor & Destructor Documentation
CrammerSingerMcSVM::CrammerSingerMcSVM (MultiClassSVM * pSVM, double C, bool unconstrained = false)
Constructor.
Definition at line 1615 of file Svm.cpp.
References exponential, and set_C().
CrammerSingerMcSVM::~CrammerSingerMcSVM ()
Destructor.
Definition at line 1622 of file Svm.cpp.
Member Function Documentation
double CrammerSingerMcSVM::get_C () [inline]
get the regularization constant
Definition at line 974 of file Svm.h.
References exponential, and Model::parameter.
Referenced by SVM_Optimizer::init().
bool CrammerSingerMcSVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1627 of file Svm.cpp.
References exponential, and Model::parameter.
bool CrammerSingerMcSVM::isUnconstrained () [inline]
return true if the exponential function is used to parameterize C
Definition at line 988 of file Svm.h.
References exponential.
void CrammerSingerMcSVM::set_C (double C) [inline]
set the regularization constant
Definition at line 981 of file Svm.h.
References exponential, and MetaSVM::setParameter().
Referenced by CrammerSingerMcSVM().
Member Data Documentation
bool CrammerSingerMcSVM::exponential [protected]
is C stored as log(C)?
Definition at line 998 of file Svm.h.
Referenced by CrammerSingerMcSVM(), get_C(), isFeasible(), isUnconstrained(), and set_C().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp