ReClaM: NormalizedKernel Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
NormalizedKernel Class Reference
Normalized version of a kernel function.
#include <KernelFunction.h>
Public Member Functions
NormalizedKernel (KernelFunction *base)
~NormalizedKernel ()
void setParameter (unsigned int index, double value)
Modifies a specific model parameter.
double eval (const Array< double > &x1, const Array< double > &x2) const
Evaluates the kernel function on a const object.
double evalDerivative (const Array< double > &x1, const Array< double > &x2, Array< double > &derivative) const
Evaluates the kernel function and computes its derivatives w.r.t.
bool isFeasible ()
check whether the parameters define a feasible model
Protected Attributes
KernelFunction * baseKernel
kernel to normalize
Detailed Description
Normalized version of a kernel function.
For a positive definite kernel k, the normalized kernel
is again a positive definite kernel function.
Definition at line 283 of file KernelFunction.h.
Constructor & Destructor Documentation
NormalizedKernel::NormalizedKernel (KernelFunction * base)
Definition at line 729 of file KernelFunction.cpp.
References baseKernel, Model::getParameter(), Model::getParameterDimension(), i, Model::parameter, and setParameter().
NormalizedKernel::~NormalizedKernel ()
Definition at line 737 of file KernelFunction.cpp.
Member Function Documentation
double NormalizedKernel::eval (const Array< double > & x1, const Array< double > & x2) const [virtual]
Evaluates the kernel function on a const object.
Implements KernelFunction.
Definition at line 747 of file KernelFunction.cpp.
References baseKernel, and KernelFunction::eval().
double NormalizedKernel::evalDerivative (const Array< double > & x1, const Array< double > & x2, Array< double > & derivative) const [virtual]
Evaluates the kernel function and computes its derivatives w.r.t.
the kernel parameters.
Reimplemented from KernelFunction.
Definition at line 752 of file KernelFunction.cpp.
References baseKernel, KernelFunction::evalDerivative(), Model::getParameterDimension(), and i.
bool NormalizedKernel::isFeasible () [virtual]
check whether the parameters define a feasible model
The default implementation returns true, that is, every parameter configuration is considered feasible and unconstrained optimization is applicable. It is the Optimizer's responsibility to check the isFeasible() flag.
Returns:
true if the model is feasible, false otherwise
Author:
T. Glasmachers
Date:
2006
Reimplemented from Model.
Definition at line 776 of file KernelFunction.cpp.
References baseKernel, and Model::isFeasible().
void NormalizedKernel::setParameter (unsigned int index, double value) [virtual]
Modifies a specific model parameter.
Reimplemented from Model.
Definition at line 741 of file KernelFunction.cpp.
References baseKernel, Model::parameter, and Model::setParameter().
Referenced by NormalizedKernel().
Member Data Documentation
KernelFunction* NormalizedKernel::baseKernel [protected]
kernel to normalize
Definition at line 298 of file KernelFunction.h.
Referenced by eval(), evalDerivative(), isFeasible(), NormalizedKernel(), and setParameter().
The documentation for this class was generated from the following files:
KernelFunction.h
KernelFunction.cpp