ReClaM: NegativeLogLikelihood Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
NegativeLogLikelihood Class Reference
negative logarithm of the likelihood of a probabilistic binary classification model
#include <NegativeLogLikelihood.h>
Public Types
enum eLabelType { elBinary, elNumber, elVector }
Public Member Functions
NegativeLogLikelihood (eLabelType labelType=elBinary, unsigned int classes=2)
Constructor.
~NegativeLogLikelihood ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
error computation, see class description
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
error computation with derivatives, see class description
Protected Attributes
eLabelType m_LabelType
type of label information expected
unsigned int m_classes
number of classes spanning the probability simplex
Detailed Description
negative logarithm of the likelihood of a probabilistic binary classification model
This class makes two assumptions: First, the data must be a binary classification problem using labels +1 and -1. Second, the model must output values in the unit interval [0, 1] which are interpreted as the probability of an example being positive.
With data , a model f the error function is .
Definition at line 65 of file NegativeLogLikelihood.h.
Member Enumeration Documentation
enum NegativeLogLikelihood::eLabelType
Enumerator:
elBinary
elNumber
-1 or +1
elVector
0, ..., #classes-1
Definition at line 68 of file NegativeLogLikelihood.h.
Constructor & Destructor Documentation
NegativeLogLikelihood::NegativeLogLikelihood (NegativeLogLikelihood::eLabelType labelType = elBinary, unsigned int classes = 2)
Constructor.
Definition at line 45 of file NegativeLogLikelihood.cpp.
References elBinary, m_classes, and m_LabelType.
NegativeLogLikelihood::~NegativeLogLikelihood ()
Destructor.
Definition at line 52 of file NegativeLogLikelihood.cpp.
Member Function Documentation
double NegativeLogLikelihood::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
error computation, see class description
Implements ErrorFunction.
Definition at line 57 of file NegativeLogLikelihood.cpp.
References elBinary, elNumber, elVector, i, m_classes, m_LabelType, and Model::model().
Referenced by NoisySvmLikelihood::error(), and NoisySvmLikelihood::errorDerivative().
double NegativeLogLikelihood::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
error computation with derivatives, see class description
Reimplemented from ErrorFunction.
Definition at line 131 of file NegativeLogLikelihood.cpp.
References elBinary, elNumber, elVector, Model::getParameterDimension(), i, m_classes, m_LabelType, and Model::modelDerivative().
Member Data Documentation
unsigned int NegativeLogLikelihood::m_classes [protected]
number of classes spanning the probability simplex
Definition at line 93 of file NegativeLogLikelihood.h.
Referenced by error(), errorDerivative(), and NegativeLogLikelihood().
eLabelType NegativeLogLikelihood::m_LabelType [protected]
type of label information expected
Definition at line 90 of file NegativeLogLikelihood.h.
Referenced by error(), errorDerivative(), and NegativeLogLikelihood().
The documentation for this class was generated from the following files:
NegativeLogLikelihood.h
NegativeLogLikelihood.cpp