ReClaM: Partitioning Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Partitioning Class Reference
The Partitioning class defined a partitioning of a set of training points and labels as it is required for a cross validation procedure.
#include <CrossValidation.h>
Public Member Functions
Partitioning ()
Constructor.
~Partitioning ()
Destructor.
void CreateIID (int numberOfPartitions, const Array< double > &input, const Array< double > &target)
Create a partition.
void CreateSameSize (int numberOfPartitions, const Array< double > &input, const Array< double > &target)
Create a partition.
void CreateSameSizeBalanced (int numberOfPartitions, const Array< double > &input, const Array< double > &target)
Create a partition.
void CreateSameSizeMultiClassBalanced (int numberOfPartitions, const Array< double > &input, const Array< double > &target)
Create a partition for multi-class problems in a stratified way.
void CreateIndexed (int numberOfPartitions, const Array< double > &input, const Array< double > &target, const Array< int > &index)
Create a partition.
int getNumberOfPartitions ()
Return the number of partitions in the partitioning.
const Array< double > & train_input (int part)
Return the part-th training point array.
const Array< double > & train_target (int part)
Return the part-th training label array.
const Array< double > & validation_input (int part)
Return the part-th validation point array.
const Array< double > & validation_target (int part)
Return the part-th validation label array.
int getPartition (int example)
Return the validation set partition for a given example.
int getExample (int part, int index)
Return the example at a given index in a given partition.
Protected Member Functions
void Clear ()
free memory
Protected Attributes
int partitions
number of partitions of the data
Array< int > part_index
index array: which example belongs to which validation set?
std::vector< Array< int > * > inverse_part_index
index array: which validation set consists of which examples?
std::vector< Array< double > * > part_train_input
training points
std::vector< Array< double > * > part_train_target
training labels
std::vector< Array< double > * > part_validation_input
validation points
std::vector< Array< double > * > part_validation_target
validation labels
Detailed Description
The Partitioning class defined a partitioning of a set of training points and labels as it is required for a cross validation procedure.
That is, the data are split into N subsets, usually of comparable size. Then, the data are combined into training and validation sets in N different ways, called partitions. For every partition, one of the N subsets is used for validation, while the union of all other subsets it used for training.
Examples:
CrossValidation.cpp.
Definition at line 69 of file CrossValidation.h.
Constructor & Destructor Documentation
Partitioning::Partitioning ()
Constructor.
Definition at line 52 of file CrossValidation.cpp.
References partitions.
Partitioning::~Partitioning ()
Destructor.
Definition at line 57 of file CrossValidation.cpp.
References Clear().
Member Function Documentation
void Partitioning::Clear () [protected]
free memory
Definition at line 363 of file CrossValidation.cpp.
References i, inverse_part_index, part_train_input, part_train_target, part_validation_input, part_validation_target, and partitions.
Referenced by CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and ~Partitioning().
void Partitioning::CreateIID (int numberOfPartitions, const Array< double > & input, const Array< double > & target)
Create a partition.
The subset each training examples belongs to is drawn independently and uniformly distributed. For every partition, all but one subset form the training set, while the remaining one is used for validation.
Parameters:
numberOfPartitions number of partitions to create
input input data to separate into subsets
target labels corresponding to the input data
Definition at line 63 of file CrossValidation.cpp.
References CreateIndexed().
void Partitioning::CreateIndexed (int numberOfPartitions, const Array< double > & input, const Array< double > & target, const Array< int > & index)
Create a partition.
Every subset contains (approximately) the same number of elements. For every partition, all but one subset form the training set, while the remaining one is used for validation.
Parameters:
numberOfPartitions number of partitions to create
input input data to separate into subsets
target labels corresponding to the input data
index partition indices of the examples in [0, ..., numberOfPartitions[.
Definition at line 222 of file CrossValidation.cpp.
References Clear(), i, inverse_part_index, part_index, part_train_input, part_train_target, part_validation_input, part_validation_target, and partitions.
Referenced by CreateIID().
void Partitioning::CreateSameSize (int numberOfPartitions, const Array< double > & input, const Array< double > & target)
Create a partition.
Every subset contains (approximately) the same number of elements. For every partition, all but one subset form the training set, while the remaining one is used for validation.
Parameters:
numberOfPartitions number of partitions to create
input input data to separate into subsets
target labels corresponding to the input data
Examples:
CrossValidation.cpp.
Definition at line 76 of file CrossValidation.cpp.
References Clear(), i, inverse_part_index, part_index, part_train_input, part_train_target, part_validation_input, part_validation_target, and partitions.
void Partitioning::CreateSameSizeBalanced (int numberOfPartitions, const Array< double > & input, const Array< double > & target)
Create a partition.
Every subset contains (approximately) the same number of elements. For every partition, all but one subset form the training set, while the remaining one is used for validation. The targets are assumed to be +1 and -1 and the subsets contain approximately the same fraction of positive and negative examples as the whole training set.
Parameters:
numberOfPartitions number of partitions to create
input input data to separate into subsets
target labels corresponding to the input data
Definition at line 138 of file CrossValidation.cpp.
References Clear(), i, inverse_part_index, part_index, part_train_input, part_train_target, part_validation_input, part_validation_target, and partitions.
void Partitioning::CreateSameSizeMultiClassBalanced (int numberOfPartitions, const Array< double > & input, const Array< double > & target)
Create a partition for multi-class problems in a stratified way.
Every subset contains (approximately) the same number of elements. For every partition, all but one subset form the training set, while the remaining one is used for validation. The targets are assumed to intergers and the subsets contain approximately the same fraction of examples from each class as the whole training set. The function is deterministic, so consider calling ShuffleTraining() before.
Parameters:
numberOfPartitions number of partitions to create
input input data to split into subsets
target labels corresponding to the input data
Definition at line 285 of file CrossValidation.cpp.
References Clear(), i, inverse_part_index, part_index, part_train_input, part_train_target, part_validation_input, part_validation_target, and partitions.
int Partitioning::getExample (int part, int index) [inline]
Return the example at a given index in a given partition.
Definition at line 198 of file CrossValidation.h.
References inverse_part_index.
int Partitioning::getNumberOfPartitions () [inline]
Return the number of partitions in the partitioning.
Definition at line 162 of file CrossValidation.h.
References partitions.
Referenced by CVError::error(), and CVError::errorDerivative().
int Partitioning::getPartition (int example) [inline]
Return the validation set partition for a given example.
Definition at line 192 of file CrossValidation.h.
References part_index.
const Array<double>& Partitioning::train_input (int part) [inline]
Return the part-th training point array.
Definition at line 168 of file CrossValidation.h.
References part_train_input.
Referenced by CVError::error(), and CVError::errorDerivative().
const Array<double>& Partitioning::train_target (int part) [inline]
Return the part-th training label array.
Definition at line 174 of file CrossValidation.h.
References part_train_target.
Referenced by CVError::error(), and CVError::errorDerivative().
const Array<double>& Partitioning::validation_input (int part) [inline]
Return the part-th validation point array.
Definition at line 180 of file CrossValidation.h.
References part_validation_input.
Referenced by CVError::error(), and CVError::errorDerivative().
const Array<double>& Partitioning::validation_target (int part) [inline]
Return the part-th validation label array.
Definition at line 186 of file CrossValidation.h.
References part_validation_target.
Referenced by CVError::error(), and CVError::errorDerivative().
Member Data Documentation
std::vector< Array<int>* > Partitioning::inverse_part_index [protected]
index array: which validation set consists of which examples?
Definition at line 214 of file CrossValidation.h.
Referenced by Clear(), CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and getExample().
Array<int> Partitioning::part_index [protected]
index array: which example belongs to which validation set?
Definition at line 211 of file CrossValidation.h.
Referenced by CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and getPartition().
std::vector< Array<double>* > Partitioning::part_train_input [protected]
training points
Definition at line 217 of file CrossValidation.h.
Referenced by Clear(), CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and train_input().
std::vector< Array<double>* > Partitioning::part_train_target [protected]
training labels
Definition at line 220 of file CrossValidation.h.
Referenced by Clear(), CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and train_target().
std::vector< Array<double>* > Partitioning::part_validation_input [protected]
validation points
Definition at line 223 of file CrossValidation.h.
Referenced by Clear(), CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and validation_input().
std::vector< Array<double>* > Partitioning::part_validation_target [protected]
validation labels
Definition at line 226 of file CrossValidation.h.
Referenced by Clear(), CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), and validation_target().
int Partitioning::partitions [protected]
number of partitions of the data
Definition at line 208 of file CrossValidation.h.
Referenced by Clear(), CreateIndexed(), CreateSameSize(), CreateSameSizeBalanced(), CreateSameSizeMultiClassBalanced(), getNumberOfPartitions(), and Partitioning().
The documentation for this class was generated from the following files:
CrossValidation.h
CrossValidation.cpp