ReClaM: TransformedProblem Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
TransformedProblem Class Reference
linear transformation of data
#include <ArtificialDistributions.h>
Public Member Functions
TransformedProblem (DataSource &source, Array2D< double > &transformation)
Constructor.
~TransformedProblem ()
Descructor.
bool GetData (Array< double > &data, Array< double > &target, int count)
This function generates examples drawn i.i.d.
Protected Attributes
DataSource & base
Array2D< double > transformation
Detailed Description
linear transformation of data
The TransformedProblem class applies a linear transformation to the input-part x of the examples (x, y) created by another DataSource object.
Definition at line 203 of file ArtificialDistributions.h.
Constructor & Destructor Documentation
TransformedProblem::TransformedProblem (DataSource & source, Array2D< double > & transformation)
Constructor.
Definition at line 259 of file ArtificialDistributions.cpp.
References DataSource::dataDim, DataSource::getDataDimension(), DataSource::getTargetDimension(), DataSource::targetDim, and transformation.
TransformedProblem::~TransformedProblem ()
Descructor.
Definition at line 271 of file ArtificialDistributions.cpp.
Member Function Documentation
bool TransformedProblem::GetData (Array< double > & data, Array< double > & target, int count) [virtual]
This function generates examples drawn i.i.d.
from the distribution.
Implements DataSource.
Definition at line 276 of file ArtificialDistributions.cpp.
References base, DataSource::dataDim, DataSource::GetData(), i, and transformation.
Member Data Documentation
DataSource& TransformedProblem::base [protected]
Definition at line 218 of file ArtificialDistributions.h.
Referenced by GetData().
Array2D<double> TransformedProblem::transformation [protected]
Definition at line 219 of file ArtificialDistributions.h.
Referenced by GetData(), and TransformedProblem().
The documentation for this class was generated from the following files:
ArtificialDistributions.h
ArtificialDistributions.cpp