ReClaM: InverseClassSeparability Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
InverseClassSeparability Class Reference
Inverse of the Class Separability Measure J by Huilin Xiong and M.
#include <InverseClassSeparability.h>
Public Member Functions
InverseClassSeparability ()
Constructor.
~InverseClassSeparability ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computes the inverse Class Separability 1/J.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Computes the inverse Class Separability 1/J and its derivatives.
Detailed Description
Inverse of the Class Separability Measure J by Huilin Xiong and M.
N. S. Swamy
Definition at line 55 of file InverseClassSeparability.h.
Constructor & Destructor Documentation
InverseClassSeparability::InverseClassSeparability ()
Constructor.
Definition at line 45 of file InverseClassSeparability.cpp.
InverseClassSeparability::~InverseClassSeparability ()
Destructor.
Definition at line 49 of file InverseClassSeparability.cpp.
Member Function Documentation
double InverseClassSeparability::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computes the inverse Class Separability 1/J.
Implements ErrorFunction.
Definition at line 54 of file InverseClassSeparability.cpp.
References KernelFunction::eval(), and i.
double InverseClassSeparability::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Computes the inverse Class Separability 1/J and its derivatives.
Reimplemented from ErrorFunction.
Definition at line 126 of file InverseClassSeparability.cpp.
References KernelFunction::evalDerivative(), Model::getParameterDimension(), and i.
The documentation for this class was generated from the following files:
InverseClassSeparability.h
InverseClassSeparability.cpp