ReClaM: NegativePolarization Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
NegativePolarization Class Reference
Implementation of the negative Kernel Polarization Measure, that is, Kernel Target Alignment without normalization.
#include <NegativePolarization.h>
Public Member Functions
NegativePolarization ()
Constructor.
~NegativePolarization ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computes the negative kernel polarization between the target and the kernel function output on the input.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Computes the negative kernel polarization between the target and the kernel function output on the input.
Detailed Description
Implementation of the negative Kernel Polarization Measure, that is, Kernel Target Alignment without normalization.
Kernel polarization measures how good a kernel fits
a binary classification training set. It is NOT invariant under kernel rescaling. To turn it into an error function (i.e., to make minimization meaningful) the negative polarization is implemented.
The polarization has two important properties: It is
differentiable and independent of the actual classifier.
The class NegativePolarization accepts two
kinds of models: KernelFunction derived classes and C_SVM with 2-norm slack penalty. In the first case, only the kernel parameters are considered in the derivative computation. In the second case, in addition the derivatives w.r.t. the parameters and are computed.
Please note that is the vast majority of cases it is a
good idea to consider the kernel target alignment class NegativeKTA instead.
Definition at line 78 of file NegativePolarization.h.
Constructor & Destructor Documentation
NegativePolarization::NegativePolarization ()
Constructor.
Definition at line 46 of file NegativePolarization.cpp.
NegativePolarization::~NegativePolarization ()
Destructor.
Definition at line 50 of file NegativePolarization.cpp.
Member Function Documentation
double NegativePolarization::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computes the negative kernel polarization between the target and the kernel function output on the input.
Implements ErrorFunction.
Definition at line 55 of file NegativePolarization.cpp.
References KernelFunction::eval(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM::getKernel(), MetaSVM::getSVM(), i, and C_SVM::is2norm().
double NegativePolarization::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Computes the negative kernel polarization between the target and the kernel function output on the input.
The partial derivatives of the negative polarization w.r.t. the model parameters are returned in the derivative parameter.
Reimplemented from ErrorFunction.
Definition at line 86 of file NegativePolarization.cpp.
References KernelFunction::evalDerivative(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM::getKernel(), Model::getParameterDimension(), MetaSVM::getSVM(), i, and C_SVM::is2norm().
The documentation for this class was generated from the following files:
NegativePolarization.h
NegativePolarization.cpp