ReClaM: sWallTimer Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
sWallTimer Class Reference
Convenience structure for wall-clock time keeping, platform-specific.
#include <Utilities.h>
Public Member Functions
void tic ()
double toc ()
double tocAndTic ()
Protected Member Functions
double getCurTimeInSecs ()
Protected Attributes
double m_temp
double m_start_time
timespec m_tv
Detailed Description
Convenience structure for wall-clock time keeping, platform-specific.
Definition at line 91 of file Utilities.h.
Member Function Documentation
double sWallTimer::getCurTimeInSecs () [inline, protected]
Definition at line 122 of file Utilities.h.
References m_tv.
Referenced by tic(), toc(), and tocAndTic().
void sWallTimer::tic () [inline]
Definition at line 95 of file Utilities.h.
References getCurTimeInSecs(), and m_start_time.
Referenced by QpEbCsDecomp::Solve().
double sWallTimer::toc () [inline]
Definition at line 100 of file Utilities.h.
References getCurTimeInSecs(), and m_start_time.
Referenced by QpEbCsDecomp::selectNextPattern(), and QpEbCsDecomp::Solve().
double sWallTimer::tocAndTic () [inline]
Definition at line 105 of file Utilities.h.
References getCurTimeInSecs(), m_start_time, and m_temp.
Member Data Documentation
double sWallTimer::m_start_time [protected]
Definition at line 114 of file Utilities.h.
Referenced by tic(), toc(), and tocAndTic().
double sWallTimer::m_temp [protected]
Definition at line 113 of file Utilities.h.
Referenced by tocAndTic().
timespec sWallTimer::m_tv [protected]
Definition at line 119 of file Utilities.h.
Referenced by getCurTimeInSecs().
The documentation for this class was generated from the following file:
Utilities.h