ReClaM: RegularizationNetwork Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
RegularizationNetwork Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
RegularizationNetwork (SVM *pSVM, double gamma)
Constructor.
~RegularizationNetwork ()
Destructor.
double get_gamma ()
void set_gamma (double gamma)
bool isFeasible ()
ensure gamma is positive
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2007
The Regularization Network is a special training scheme for SVM training. It simply minimizes the regularized mean squared error resulting in a quadratic program without any constraints.
Definition at line 871 of file Svm.h.
Constructor & Destructor Documentation
RegularizationNetwork::RegularizationNetwork (SVM * pSVM, double gamma)
Constructor.
Definition at line 1268 of file Svm.cpp.
References Model::parameter.
RegularizationNetwork::~RegularizationNetwork ()
Destructor.
Definition at line 1274 of file Svm.cpp.
Member Function Documentation
double RegularizationNetwork::get_gamma () [inline]
Definition at line 881 of file Svm.h.
References Model::parameter.
Referenced by SVM_Optimizer::init().
bool RegularizationNetwork::isFeasible () [virtual]
ensure gamma is positive
Reimplemented from MetaSVM.
Definition at line 1279 of file Svm.cpp.
References MetaSVM::isFeasible(), and Model::parameter.
void RegularizationNetwork::set_gamma (double gamma) [inline]
Definition at line 882 of file Svm.h.
References MetaSVM::setParameter().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp