ReClaM: LinearEquation Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LinearEquation Class Reference
Model and Error Function for the iterative approximate solution of a linear system.
#include <LinearEquation.h>
Public Member Functions
LinearEquation (const Array< double > &mat, const Array< double > &vec)
Constructor.
~LinearEquation ()
Destructor.
void model (const Array< double > &input, Array< double > &output)
The model method throws an exception because this is not a data processing model.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computation of the error.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Computation of the error and its derivative.
void getSolution (Array< double > &solution)
Return of the current solution.
Protected Member Functions
double error ()
double errorDerivative (Array< double > &derivative)
Protected Attributes
const Array< double > & matrix
const Array< double > & vector
Detailed Description
Model and Error Function for the iterative approximate solution of a linear system.
The LinearEquation class takes a matrix M and a vector v as arguments to its constructor, representing the equation . The model represents the vector x, while the error function encapsulates the quadratic term . With this error function any ReClaM optimizer can be used to iteratively solve the linear system.
This class is useful in cases where the inverse of the matrix M is hard to compute, either because the conditioning number or the dimension of M is large, leading to numerical instability.
Definition at line 73 of file LinearEquation.h.
Constructor & Destructor Documentation
LinearEquation::LinearEquation (const Array< double > & mat, const Array< double > & vec)
Constructor.
Definition at line 48 of file LinearEquation.cpp.
References Model::parameter.
LinearEquation::~LinearEquation ()
Destructor.
Definition at line 60 of file LinearEquation.cpp.
Member Function Documentation
double LinearEquation::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computation of the error.
Implements ErrorFunction.
Definition at line 110 of file LinearEquation.cpp.
References error().
double LinearEquation::error () [protected]
Definition at line 70 of file LinearEquation.cpp.
References Model::getParameter(), i, matrix, and vector.
Referenced by error().
double LinearEquation::errorDerivative (Array< double > & derivative) [protected]
Definition at line 86 of file LinearEquation.cpp.
References Model::getParameter(), i, matrix, and vector.
double LinearEquation::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Computation of the error and its derivative.
Reimplemented from ErrorFunction.
Definition at line 115 of file LinearEquation.cpp.
void LinearEquation::getSolution (Array< double > & solution)
Return of the current solution.
Definition at line 120 of file LinearEquation.cpp.
References Model::parameter.
void LinearEquation::model (const Array< double > & input, Array< double > & output) [virtual]
The model method throws an exception because this is not a data processing model.
Implements Model.
Definition at line 65 of file LinearEquation.cpp.
Member Data Documentation
const Array<double>& LinearEquation::matrix [protected]
Definition at line 99 of file LinearEquation.h.
Referenced by error(), and errorDerivative().
const Array<double>& LinearEquation::vector [protected]
Definition at line 100 of file LinearEquation.h.
Referenced by error(), and errorDerivative().
The documentation for this class was generated from the following files:
LinearEquation.h
LinearEquation.cpp