ReClaM: ComponentWiseModel Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ComponentWiseModel Class Reference
The ComponentWiseModel encapsulates the component wise application of a base model.
#include <ComponentWiseModel.h>
Public Member Functions
ComponentWiseModel (Model *pBase, int numberOfCopies)
Constructor.
~ComponentWiseModel ()
Destructor.
void model (const Array< double > &input, Array< double > &output)
Evaluate the ComponentWise model.
void modelDerivative (const Array< double > &input, Array< double > &derivative)
Evaluate the ComponentWise model and compute its derivative.
void modelDerivative (const Array< double > &input, Array< double > &output, Array< double > &derivative)
Evaluate the ComponentWise model and compute its derivative.
bool isFeasible ()
Check whether the parameters define a valid model.
Protected Attributes
int copies
number of base model copies
Model * base
single base model
Detailed Description
The ComponentWiseModel encapsulates the component wise application of a base model.
The component wise application of a model to data is a mapping of the form , that is, the model f makes its predictions by applying the model g to each component of the input data. Of course, the parameters of f and g coincide.
Definition at line 60 of file ComponentWiseModel.h.
Constructor & Destructor Documentation
ComponentWiseModel::ComponentWiseModel (Model * pBase, int numberOfCopies)
Constructor.
Definition at line 46 of file ComponentWiseModel.cpp.
References base, copies, Model::getInputDimension(), Model::getOutputDimension(), Model::getParameter(), Model::getParameterDimension(), Model::inputDimension, Model::outputDimension, and Model::parameter.
ComponentWiseModel::~ComponentWiseModel ()
Destructor.
Definition at line 59 of file ComponentWiseModel.cpp.
Member Function Documentation
bool ComponentWiseModel::isFeasible () [virtual]
Check whether the parameters define a valid model.
Reimplemented from Model.
Definition at line 135 of file ComponentWiseModel.cpp.
References base, and Model::isFeasible().
void ComponentWiseModel::model (const Array< double > & input, Array< double > & output) [virtual]
Evaluate the ComponentWise model.
Implements Model.
Definition at line 64 of file ComponentWiseModel.cpp.
References base, copies, Model::getInputDimension(), Model::getOutputDimension(), Model::getParameterDimension(), i, Model::model(), Model::parameter, and Model::setParameter().
void ComponentWiseModel::modelDerivative (const Array< double > & input, Array< double > & output, Array< double > & derivative) [virtual]
Evaluate the ComponentWise model and compute its derivative.
Reimplemented from Model.
Definition at line 126 of file ComponentWiseModel.cpp.
References base, Model::getParameterDimension(), Model::parameter, and Model::setParameter().
void ComponentWiseModel::modelDerivative (const Array< double > & input, Array< double > & derivative) [virtual]
Evaluate the ComponentWise model and compute its derivative.
Reimplemented from Model.
Definition at line 117 of file ComponentWiseModel.cpp.
References base, Model::getParameterDimension(), Model::parameter, and Model::setParameter().
Member Data Documentation
Model* ComponentWiseModel::base [protected]
single base model
Definition at line 87 of file ComponentWiseModel.h.
Referenced by ComponentWiseModel(), isFeasible(), model(), and modelDerivative().
int ComponentWiseModel::copies [protected]
number of base model copies
Definition at line 84 of file ComponentWiseModel.h.
Referenced by ComponentWiseModel(), and model().
The documentation for this class was generated from the following files:
ComponentWiseModel.h
ComponentWiseModel.cpp