ReClaM: SpanBoundA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SpanBoundA Class Reference
approximate SpanBound for the 1-norm SVM
#include <SpanBoundA.h>
Public Member Functions
SpanBoundA ()
Constructor.
~SpanBoundA ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computation of the span bound.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Computation of the span bound and its derivative.
void setMaxIterations (SharkInt64 maxiter=-1)
set the maximum number of iterations for the quadratic program solver
SharkInt64 iterations ()
return the number of iterations last used by the quadratic program solver
Protected Attributes
SharkInt64 maxIter
maximum number of #C_Solver iterations
SharkInt64 iter
last number if #C_Solver iterations
Detailed Description
approximate SpanBound for the 1-norm SVM
Definition at line 51 of file SpanBoundA.h.
Constructor & Destructor Documentation
SpanBoundA::SpanBoundA ()
Constructor.
Definition at line 45 of file SpanBoundA.cpp.
References maxIter.
SpanBoundA::~SpanBoundA ()
Destructor.
Definition at line 50 of file SpanBoundA.cpp.
Member Function Documentation
double SpanBoundA::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computation of the span bound.
Implements ErrorFunction.
Definition at line 55 of file SpanBoundA.cpp.
References KernelFunction::eval(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM_Optimizer::get_Solver(), SVM::getKernel(), Model::getParameter(), MetaSVM::getSVM(), i, SVM_Optimizer::init(), C_SVM::is2norm(), QpSvmDecomp::isOptimal(), iter, QpSvmDecomp::iterations(), maxIter, SVM_Optimizer::optimize(), and SVM_Optimizer::setMaxIterations().
double SpanBoundA::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Computation of the span bound and its derivative.
Reimplemented from ErrorFunction.
Definition at line 126 of file SpanBoundA.cpp.
References KernelFunction::eval(), KernelFunction::evalDerivative(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM_Optimizer::get_Solver(), SVM::getKernel(), Model::getParameter(), Model::getParameterDimension(), MetaSVM::getSVM(), i, SVM_Optimizer::init(), C_SVM::is2norm(), QpSvmDecomp::isOptimal(), iter, QpSvmDecomp::iterations(), maxIter, SVM_Optimizer::optimize(), C_SVM::PrepareDerivative(), and SVM_Optimizer::setMaxIterations().
SharkInt64 SpanBoundA::iterations () [inline]
return the number of iterations last used by the quadratic program solver
Definition at line 76 of file SpanBoundA.h.
References iter.
void SpanBoundA::setMaxIterations (SharkInt64 maxiter = -1) [inline]
set the maximum number of iterations for the quadratic program solver
Definition at line 69 of file SpanBoundA.h.
References maxIter.
Member Data Documentation
SharkInt64 SpanBoundA::iter [protected]
last number if #C_Solver iterations
Definition at line 86 of file SpanBoundA.h.
Referenced by error(), errorDerivative(), and iterations().
SharkInt64 SpanBoundA::maxIter [protected]
maximum number of #C_Solver iterations
Definition at line 83 of file SpanBoundA.h.
Referenced by error(), errorDerivative(), setMaxIterations(), and SpanBoundA().
The documentation for this class was generated from the following files:
SpanBoundA.h
SpanBoundA.cpp