ReClaM: CVError Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CVError Class Reference
ErrorFunction based on a cross validation procedure
#include <CrossValidation.h>
Public Member Functions
CVError (Partitioning &part, ErrorFunction &error, Optimizer &optimizer, int iter)
Constructor.
~CVError ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Compute the cross validation error defined as the mean error over the subsets.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Compute the cross validation error defined as the mean error over the subsets and its derivative.
ErrorFunction & getBaseError ()
Optimizer & getBaseOptimizer ()
Partitioning & getPartitioning ()
Protected Attributes
Partitioning & partitioning
Partitioning upon which the cross validation procedure is based.
ErrorFunction & baseError
ErrorFunction to use for the single cross validation tasks.
Optimizer & baseOptimizer
Optimizer to use for the single cross validation tasks.
int iterations
Number of iterations to perform for the optimization of the single cross validation tasks.
Detailed Description
ErrorFunction based on a cross validation procedure
The CVError class computes the mean error over partitions, that is, the cross validation error. It trains the sub-models defined by the CVModel object with a given Optimizer on a given ErrorFunction using the training parts of the partitions. For the mean error computation, it uses the varidation part of the partitions, which contain every example exactly once.
Examples:
CrossValidation.cpp.
Definition at line 324 of file CrossValidation.h.
Constructor & Destructor Documentation
CVError::CVError (Partitioning & part, ErrorFunction & error, Optimizer & optimizer, int iter)
Constructor.
Parameters:
part Partitioning defining subsets
error ErrorFunction used for the subset tasks
optimizer Optimizer used for the subset tasks
iter number of optimization iterations for the subset tasks
Definition at line 455 of file CrossValidation.cpp.
References iterations.
CVError::~CVError ()
Destructor.
Definition at line 463 of file CrossValidation.cpp.
Member Function Documentation
double CVError::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Compute the cross validation error defined as the mean error over the subsets.
Parameters:
model The model parameter has to be a reference to a CVModel object.
Implements ErrorFunction.
Definition at line 468 of file CrossValidation.cpp.
References baseError, baseOptimizer, ErrorFunction::error(), CVModel::getBaseModel(), Partitioning::getNumberOfPartitions(), Optimizer::init(), iterations, Optimizer::optimize(), partitioning, CVModel::setBaseModel(), Partitioning::train_input(), Partitioning::train_target(), Partitioning::validation_input(), and Partitioning::validation_target().
double CVError::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Compute the cross validation error defined as the mean error over the subsets and its derivative.
This makes rarely sense, as cross validation is usually used with non-differentiable error measures.
Reimplemented from ErrorFunction.
Definition at line 503 of file CrossValidation.cpp.
References baseError, baseOptimizer, ErrorFunction::errorDerivative(), CVModel::getBaseModel(), Partitioning::getNumberOfPartitions(), Model::getParameterDimension(), Optimizer::init(), iterations, Optimizer::optimize(), partitioning, CVModel::setBaseModel(), Partitioning::train_input(), Partitioning::train_target(), Partitioning::validation_input(), and Partitioning::validation_target().
ErrorFunction& CVError::getBaseError () [inline]
Definition at line 351 of file CrossValidation.h.
References baseError.
Optimizer& CVError::getBaseOptimizer () [inline]
Definition at line 356 of file CrossValidation.h.
References baseOptimizer.
Partitioning& CVError::getPartitioning () [inline]
Definition at line 361 of file CrossValidation.h.
References partitioning.
Member Data Documentation
ErrorFunction& CVError::baseError [protected]
ErrorFunction to use for the single cross validation tasks.
Definition at line 371 of file CrossValidation.h.
Referenced by error(), errorDerivative(), and getBaseError().
Optimizer& CVError::baseOptimizer [protected]
Optimizer to use for the single cross validation tasks.
Definition at line 374 of file CrossValidation.h.
Referenced by error(), errorDerivative(), and getBaseOptimizer().
int CVError::iterations [protected]
Number of iterations to perform for the optimization of the single cross validation tasks.
Definition at line 377 of file CrossValidation.h.
Referenced by CVError(), error(), and errorDerivative().
Partitioning& CVError::partitioning [protected]
Partitioning upon which the cross validation procedure is based.
Definition at line 368 of file CrossValidation.h.
Referenced by error(), errorDerivative(), and getPartitioning().
The documentation for this class was generated from the following files:
CrossValidation.h
CrossValidation.cpp