ReClaM: Perceptron Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Perceptron Class Reference
Perceptron online learning algorith.
#include <Perceptron.h>
Public Member Functions
Perceptron ()
Constructor.
~Perceptron ()
Destructor.
void init (Model &model)
basic initialization with default parameters
void optimize (SVM &svm, const Array< double > &input, const Array< double > &target)
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Performes one optimization step, for example a gradient descent step or an evolution cycle.
Detailed Description
Perceptron online learning algorith.
Definition at line 54 of file Perceptron.h.
Constructor & Destructor Documentation
Perceptron::Perceptron ()
Constructor.
Definition at line 48 of file Perceptron.cpp.
Perceptron::~Perceptron ()
Destructor.
Definition at line 52 of file Perceptron.cpp.
Member Function Documentation
void Perceptron::init (Model & model) [virtual]
basic initialization with default parameters
Implements Optimizer.
Definition at line 57 of file Perceptron.cpp.
double Perceptron::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Performes one optimization step, for example a gradient descent step or an evolution cycle.
Parameters:
model Model to use for the computation.
errorfunction ErrorFunction on which decisions are based.
input Vector of input values.
target Vector of output values.
Returns:
The error E returned by the ErrorFunction.
Implements Optimizer.
Definition at line 89 of file Perceptron.cpp.
References optimize().
void Perceptron::optimize (SVM & svm, const Array< double > & input, const Array< double > & target)
Definition at line 63 of file Perceptron.cpp.
References Model::getParameter(), i, SVM::model(), Model::setParameter(), and SVM::SetTrainingData().
Referenced by optimize().
The documentation for this class was generated from the following files:
Perceptron.h
Perceptron.cpp