ReClaM: MultiClassSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
MultiClassSVM Class Reference
Multi Class Support Vector Machine Model.
#include <Svm.h>
Public Member Functions
MultiClassSVM (KernelFunction *pKernel, unsigned int numberOfClasses, bool bNumberOutput=true)
Constructor.
~MultiClassSVM ()
Destructor.
void setNumberOutput (bool bNumberOutput=true)
Set the output mode to integer or vector mode.
void SetTrainingData (const Array< double > &input, const Array< double > &target, bool copy=false)
Make the training data known to the SVM.
void SetTrainingData (const Array< double > &input, bool copy=false)
Make the training data known to the SVM.
void model (const Array< double > &input, Array< double > &output)
compute the SVM prediction on data
unsigned int model (const Array< double > &input)
compute the SVM prediction on data
bool isSupportVector (unsigned exampleIndex)
returns true if alpha != 0 in one of the machines
unsigned getNumberOfSupportVectors ()
returns the number of examples that have an alpha != 0 in one of the classes
unsigned getNumberOfSupportVectors (unsigned c)
returns the number of examples that have an alpha != 0 in a certain class
KernelFunction * getKernel ()
return the kernel function object
const Array< double > & getPoints ()
return the training data points
const Array< double > & getTargets ()
return the training data labels
double getAlpha (unsigned int index, unsigned int c) const
return the coefficient of a given example and label
double getOffset (unsigned int c) const
return the solution offset vector
unsigned int getClasses () const
return the number of classes
unsigned int getExamples () const
return the number of examples
unsigned int getDimension ()
return the input space dimension
unsigned int VectorToClass (const Array< double > &v)
convert a label vector into a class index
void MakeSparse ()
Discard zero coefficients and corresponding training data.
Protected Member Functions
void Predict (const Array< double > &input, Array< double > &output)
void Predict (const Array< double > &input, ArrayReference< double > output)
void setAlpha (unsigned int index, unsigned int c, double value)
sets the coefficient of a given example and label
double getOffset (unsigned int c, double value) const
sets the solution offset vector
Protected Attributes
KernelFunction * kernel
kernel function
bool bOwnMemory
true if x and y are allocated by LoadModel
const Array< double > * x
training data points
const Array< double > * y
training data labels
bool numberOutput
true if the SVM outputs the class label only false if the SVM outputs the value of the linear feature space function.
unsigned int examples
number of training data points and labels
unsigned int classes
number of classes
Friends
class McSvmApproximation
Detailed Description
Multi Class Support Vector Machine Model.
Author:
T. Glasmachers
Date:
2007
The MultiClassSVM class provides a Support Vector
Machine as a parametric Model, that is, it computes a linear expansion of the kernel function with fixed training examples as one component. It can be viewed as a parametrized family of maps from the input space to the output space. In this formulation the output space is some .
In constrast to the binary classification or
regression SVM the MultiClassSVM maps inputs not to the reals but to a vector space, using one component per class. The prediction of the machine is simply the index of the largest component.
The parameters of this machine are organized
into one decision function per class. Therefore there exist as many parameters as there are training examples times classes. For some formulations of multi class SVMs some of these are dummy variables which are always zero. Furthermore, for most training procedures available by now the offset or bias term is set to zero.
Examples:
McSvm.cpp.
Definition at line 374 of file Svm.h.
Constructor & Destructor Documentation
MultiClassSVM::MultiClassSVM (KernelFunction * pKernel, unsigned int numberOfClasses, bool bNumberOutput = true)
Constructor.
Parameters:
pKernel input space kernel
numberOfClasses number of classes with indices starting from 0
bNumberOutput true: output class index; false: output vector
Definition at line 699 of file Svm.cpp.
MultiClassSVM::~MultiClassSVM ()
Destructor.
Definition at line 713 of file Svm.cpp.
Member Function Documentation
double MultiClassSVM::getAlpha (unsigned int index, unsigned int c) const [inline]
return the coefficient of a given example and label
Parameters:
index index of the corresponding training example
c zero-based class index (0, ..., classes-1)
Definition at line 456 of file Svm.h.
References classes, and Model::parameter.
Referenced by McSvmApproximationErrorFunction::errorDerivative(), and AllInOneMcSVM::modelDerivative().
unsigned int MultiClassSVM::getClasses () const [inline]
return the number of classes
Definition at line 469 of file Svm.h.
References classes.
Referenced by McSvmApproximationErrorFunction::errorDerivative(), AllInOneMcSVM::modelDerivative(), SVM_Optimizer::optimize(), and AllInOneMcSVM::PrepareDerivative().
unsigned int MultiClassSVM::getDimension () [inline]
return the input space dimension
Definition at line 481 of file Svm.h.
References Model::inputDimension.
Referenced by McSvmApproximationErrorFunction::errorDerivative().
unsigned int MultiClassSVM::getExamples () const [inline]
return the number of examples
Definition at line 475 of file Svm.h.
References x.
Referenced by McSvmApproximationErrorFunction::errorDerivative(), AllInOneMcSVM::modelDerivative(), and AllInOneMcSVM::PrepareDerivative().
KernelFunction* MultiClassSVM::getKernel () [inline]
return the kernel function object
Definition at line 436 of file Svm.h.
References kernel.
Referenced by McSvmApproximationErrorFunction::errorDerivative(), McSvmApproximation::McSvmApproximation(), MetaSVM::MetaSVM(), SVM_Optimizer::optimize(), and AllInOneMcSVM::PrepareDerivative().
unsigned MultiClassSVM::getNumberOfSupportVectors ()
returns the number of examples that have an alpha != 0 in one of the classes
Definition at line 832 of file Svm.cpp.
References i.
unsigned MultiClassSVM::getNumberOfSupportVectors (unsigned c)
returns the number of examples that have an alpha != 0 in a certain class
Definition at line 842 of file Svm.cpp.
References i.
double MultiClassSVM::getOffset (unsigned int c, double value) const [inline, protected]
sets the solution offset vector
Parameters:
c zero-based class index (0, ..., classes-1)
Definition at line 536 of file Svm.h.
References classes, examples, and Model::parameter.
double MultiClassSVM::getOffset (unsigned int c) const [inline]
return the solution offset vector
Parameters:
c zero-based class index (0, ..., classes-1)
Definition at line 463 of file Svm.h.
References classes, examples, and Model::parameter.
const Array<double>& MultiClassSVM::getPoints () [inline]
return the training data points
Definition at line 442 of file Svm.h.
References x.
Referenced by McSvmApproximation::calcOffsetForReducedModel(), McSvmApproximation::calcOptimalAlphaOfApproximatedSVM(), McSvmApproximationErrorFunction::errorDerivative(), AllInOneMcSVM::modelDerivative(), and AllInOneMcSVM::PrepareDerivative().
const Array<double>& MultiClassSVM::getTargets () [inline]
return the training data labels
Definition at line 448 of file Svm.h.
References y.
Referenced by AllInOneMcSVM::PrepareDerivative().
bool MultiClassSVM::isSupportVector (unsigned exampleIndex)
returns true if alpha != 0 in one of the machines
Definition at line 823 of file Svm.cpp.
void MultiClassSVM::MakeSparse ()
Discard zero coefficients and corresponding training data.
If the SVM object onws its training data array, it can make itself sparse after training.
Definition at line 872 of file Svm.cpp.
References i.
Referenced by SVM_Optimizer::optimize().
unsigned int MultiClassSVM::model (const Array< double > & input)
compute the SVM prediction on data
Definition at line 812 of file Svm.cpp.
void MultiClassSVM::model (const Array< double > & input, Array< double > & output) [virtual]
compute the SVM prediction on data
Implements Model.
Definition at line 769 of file Svm.cpp.
References i.
void MultiClassSVM::Predict (const Array< double > & input, ArrayReference< double > output) [protected]
Definition at line 936 of file Svm.cpp.
References i.
void MultiClassSVM::Predict (const Array< double > & input, Array< double > & output) [protected]
Definition at line 920 of file Svm.cpp.
References i.
void MultiClassSVM::setAlpha (unsigned int index, unsigned int c, double value) [inline, protected]
sets the coefficient of a given example and label
Parameters:
index index of the corresponding training example
c zero-based class index (0, ..., classes-1)
Definition at line 529 of file Svm.h.
References classes, and Model::parameter.
void MultiClassSVM::setNumberOutput (bool bNumberOutput = true) [inline]
Set the output mode to integer or vector mode.
In number mode (bNumberOutput = true), the machine predicts the class encoded as a single number in the set , where c is the number of classes. In vector mode, the machine outputs a (non-normalized) vector of confidence values, with one real value per class.
Definition at line 394 of file Svm.h.
References numberOutput.
void MultiClassSVM::SetTrainingData (const Array< double > & input, bool copy = false)
Make the training data known to the SVM.
The training data are needed in order to represent the SVM model because the parameter vector stores only coefficients relative to these data.
Parameters:
input training data points
copy maintain a copy of the input data
Definition at line 746 of file Svm.cpp.
void MultiClassSVM::SetTrainingData (const Array< double > & input, const Array< double > & target, bool copy = false)
Make the training data known to the SVM.
The training data are needed in order to represent the SVM model because the parameter vector stores only coefficients relative to these data.
Parameters:
input training data points
target training data labels
copy maintain a copy of the input data
Definition at line 719 of file Svm.cpp.
Referenced by McSvmApproximation::McSvmApproximation(), and SVM_Optimizer::optimize().
unsigned int MultiClassSVM::VectorToClass (const Array< double > & v)
convert a label vector into a class index
Definition at line 852 of file Svm.cpp.
Friends And Related Function Documentation
friend class McSvmApproximation [friend]
Definition at line 498 of file Svm.h.
Member Data Documentation
bool MultiClassSVM::bOwnMemory [protected]
true if x and y are allocated by LoadModel
Definition at line 508 of file Svm.h.
unsigned int MultiClassSVM::classes [protected]
number of classes
Definition at line 524 of file Svm.h.
Referenced by getAlpha(), getClasses(), getOffset(), and setAlpha().
unsigned int MultiClassSVM::examples [protected]
number of training data points and labels
Definition at line 521 of file Svm.h.
Referenced by getOffset().
KernelFunction* MultiClassSVM::kernel [protected]
kernel function
Definition at line 505 of file Svm.h.
Referenced by getKernel().
bool MultiClassSVM::numberOutput [protected]
true if the SVM outputs the class label only false if the SVM outputs the value of the linear feature space function.
Definition at line 518 of file Svm.h.
Referenced by setNumberOutput().
const Array<double>* MultiClassSVM::x [protected]
training data points
Definition at line 511 of file Svm.h.
Referenced by getExamples(), and getPoints().
const Array<double>* MultiClassSVM::y [protected]
training data labels
Definition at line 514 of file Svm.h.
Referenced by getTargets().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp