ReClaM: SteepestDescent Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SteepestDescent Class Reference
Standard steepest descent.
#include <SteepestDescent.h>
Public Member Functions
SteepestDescent ()
default constructor
void init (Model &model)
basic initialization with default parameters
void init (Model &model, double lr, double mu, bool online)
double getLearningRate () const
get learning rate
void setLearningRate (double lr)
set learning rate
double getMomentum () const
get momentum parameter
void setMomentum (double mu)
set momentum parameter
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Iterative updating of the weights either by presenting all patterns (batch) or by presenting the patterns one at a time (online).
void clearMemory ()
Clears array of momentum values.
Detailed Description
Standard steepest descent.
Author:
C. Igel
Date:
1999
Definition at line 57 of file SteepestDescent.h.
Constructor & Destructor Documentation
SteepestDescent::SteepestDescent () [inline]
default constructor
Definition at line 63 of file SteepestDescent.h.
Member Function Documentation
void SteepestDescent::clearMemory () [inline]
Clears array of momentum values.
Returns:
None.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 181 of file SteepestDescent.h.
double SteepestDescent::getLearningRate () const [inline]
get learning rate
Definition at line 93 of file SteepestDescent.h.
double SteepestDescent::getMomentum () const [inline]
get momentum parameter
Definition at line 107 of file SteepestDescent.h.
void SteepestDescent::init (Model & model, double lr, double mu, bool online) [inline]
Parameters:
model ReClaM Model to optimize
lr Learning rate .
mu Momentum parameter .
online Learn in online or batch mode
Definition at line 80 of file SteepestDescent.h.
References Model::getParameterDimension().
void SteepestDescent::init (Model & model) [inline, virtual]
basic initialization with default parameters
Implements Optimizer.
Definition at line 69 of file SteepestDescent.h.
double SteepestDescent::optimize (Model & model, ErrorFunction & error, const Array< double > & input, const Array< double > & target) [inline, virtual]
Iterative updating of the weights either by presenting all patterns (batch) or by presenting the patterns one at a time (online).
Implements Optimizer.
Definition at line 125 of file SteepestDescent.h.
References ErrorFunction::errorDerivative(), Model::getParameter(), Model::getParameterDimension(), and Model::setParameter().
void SteepestDescent::setLearningRate (double lr) [inline]
set learning rate
Definition at line 100 of file SteepestDescent.h.
void SteepestDescent::setMomentum (double mu) [inline]
set momentum parameter
Definition at line 114 of file SteepestDescent.h.
The documentation for this class was generated from the following file:
SteepestDescent.h