ReClaM: SVM_Optimizer Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SVM_Optimizer Class Reference
Optimizer for SVM training by quadratic programming.
#include <Svm.h>
Public Member Functions
SVM_Optimizer ()
Constructor.
~SVM_Optimizer ()
Destructor.
void init (Model &model)
Default initialization.
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Default Optimizer interface.
double optimize (SVM &model, const Array< double > &input, const Array< double > &target, bool copy=false)
Trains the SVM with the given dataset.
void optimize (MultiClassSVM &model, const Array< double > &input, const Array< double > &target, bool copy=false)
Trains the MultiClassSVM with the given dataset.
QPSolver * get_Solver ()
Return the QpSvmDecomp used by the previous call to optimize.
void setAccuracy (double accuracy=0.001)
Set the solution accuracy.
void setMaxIterations (SharkInt64 maxiter=-1)
Set the maximum number of iterations for the quadratic program solver.
void setMaxSeconds (int seconds=-1)
Set the maximum number of seconds for the quadratic program solver.
void setVerbose (bool verbose=true)
Set the verbosity.
void setCacheSize (unsigned int cacheSize)
Set the cache size in megabytes.
void usePrecomputedMatrix (bool precomputed=true)
Enable the use of a precomputed kernel matrix.
bool isOptimal () const
Return true if the accuracy stopping condition was met during training, and false if the solver ran out of iterations or time.
Static Public Attributes
static ErrorFunction & dummyError = * ((ErrorFunction*) NULL)
The static member dummyError is provided for calls to the optimize method in case there is no ErrorFunction object available.
Protected Attributes
eSvmMode mode
mode of operation
QPMatrix * matrix
kernel matrix
CachedMatrix * cache
kernel matrix with cache
QPSolver * solver
quadratic program solver used in the last optimize call
double Cplus
upper bound for the variables corresponding to positive class examples
double Cminus
upper bound for the variables corresponding to negative class examples
double C
upper bound C and lower bound -C for regression coefficients
double epsilon
parameter of the -insensitive regression loss function
double gamma
gamma parameter of the regularization network
double fractionOfOutliers
Fraction of outliers for One-Class SVM XXX.
double OneClassBoxUpper
upper bound for all One Class SVM Lagrange multipliers XXX
unsigned int epochLimit
maximum number of epochs for all epoch-based (on-line) algorithms
double dualLimit
desired duality gap for epoch-based (on-line) algorithms. this is weaker than the accuracy-limit.
unsigned int wssPref
working set selection preference. so far used in ebcs.
unsigned int reruPref
reprocess alternation rule preference. so far used in ebcs.
bool countKernels
preference for counting kernel evaluations. so far used in ebcs.
SvmStatesCollection * mep_historian
pointer to statesCollection class. use to take snapshots of your svm during training. so far used in ebcs.
bool precomputedMatrix
should the solver use a precomputed kernel matrix?
bool printInfo
should the quadratic program solver output its progress?
double cacheMB
kernel cache size in megabytes used by the quadratic program solver
double accuracy
accuracy up to which the KKT conditions have to be fulfilled
SharkInt64 maxIter
maximum number of QpSvmDecomp iterations
int maxSeconds
maximum time for the QpSvmDecomp
bool optimal
Variable That checks if the solver converged.
Detailed Description
Optimizer for SVM training by quadratic programming.
Author:
T. Glasmachers
Date:
2006
Although the SVM_Optimizer fits into the ReClaM concept of an Optimizer, it should not be used the usual way, for three reasons:
It does not depend on the error function object provided as a parameter to optimize.
It does not return a useful error value. The quadratic program optimum is returned, which is not suitable for model selection.
It is not an iterative optimizer. The first call to optimize already finds the optimal solution.
Nevertheless, the SVM_Optimizer is one of the most important classes in the SVM context, as it calls the #QuadraticProgram class to solve the SVM dual problem, computing the SVM coefficients and b.
Examples:
CrossValidation.cpp, McSvm.cpp, SvmApproximationExample.cpp, SVMclassification-gnuplot.cpp, SVMclassification.cpp, SVMregression-gnuplot.cpp, and SVMregression.cpp.
Definition at line 1303 of file Svm.h.
Constructor & Destructor Documentation
SVM_Optimizer::SVM_Optimizer ()
Constructor.
Definition at line 1748 of file Svm.cpp.
References accuracy, cache, cacheMB, matrix, maxIter, maxSeconds, optimal, precomputedMatrix, printInfo, and solver.
SVM_Optimizer::~SVM_Optimizer ()
Destructor.
Definition at line 1764 of file Svm.cpp.
References cache, matrix, and solver.
Member Function Documentation
QPSolver* SVM_Optimizer::get_Solver () [inline]
Return the QpSvmDecomp used by the previous call to optimize.
The #QuadraticProgram object may be of use for the calling procedure as it proviedes some solution statistics as the number of iterations used for training and the final objective function value.
Definition at line 1389 of file Svm.h.
References solver.
Referenced by SpanBoundA::error(), SpanBound2::error(), SpanBound1::error(), SpanBoundA::errorDerivative(), and SpanBound1::errorDerivative().
void SVM_Optimizer::init (Model & model) [virtual]
Default initialization.
This is the default Model initialization method. If the model parameter is not a valid MetaSVM model, the method will throw an exception.
Parameters:
model Meta model containing complexity constant and kernel
Implements Optimizer.
Examples:
CrossValidation.cpp, McSvm.cpp, SvmApproximationExample.cpp, SVMclassification-gnuplot.cpp, SVMclassification.cpp, SVMregression-gnuplot.cpp, and SVMregression.cpp.
Definition at line 1784 of file Svm.cpp.
References C, cache, Cminus, countKernels, Cplus, dualLimit, e1Class, eAllInOne, eC1, eC2, eCrammerSinger, eDGI, eEBCS, eEpsilon, eGaussianProcess, eLLW, eOCC, eOVA, epochLimit, epsilon, eRegularizationNetwork, fractionOfOutliers, gamma, EpochBasedCsMcSvm::get_C(), OCCMcSVM::get_C(), OVAMcSVM::get_C(), DGIMcSVM::get_C(), LLWMcSVM::get_C(), CrammerSingerMcSVM::get_C(), AllInOneMcSVM::get_C(), Epsilon_SVM::get_C(), C_SVM::get_Cminus(), EpochBasedCsMcSvm::get_countPreference(), C_SVM::get_Cplus(), EpochBasedCsMcSvm::get_dualAim(), EpochBasedCsMcSvm::get_epochLim(), Epsilon_SVM::get_epsilon(), RegularizationNetwork::get_gamma(), EpochBasedCsMcSvm::get_historian(), EpochBasedCsMcSvm::get_reruMode(), EpochBasedCsMcSvm::get_wssMode(), OneClassSVM::getNu(), C_SVM::is2norm(), matrix, mep_historian, mode, reruPref, solver, and wssPref.
Referenced by SpanBound1::bound(), SpanBound1::boundDerivative(), SpanBoundA::error(), SpanBound2::error(), SpanBound1::error(), NoisySvmLikelihood::error(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), and NoisySvmLikelihood::errorDerivative().
bool SVM_Optimizer::isOptimal () const [inline]
Return true if the accuracy stopping condition was met during training, and false if the solver ran out of iterations or time.
Definition at line 1435 of file Svm.h.
References optimal.
void SVM_Optimizer::optimize (MultiClassSVM & model, const Array< double > & input, const Array< double > & target, bool copy = false)
Trains the MultiClassSVM with the given dataset.
This version of the optimize member is well suited for MultiClassSVM training, but it does not fit into the ReClaM concept. Thus, a less specialized version of optimize is available, which overrides the corresponding Optimizer member.
Parameters:
model The MultiClassSVM model to optimize
input Training input used for the optimization
target Training labels used for the optimization
copy Maintain a copy of the input data in the MultiClassSVM object
Returns:
As there is no error evaluation, the function returns zero.
Definition at line 2333 of file Svm.cpp.
References accuracy, C, cache, cacheMB, countKernels, dualLimit, eAllInOne, eCrammerSinger, eDGI, eEBCS, eLLW, eOCC, eOVA, epochLimit, MultiClassSVM::getClasses(), MultiClassSVM::getKernel(), Model::getParameter(), i, QpBoxDecomp::isOptimal(), QpMcStzDecomp::isOptimal(), QpMcDecomp::isOptimal(), MultiClassSVM::MakeSparse(), matrix, maxIter, mep_historian, mode, optimal, precomputedMatrix, printInfo, reruPref, QpBoxDecomp::Set_WSS_Strategy(), QpMcDecomp::Set_WSS_Strategy(), QpBoxDecomp::setMaxIterations(), QpMcStzDecomp::setMaxIterations(), QpMcDecomp::setMaxIterations(), Model::setParameter(), QpEbCsDecomp::setStoppingConditions(), MultiClassSVM::SetTrainingData(), QpEbCsDecomp::setVerbose(), QpEbCsDecomp::Solve(), QpBoxDecomp::Solve(), QpMcStzDecomp::Solve(), QpMcDecomp::Solve(), solver, and wssPref.
double SVM_Optimizer::optimize (Model & model, ErrorFunction & error, const Array< double > & input, const Array< double > & target) [virtual]
Default Optimizer interface.
The optimize member uses the QuadraticProgram class to train the Support Vector Machine. If the model parameter supplied is not a valid SVM object, the method checks for a C_SVM object to determine the unserlying SVM. Otherwise it throws an exception.
Note that no ErrorFunction object is needed for SVM training. If no ErrorFunction object is available, the static dummy reference dummyError can be used.
Parameters:
model The SVM model to optimize
error The error object is not used at all. The dummyError can be used.
input Training input used for the optimization
target Training labels used for the optimization
Returns:
As there is no error evaluation, the function returns the dual target function value.
Implements Optimizer.
Examples:
CrossValidation.cpp, McSvm.cpp, SvmApproximationExample.cpp, SVMclassification-gnuplot.cpp, SVMclassification.cpp, SVMregression-gnuplot.cpp, and SVMregression.cpp.
Definition at line 1886 of file Svm.cpp.
References e1Class, eAllInOne, eC1, eC2, eCrammerSinger, eDGI, eEBCS, eEpsilon, eGaussianProcess, eLLW, eNu, eOCC, eOVA, eRegularizationNetwork, MetaSVM::getMultiClassSVM(), MetaSVM::getSVM(), mode, and GaussianProcess::train().
Referenced by SpanBoundA::error(), SpanBound2::error(), SpanBound1::error(), NoisySvmLikelihood::error(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), and NoisySvmLikelihood::errorDerivative().
double SVM_Optimizer::optimize (SVM & model, const Array< double > & input, const Array< double > & target, bool copy = false)
Trains the SVM with the given dataset.
This version of the optimize member is well suited for SVM training, but it does not fit into the ReClaM concept. Thus, a less specialized version of optimize is available, which overrides the corresponding Optimizer member.
Parameters:
model The SVM model to optimize
input Training input used for the optimization
target Training labels used for the optimization
copy Maintain a copy of the input data in the SVM object
Returns:
As there is no error evaluation, the function returns the dual target function value.
Definition at line 1943 of file Svm.cpp.
References accuracy, C, cache, cacheMB, Cminus, Cplus, e1Class, eC1, eC2, eEpsilon, epsilon, eRegularizationNetwork, KernelFunction::eval(), fractionOfOutliers, gamma, QpSvmDecomp::getGradient(), SVM::getKernel(), Model::getParameter(), SVM::MakeSparse(), matrix, maxIter, maxSeconds, mode, precomputedMatrix, printInfo, QpSvmDecomp::setMaxIterations(), QpSvmDecomp::setMaxSeconds(), Model::setParameter(), SVM::SetTrainingData(), QpSvmDecomp::setVerbose(), QpSvmDecomp::Solve(), and solver.
void SVM_Optimizer::setAccuracy (double accuracy = 0.001) [inline]
Set the solution accuracy.
Definition at line 1395 of file Svm.h.
References accuracy.
void SVM_Optimizer::setCacheSize (unsigned int cacheSize) [inline]
Set the cache size in megabytes.
Definition at line 1421 of file Svm.h.
References cacheMB.
void SVM_Optimizer::setMaxIterations (SharkInt64 maxiter = -1) [inline]
Set the maximum number of iterations for the quadratic program solver.
Definition at line 1402 of file Svm.h.
References maxIter.
Referenced by SpanBoundA::error(), SpanBound2::error(), SpanBound1::error(), SpanBoundA::errorDerivative(), and SpanBound1::errorDerivative().
void SVM_Optimizer::setMaxSeconds (int seconds = -1) [inline]
Set the maximum number of seconds for the quadratic program solver.
Definition at line 1409 of file Svm.h.
References maxSeconds.
void SVM_Optimizer::setVerbose (bool verbose = true) [inline]
Set the verbosity.
Definition at line 1415 of file Svm.h.
References printInfo.
void SVM_Optimizer::usePrecomputedMatrix (bool precomputed = true) [inline]
Enable the use of a precomputed kernel matrix.
Definition at line 1427 of file Svm.h.
References precomputedMatrix.
Member Data Documentation
double SVM_Optimizer::accuracy [protected]
accuracy up to which the KKT conditions have to be fulfilled
Definition at line 1504 of file Svm.h.
Referenced by optimize(), setAccuracy(), and SVM_Optimizer().
double SVM_Optimizer::C [protected]
upper bound C and lower bound -C for regression coefficients
Definition at line 1461 of file Svm.h.
Referenced by init(), and optimize().
CachedMatrix* SVM_Optimizer::cache [protected]
kernel matrix with cache
Definition at line 1449 of file Svm.h.
Referenced by init(), optimize(), SVM_Optimizer(), and ~SVM_Optimizer().
double SVM_Optimizer::cacheMB [protected]
kernel cache size in megabytes used by the quadratic program solver
Definition at line 1501 of file Svm.h.
Referenced by optimize(), setCacheSize(), and SVM_Optimizer().
double SVM_Optimizer::Cminus [protected]
upper bound for the variables corresponding to negative class examples
Definition at line 1458 of file Svm.h.
Referenced by init(), and optimize().
bool SVM_Optimizer::countKernels [protected]
preference for counting kernel evaluations. so far used in ebcs.
Definition at line 1488 of file Svm.h.
Referenced by init(), and optimize().
double SVM_Optimizer::Cplus [protected]
upper bound for the variables corresponding to positive class examples
Definition at line 1455 of file Svm.h.
Referenced by init(), and optimize().
double SVM_Optimizer::dualLimit [protected]
desired duality gap for epoch-based (on-line) algorithms. this is weaker than the accuracy-limit.
Definition at line 1479 of file Svm.h.
Referenced by init(), and optimize().
ErrorFunction & SVM_Optimizer::dummyError = * ((ErrorFunction*) NULL) [static]
The static member dummyError is provided for calls to the optimize method in case there is no ErrorFunction object available.
Do not use or call any members of dummyError, as it is an invalid reference. It is only provided for making syntactically correct calls to the optimize method.
Definition at line 1382 of file Svm.h.
unsigned int SVM_Optimizer::epochLimit [protected]
maximum number of epochs for all epoch-based (on-line) algorithms
Definition at line 1476 of file Svm.h.
Referenced by init(), and optimize().
double SVM_Optimizer::epsilon [protected]
parameter of the -insensitive regression loss function
Definition at line 1464 of file Svm.h.
Referenced by init(), and optimize().
double SVM_Optimizer::fractionOfOutliers [protected]
Fraction of outliers for One-Class SVM XXX.
Definition at line 1470 of file Svm.h.
Referenced by init(), and optimize().
double SVM_Optimizer::gamma [protected]
gamma parameter of the regularization network
Definition at line 1467 of file Svm.h.
Referenced by init(), and optimize().
QPMatrix* SVM_Optimizer::matrix [protected]
kernel matrix
Definition at line 1446 of file Svm.h.
Referenced by init(), optimize(), SVM_Optimizer(), and ~SVM_Optimizer().
SharkInt64 SVM_Optimizer::maxIter [protected]
maximum number of QpSvmDecomp iterations
Definition at line 1507 of file Svm.h.
Referenced by optimize(), setMaxIterations(), and SVM_Optimizer().
int SVM_Optimizer::maxSeconds [protected]
maximum time for the QpSvmDecomp
Definition at line 1510 of file Svm.h.
Referenced by optimize(), setMaxSeconds(), and SVM_Optimizer().
SvmStatesCollection* SVM_Optimizer::mep_historian [protected]
pointer to statesCollection class. use to take snapshots of your svm during training. so far used in ebcs.
Definition at line 1491 of file Svm.h.
Referenced by init(), and optimize().
eSvmMode SVM_Optimizer::mode [protected]
mode of operation
Definition at line 1443 of file Svm.h.
Referenced by init(), and optimize().
double SVM_Optimizer::OneClassBoxUpper [protected]
upper bound for all One Class SVM Lagrange multipliers XXX
Definition at line 1473 of file Svm.h.
bool SVM_Optimizer::optimal [protected]
Variable That checks if the solver converged.
Definition at line 1513 of file Svm.h.
Referenced by isOptimal(), optimize(), and SVM_Optimizer().
bool SVM_Optimizer::precomputedMatrix [protected]
should the solver use a precomputed kernel matrix?
Definition at line 1494 of file Svm.h.
Referenced by optimize(), SVM_Optimizer(), and usePrecomputedMatrix().
bool SVM_Optimizer::printInfo [protected]
should the quadratic program solver output its progress?
Definition at line 1497 of file Svm.h.
Referenced by optimize(), setVerbose(), and SVM_Optimizer().
unsigned int SVM_Optimizer::reruPref [protected]
reprocess alternation rule preference. so far used in ebcs.
Definition at line 1485 of file Svm.h.
Referenced by init(), and optimize().
QPSolver* SVM_Optimizer::solver [protected]
quadratic program solver used in the last optimize call
Definition at line 1452 of file Svm.h.
Referenced by get_Solver(), init(), optimize(), SVM_Optimizer(), and ~SVM_Optimizer().
unsigned int SVM_Optimizer::wssPref [protected]
working set selection preference. so far used in ebcs.
Definition at line 1482 of file Svm.h.
Referenced by init(), and optimize().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp