ReClaM: C_SVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
C_SVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
C_SVM (SVM *pSVM, double Cplus, double Cminus, bool norm2=false, bool unconst=false)
Constructor.
~C_SVM ()
Descructor.
const Array< double > & PrepareDerivative ()
Prepare the computation of modelDerivative.
void modelDerivative (const Array< double > &input, Array< double > &derivative)
Computes the derivative of the model w.r.t.
void setParameter (unsigned int index, double value)
overloaded version of Model::setParameter
double get_Cplus ()
return the parameter C for positive class examples
double get_Cminus ()
return the parameter C for negative class examples
bool is2norm ()
return true if the 2-norm slack penalty is in use
bool isUnconstrained ()
return true if the exponential function is used to parameterize C
double getCRatio ()
return the quotient
bool isFeasible ()
ensure C is positive
Protected Attributes
bool norm2penalty
true if the 2-norm slack penalty is to be used
double C_plus
Complexity constant used for positive training examples.
double C_minus
Complexity constant used for negative training examples.
double C_ratio
fraction
bool exponential
if true the C-parameters are computed via .
Array< double > alpha_b_Derivative
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2006
The C-SVM is a training scheme for Support Vector Machines. It defines a positive constant C controlling the solution complexity.
In the 1-norm SVM formulation, this constant bounds the parameters of the SVM from above, limiting their contribution to the solution. For the 2-norm SVM formulation, the are not bounded from above. Instead, the kernel matrix is reglarized by adding to the diagonal entries.
The C_SVM class is a meta model which is based on an SVM model. Its parameter vector is composed of the SVM hyper- parameters, i.e., the complexity parameter C and the parameters of a KernelFunction object. As a meta model it does not make sense to call the model or modelDerivative members of this class. However, the modelDerivative function has been implemented to compute the derivative of the underlying SVM model w.r.t. the hyperparameters stored in the C_SVM model. See PrepareDerivative and modelDerivative for further reference.
For unbalanced data, it has proven fertile to consider class specific complexity parameters and instead of a single constant C. These parameters are usually coupled by the equation , where ${}$ are the class magnitudes. Therefore, the C_SVM model introduces only the parameter as a model parameter, whereas can be computed from this parameter. As only the parameter is subject to optimization, all derivatives have to be computed w.r.t , even if is used for the computation.
The parameter can be stored in a way allowing for unconstrained optimization, that is, the exponential function is used to compute the value from the model parameter. As a side effect, this parameterization is more natural and therefore probably better suited for optimization.
Examples:
CrossValidation.cpp, KernelOptimization.cpp, SvmApproximationExample.cpp, SVMclassification-gnuplot.cpp, and SVMclassification.cpp.
Definition at line 660 of file Svm.h.
Constructor & Destructor Documentation
C_SVM::C_SVM (SVM * pSVM, double Cplus, double Cminus, bool norm2 = false, bool unconst = false)
Constructor.
Parameters:
pSVM Pointer to the SVM to be optimized.
Cplus initial value of
Cminus initial value of
norm2 true if 2-norm slack penalty is to be used
unconst true if the parameters are to be represented as . This allows for unconstrained optimization.
Definition at line 1008 of file Svm.cpp.
References C_ratio, exponential, norm2penalty, and setParameter().
C_SVM::~C_SVM ()
Descructor.
Definition at line 1018 of file Svm.cpp.
Member Function Documentation
double C_SVM::get_Cminus () [inline]
return the parameter C for negative class examples
Definition at line 699 of file Svm.h.
References C_minus.
Referenced by SpanBound1::bound(), SpanBound1::boundDerivative(), SpanBoundA::error(), SpanBound1::error(), RadiusMargin::error(), NegativePolarization::error(), LOO::error(), NegativeBKTA::error(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), RadiusMargin::errorDerivative(), NegativePolarization::errorDerivative(), NegativeBKTA::errorDerivative(), and SVM_Optimizer::init().
double C_SVM::get_Cplus () [inline]
return the parameter C for positive class examples
Definition at line 693 of file Svm.h.
References C_plus.
Referenced by SpanBound1::bound(), SpanBound1::boundDerivative(), SpanBoundA::error(), SpanBound1::error(), RadiusMargin::error(), NegativePolarization::error(), LOO::error(), NegativeBKTA::error(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), RadiusMargin::errorDerivative(), NegativePolarization::errorDerivative(), NegativeBKTA::errorDerivative(), and SVM_Optimizer::init().
double C_SVM::getCRatio () [inline]
return the quotient
Definition at line 717 of file Svm.h.
References C_ratio.
Referenced by RadiusMargin::errorDerivative(), and NegativeBKTA::errorDerivative().
bool C_SVM::is2norm () [inline]
return true if the 2-norm slack penalty is in use
Definition at line 705 of file Svm.h.
References norm2penalty.
Referenced by SpanBound1::boundDerivative(), SpanBoundA::error(), SpanBound2::error(), SpanBound1::error(), RadiusMargin::error(), NegativePolarization::error(), LOO::error(), NegativeBKTA::error(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), RadiusMargin::errorDerivative(), NegativePolarization::errorDerivative(), NegativeBKTA::errorDerivative(), and SVM_Optimizer::init().
bool C_SVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1180 of file Svm.cpp.
References C_plus, and MetaSVM::isFeasible().
bool C_SVM::isUnconstrained () [inline]
return true if the exponential function is used to parameterize C
Definition at line 711 of file Svm.h.
References exponential.
Referenced by SpanBound1::boundDerivative().
void C_SVM::modelDerivative (const Array< double > & input, Array< double > & derivative) [virtual]
Computes the derivative of the model w.r.t.
regularization and kernel parameters. Be sure to call PrepareDerivative after SVM training and before calling this function!
Reimplemented from Model.
Definition at line 1140 of file Svm.cpp.
References alpha_b_Derivative, KernelFunction::evalDerivative(), SVM::getAlpha(), SVM::getExamples(), Model::getParameterDimension(), SVM::getPoints(), MetaSVM::getSVM(), MetaSVM::kernel, and MetaSVM::svm.
Referenced by SpanBound1::errorDerivative().
const Array< double > & C_SVM::PrepareDerivative ()
Prepare the computation of modelDerivative.
This method computes and stores the derivatives of the SVM parameters w.r.t. the regularization and kernel parameters for later reference by the modelDerivative function.
Definition at line 1023 of file Svm.cpp.
References alpha_b_Derivative, C_minus, C_plus, C_ratio, KernelFunction::evalDerivative(), exponential, SVM::getAlpha(), SVM::getExamples(), SVM::getOffset(), Model::getParameterDimension(), SVM::getPoints(), MetaSVM::getSVM(), MetaSVM::kernel, norm2penalty, and MetaSVM::svm.
Referenced by SpanBoundA::errorDerivative(), and SpanBound1::errorDerivative().
void C_SVM::setParameter (unsigned int index, double value) [virtual]
overloaded version of Model::setParameter
Reimplemented from MetaSVM.
Definition at line 1165 of file Svm.cpp.
References C_minus, C_plus, C_ratio, and exponential.
Referenced by C_SVM().
Member Data Documentation
Array<double> C_SVM::alpha_b_Derivative [protected]
Definition at line 741 of file Svm.h.
Referenced by modelDerivative(), and PrepareDerivative().
double C_SVM::C_minus [protected]
Complexity constant used for negative training examples.
Definition at line 733 of file Svm.h.
Referenced by get_Cminus(), PrepareDerivative(), and setParameter().
double C_SVM::C_plus [protected]
Complexity constant used for positive training examples.
Definition at line 730 of file Svm.h.
Referenced by get_Cplus(), isFeasible(), PrepareDerivative(), and setParameter().
double C_SVM::C_ratio [protected]
fraction
Definition at line 736 of file Svm.h.
Referenced by C_SVM(), getCRatio(), PrepareDerivative(), and setParameter().
bool C_SVM::exponential [protected]
if true the C-parameters are computed via .
Definition at line 739 of file Svm.h.
Referenced by C_SVM(), isUnconstrained(), PrepareDerivative(), and setParameter().
bool C_SVM::norm2penalty [protected]
true if the 2-norm slack penalty is to be used
Definition at line 727 of file Svm.h.
Referenced by C_SVM(), is2norm(), and PrepareDerivative().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp