ReClaM: LLWMcSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LLWMcSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
LLWMcSVM (MultiClassSVM *pSVM, double C, bool unconstrained=false)
Constructor.
~LLWMcSVM ()
Destructor.
double get_C ()
get the regularization constant
void set_C (double C)
set the regularization constant
bool isUnconstrained ()
return true if the exponential function is used to parameterize C
bool isFeasible ()
ensure C is positive
Protected Attributes
bool exponential
is C stored as log(C)?
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2010
Meta model for the multi class SVM proposed by Lee, Lin and Wahba
Examples:
McSvm.cpp.
Definition at line 1012 of file Svm.h.
Constructor & Destructor Documentation
LLWMcSVM::LLWMcSVM (MultiClassSVM * pSVM, double C, bool unconstrained = false)
Constructor.
Definition at line 1637 of file Svm.cpp.
References exponential, and set_C().
LLWMcSVM::~LLWMcSVM ()
Destructor.
Definition at line 1644 of file Svm.cpp.
Member Function Documentation
double LLWMcSVM::get_C () [inline]
get the regularization constant
Definition at line 1023 of file Svm.h.
References exponential, and Model::parameter.
Referenced by SVM_Optimizer::init().
bool LLWMcSVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1649 of file Svm.cpp.
References exponential, and Model::parameter.
bool LLWMcSVM::isUnconstrained () [inline]
return true if the exponential function is used to parameterize C
Definition at line 1037 of file Svm.h.
References exponential.
void LLWMcSVM::set_C (double C) [inline]
set the regularization constant
Definition at line 1030 of file Svm.h.
References exponential, and MetaSVM::setParameter().
Referenced by LLWMcSVM().
Member Data Documentation
bool LLWMcSVM::exponential [protected]
is C stored as log(C)?
Definition at line 1047 of file Svm.h.
Referenced by get_C(), isFeasible(), isUnconstrained(), LLWMcSVM(), and set_C().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp