ReClaM: NestedGridSearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
NestedGridSearch Class Reference
Nested grid search.
#include <GridSearch.h>
Public Member Functions
NestedGridSearch (int verbosity=0)
Constructor.
~NestedGridSearch ()
Destructor.
void init (Model &model)
There is no useful default initialization for this optimizer.
void init (Model &model, const Array< double > &min, const Array< double > &max)
Initialization of the nested grid search.
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target)
Every call of the optimization member computes the error landscape on the current grid.
Protected Attributes
Array< double > minimum
minimum parameter value to check
Array< double > maximum
maximum parameter value to check
Array< double > step
current step size for every parameter
Array< double > landscape
error landscape
int verbosity
verbosity level
Detailed Description
Nested grid search.
The NestedGridSearch class is an iterative optimizer, doing one grid search in every iteration. In every iteration, it halves the grid extent doubling the resolution in every coordinate.
Although nested grid search is much less exhaustive than standard grid search, it still suffers from exponential time and memory complexity in the number of variables optimized. Therefore, if the number of variables is larger than 2 or 3, consider using the CMA instead.
Nested grid search works as follows: The optimizer defined a 5x5x...x5 equi-distant grid (depending on the search space dimension) on an initially defined search cube. During every grid search iteration, the error is computed for all grid points not seen during previous iterations. Then the grid is moved to the best grid point found so far and contracted by a factor of two in each dimension. Each call to the optimize() function performs one such step.
Let N denote the number of parameters to optimize. To compute the error landscape at the current zoom level, the algorithm has to do error function evaluation in the first iteration, and roughtly evaluations in subsequent iterations.
The grid is always centered around the best solution currently known. If this solution is located at the boundary, the landscape may exceed the parameter range defined minimum and maximum. These invalid landscape values are not used and are always set to 1e100, indicating non-optimality.
Definition at line 202 of file GridSearch.h.
Constructor & Destructor Documentation
NestedGridSearch::NestedGridSearch (int verbosity = 0)
Constructor.
Parameters:
verbosity 0=none, 1=dots, 2=values
Definition at line 244 of file GridSearch.cpp.
References verbosity.
NestedGridSearch::~NestedGridSearch ()
Destructor.
Definition at line 249 of file GridSearch.cpp.
Member Function Documentation
void NestedGridSearch::init (Model & model) [virtual]
There is no useful default initialization for this optimizer.
Thus, this member throws an exception.
Implements Optimizer.
Definition at line 254 of file GridSearch.cpp.
void NestedGridSearch::init (Model & model, const Array< double > & min, const Array< double > & max)
Initialization of the nested grid search.
The min and max arrays define ranges for every parameter to optimize. These ranges are strict, that is, the algorithm will not try values beyond the range, even if is finds a boundary minimum.
Parameters:
model Model to optimize
min lower end of the parameter range
max upper end of the parameter range
Definition at line 259 of file GridSearch.cpp.
References Model::getParameterDimension(), landscape, maximum, minimum, Model::setParameter(), and step.
double NestedGridSearch::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Every call of the optimization member computes the error landscape on the current grid.
It picks the best error value and zooms into the error landscape by a factor of 2 reusing already computed grid points.
Implements Optimizer.
Definition at line 284 of file GridSearch.cpp.
References ErrorFunction::error(), Model::getParameter(), Model::getParameterDimension(), i, Model::isFeasible(), landscape, maximum, minimum, Model::setParameter(), step, and verbosity.
Member Data Documentation
Array<double> NestedGridSearch::landscape [protected]
error landscape
The landscape array has as many dimensions as there are parameters to optimize. In every array dimension there are 5 entries.
Definition at line 254 of file GridSearch.h.
Referenced by init(), and optimize().
Array<double> NestedGridSearch::maximum [protected]
maximum parameter value to check
Definition at line 243 of file GridSearch.h.
Referenced by init(), and optimize().
Array<double> NestedGridSearch::minimum [protected]
minimum parameter value to check
Definition at line 240 of file GridSearch.h.
Referenced by init(), and optimize().
Array<double> NestedGridSearch::step [protected]
current step size for every parameter
Definition at line 246 of file GridSearch.h.
Referenced by init(), and optimize().
int NestedGridSearch::verbosity [protected]
verbosity level
Definition at line 257 of file GridSearch.h.
Referenced by NestedGridSearch(), and optimize().
The documentation for this class was generated from the following files:
GridSearch.h
GridSearch.cpp