ReClaM: Epsilon_SVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Epsilon_SVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
Epsilon_SVM (SVM *pSVM, double C, double epsilon, bool unconst=false)
Constructor.
~Epsilon_SVM ()
Descructor.
void setParameter (unsigned int index, double value)
overloaded version of Model::setParameter
double get_C ()
return the complexity control parameter C
double get_epsilon ()
return the regression loss parameter
bool isFeasible ()
ensure C and epsilon are positive
Protected Attributes
double C
complexity control parameter C
double epsilon
regression loss parameter
bool exponential
if set the parameters are computed via exp.
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2007
The -SVM is a training scheme for Support Vector Machines for regression. It defines a positive constant controlling loss accuracy and another positive constant C controlling the solution complexity.
The Epsilon_SVM class is a meta model which is based on an SVM model. Its parameter vector is composed of the SVM hyper- parameters, that is the hyperparameters C and , and the parameters of a KernelFunction object. As a meta model it does not make sense to call the model or modelDerivative members of this class.
The parameters C and can be stored in a way allowing for unconstrained optimization, that is, the exponential function is used to compute the value from the model parameter. As a side effect, this parameterization is more natural and therefore probably better suited for optimization.
Examples:
SVMregression-gnuplot.cpp, and SVMregression.cpp.
Definition at line 773 of file Svm.h.
Constructor & Destructor Documentation
Epsilon_SVM::Epsilon_SVM (SVM * pSVM, double C, double epsilon, bool unconst = false)
Constructor.
Parameters:
pSVM Pointer to the SVM to be optimized.
Cplus initial value of
Cminus initial value of
epsilon initial value of
unconst true if the parameters are to be represented as and . This allows for unconstrained optimization.
Definition at line 1222 of file Svm.cpp.
References C, epsilon, exponential, and setParameter().
Epsilon_SVM::~Epsilon_SVM ()
Descructor.
Definition at line 1234 of file Svm.cpp.
Member Function Documentation
double Epsilon_SVM::get_C () [inline]
return the complexity control parameter C
Definition at line 793 of file Svm.h.
References C.
Referenced by SVM_Optimizer::init().
double Epsilon_SVM::get_epsilon () [inline]
return the regression loss parameter
Definition at line 799 of file Svm.h.
References epsilon.
Referenced by SVM_Optimizer::init().
bool Epsilon_SVM::isFeasible () [virtual]
ensure C and epsilon are positive
Reimplemented from MetaSVM.
Definition at line 1259 of file Svm.cpp.
References C, epsilon, and MetaSVM::isFeasible().
void Epsilon_SVM::setParameter (unsigned int index, double value) [virtual]
overloaded version of Model::setParameter
Reimplemented from MetaSVM.
Definition at line 1239 of file Svm.cpp.
References C, epsilon, exponential, and MetaSVM::hyperparameters.
Referenced by Epsilon_SVM().
Member Data Documentation
double Epsilon_SVM::C [protected]
complexity control parameter C
Definition at line 809 of file Svm.h.
Referenced by Epsilon_SVM(), get_C(), isFeasible(), and setParameter().
double Epsilon_SVM::epsilon [protected]
regression loss parameter
Reimplemented from Model.
Definition at line 812 of file Svm.h.
Referenced by Epsilon_SVM(), get_epsilon(), isFeasible(), and setParameter().
bool Epsilon_SVM::exponential [protected]
if set the parameters are computed via exp.
Definition at line 815 of file Svm.h.
Referenced by Epsilon_SVM(), and setParameter().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp