ReClaM: SvmApproximationErrorFunctionGlobal Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SvmApproximationErrorFunctionGlobal Class Reference
Approximation of Support Vector Machines (SVMs)
#include <SvmApproximation.h>
Public Member Functions
SvmApproximationErrorFunctionGlobal (SvmApproximation *svmApprox)
double error (Model &model, const Array< double > &input, const Array< double > &target)
Error of the model.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Calculates the field derivative, the derivative of the error with respect to the model parameters.
Public Attributes
SvmApproximation * mpApproxSVM
Detailed Description
Approximation of Support Vector Machines (SVMs)
Definition at line 229 of file SvmApproximation.h.
Constructor & Destructor Documentation
SvmApproximationErrorFunctionGlobal::SvmApproximationErrorFunctionGlobal (SvmApproximation * svmApprox)
Definition at line 256 of file SvmApproximation.cpp.
Member Function Documentation
double SvmApproximationErrorFunctionGlobal::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Error of the model.
This method calculates the error of the model. #target is compared with the model's output for stimulus #input.
Parameters:
model Model to use for the computation.
input Vector of input values.
target Vector of output values.
Returns:
The error of the model.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Implements ErrorFunction.
Definition at line 261 of file SvmApproximation.cpp.
double SvmApproximationErrorFunctionGlobal::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Calculates the field derivative, the derivative of the error with respect to the model parameters.
Calculates the derivates of the error with respect to the model parameters and stores the result in the elements of the array #derivative. As a default implementation, the derivatives are estimated numerically by using small variations epsilon:
However, to improve the speed, it is adviserable to overload this method by a more sophisticated calculation, depending on the method error. Nevertheless, this default implementation can be used to check new implementations of the derivative of the error with respect to the model parameters.
Usually, as a byproduct of the calculation of the derivative one gets the the error itself very efficiently. Therefore, the method errorDerivative gives back this value.
Parameters:
model Model to use for the computation.
input Vector of input values.
target Vector of output values.
derivative Vector of partial derivatives.
Returns:
The error E
Author:
C. Igel
Date:
1999
Changes
3/2006 Tobias Glasmachers: step size epsilon has bacome a fraction of the current parameter value
Status
stable
Reimplemented from ErrorFunction.
Definition at line 310 of file SvmApproximation.cpp.
References KernelFunction::eval(), SVM::getAlpha(), SVM::getDimension(), SVM::getExamples(), SVM::getKernel(), Model::getParameter(), SVM::getPoints(), and i.
Member Data Documentation
SvmApproximation* SvmApproximationErrorFunctionGlobal::mpApproxSVM
Definition at line 237 of file SvmApproximation.h.
The documentation for this class was generated from the following files:
SvmApproximation.h
SvmApproximation.cpp