ReClaM: AllInOneMcSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
AllInOneMcSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
AllInOneMcSVM (MultiClassSVM *pSVM, double C, bool unconstrained=false)
Constructor.
~AllInOneMcSVM ()
Destructor.
double get_C ()
get the regularization constant
void set_C (double C)
set the regularization constant
bool isUnconstrained ()
return true if the exponential function is used to parameterize C
bool isFeasible ()
ensure C is positive
const Array< double > & PrepareDerivative ()
Prepare the computation of modelDerivative.
void modelDerivative (const Array< double > &input, Array< double > &derivative)
Computes the derivative of the model w.r.t.
Protected Attributes
bool exponential
is C stored as log(C)?
Array< double > alphaDerivative
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2008
Canonical multi class SVM meta model, covering the machines proposed independently by Weston and Watkins and by Vapnik.
Examples:
McSvm.cpp.
Definition at line 899 of file Svm.h.
Constructor & Destructor Documentation
AllInOneMcSVM::AllInOneMcSVM (MultiClassSVM * pSVM, double C, bool unconstrained = false)
Constructor.
Definition at line 1288 of file Svm.cpp.
References exponential, and set_C().
AllInOneMcSVM::~AllInOneMcSVM ()
Destructor.
Definition at line 1295 of file Svm.cpp.
Member Function Documentation
double AllInOneMcSVM::get_C () [inline]
get the regularization constant
Definition at line 910 of file Svm.h.
References exponential, and Model::parameter.
Referenced by SVM_Optimizer::init(), and PrepareDerivative().
bool AllInOneMcSVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1300 of file Svm.cpp.
References exponential, MetaSVM::isFeasible(), and Model::parameter.
bool AllInOneMcSVM::isUnconstrained () [inline]
return true if the exponential function is used to parameterize C
Definition at line 924 of file Svm.h.
References exponential.
void AllInOneMcSVM::modelDerivative (const Array< double > & input, Array< double > & derivative) [virtual]
Computes the derivative of the model w.r.t.
regularization and kernel parameters. Be sure to call PrepareDerivative after SVM training and before calling this function!
Reimplemented from Model.
Definition at line 1575 of file Svm.cpp.
References alphaDerivative, KernelFunction::evalDerivative(), MultiClassSVM::getAlpha(), MultiClassSVM::getClasses(), MultiClassSVM::getExamples(), MetaSVM::getMultiClassSVM(), Model::getParameterDimension(), MultiClassSVM::getPoints(), MetaSVM::kernel, and MetaSVM::svm.
const Array< double > & AllInOneMcSVM::PrepareDerivative ()
Prepare the computation of modelDerivative.
This method computes and stores the derivatives of the SVM parameters w.r.t. the regularization and kernel parameters for later reference by the modelDerivative function.
Definition at line 1307 of file Svm.cpp.
References alphaDerivative, KernelFunction::evalDerivative(), get_C(), MultiClassSVM::getClasses(), MultiClassSVM::getExamples(), MultiClassSVM::getKernel(), MetaSVM::getMultiClassSVM(), Model::getParameter(), Model::getParameterDimension(), MultiClassSVM::getPoints(), MultiClassSVM::getTargets(), MetaSVM::kernel, and MetaSVM::svm.
void AllInOneMcSVM::set_C (double C) [inline]
set the regularization constant
Definition at line 917 of file Svm.h.
References exponential, and MetaSVM::setParameter().
Referenced by AllInOneMcSVM().
Member Data Documentation
Array<double> AllInOneMcSVM::alphaDerivative [protected]
Definition at line 949 of file Svm.h.
Referenced by modelDerivative(), and PrepareDerivative().
bool AllInOneMcSVM::exponential [protected]
is C stored as log(C)?
Definition at line 947 of file Svm.h.
Referenced by AllInOneMcSVM(), get_C(), isFeasible(), isUnconstrained(), and set_C().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp