ReClaM: FisherLDA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
FisherLDA Class Reference
Fisher's Linear Discriminant Analysis for data compression.
#include <FisherLDA.h>
Public Member Functions
FisherLDA ()
~FisherLDA ()
void init (Model &model)
basic initialization with default parameters
void init (bool whitening=false)
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Performes one optimization step, for example a gradient descent step or an evolution cycle.
double optimize (AffineLinearMap &model, const Array< double > &input, const Array< double > &target)
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target, Array< double > &eigenvalues, Array< double > &eigenvectors)
double optimize (AffineLinearMap &model, const Array< double > &input, const Array< double > &target, Array< double > &eigenvalues, Array< double > &eigenvectors)
Protected Member Functions
void MeanAndScatter (AffineLinearMap &model, const Array< double > &input, const Array< double > &target, Vector &mean, Matrix &scatter)
Protected Attributes
bool bWhitening
Detailed Description
Fisher's Linear Discriminant Analysis for data compression.
Similar to PCA, Fisher's Linear Discriminant Analysis is a method for reducing the datas dimensionality. In contrast to PCA it also uses class information.
Consider the datas covariance matrix and a unit vector which defines a one-dimensional subspace of the data. Then, PCA would maximmize the objective , namely the datas variance in the subspace. Fisher-LDA, however, maximizes
where is the covariance matrix of the class-means and is the average covariance matrix of all classes (in both cases, each class' influence is weighted by it's size). As a result, Fisher-LDA finds a subspace in which the class means are wide-spread while (in average) the variance of each class becomes small. This leads to good lower-dimensional representations of the data in cases where the classes are linearly separable.
If a subspace with more than one dimension is requested, the above step is executed consecutively to find the next optimal subspace-dimension orthogonally to the others.
Note: the max. dimensionality for the subspace is #NumOfClasses-1.
For more detailed information about Fisher-LDA, see Bishop, Pattern Recognition and Machine Learning.
Definition at line 90 of file FisherLDA.h.
Constructor & Destructor Documentation
FisherLDA::FisherLDA ()
Definition at line 61 of file FisherLDA.cpp.
FisherLDA::~FisherLDA ()
Definition at line 66 of file FisherLDA.cpp.
Member Function Documentation
void FisherLDA::init (Model & model) [virtual]
basic initialization with default parameters
Implements Optimizer.
Definition at line 71 of file FisherLDA.cpp.
References Model::getInputDimension(), and Model::getOutputDimension().
void FisherLDA::init (bool whitening = false)
Definition at line 80 of file FisherLDA.cpp.
void FisherLDA::MeanAndScatter (AffineLinearMap & model, const Array< double > & input, const Array< double > & target, Vector & mean, Matrix & scatter) [protected]
Definition at line 153 of file FisherLDA.cpp.
References Model::getOutputDimension(), and i.
double FisherLDA::optimize (Model & model, ErrorFunction & error, const Array< double > & input, const Array< double > & target, Array< double > & eigenvalues, Array< double > & eigenvectors)
Definition at line 92 of file FisherLDA.cpp.
double FisherLDA::optimize (AffineLinearMap & model, const Array< double > & input, const Array< double > & target)
Definition at line 99 of file FisherLDA.cpp.
double FisherLDA::optimize (AffineLinearMap & model, const Array< double > & input, const Array< double > & target, Array< double > & eigenvalues, Array< double > & eigenvectors)
Definition at line 106 of file FisherLDA.cpp.
References Model::getInputDimension(), Model::getOutputDimension(), i, and Model::setParameter().
double FisherLDA::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Performes one optimization step, for example a gradient descent step or an evolution cycle.
Parameters:
model Model to use for the computation.
errorfunction ErrorFunction on which decisions are based.
input Vector of input values.
target Vector of output values.
Returns:
The error E returned by the ErrorFunction.
Implements Optimizer.
Definition at line 85 of file FisherLDA.cpp.
Member Data Documentation
bool FisherLDA::bWhitening [protected]
Definition at line 107 of file FisherLDA.h.
The documentation for this class was generated from the following files:
FisherLDA.h
FisherLDA.cpp