ReClaM: GeneralGaussKernel Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
GeneralGaussKernel Class Reference
General Guassian Kernel.
#include <GaussKernel.h>
Public Member Functions
GeneralGaussKernel (int dim, double gamma=1.0)
Constructor.
GeneralGaussKernel (const Array2D< double > &symmetricTransformation)
Constructor.
~GeneralGaussKernel ()
Destructor.
double eval (const Array< double > &x1, const Array< double > &x2) const
Evaluates the kernel function.
double evalDerivative (const Array< double > &x1, const Array< double > &x2, Array< double > &derivative) const
Evaluates the kernel function and computes its derivatives w.r.t.
void getTransformation (Array< double > &trans)
This method fills in the quadratic matrix trans with the linear transformation the kernel applies to the input data before applying the standard Gaussian kernel .
double computeGamma ()
compute the single RBF coefficient gamma, which is in this context best defined as the determinant of the matrix M to 2/d, where d is the input space dimension.
Static Protected Member Functions
static int index (int i, int j)
compute the index into the parameter vector
Detailed Description
General Guassian Kernel.
with symmetric matrix M
In case computation speed matters, it is equivalent to linearly transform the input data according to the matrix M before applying the standard #RBFKenerl with . This matrix can be determined calling getTransformation.
Definition at line 94 of file GaussKernel.h.
Constructor & Destructor Documentation
GeneralGaussKernel::GeneralGaussKernel (int dim, double gamma = 1.0)
Constructor.
Definition at line 109 of file GaussKernel.cpp.
References i, index(), and Model::parameter.
GeneralGaussKernel::GeneralGaussKernel (const Array2D< double > & symmetricTransformation)
Constructor.
Parameters:
symmetricTransformation symmetric positive definite inverse square root of the covariance of the Gaussian
Definition at line 119 of file GaussKernel.cpp.
References i, index(), and Model::parameter.
GeneralGaussKernel::~GeneralGaussKernel ()
Destructor.
Definition at line 135 of file GaussKernel.cpp.
Member Function Documentation
double GeneralGaussKernel::computeGamma ()
compute the single RBF coefficient gamma, which is in this context best defined as the determinant of the matrix M to 2/d, where d is the input space dimension.
Definition at line 222 of file GaussKernel.cpp.
References Model::getParameterDimension(), i, index(), and Model::parameter.
double GeneralGaussKernel::eval (const Array< double > & x1, const Array< double > & x2) const [virtual]
Evaluates the kernel function.
Implements KernelFunction.
Definition at line 140 of file GaussKernel.cpp.
References Model::getParameterDimension(), i, index(), and Model::parameter.
double GeneralGaussKernel::evalDerivative (const Array< double > & x1, const Array< double > & x2, Array< double > & derivative) const [virtual]
Evaluates the kernel function and computes its derivatives w.r.t.
the kernel parameters.
Reimplemented from KernelFunction.
Definition at line 166 of file GaussKernel.cpp.
References Model::getParameterDimension(), i, index(), and Model::parameter.
void GeneralGaussKernel::getTransformation (Array< double > & trans)
This method fills in the quadratic matrix trans with the linear transformation the kernel applies to the input data before applying the standard Gaussian kernel .
Definition at line 205 of file GaussKernel.cpp.
References Model::getParameterDimension(), i, index(), and Model::parameter.
static int GeneralGaussKernel::index (int i, int j) [inline, static, protected]
compute the index into the parameter vector
Definition at line 129 of file GaussKernel.h.
Referenced by computeGamma(), eval(), evalDerivative(), GeneralGaussKernel(), and getTransformation().
The documentation for this class was generated from the following files:
GaussKernel.h
GaussKernel.cpp