ReClaM: LinNorm Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
LinNorm Class Reference
Normalizes the (non-negative) output of a base model by dividing by the overall sum.
#include <NormedModels.h>
Public Member Functions
LinNorm (Model *m)
~LinNorm ()
void model (const Array< double > &input, Array< double > &output)
Returns the model's answer #output on the stimulus #input.
void modelDerivative (const Array< double > &input, Array< double > &derivative)
Calculates the derivative of the model output with respect to the parameters.
void setParameter (unsigned int index, double value)
Modifies a specific model parameter.
Protected Attributes
Model * m_baseModel
Detailed Description
Normalizes the (non-negative) output of a base model by dividing by the overall sum.
Definition at line 142 of file NormedModels.h.
Constructor & Destructor Documentation
LinNorm::LinNorm (Model * m) [inline]
Definition at line 145 of file NormedModels.h.
References Model::epsilon, Model::getInputDimension(), Model::getOutputDimension(), Model::getParameter(), Model::getParameterDimension(), i, Model::inputDimension, m_baseModel, Model::outputDimension, and Model::parameter.
LinNorm::~LinNorm () [inline]
Definition at line 159 of file NormedModels.h.
Member Function Documentation
void LinNorm::model (const Array< double > & input, Array< double > & output) [inline, virtual]
Returns the model's answer #output on the stimulus #input.
This method calculates the output of the model depending on the #input. The arrays #input and #output can either be one- or two-dimensional, depending on whether one or many patterns should be processed. The number of elements in the last dimension of these arrays must fit the inputDimension and outputDimension, in case of two-dimensional input, the number of elements in the first dimension equals the number of patterns. The method is pure virtual as it has to be implemented by the different models.
Parameters:
input Vector of input values.
output Vector of output values.
Returns:
None.
Implements Model.
Definition at line 162 of file NormedModels.h.
References i, m_baseModel, Model::model(), and Model::outputDimension.
void LinNorm::modelDerivative (const Array< double > & input, Array< double > & derivative) [inline, virtual]
Calculates the derivative of the model output with respect to the parameters.
This method performs the calculation of the model output with respect to the model parameters. Sometimes this calculation can only be performed based on a single input pattern; therefore #input must be a onedimensional array. As a default implementation, the derivatives are estimated numerically by using small variations epsilon:
However, to improve the speed, it is adviserable to overload this method by a more sophisticated calculation, depending on the method model. Nevertheless, this default implementation can be used to check new implementations of the derivative of the model with respect to the parameters.
Parameters:
input Vector of input values.
derivative Matrix of partial derivatives.
Reimplemented from Model.
Definition at line 192 of file NormedModels.h.
References Model::getParameterDimension(), i, m_baseModel, Model::model(), Model::modelDerivative(), and Model::outputDimension.
void LinNorm::setParameter (unsigned int index, double value) [inline, virtual]
Modifies a specific model parameter.
Reimplemented from Model.
Definition at line 221 of file NormedModels.h.
References m_baseModel, Model::parameter, and Model::setParameter().
Member Data Documentation
Model* LinNorm::m_baseModel [protected]
Definition at line 229 of file NormedModels.h.
Referenced by LinNorm(), model(), modelDerivative(), and setParameter().
The documentation for this class was generated from the following file:
NormedModels.h