ReClaM: OneClassSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
OneClassSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
OneClassSVM (SVM *pSVM, double fractionNu)
~OneClassSVM ()
Descructor.
void setParameter (unsigned int index, double value)
overloaded version of Model::setParameter
double getNu ()
return regularization parameter
bool isFeasible ()
ensure nu is positive
Protected Attributes
double nu
Regualrization parameter, which directly controls the fraction of misclassified training pattern (outlier).
Detailed Description
Meta Model for SVM training.
Author:
E. Diner
Date:
2008
The one class SVM is a training scheme for classification and density estimation. It defines a positive constant allows to misclassify a certain fraction of the training pattern which lie closest to the origin. For more information read: Estimating the Support of a High-Dimensional Distribution, B. Schölkopf
Definition at line 831 of file Svm.h.
Constructor & Destructor Documentation
OneClassSVM::OneClassSVM (SVM * pSVM, double fractionNu)
Parameters:
pSVM Pointer to the SVM to be optimized.
nu fraction of the training data that can be misclassified
Definition at line 1189 of file Svm.cpp.
References setParameter().
OneClassSVM::~OneClassSVM ()
Descructor.
Definition at line 1195 of file Svm.cpp.
Member Function Documentation
double OneClassSVM::getNu () [inline]
return regularization parameter
Definition at line 846 of file Svm.h.
References nu.
Referenced by SVM_Optimizer::init().
bool OneClassSVM::isFeasible () [virtual]
ensure nu is positive
Reimplemented from MetaSVM.
Definition at line 1213 of file Svm.cpp.
References MetaSVM::isFeasible(), and nu.
void OneClassSVM::setParameter (unsigned int index, double value) [virtual]
overloaded version of Model::setParameter
Reimplemented from MetaSVM.
Definition at line 1200 of file Svm.cpp.
References nu.
Referenced by OneClassSVM().
Member Data Documentation
double OneClassSVM::nu [protected]
Regualrization parameter, which directly controls the fraction of misclassified training pattern (outlier).
Definition at line 855 of file Svm.h.
Referenced by getNu(), isFeasible(), and setParameter().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp