ReClaM: SpanBound1 Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SpanBound1 Class Reference
SpanBound for the 1-norm SVM.
#include <SpanBound1.h>
Public Member Functions
SpanBound1 (bool verbose=false)
Constructor.
~SpanBound1 ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
This method computes an upper bound on the leave one out error.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
This method computes an upper bound on the leave one out error as well as its derivative w.r.t.
void setMaxIterations (SharkInt64 maxiter=-1)
set the maximum number of iterations for the quadratic program solver
Protected Member Functions
double bound (C_SVM *csvm, int p, const Array< double > &input, const Array< double > &target)
double boundDerivative (C_SVM *csvm, int p, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Protected Attributes
bool verbose
output the status to stdout?
SharkInt64 maxiter
maximum number of iterations for the quadratic program solver
Detailed Description
SpanBound for the 1-norm SVM.
Definition at line 55 of file SpanBound1.h.
Constructor & Destructor Documentation
SpanBound1::SpanBound1 (bool verbose = false)
Constructor.
Definition at line 50 of file SpanBound1.cpp.
References maxiter, and verbose.
SpanBound1::~SpanBound1 ()
Destructor.
Definition at line 56 of file SpanBound1.cpp.
Member Function Documentation
double SpanBound1::bound (C_SVM * csvm, int p, const Array< double > & input, const Array< double > & target) [protected]
Definition at line 176 of file SpanBound1.cpp.
References C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM::getKernel(), MetaSVM::getSVM(), i, and SVM_Optimizer::init().
Referenced by error().
double SpanBound1::boundDerivative (C_SVM * csvm, int p, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [protected]
Definition at line 208 of file SpanBound1.cpp.
References C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM::getKernel(), MetaSVM::getSVM(), i, SVM_Optimizer::init(), C_SVM::is2norm(), and C_SVM::isUnconstrained().
Referenced by errorDerivative().
double SpanBound1::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
This method computes an upper bound on the leave one out error.
Implements ErrorFunction.
Definition at line 61 of file SpanBound1.cpp.
References bound(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM_Optimizer::get_Solver(), SVM::getAlpha(), SVM::getExamples(), MetaSVM::getSVM(), i, SVM_Optimizer::init(), C_SVM::is2norm(), QpSvmDecomp::isOptimal(), maxiter, SVM::model(), SVM_Optimizer::optimize(), and SVM_Optimizer::setMaxIterations().
double SpanBound1::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
This method computes an upper bound on the leave one out error as well as its derivative w.r.t.
the kernel parameters and C.
Reimplemented from ErrorFunction.
Definition at line 112 of file SpanBound1.cpp.
References boundDerivative(), C_SVM::get_Cminus(), C_SVM::get_Cplus(), SVM_Optimizer::get_Solver(), SVM::getAlpha(), SVM::getExamples(), Model::getParameterDimension(), MetaSVM::getSVM(), i, SVM_Optimizer::init(), C_SVM::is2norm(), QpSvmDecomp::isOptimal(), maxiter, SVM::model(), C_SVM::modelDerivative(), SVM_Optimizer::optimize(), C_SVM::PrepareDerivative(), and SVM_Optimizer::setMaxIterations().
void SpanBound1::setMaxIterations (SharkInt64 maxiter = -1) [inline]
set the maximum number of iterations for the quadratic program solver
Definition at line 76 of file SpanBound1.h.
References maxiter.
Member Data Documentation
SharkInt64 SpanBound1::maxiter [protected]
maximum number of iterations for the quadratic program solver
Definition at line 89 of file SpanBound1.h.
Referenced by error(), errorDerivative(), setMaxIterations(), and SpanBound1().
bool SpanBound1::verbose [protected]
output the status to stdout?
Definition at line 86 of file SpanBound1.h.
Referenced by SpanBound1().
The documentation for this class was generated from the following files:
SpanBound1.h
SpanBound1.cpp