ReClaM: GaussianProcessEvidence Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
GaussianProcessEvidence Class Reference
negative evidence of a Gaussian process
#include <GaussianProcess.h>
Public Member Functions
GaussianProcessEvidence ()
Constructor.
~GaussianProcessEvidence ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computation of the negative Gaussian process evidence.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Computation of the derivative of the negative Gaussian process evidence.
Protected Member Functions
double evidence (GaussianProcess *gp)
Computation of the evidence.
void dEvidenceDTheta (GaussianProcess *gp, double &dEdBI, Array< double > &dEdS)
Computation of the derivative of the evidence.
Detailed Description
negative evidence of a Gaussian process
The GaussianProcessEvidence class serves as an ErrorFunction, that is, any Optimizer can be used for its minimization (aiming at evidence maximization).
Definition at line 163 of file GaussianProcess.h.
Constructor & Destructor Documentation
GaussianProcessEvidence::GaussianProcessEvidence ()
Constructor.
Definition at line 180 of file GaussianProcess.cpp.
GaussianProcessEvidence::~GaussianProcessEvidence ()
Destructor.
Definition at line 183 of file GaussianProcess.cpp.
Member Function Documentation
void GaussianProcessEvidence::dEvidenceDTheta (GaussianProcess * gp, double & dEdBI, Array< double > & dEdS) [protected]
Computation of the derivative of the evidence.
Definition at line 225 of file GaussianProcess.cpp.
References KernelFunction::evalDerivative(), GaussianProcess::getC(), GaussianProcess::getCInv(), SVM::getExamples(), SVM::getKernel(), Model::getParameterDimension(), SVM::getPoints(), MetaSVM::getSVM(), GaussianProcess::getTarget(), and i.
Referenced by errorDerivative().
double GaussianProcessEvidence::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computation of the negative Gaussian process evidence.
Parameters:
model A GaussianProcess model must be provided, otherwise an exception will be thrown
Implements ErrorFunction.
Definition at line 187 of file GaussianProcess.cpp.
References evidence().
Referenced by GaussianProcess::Evidence().
double GaussianProcessEvidence::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Computation of the derivative of the negative Gaussian process evidence.
Parameters:
model A GaussianProcess model must be provided, otherwise an exception will be thrown
Reimplemented from ErrorFunction.
Definition at line 195 of file GaussianProcess.cpp.
References dEvidenceDTheta(), and evidence().
double GaussianProcessEvidence::evidence (GaussianProcess * gp) [protected]
Computation of the evidence.
Definition at line 211 of file GaussianProcess.cpp.
References GaussianProcess::getC(), GaussianProcess::getCInv(), SVM::getExamples(), MetaSVM::getSVM(), and GaussianProcess::getTarget().
Referenced by error(), and errorDerivative().
The documentation for this class was generated from the following files:
GaussianProcess.h
GaussianProcess.cpp