ReClaM: PointSearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
PointSearch Class Reference
Optimize by trying out predefined configurations.
#include <GridSearch.h>
Public Member Functions
PointSearch (int verbosity)
Constructor.
~PointSearch ()
Destructor.
void init (Model &model)
There is no useful default initialization for this optimizer.
void init (Array< double > &values)
Initialization of the search points.
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target)
Please note that for the point search optimizer it does not make sense to call optimize more than once, as the solution does not improve iteratively.
Protected Attributes
Array< double > nodes
The array holds one parameter configuration in every column.
int verbosity
verbosity level
Detailed Description
Optimize by trying out predefined configurations.
The PointSearch class is similair to the GridSearch class by the property that it optimizes a model in a single pass just trying out a predefined number of parameter configurations. The main difference is that every parameter configuration has to be explicitly defined. It is not possible to define a set of values for every axis; refer to GridSearch for this purpose. Thus, the optPointSearch class allows for more flexibility.
Definition at line 273 of file GridSearch.h.
Constructor & Destructor Documentation
PointSearch::PointSearch (int verbosity)
Constructor.
Parameters:
verbosity 0=none, 1=dots, 2=values
Definition at line 422 of file GridSearch.cpp.
References verbosity.
PointSearch::~PointSearch ()
Destructor.
Definition at line 427 of file GridSearch.cpp.
Member Function Documentation
void PointSearch::init (Model & model) [virtual]
There is no useful default initialization for this optimizer.
Thus, this member throws an exception.
Implements Optimizer.
Definition at line 432 of file GridSearch.cpp.
void PointSearch::init (Array< double > & values)
Initialization of the search points.
Parameters:
values two-dimensional array; every column contains one parameter configuration.
Definition at line 437 of file GridSearch.cpp.
References nodes.
double PointSearch::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Please note that for the point search optimizer it does not make sense to call optimize more than once, as the solution does not improve iteratively.
Implements Optimizer.
Definition at line 442 of file GridSearch.cpp.
References ErrorFunction::error(), Model::getParameter(), Model::getParameterDimension(), i, Model::isFeasible(), nodes, Model::setParameter(), and verbosity.
Member Data Documentation
Array<double> PointSearch::nodes [protected]
The array holds one parameter configuration in every column.
Definition at line 301 of file GridSearch.h.
Referenced by init(), and optimize().
int PointSearch::verbosity [protected]
verbosity level
Definition at line 304 of file GridSearch.h.
Referenced by optimize(), and PointSearch().
The documentation for this class was generated from the following files:
GridSearch.h
GridSearch.cpp