ReClaM: BinaryCriterion Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
BinaryCriterion Class Reference
Use thresholds for transforming output and target vectors into binary vectors and then calculates the classification error.
#include <BinaryCriterion.h>
Public Member Functions
BinaryCriterion (double t=0.0)
Constructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Uses thresholds for transforming output and target vectors into binary vectors and then calculating the error.
Protected Member Functions
void binary (Array< double > &a, double t)
Used to mark output neurons as set/unset.
Protected Attributes
double buffersize
Size of the buffer interval.
Detailed Description
Use thresholds for transforming output and target vectors into binary vectors and then calculates the classification error.
Definition at line 52 of file BinaryCriterion.h.
Constructor & Destructor Documentation
BinaryCriterion::BinaryCriterion (double t = 0.0) [inline]
Constructor.
Parameters:
t Defines an interval of length 2t, output values in this interval are not transformed into binary values.
Definition at line 61 of file BinaryCriterion.h.
References buffersize.
Member Function Documentation
void BinaryCriterion::binary (Array< double > & a, double t) [inline, protected]
Used to mark output neurons as set/unset.
Normally the threshold for a neuron to be set is 0.5 and higher, but with parameter t a buffer interval between set and unset neurons is defined. All neurons lying in this interval are ignored.
Definition at line 220 of file BinaryCriterion.h.
References i.
Referenced by error().
double BinaryCriterion::error (Model & model, const Array< double > & input, const Array< double > & target) [inline, virtual]
Uses thresholds for transforming output and target vectors into binary vectors and then calculating the error.
Used for qualification strategies. The target vectors are transformed into binary vectors by using a threshold of "0.5". All target neurons greater than "0.5" are set to "1", all other target neurons are set to zero. The output vectors are transformed into binary vectors in the same way, but by using the parameter t, you can define a "buffer interval" of size . All output neurons with a value of 0.5 - t or less are set to zero, all output neurons with a value greater than 0.5 + t are set to 1, output neurons with a value in the interval are ignored. This make for these values counted as errors, because normally the unmodified values of the output neurons are not "0" or "1". After this transformation of the vectors the number of vectors is counted for which the used model calculates another output than given by the corresponding target vector. Then the number of different vector-pairs is normalized by the number of input patterns. Given a number of patterns the error is calculated by:
binary is used here for the notation of the transformation of the original vectors to binary vectors.
Example
The first example shows the binary transformation for a value for parameter t of "0" resulting in 4 differences between the output and the target vector, the second shows the same transformation for a value of "0.2", resulting in twice as many differences.
Parameters:
model The model used for prediction
input Input vector for the model.
target Target vector.
Returns:
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Implements ErrorFunction.
Definition at line 171 of file BinaryCriterion.h.
References binary(), buffersize, i, and Model::model().
Member Data Documentation
double BinaryCriterion::buffersize [protected]
Size of the buffer interval.
Definition at line 244 of file BinaryCriterion.h.
Referenced by BinaryCriterion(), and error().
The documentation for this class was generated from the following file:
BinaryCriterion.h