ReClaM: SpanBound2 Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SpanBound2 Class Reference
SpanBound for the 2-norm SVM.
#include <SpanBound2.h>
Public Member Functions
SpanBound2 (bool verbose=false)
Constructor.
~SpanBound2 ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computation of the span bound If the quadratic program solver does not reach the optimum within the maximal number of iterations the method returns 1e100.
void setMaxIterations (SharkInt64 maxiter=-1)
set the maximum number of iterations for the quadratic program solver
SharkInt64 iterations ()
return the number of iterations last used by the quadratic program solver
Protected Attributes
bool verbose
output the status to stdout?
SharkInt64 maxIter
maximum number of #C_Solver iterations
SharkInt64 iter
last number if #C_Solver iterations
Detailed Description
SpanBound for the 2-norm SVM.
Definition at line 54 of file SpanBound2.h.
Constructor & Destructor Documentation
SpanBound2::SpanBound2 (bool verbose = false)
Constructor.
Definition at line 44 of file SpanBound2.cpp.
References maxIter, and verbose.
SpanBound2::~SpanBound2 ()
Destructor.
Definition at line 50 of file SpanBound2.cpp.
Member Function Documentation
double SpanBound2::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computation of the span bound If the quadratic program solver does not reach the optimum within the maximal number of iterations the method returns 1e100.
Implements ErrorFunction.
Definition at line 55 of file SpanBound2.cpp.
References SVM_Optimizer::get_Solver(), SVM::getAlpha(), MetaSVM::getSVM(), i, SVM_Optimizer::init(), C_SVM::is2norm(), QpSvmDecomp::isOptimal(), iter, QpSvmDecomp::iterations(), maxIter, SVM::model(), SVM_Optimizer::optimize(), SVM_Optimizer::setMaxIterations(), QpSvmDecomp::Solve(), and verbose.
SharkInt64 SpanBound2::iterations () [inline]
return the number of iterations last used by the quadratic program solver
Definition at line 79 of file SpanBound2.h.
References iter.
void SpanBound2::setMaxIterations (SharkInt64 maxiter = -1) [inline]
set the maximum number of iterations for the quadratic program solver
Definition at line 72 of file SpanBound2.h.
References maxIter.
Member Data Documentation
SharkInt64 SpanBound2::iter [protected]
last number if #C_Solver iterations
Definition at line 92 of file SpanBound2.h.
Referenced by error(), and iterations().
SharkInt64 SpanBound2::maxIter [protected]
maximum number of #C_Solver iterations
Definition at line 89 of file SpanBound2.h.
Referenced by error(), setMaxIterations(), and SpanBound2().
bool SpanBound2::verbose [protected]
output the status to stdout?
Definition at line 86 of file SpanBound2.h.
Referenced by error(), and SpanBound2().
The documentation for this class was generated from the following files:
SpanBound2.h
SpanBound2.cpp