ReClaM: SvmApproximation Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SvmApproximation Class Reference
Approximation of Support Vector Machines (SVMs)
#include <SvmApproximation.h>
Public Types
enum approximationAlgorithm { iRpropPlus, fixedPointIteration }
enum approximationTarget { noSVs, classificationRateOnSVs }
enum vectorGenerationMode { randomSelection, stochasticUniversalSampling, kMeansClustering }
Public Member Functions
SvmApproximation (SVM *pSVM, bool verbose=false)
constructor
~SvmApproximation ()
destructor
float approximate ()
approximate SVM
float gradientDescent ()
perform gradient descent on overall model of approximated SVM (SVs and coefficients)
SVM * getApproximatedSVM ()
return pointer to approximated SVM
void setApproximationAlgorithm (approximationAlgorithm aA)
specify the algorithm for the approximation
void setVectorGenerationMode (int mode)
specify technique for choosing initial vectors
void setApproximationTarget (approximationTarget aT)
specify the goal iterate until the approximated SV consists of a specified number of SVs or until a certain classification on the SVs of the original SVM is achieved
void setTargetNoVecsForApproximatedSVM (unsigned noVecs)
specify the number of the SVs for the approximated SVM only used if "approximationTarget" is set to "noSVs"
void setTargetClassificationRateOnSVsForApproximatedSVM (float classificationRate)
specify the classification rate that should be achieved on the SVs of the original SVM only used if "approximationTarget" is set to "classificationRateOnSVs"
void setNoGradientDescentIterations (unsigned no)
Protected Member Functions
double error ()
determine "difference" between original and approximated SVM
void addVecRprop ()
optimize vector using iRpropPlus
void addVecFixPointIteration ()
optimize using fixed-point iteration
bool calcOptimalAlphaOfApproximatedSVM ()
calculate optimal coefficients for approx. SVM
bool calcOffsetForReducedModel ()
calculate bias "b" for approx. SVM
float getClassificationRateOnSVsCorrectlyClassifiedByOrigSVM ()
determine classification rate of approx. SVM on SVs of original SVM
void determineNoPositiveAndNegativeVectorsForApproximation ()
bool chooseVectorForNextIteration (Array< double > &vec)
choose vector from original SVs
void createIndexListWithStochasticUniversalSampling ()
choose initials vectors with k-means-clustering
void createIndexListWithKMeans ()
Protected Attributes
bool verbose
in verbose mode the algorithm outputs some helpful comments to stdout.
SVM * mpSVM
SVM * mpApproximatedSVM
double * labels
Array< double > approximatedVectors
unsigned mNoExamplesOfOrigSVM
unsigned mDimension
unsigned mNoSVs
unsigned * mpNoExamplesOfApproximatedSVM
double mOffsetOfApproximatedSVM
unsigned mTargetNoVecsForApproximatedSVM
unsigned mTargetNoPositiveVectors
unsigned mTargetNoNegativeVectors
float mTargetClassificationRateForApproximatedSVM
approximationAlgorithm mApproximationAlgorithm
approximationTarget mApproximationTarget
KernelFunction * mpKernel
double mGamma
unsigned int mVectorGenerationMode
bool mbIsApproximatedModelValid
bool mbPerformedGradientDescent
unsigned mNoGradientDescentIterations
unsigned int mNoPositiveSVsOfOrigSVM
unsigned int mNoNegativeSVsOfOrigSVM
unsigned int mNoPositiveVecsDrawn
unsigned int mNoNegativeVecsDrawn
const char * mOutputDir
unsigned mIndexOfChosenVec
std::vector< int > * mpIndexListOfVecsForSelection
Friends
class SvmApproximationErrorFunction
class SvmApproximationErrorFunctionGlobal
Detailed Description
Approximation of Support Vector Machines (SVMs)
Author:
T. Suttorp
Date:
2006
The SvmApproximator class approximates the decision
function of an Shark-SVM object
Examples:
SvmApproximationExample.cpp.
Definition at line 61 of file SvmApproximation.h.
Member Enumeration Documentation
enum SvmApproximation::approximationAlgorithm
Enumerator:
iRpropPlus
fixedPointIteration
Definition at line 64 of file SvmApproximation.h.
enum SvmApproximation::approximationTarget
Enumerator:
noSVs
classificationRateOnSVs
Definition at line 70 of file SvmApproximation.h.
enum SvmApproximation::vectorGenerationMode
Enumerator:
randomSelection
stochasticUniversalSampling
kMeansClustering
Definition at line 76 of file SvmApproximation.h.
Constructor & Destructor Documentation
SvmApproximation::SvmApproximation (SVM * pSVM, bool verbose = false)
constructor
Parameters:
pSVM SVM to be approximated
Definition at line 70 of file SvmApproximation.cpp.
References SVM::getKernel(), Model::getParameter(), and SVM::SetTrainingData().
SvmApproximation::~SvmApproximation ()
destructor
Definition at line 149 of file SvmApproximation.cpp.
Member Function Documentation
void SvmApproximation::addVecFixPointIteration () [protected]
optimize using fixed-point iteration
Definition at line 485 of file SvmApproximation.cpp.
References SVM::getPoints(), and i.
void SvmApproximation::addVecRprop () [protected]
optimize vector using iRpropPlus
Definition at line 440 of file SvmApproximation.cpp.
References Model::getParameter(), IRpropPlus::initUserDefined(), and IRpropPlus::optimize().
float SvmApproximation::approximate ()
approximate SVM
Examples:
SvmApproximationExample.cpp.
Definition at line 267 of file SvmApproximation.cpp.
bool SvmApproximation::calcOffsetForReducedModel () [protected]
calculate bias "b" for approx. SVM
Definition at line 668 of file SvmApproximation.cpp.
References SVM::getPoints(), and i.
bool SvmApproximation::calcOptimalAlphaOfApproximatedSVM () [protected]
calculate optimal coefficients for approx. SVM
Definition at line 563 of file SvmApproximation.cpp.
References SVM::getPoints(), and i.
bool SvmApproximation::chooseVectorForNextIteration (Array< double > & vec) [protected]
choose vector from original SVs
Definition at line 799 of file SvmApproximation.cpp.
void SvmApproximation::createIndexListWithKMeans () [protected]
Definition at line 705 of file SvmApproximation.cpp.
References KernelKMeans::clusterVectors(), SVM::getAlpha(), and i.
void SvmApproximation::createIndexListWithStochasticUniversalSampling () [protected]
choose initials vectors with k-means-clustering
Definition at line 752 of file SvmApproximation.cpp.
References SVM::getAlpha(), and i.
void SvmApproximation::determineNoPositiveAndNegativeVectorsForApproximation () [protected]
Definition at line 919 of file SvmApproximation.cpp.
double SvmApproximation::error () [protected]
determine "difference" between original and approximated SVM
Definition at line 158 of file SvmApproximation.cpp.
References KernelFunction::eval(), SVM::getAlpha(), SVM::getPoints(), and i.
SVM* SvmApproximation::getApproximatedSVM () [inline]
return pointer to approximated SVM
Examples:
SvmApproximationExample.cpp.
Definition at line 99 of file SvmApproximation.h.
References mpApproximatedSVM.
float SvmApproximation::getClassificationRateOnSVsCorrectlyClassifiedByOrigSVM () [protected]
determine classification rate of approx. SVM on SVs of original SVM
Definition at line 884 of file SvmApproximation.cpp.
References i.
float SvmApproximation::gradientDescent ()
perform gradient descent on overall model of approximated SVM (SVs and coefficients)
Examples:
SvmApproximationExample.cpp.
Definition at line 371 of file SvmApproximation.cpp.
References Model::getParameter(), i, IRpropPlus::initUserDefined(), and IRpropPlus::optimize().
void SvmApproximation::setApproximationAlgorithm (approximationAlgorithm aA) [inline]
specify the algorithm for the approximation
Examples:
SvmApproximationExample.cpp.
Definition at line 105 of file SvmApproximation.h.
References mApproximationAlgorithm.
void SvmApproximation::setApproximationTarget (approximationTarget aT) [inline]
specify the goal iterate until the approximated SV consists of a specified number of SVs or until a certain classification on the SVs of the original SVM is achieved
Examples:
SvmApproximationExample.cpp.
Definition at line 114 of file SvmApproximation.h.
References mApproximationTarget.
void SvmApproximation::setNoGradientDescentIterations (unsigned no) [inline]
Examples:
SvmApproximationExample.cpp.
Definition at line 126 of file SvmApproximation.h.
References mNoGradientDescentIterations.
void SvmApproximation::setTargetClassificationRateOnSVsForApproximatedSVM (float classificationRate) [inline]
specify the classification rate that should be achieved on the SVs of the original SVM only used if "approximationTarget" is set to "classificationRateOnSVs"
Definition at line 123 of file SvmApproximation.h.
References mTargetClassificationRateForApproximatedSVM.
void SvmApproximation::setTargetNoVecsForApproximatedSVM (unsigned noVecs) [inline]
specify the number of the SVs for the approximated SVM only used if "approximationTarget" is set to "noSVs"
Examples:
SvmApproximationExample.cpp.
Definition at line 118 of file SvmApproximation.h.
References mTargetNoVecsForApproximatedSVM.
void SvmApproximation::setVectorGenerationMode (int mode) [inline]
specify technique for choosing initial vectors
Examples:
SvmApproximationExample.cpp.
Definition at line 109 of file SvmApproximation.h.
References mVectorGenerationMode.
Friends And Related Function Documentation
friend class SvmApproximationErrorFunction [friend]
Definition at line 201 of file SvmApproximation.h.
friend class SvmApproximationErrorFunctionGlobal [friend]
Definition at line 202 of file SvmApproximation.h.
Member Data Documentation
Array<double> SvmApproximation::approximatedVectors [protected]
Definition at line 168 of file SvmApproximation.h.
double* SvmApproximation::labels [protected]
Definition at line 166 of file SvmApproximation.h.
approximationAlgorithm SvmApproximation::mApproximationAlgorithm [protected]
Definition at line 178 of file SvmApproximation.h.
Referenced by setApproximationAlgorithm().
approximationTarget SvmApproximation::mApproximationTarget [protected]
Definition at line 179 of file SvmApproximation.h.
Referenced by setApproximationTarget().
bool SvmApproximation::mbIsApproximatedModelValid [protected]
Definition at line 185 of file SvmApproximation.h.
bool SvmApproximation::mbPerformedGradientDescent [protected]
Definition at line 186 of file SvmApproximation.h.
unsigned SvmApproximation::mDimension [protected]
Definition at line 170 of file SvmApproximation.h.
double SvmApproximation::mGamma [protected]
Definition at line 182 of file SvmApproximation.h.
unsigned SvmApproximation::mIndexOfChosenVec [protected]
Definition at line 197 of file SvmApproximation.h.
unsigned SvmApproximation::mNoExamplesOfOrigSVM [protected]
Definition at line 170 of file SvmApproximation.h.
unsigned SvmApproximation::mNoGradientDescentIterations [protected]
Definition at line 188 of file SvmApproximation.h.
Referenced by setNoGradientDescentIterations().
unsigned int SvmApproximation::mNoNegativeSVsOfOrigSVM [protected]
Definition at line 191 of file SvmApproximation.h.
unsigned int SvmApproximation::mNoNegativeVecsDrawn [protected]
Definition at line 192 of file SvmApproximation.h.
unsigned int SvmApproximation::mNoPositiveSVsOfOrigSVM [protected]
Definition at line 191 of file SvmApproximation.h.
unsigned int SvmApproximation::mNoPositiveVecsDrawn [protected]
Definition at line 192 of file SvmApproximation.h.
unsigned SvmApproximation::mNoSVs [protected]
Definition at line 170 of file SvmApproximation.h.
double SvmApproximation::mOffsetOfApproximatedSVM [protected]
Definition at line 172 of file SvmApproximation.h.
const char* SvmApproximation::mOutputDir [protected]
Definition at line 195 of file SvmApproximation.h.
SVM* SvmApproximation::mpApproximatedSVM [protected]
Definition at line 164 of file SvmApproximation.h.
Referenced by getApproximatedSVM().
std::vector<int>* SvmApproximation::mpIndexListOfVecsForSelection [protected]
Definition at line 199 of file SvmApproximation.h.
KernelFunction* SvmApproximation::mpKernel [protected]
Definition at line 181 of file SvmApproximation.h.
unsigned* SvmApproximation::mpNoExamplesOfApproximatedSVM [protected]
Definition at line 171 of file SvmApproximation.h.
SVM* SvmApproximation::mpSVM [protected]
Definition at line 163 of file SvmApproximation.h.
float SvmApproximation::mTargetClassificationRateForApproximatedSVM [protected]
Definition at line 176 of file SvmApproximation.h.
Referenced by setTargetClassificationRateOnSVsForApproximatedSVM().
unsigned SvmApproximation::mTargetNoNegativeVectors [protected]
Definition at line 175 of file SvmApproximation.h.
unsigned SvmApproximation::mTargetNoPositiveVectors [protected]
Definition at line 175 of file SvmApproximation.h.
unsigned SvmApproximation::mTargetNoVecsForApproximatedSVM [protected]
Definition at line 175 of file SvmApproximation.h.
Referenced by setTargetNoVecsForApproximatedSVM().
unsigned int SvmApproximation::mVectorGenerationMode [protected]
Definition at line 184 of file SvmApproximation.h.
Referenced by setVectorGenerationMode().
bool SvmApproximation::verbose [protected]
in verbose mode the algorithm outputs some helpful comments to stdout.
Definition at line 131 of file SvmApproximation.h.
The documentation for this class was generated from the following files:
SvmApproximation.h
SvmApproximation.cpp