ReClaM: OVAMcSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
OVAMcSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
OVAMcSVM (MultiClassSVM *pSVM, double C)
Constructor.
~OVAMcSVM ()
Destructor.
double get_C ()
void set_C (double C)
bool isFeasible ()
ensure C is positive
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2008
Set of binary machines trained with the all-versus-one rule.
Examples:
McSvm.cpp.
Definition at line 1110 of file Svm.h.
Constructor & Destructor Documentation
OVAMcSVM::OVAMcSVM (MultiClassSVM * pSVM, double C)
Constructor.
Definition at line 1681 of file Svm.cpp.
References Model::parameter.
OVAMcSVM::~OVAMcSVM ()
Destructor.
Definition at line 1687 of file Svm.cpp.
Member Function Documentation
double OVAMcSVM::get_C () [inline]
Definition at line 1120 of file Svm.h.
References Model::parameter.
Referenced by SVM_Optimizer::init().
bool OVAMcSVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1692 of file Svm.cpp.
References MetaSVM::isFeasible(), and Model::parameter.
void OVAMcSVM::set_C (double C) [inline]
Definition at line 1121 of file Svm.h.
References MetaSVM::setParameter().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp