ReClaM: QuickpropOriginal Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
QuickpropOriginal Class Reference
This class offers methods for using the popular heuristic "Quickprop" optimization algorithm.
#include <Quickprop.h>
Public Member Functions
void init (Model &model)
Initializes the optimizer with default parameters.
void initUserDefined (Model &model, double nuP=1.5, double dMaxP=1.75)
Prepares the Quickprop algorithm for the currently used network.
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target)
Performs one run of the original Quickprop algorithm.
void clearMemory ()
Resets internal variables used by the current class instance.
Protected Member Functions
double sgn (double x)
Determines the sign of "x".
Protected Attributes
double delta
The update value for the currently processed weight.
Array< double > deltaw
The update values for all weights.
Array< double > dedwOld
The last error gradient.
double nu
The learning rate , set to 1.5 by default.
double dMax
Upper limit for the increase factor: No weight adaption may be greater than the dMax times the previous adaption, set to 1.75 by default.
Detailed Description
This class offers methods for using the popular heuristic "Quickprop" optimization algorithm.
The "Quickprop" algorithm sees the weights of a network as if they were quasi-independant and tries to approximate the error surface, as a function of each of the weights, by a quadratic polynomial (a parabola). Then two successive evaluations of the error function and an evaluation of its gradient follow to determine the coefficients of the polynomial. At the next step of the iteration, the weight parameter is moved to the minimum of the parabola. This leads to a calculation of the update factor for weight no. from iteration to iteration as
where .
For further information about this algorithm, please refer to:
S. E. Fahlman,
"Faster-learning variations on back-propagation: an empirical study."
In D. Touretzky, G.E. Hinton and T,J, Sejnowski (Eds.),
"Proceedings of the 1988 Connectionist Models Summer School", pp. 38-51, San Mateo, CA: Morgan Kaufmann
Author:
C. Igel
Date:
1999
Changes:
none
Status:
stable
Definition at line 327 of file Quickprop.h.
Member Function Documentation
void QuickpropOriginal::clearMemory () [inline]
Resets internal variables used by the current class instance.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 488 of file Quickprop.h.
References dedwOld, and deltaw.
void QuickpropOriginal::init (Model & model) [inline, virtual]
Initializes the optimizer with default parameters.
Initializes the optimizer's parameters with the following defaults:
Learning rate
Upper limit for increase factor = 1.75
Parameters:
model Model to be optimized.
Returns:
None.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Implements Optimizer.
Definition at line 354 of file Quickprop.h.
References initUserDefined().
void QuickpropOriginal::initUserDefined (Model & model, double nuP = 1.5, double dMaxP = 1.75) [inline]
Prepares the Quickprop algorithm for the currently used network.
Internal variables of the class instance are initialized and memory for used structures adapted to the used network.
Parameters:
model Model to be optimized.
lrP Learning rate , set to 1.5 by default.
dmaxP Upper limit for the increase factor, set to 1.75 by default.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 382 of file Quickprop.h.
References dedwOld, deltaw, dMax, Model::getParameterDimension(), and nu.
Referenced by init().
double QuickpropOriginal::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [inline, virtual]
Performs one run of the original Quickprop algorithm.
The error of the used network for the current iteration is calculated and the values of the weights are optimized depending on this error.
Parameters:
model Model to be optimized.
errorfunction Error function to be used for the optimization.
input Input vector for the model.
target Corresponding targets to the given inputs.
Returns:
The current error.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Implements Optimizer.
Definition at line 418 of file Quickprop.h.
References dedwOld, delta, deltaw, dMax, ErrorFunction::errorDerivative(), Model::getParameter(), Model::getParameterDimension(), i, nu, and Model::setParameter().
double QuickpropOriginal::sgn (double x) [inline, protected]
Determines the sign of "x".
Parameters:
x The value of which the sign shall be determined.
Returns:
"-1", if the sign of x is negative, "0" otherwise.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 512 of file Quickprop.h.
Member Data Documentation
Array<double> QuickpropOriginal::dedwOld [protected]
The last error gradient.
Definition at line 524 of file Quickprop.h.
Referenced by clearMemory(), initUserDefined(), and optimize().
double QuickpropOriginal::delta [protected]
The update value for the currently processed weight.
Definition at line 518 of file Quickprop.h.
Referenced by optimize().
Array<double> QuickpropOriginal::deltaw [protected]
The update values for all weights.
Definition at line 521 of file Quickprop.h.
Referenced by clearMemory(), initUserDefined(), and optimize().
double QuickpropOriginal::dMax [protected]
Upper limit for the increase factor: No weight adaption may be greater than the dMax times the previous adaption, set to 1.75 by default.
Definition at line 530 of file Quickprop.h.
Referenced by initUserDefined(), and optimize().
double QuickpropOriginal::nu [protected]
The learning rate , set to 1.5 by default.
Definition at line 527 of file Quickprop.h.
Referenced by initUserDefined(), and optimize().
The documentation for this class was generated from the following file:
Quickprop.h