ReClaM: NegativeKTA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
NegativeKTA Class Reference
Implementation of the negative Kernel Target Alignment (KTA) as proposed by Nello Cristianini. This measure is extended for multi-class problems.
#include <KTA.h>
Public Member Functions
NegativeKTA (unsigned int numberOfClasses=2)
Constructor.
~NegativeKTA ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computes the negative Kernel Target Alignment between the target and the kernel function output on the input.
double errorDerivative (Model &model, const Array< double > &input, const Array< double > &target, Array< double > &derivative)
Computes the negative Kernel Target Alignment between the target and the kernel function output on the input.
Protected Attributes
unsigned int m_numberOfClasses
double m_offdiag
double m_offdiag2
double m_2offdiag
double m_2offdiag2
Detailed Description
Implementation of the negative Kernel Target Alignment (KTA) as proposed by Nello Cristianini. This measure is extended for multi-class problems.
Kernel Target Alignment measures how well a kernel fits a classification training set. It is invariant under kernel rescaling. To turn it into an error function (i.e., to make minimization meaningful) the negative KTA is implemented.
The KTA has two important properties: It is differentiable and independent of the actual classifier.
The KTA as originally proposed by Nello Cristianini is not properly arranged for unbalanced datasets. Thus, the NegativeBKTA (balanced kernel target alignment) class implements an invariant version, which is preferable for unbalanced datasets.
KTA measures the similarity, in terms of the inner product, of the kernel Gram matrix K with a perfect Gram matrix D with entries 1 or -1 for examples of coinciding or different label, respectively. Then the kernel target alignment is given by
We generalize the measure by using the value -1/(N-1) for entries corresponding to different classes, which gives a canonical and symmetric generalization. Here, N denotes the number of classes.
Examples:
KernelOptimization.cpp.
Definition at line 86 of file KTA.h.
Constructor & Destructor Documentation
NegativeKTA::NegativeKTA (unsigned int numberOfClasses = 2)
Constructor.
Definition at line 42 of file KTA.cpp.
References m_2offdiag, m_2offdiag2, m_numberOfClasses, m_offdiag, and m_offdiag2.
NegativeKTA::~NegativeKTA ()
Destructor.
Definition at line 51 of file KTA.cpp.
Member Function Documentation
double NegativeKTA::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computes the negative Kernel Target Alignment between the target and the kernel function output on the input.
Implements ErrorFunction.
Definition at line 56 of file KTA.cpp.
References JointKernelFunction::eval(), KernelFunction::eval(), i, m_2offdiag, and m_2offdiag2.
double NegativeKTA::errorDerivative (Model & model, const Array< double > & input, const Array< double > & target, Array< double > & derivative) [virtual]
Computes the negative Kernel Target Alignment between the target and the kernel function output on the input.
The partial derivatives of the negative KTA w.r.t. the model parameters are returned in the derivative parameter.
Reimplemented from ErrorFunction.
Definition at line 125 of file KTA.cpp.
References JointKernelFunction::evalDerivative(), KernelFunction::evalDerivative(), Model::getParameterDimension(), i, m_2offdiag, and m_2offdiag2.
Member Data Documentation
double NegativeKTA::m_2offdiag [protected]
Definition at line 110 of file KTA.h.
Referenced by error(), errorDerivative(), and NegativeKTA().
double NegativeKTA::m_2offdiag2 [protected]
Definition at line 111 of file KTA.h.
Referenced by error(), errorDerivative(), and NegativeKTA().
unsigned int NegativeKTA::m_numberOfClasses [protected]
Definition at line 107 of file KTA.h.
Referenced by NegativeKTA().
double NegativeKTA::m_offdiag [protected]
Definition at line 108 of file KTA.h.
Referenced by NegativeKTA().
double NegativeKTA::m_offdiag2 [protected]
Definition at line 109 of file KTA.h.
Referenced by NegativeKTA().
The documentation for this class was generated from the following files:
KTA.h
KTA.cpp