ReClaM: OCCMcSVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
OCCMcSVM Class Reference
Meta Model for SVM training.
#include <Svm.h>
Public Member Functions
OCCMcSVM (MultiClassSVM *pSVM, double C)
Constructor.
~OCCMcSVM ()
Destructor.
double get_C ()
void set_C (double C)
bool isFeasible ()
ensure C is positive
Detailed Description
Meta Model for SVM training.
Author:
T. Glasmachers
Date:
2008
Multi-Class SVM training at the cost of a binary classification machine.
S. Szedmak, S. Shawe-Taylor, E. Parado-Hernandez, "Learning via Linear Operators: Maximum Margin Regression; Multiclass and Multiview Learning at One-class Complexity", Technical report, PASCAL, Southampton, UK (2006)
Examples:
McSvm.cpp.
Definition at line 1142 of file Svm.h.
Constructor & Destructor Documentation
OCCMcSVM::OCCMcSVM (MultiClassSVM * pSVM, double C)
Constructor.
Definition at line 1701 of file Svm.cpp.
References Model::parameter.
OCCMcSVM::~OCCMcSVM ()
Destructor.
Definition at line 1707 of file Svm.cpp.
Member Function Documentation
double OCCMcSVM::get_C () [inline]
Definition at line 1152 of file Svm.h.
References Model::parameter.
Referenced by SVM_Optimizer::init().
bool OCCMcSVM::isFeasible () [virtual]
ensure C is positive
Reimplemented from MetaSVM.
Definition at line 1712 of file Svm.cpp.
References MetaSVM::isFeasible(), and Model::parameter.
void OCCMcSVM::set_C (double C) [inline]
Definition at line 1153 of file Svm.h.
References MetaSVM::setParameter().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp