ReClaM: Model Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Model Class Reference
Base class of all models.
#include <Model.h>
Public Member Functions
Model ()
Constructor.
virtual ~Model ()
Destructor.
virtual void model (const Array< double > &input, Array< double > &output)=0
Returns the model's answer #output on the stimulus #input.
void model (const Array< double > &input, Array< double > &output) const
Do a model evaluation on a const object.
virtual void modelDerivative (const Array< double > &input, Array< double > &derivative)
Calculates the derivative of the model output with respect to the parameters.
void modelDerivative (const Array< double > &input, Array< double > &derivative) const
Compute the model derivative on a const object.
virtual void modelDerivative (const Array< double > &input, Array< double > &output, Array< double > &derivative)
Calculates the model output and the derivative of the model output with respect to the parameters.
void modelDerivative (const Array< double > &input, Array< double > &output, Array< double > &derivative) const
Compute the model derivative on a const object.
virtual void generalDerivative (const Array< double > &input, const Array< double > &coefficient, Array< double > &derivative)
Calculates the model's general derivative.
void generalDerivative (const Array< double > &input, const Array< double > &coefficient, Array< double > &derivative) const
general derivative for a const object
virtual bool isFeasible ()
check whether the parameters define a feasible model
bool isFeasible () const
check whether the parameters define a feasible model on a const object
const unsigned int getInputDimension () const
Returns the dimension of the model input.
const unsigned int getOutputDimension () const
Returns the dimension of the model output.
const unsigned int getParameterDimension () const
Returns the number of optimizable model parameters, i.e.
virtual double getParameter (unsigned int index) const
Returns a specific model parameter.
virtual void setParameter (unsigned int index, double value)
Modifies a specific model parameter.
void setEpsilon (double eps)
Sets the value of epsilon.
Model * Clone ()
Copy the model.
virtual void read (std::istream &is)
Read the model parameters from a stream.
virtual void write (std::ostream &os) const
Write the model parameters to a stream.
bool load (const char *filename)
Read the model parameters from a file.
bool save (const char *filename)
Write the model parameters to a file.
Protected Member Functions
virtual Model * CloneI ()
Clone the class of the model.
Protected Attributes
Array< double > parameter
Model parameter vector.
unsigned int inputDimension
Dimension of the data accepted by the model as input.
unsigned int outputDimension
Dimension of the model output per single input pattern.
double epsilon
Precision parameter for the numerical error gradient approximation.
Friends
std::istream & operator>> (std::istream &is, Model &model)
Read the model parameters from a stream.
std::ostream & operator<< (std::ostream &os, const Model &model)
Write the model parameters to a stream.
Detailed Description
Base class of all models.
ReClaM provides the three base classes Model, ErrorFunction and Optimizer which make up the ReClaM framework for solving regression and classification tasks. This design overrides the ModelInterface design which is kept for backwards compatibility.
The Model class encapsulates a data processing trainable model. Its internal state is described by an array of parameters.
A model can be thought of as a parameterized family of mappings
where n and m are the input and output dimensions, respectively. The important special case m=1 is not treated separatly, that is, the trivial output coordinate of 0 has to be supplied for all array operations.
Models can be operated in two modes:
The model is presented a single input pattern, that is, a one dimensional #input array. It produces one output pattern, that is, a one dimensional #output array.
The model is presented a set of input patterns (batch mode), that is, a two dimensional #input array. The first index corresponds to the pattern index, such that #input[i] is the i-th input pattern. The model's answer is a two dimensional output array where again the first index corresponds the pattern index, that is, #output[i] is the answer of the model to the input pattern #input[i].
For gradient based optimization the derivative of the model output with respect to the parameters has to be computed. For the derivative, two rules apply: First, the derivative can only be computed for a single input pattern, that is, not for a batch of patterns. Second, the derivative has the same dimension as the output plus one dimension for the parameters. The parameter dimension always comes last. Thus, the #derivative array is two dimensional. The first dimension represents the model output dimension. The second dimension is indexed by the model parameters. If the derivative of a whole batch of input patterns is needed (as it is usually the case for error derivative computations), the derivative has to be computes sequentially for each input pattern at a time.
When deriving a sub class from Model, the following has to be considered:
The model(...) member must be overloaded to compute the model's predictions. For differentiable models, the modelDerivative members should be overloaded, too.
The members inputDimension and outputDimension must be set in the constructor. Further, the parameter vector has to be resized accordingly.
If the model uses an internal parameter representation which differs from the parameter vector, setParameter(...) should be overloaded in order to keep the parameter values consistent with the parameter member.
Examples:
KernelOptimization.cpp.
Definition at line 128 of file Model.h.
Constructor & Destructor Documentation
Model::Model ()
Constructor.
Definition at line 46 of file Model.cpp.
References epsilon.
Model::~Model () [virtual]
Destructor.
Definition at line 51 of file Model.cpp.
Member Function Documentation
Model* Model::Clone () [inline]
Copy the model.
The Clone method first calls the virtual CloneI() method and then copies its parameters to the new model. Per definition, this is sufficient to obtain a copy of the model. The method may return NULL if the type of model does not support cloning.
Author:
T. Glasmachers
Date:
2008
Definition at line 395 of file Model.h.
References CloneI(), getParameter(), getParameterDimension(), and setParameter().
virtual Model* Model::CloneI () [inline, protected, virtual]
Clone the class of the model.
This method returns a new object of the same type like the current model. In most cases it is sufficient to return new MyModel(). However, complex models may manage additional information beyond their parameter vector. These information must be copied by CloneI in order to make Clone work correctly. If cloning fails, the method is required to return a NULL pointer.
Author:
T. Glasmachers
Date:
2008
Definition at line 420 of file Model.h.
Referenced by Clone().
void Model::generalDerivative (const Array< double > & input, const Array< double > & coefficient, Array< double > & derivative) [virtual]
Calculates the model's general derivative.
After a call of model, generalDerivative calculates the gradient and stores it in derivative. Here is some input pattern, and denotes the parameter vector of the model and its th component. The index indicates the th output. The coefficients can be chosen freely.
The point of this function is that for many models, the complexity of calculating this linear combination of gradients is the same as of calculating a single output gradient
Via the chain rule, the gradient of _any_ (e.g., error) functional can be calculated.
Example 1: Let , then
is the parameter gradient of an MSE with respect to target values As above, the index runs over the outputs.
Example 2: Let , then the gradients of only the th output will be calculated:
and
The default implementation is the computationally inefficient usage of modelDerivative.
Parameters:
input the corefficients in the formula above.
coefficient the corefficients in the formula above.
derivative the calculated model's general derivative.
Returns:
None.
Author:
M. Toussaint, C. Igel
Date:
2002
Reimplemented in FFNet.
Definition at line 88 of file Model.cpp.
References getOutputDimension(), getParameterDimension(), and modelDerivative().
Referenced by DF_MeanSquaredError::errorDerivative(), DF_CrossEntropyIndependent::errorDerivative(), DF_CrossEntropy::errorDerivative(), and generalDerivative().
void Model::generalDerivative (const Array< double > & input, const Array< double > & coefficient, Array< double > & derivative) const [inline]
general derivative for a const object
Definition at line 299 of file Model.h.
References generalDerivative().
const unsigned int Model::getInputDimension () const [inline]
Returns the dimension of the model input.
Definition at line 330 of file Model.h.
References inputDimension.
Referenced by ComponentWiseModel::ComponentWiseModel(), ExpNorm::ExpNorm(), PCA::init(), FisherLDA::init(), LinNorm::LinNorm(), ComponentWiseModel::model(), FFNet::operator=(), PCA::optimize(), LinearRegression::optimize(), LDA::optimize(), and FisherLDA::optimize().
const unsigned int Model::getOutputDimension () const [inline]
Returns the dimension of the model output.
Definition at line 336 of file Model.h.
References outputDimension.
Referenced by ComponentWiseModel::ComponentWiseModel(), ErrorPercentage::error(), DF_CrossEntropyIndependent::error(), DF_CrossEntropy::error(), CrossEntropyIndependent::error(), CrossEntropy::error(), DF_CrossEntropyIndependent::errorDerivative(), DF_CrossEntropy::errorDerivative(), CrossEntropyIndependent::errorDerivative(), CrossEntropy::errorDerivative(), ExpNorm::ExpNorm(), generalDerivative(), PCA::init(), FisherLDA::init(), LinNorm::LinNorm(), FisherLDA::MeanAndScatter(), ComponentWiseModel::model(), FFNet::operator=(), PCA::optimize(), LinearRegression::optimize(), and FisherLDA::optimize().
double Model::getParameter (unsigned int index) const [virtual]
Returns a specific model parameter.
Examples:
CrossValidation.cpp, and KernelOptimization.cpp.
Definition at line 114 of file Model.cpp.
References parameter.
Referenced by SvmApproximation::addVecRprop(), McSvmApproximation::addVecRprop(), BFGS::bfgs(), Clone(), ComponentWiseModel::ComponentWiseModel(), CVModel::CVModel(), SpanBoundA::error(), NoisySvmLikelihood::error(), MSERBFNet::error(), LinearEquation::error(), GaussianProcessVariance::error(), SvmApproximationErrorFunctionGlobal::errorDerivative(), SvmApproximationErrorFunction::errorDerivative(), SpanBoundA::errorDerivative(), NoisySvmLikelihood::errorDerivative(), MSERBFNet::errorDerivative(), McSvmApproximationErrorFunction::errorDerivative(), LinearEquation::errorDerivative(), ErrorFunction::errorDerivative(), KernelFunction::evalDerivative(), ExpNorm::ExpNorm(), SparseRBFKernel::getSigma(), RBFKernel::getSigma(), SvmApproximation::gradientDescent(), GridSearch::init(), CMAOptimizer::init(), BFGS::initBfgs(), JointKernelFunction::JointKernelFunction(), KernelMeanClassifier::KernelMeanClassifier(), KernelNearestNeighbor::KernelNearestNeighbor(), LinNorm::LinNorm(), McSvmApproximation::McSvmApproximation(), modelDerivative(), NormalizedKernel::NormalizedKernel(), SVM_Optimizer::optimize(), SteepestDescent::optimize(), IRpropMinus::optimize(), IRpropPlus::optimize(), RpropMinus::optimize(), RpropPlus::optimize(), QuickpropOriginal::optimize(), Quickprop::optimize(), Perceptron::optimize(), NoisyRprop::optimize(), PointSearch::optimize(), NestedGridSearch::optimize(), GridSearch::optimize(), CG::optimize(), AdpBP90b::optimize(), AdpBP90a::optimize(), AllInOneMcSVM::PrepareDerivative(), and SvmApproximation::SvmApproximation().
const unsigned int Model::getParameterDimension () const [inline]
Returns the number of optimizable model parameters, i.e.
the dimension of the parameter array.
Definition at line 343 of file Model.h.
References parameter.
Referenced by Clone(), ComponentWiseModel::ComponentWiseModel(), GeneralGaussKernel::computeGamma(), DiagGaussKernel::computeGamma(), CVModel::CVModel(), GaussianProcessEvidence::dEvidenceDTheta(), MSERBFNet::error(), SquaredError::errorDerivative(), SpanBoundA::errorDerivative(), SpanBound1::errorDerivative(), RadiusMargin::errorDerivative(), NegativePolarization::errorDerivative(), NegativeLogLikelihood::errorDerivative(), MSERBFNet::errorDerivative(), MSEFFNet::errorDerivative(), MeanSquaredError::errorDerivative(), LMSEFFNet::errorDerivative(), NegativeBKTA::errorDerivative(), NegativeKTA::errorDerivative(), InverseClassSeparability::errorDerivative(), ErrorFunction::errorDerivative(), DF_MeanSquaredError::errorDerivative(), DF_CrossEntropy::errorDerivative(), CVError::errorDerivative(), CrossEntropyIndependent::errorDerivative(), CrossEntropy::errorDerivative(), GeneralGaussKernel::eval(), JointKernelFunction::evalDerivative(), WeightedSumKernel2::evalDerivative(), WeightedSumKernel::evalDerivative(), NormalizedKernel::evalDerivative(), KernelFunction::evalDerivative(), GeneralGaussKernel::evalDerivative(), ExpNorm::ExpNorm(), generalDerivative(), GeneralGaussKernel::getTransformation(), CMAOptimizer::Ind2Model(), SteepestDescent::init(), NestedGridSearch::init(), GridSearch::init(), CMAOptimizer::init(), CG::init(), BFGS::initBfgs(), IRpropMinus::initUserDefined(), IRpropPlus::initUserDefined(), RpropMinus::initUserDefined(), RpropPlus::initUserDefined(), QuickpropOriginal::initUserDefined(), Quickprop::initUserDefined(), NoisyRprop::initUserDefined(), AdpBP90b::initUserDefined(), AdpBP90a::initUserDefined(), JointKernelFunction::JointKernelFunction(), KernelMeanClassifier::KernelMeanClassifier(), KernelNearestNeighbor::KernelNearestNeighbor(), LinNorm::LinNorm(), MetaSVM::MetaSVM(), ComponentWiseModel::model(), AllInOneMcSVM::modelDerivative(), C_SVM::modelDerivative(), LinNorm::modelDerivative(), ExpNorm::modelDerivative(), AffineLinearMap::modelDerivative(), LinearMap::modelDerivative(), ComponentWiseModel::modelDerivative(), CMACMap::modelDerivative(), NormalizedKernel::NormalizedKernel(), SteepestDescent::optimize(), IRpropMinus::optimize(), IRpropPlus::optimize(), RpropMinus::optimize(), RpropPlus::optimize(), QuickpropOriginal::optimize(), Quickprop::optimize(), NoisyRprop::optimize(), PointSearch::optimize(), NestedGridSearch::optimize(), CMAOptimizer::optimize(), AdpBP90b::optimize(), AdpBP90a::optimize(), AllInOneMcSVM::PrepareDerivative(), C_SVM::PrepareDerivative(), and JointKernelFunction::setParameter().
bool Model::isFeasible () [virtual]
check whether the parameters define a feasible model
The default implementation returns true, that is, every parameter configuration is considered feasible and unconstrained optimization is applicable. It is the Optimizer's responsibility to check the isFeasible() flag.
Returns:
true if the model is feasible, false otherwise
Author:
T. Glasmachers
Date:
2006
Reimplemented in ComponentWiseModel, CVModel, GaussianProcess, PolynomialKernel, RBFKernel, SparseRBFKernel, NormalizedKernel, WeightedSumKernel, WeightedSumKernel2, SimpleSigmoidModel, MetaSVM, C_SVM, Epsilon_SVM, OneClassSVM, RegularizationNetwork, AllInOneMcSVM, CrammerSingerMcSVM, LLWMcSVM, DGIMcSVM, OVAMcSVM, OCCMcSVM, and EpochBasedCsMcSvm.
Definition at line 109 of file Model.cpp.
Referenced by GridSearch::init(), isFeasible(), NormalizedKernel::isFeasible(), CVModel::isFeasible(), ComponentWiseModel::isFeasible(), IRpropMinus::optimize(), IRpropPlus::optimize(), RpropMinus::optimize(), RpropPlus::optimize(), NoisyRprop::optimize(), PointSearch::optimize(), NestedGridSearch::optimize(), GridSearch::optimize(), and CMAOptimizer::optimize().
bool Model::isFeasible () const [inline]
check whether the parameters define a feasible model on a const object
Definition at line 323 of file Model.h.
References isFeasible().
bool Model::load (const char * filename)
Read the model parameters from a file.
Author:
T. Glasmachers
Date:
2006
Definition at line 163 of file Model.cpp.
References read().
void Model::model (const Array< double > & input, Array< double > & output) const [inline]
Do a model evaluation on a const object.
Definition at line 159 of file Model.h.
References model().
virtual void Model::model (const Array< double > & input, Array< double > & output) [pure virtual]
Returns the model's answer #output on the stimulus #input.
This method calculates the output of the model depending on the #input. The arrays #input and #output can either be one- or two-dimensional, depending on whether one or many patterns should be processed. The number of elements in the last dimension of these arrays must fit the inputDimension and outputDimension, in case of two-dimensional input, the number of elements in the first dimension equals the number of patterns. The method is pure virtual as it has to be implemented by the different models.
Parameters:
input Vector of input values.
output Vector of output values.
Returns:
None.
Implemented in CMACMap, ComponentWiseModel, CVModel, FFNet, KalmanFilter, KernelFunction, JointKernelFunction, KernelMeanClassifier, KernelNearestNeighbor, KernelNearestNeighborRegression, LinearEquation, LinearMap, AffineLinearMap, LinearClassifier, McSvmApproximationModel, MSERNNet, ExpNorm, LinNorm, Paraboloid, RBFNet, SigmoidModel, SimpleSigmoidModel, Softmax, SVM, MultiClassSVM, MetaSVM, and SvmApproximationModel.
Referenced by WTA::error(), SquaredError::error(), NegativeLogLikelihood::error(), MSEFFNet::error(), MeanSquaredError::error(), LMSEFFNet::error(), ErrorPercentage::error(), DF_MeanSquaredError::error(), DF_CrossEntropyIndependent::error(), DF_CrossEntropy::error(), CrossEntropy::error(), ZeroOneLoss::error(), BalancedClassificationError::error(), ClassificationError::error(), BinaryCriterion::error(), DF_MeanSquaredError::errorDerivative(), DF_CrossEntropyIndependent::errorDerivative(), DF_CrossEntropy::errorDerivative(), LinNorm::model(), ExpNorm::model(), model(), ComponentWiseModel::model(), LinNorm::modelDerivative(), modelDerivative(), and ROC::ROC().
void Model::modelDerivative (const Array< double > & input, Array< double > & derivative) const [inline]
Compute the model derivative on a const object.
Definition at line 194 of file Model.h.
References modelDerivative().
void Model::modelDerivative (const Array< double > & input, Array< double > & output, Array< double > & derivative) [virtual]
Calculates the model output and the derivative of the model output with respect to the parameters.
This method performs the calculation of the model output with respect to the model parameters. Sometimes this calculation can only be performed based on a single input pattern; therefore #input must be a onedimensional array. As a default implementation, the derivatives are estimated numerically by using small variations epsilon:
However, to improve the speed, it is adviserable to overload this method by a more sophisticated calculation, depending on the method model. Nevertheless, this default implementation can be used to check new implementations of the derivative of the model with respect to the parameters.
Parameters:
input Vector of input values.
output Vector of model output.
derivative Matrix of partial derivatives.
Reimplemented in ComponentWiseModel, CVModel, FFNet, KernelFunction, MSEFFNet, RBFNet, SigmoidModel, SimpleSigmoidModel, Softmax, and SVM.
Definition at line 82 of file Model.cpp.
References model(), and modelDerivative().
void Model::modelDerivative (const Array< double > & input, Array< double > & output, Array< double > & derivative) const [inline]
Compute the model derivative on a const object.
Definition at line 230 of file Model.h.
References modelDerivative().
void Model::modelDerivative (const Array< double > & input, Array< double > & derivative) [virtual]
Calculates the derivative of the model output with respect to the parameters.
This method performs the calculation of the model output with respect to the model parameters. Sometimes this calculation can only be performed based on a single input pattern; therefore #input must be a onedimensional array. As a default implementation, the derivatives are estimated numerically by using small variations epsilon:
However, to improve the speed, it is adviserable to overload this method by a more sophisticated calculation, depending on the method model. Nevertheless, this default implementation can be used to check new implementations of the derivative of the model with respect to the parameters.
Parameters:
input Vector of input values.
derivative Matrix of partial derivatives.
Reimplemented in CMACMap, ComponentWiseModel, CVModel, FFNet, KernelFunction, LinearMap, AffineLinearMap, MSEFFNet, ExpNorm, LinNorm, Paraboloid, RBFNet, SigmoidModel, SimpleSigmoidModel, Softmax, SVM, C_SVM, and AllInOneMcSVM.
Definition at line 56 of file Model.cpp.
References epsilon, getParameter(), model(), parameter, and setParameter().
Referenced by SquaredError::errorDerivative(), NegativeLogLikelihood::errorDerivative(), MeanSquaredError::errorDerivative(), CrossEntropyIndependent::errorDerivative(), CrossEntropy::errorDerivative(), VarianceEstimator::estimateFisherInformation(), VarianceEstimator::estimateInvFisher(), VarianceEstimator::estimateVariance(), VarianceEstimator::estimateVarianceChange(), generalDerivative(), LinNorm::modelDerivative(), ExpNorm::modelDerivative(), modelDerivative(), and VarianceEstimator::overallVariance().
void Model::read (std::istream & is) [virtual]
Read the model parameters from a stream.
The model parameters are read from a text stream. The single numbers are separated with a single space character. The line break CR/LF is used as an end marker. The setParameter member is used to set the parameter values in order to support models that override the parameter manegement. This virtual method is called by the stream operator.
Author:
C. Igel
Date:
2009
Reimplemented in FFNet, and RBFNet.
Definition at line 124 of file Model.cpp.
References parameter, and setParameter().
Referenced by load(), and operator>>().
bool Model::save (const char * filename)
Write the model parameters to a file.
Author:
T. Glasmachers
Date:
2006
Definition at line 173 of file Model.cpp.
References write().
void Model::setEpsilon (double eps) [inline]
Sets the value of epsilon.
The value of epsilon is utilized for a numeric estimation of the derivative of the error, with respect to the model parameters. epsilon should be choosen as a small value. The default value is epsilon = 1e-8.
Parameters:
epsilon New value for epsilon.
Returns:
None.
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 377 of file Model.h.
References epsilon.
void Model::setParameter (unsigned int index, double value) [virtual]
Modifies a specific model parameter.
Reimplemented in CVModel, PolynomialKernel, NormalizedKernel, WeightedSumKernel, WeightedSumKernel2, JointKernelFunction, KernelMeanClassifier, KernelNearestNeighbor, LinearClassifier, ExpNorm, LinNorm, RBFNet, MetaSVM, C_SVM, Epsilon_SVM, and OneClassSVM.
Definition at line 119 of file Model.cpp.
References parameter.
Referenced by BFGS::bfgs(), Clone(), NoisySvmLikelihood::error(), NoisySvmLikelihood::errorDerivative(), ErrorFunction::errorDerivative(), SVM::ImportLibsvmModel(), CMAOptimizer::Ind2Model(), NestedGridSearch::init(), BFGS::initBfgs(), ComponentWiseModel::model(), modelDerivative(), ComponentWiseModel::modelDerivative(), SVM_Optimizer::optimize(), SteepestDescent::optimize(), SigmoidFit::optimize(), IRpropMinus::optimize(), IRpropPlus::optimize(), RpropMinus::optimize(), RpropPlus::optimize(), QuickpropOriginal::optimize(), Quickprop::optimize(), Perceptron::optimize(), PCA::optimize(), NoisyRprop::optimize(), LinearRegression::optimize(), LDA::optimize(), PointSearch::optimize(), NestedGridSearch::optimize(), GridSearch::optimize(), FisherLDA::optimize(), CMAOptimizer::optimize(), CG::optimize(), AdpBP90b::optimize(), AdpBP90a::optimize(), read(), MetaSVM::setParameter(), LinNorm::setParameter(), ExpNorm::setParameter(), KernelNearestNeighbor::setParameter(), KernelMeanClassifier::setParameter(), JointKernelFunction::setParameter(), NormalizedKernel::setParameter(), NormalizedRBFKernel::setSigma(), SparseRBFKernel::setSigma(), RBFKernel::setSigma(), and GaussianProcess::train().
void Model::write (std::ostream & os) const [virtual]
Write the model parameters to a stream.
The model parameters are written to a text stream. The single numbers are separated with a single space character. The line break CR/LF is used as an end marker. This virtual method is called by the stream operator.
Author:
C. Igel
Date:
2009
Reimplemented in FFNet, and RBFNet.
Definition at line 149 of file Model.cpp.
References parameter.
Referenced by operator<<(), and save().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Model & model) [friend]
Write the model parameters to a stream.
The model parameters are written to a text stream. The single numbers are separated with a single space character. The line break CR/LF is used as an end marker.
Author:
T. Glasmachers
Date:
2006
Definition at line 192 of file Model.cpp.
std::istream& operator>> (std::istream & is, Model & model) [friend]
Read the model parameters from a stream.
The model parameters are read from a text stream. The single numbers are separated with a single space character. The line break CR/LF is used as an end marker. The setParameter member is used to set the parameter values in order to support models that override the parameter manegement.
Author:
T. Glasmachers
Date:
2006
Definition at line 185 of file Model.cpp.
Member Data Documentation
double Model::epsilon [protected]
Precision parameter for the numerical error gradient approximation.
Reimplemented in Epsilon_SVM.
Definition at line 439 of file Model.h.
Referenced by KernelFunction::evalDerivative(), ExpNorm::ExpNorm(), LinNorm::LinNorm(), Model(), modelDerivative(), and setEpsilon().
unsigned int Model::inputDimension [protected]
Dimension of the data accepted by the model as input.
Definition at line 433 of file Model.h.
Referenced by FFNet::activate(), AffineLinearMap::AffineLinearMap(), CMACMap::CMACMap(), ComponentWiseModel::ComponentWiseModel(), LMSEFFNet::errorDerivative(), ExpNorm::ExpNorm(), MultiClassSVM::getDimension(), SVM::getDimension(), getInputDimension(), SVM::ImportLibsvmModel(), SVM::ImportSvmlightModel(), CMACMap::init(), KernelNearestNeighborRegression::KernelNearestNeighborRegression(), LinearClassifier::LinearClassifier(), LinearMap::LinearMap(), LinNorm::LinNorm(), Softmax::model(), LinearClassifier::model(), AffineLinearMap::model(), LinearMap::model(), KernelNearestNeighborRegression::model(), Softmax::modelDerivative(), AffineLinearMap::modelDerivative(), LinearMap::modelDerivative(), FFNet::operator=(), RBFNet::RBFNet(), LinearClassifier::setParameter(), KernelNearestNeighbor::SetPoints(), KernelMeanClassifier::SetPoints(), SigmoidModel::SigmoidModel(), SimpleSigmoidModel::SimpleSigmoidModel(), and Softmax::Softmax().
unsigned int Model::outputDimension [protected]
Dimension of the model output per single input pattern.
Definition at line 436 of file Model.h.
Referenced by AffineLinearMap::AffineLinearMap(), CMACMap::CMACMap(), ComponentWiseModel::ComponentWiseModel(), MSERBFNet::error(), MSERBFNet::errorDerivative(), ExpNorm::ExpNorm(), getOutputDimension(), KernelNearestNeighborRegression::KernelNearestNeighborRegression(), LinearClassifier::LinearClassifier(), LinearMap::LinearMap(), LinNorm::LinNorm(), LinNorm::model(), ExpNorm::model(), AffineLinearMap::model(), LinearMap::model(), KernelNearestNeighborRegression::model(), CMACMap::model(), LinNorm::modelDerivative(), ExpNorm::modelDerivative(), AffineLinearMap::modelDerivative(), LinearMap::modelDerivative(), CMACMap::modelDerivative(), FFNet::operator=(), RBFNet::RBFNet(), KernelNearestNeighbor::SetPoints(), KernelMeanClassifier::SetPoints(), SigmoidModel::SigmoidModel(), SimpleSigmoidModel::SimpleSigmoidModel(), and Softmax::Softmax().
Array<double> Model::parameter [protected]
Model parameter vector.
parameter is a 1-dimensional array with the number of elements equal to the number of free parameters of the model (i.e., equal to the number of weights of a neural network).
Definition at line 430 of file Model.h.
Referenced by AffineLinearMap::AffineLinearMap(), CMACMap::CMACMap(), ComponentWiseModel::ComponentWiseModel(), GeneralGaussKernel::computeGamma(), DiagGaussKernel::computeGamma(), CVModel::CVModel(), DiagGaussKernel::DiagGaussKernel(), Paraboloid::error(), Paraboloid::errorDerivative(), PrototypeKernel::eval(), NormalizedRBFKernel::eval(), SparseRBFKernel::eval(), RBFKernel::eval(), PolynomialKernel::eval(), GeneralGaussKernel::eval(), DiagGaussKernel::eval(), PrototypeKernel::evalDerivative(), NormalizedRBFKernel::evalDerivative(), SparseRBFKernel::evalDerivative(), RBFKernel::evalDerivative(), GeneralGaussKernel::evalDerivative(), DiagGaussKernel::evalDerivative(), ExpNorm::ExpNorm(), GeneralGaussKernel::GeneralGaussKernel(), SigmoidModel::get_A(), SigmoidModel::get_B(), EpochBasedCsMcSvm::get_C(), OCCMcSVM::get_C(), OVAMcSVM::get_C(), DGIMcSVM::get_C(), LLWMcSVM::get_C(), CrammerSingerMcSVM::get_C(), AllInOneMcSVM::get_C(), RegularizationNetwork::get_gamma(), SimpleSigmoidModel::get_s(), KalmanFilter::get_x_p(), MultiClassSVM::getAlpha(), SVM::getAlpha(), MultiClassSVM::getOffset(), SVM::getOffset(), getParameter(), getParameterDimension(), PrototypeKernel::getPrototype(), LinearEquation::getSolution(), GeneralGaussKernel::getTransformation(), SVM::ImportLibsvmModel(), SVM::ImportSvmlightModel(), Paraboloid::init(), RBFNet::initRBFNet(), EpochBasedCsMcSvm::isFeasible(), OCCMcSVM::isFeasible(), OVAMcSVM::isFeasible(), DGIMcSVM::isFeasible(), LLWMcSVM::isFeasible(), CrammerSingerMcSVM::isFeasible(), AllInOneMcSVM::isFeasible(), RegularizationNetwork::isFeasible(), SimpleSigmoidModel::isFeasible(), SparseRBFKernel::isFeasible(), RBFKernel::isFeasible(), PolynomialKernel::isFeasible(), GaussianProcess::isFeasible(), JointKernelFunction::JointKernelFunction(), KernelMeanClassifier::KernelMeanClassifier(), KernelNearestNeighbor::KernelNearestNeighbor(), LinearClassifier::LinearClassifier(), LinearEquation::LinearEquation(), LinearKernel::LinearKernel(), LinearMap::LinearMap(), LinNorm::LinNorm(), McSvmApproximationModel::McSvmApproximationModel(), Softmax::model(), SimpleSigmoidModel::model(), SigmoidModel::model(), RBFNet::model(), AffineLinearMap::model(), LinearMap::model(), KalmanFilter::model(), ComponentWiseModel::model(), CMACMap::model(), Softmax::modelDerivative(), SimpleSigmoidModel::modelDerivative(), SigmoidModel::modelDerivative(), RBFNet::modelDerivative(), modelDerivative(), ComponentWiseModel::modelDerivative(), NormalizedKernel::NormalizedKernel(), NormalizedRBFKernel::NormalizedRBFKernel(), OCCMcSVM::OCCMcSVM(), FFNet::operator=(), OVAMcSVM::OVAMcSVM(), Paraboloid::Paraboloid(), PolynomialKernel::PolynomialKernel(), KalmanFilter::predict(), PrototypeKernel::PrototypeKernel(), RBFKernel::RBFKernel(), RBFNet::RBFNet(), read(), RegularizationNetwork::RegularizationNetwork(), MultiClassSVM::setAlpha(), RBFNet::setBias(), RBFNet::setCenter(), RBFNet::setParameter(), LinNorm::setParameter(), ExpNorm::setParameter(), setParameter(), KernelNearestNeighbor::setParameter(), KernelMeanClassifier::setParameter(), WeightedSumKernel2::setParameter(), WeightedSumKernel::setParameter(), NormalizedKernel::setParameter(), PolynomialKernel::setParameter(), PrototypeKernel::setPrototype(), KalmanFilter::setStateVector(), RBFNet::setVariance(), RBFNet::setWeights(), SigmoidModel::SigmoidModel(), SimpleSigmoidModel::SimpleSigmoidModel(), Softmax::Softmax(), SparseLinearKernel::SparseLinearKernel(), SparseRBFKernel::SparseRBFKernel(), SvmApproximationModel::SvmApproximationModel(), GaussianProcess::train(), KalmanFilter::updateEstimate(), WeightedSumKernel::WeightedSumKernel(), WeightedSumKernel2::WeightedSumKernel2(), and write().
The documentation for this class was generated from the following files:
Model.h
Model.cpp