ReClaM: ROC Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ROC Class Reference
ROC-Curve - false negatives over false positives.
#include <ROC.h>
Public Member Functions
ROC (Model &model, const Array< double > &input, const Array< double > &target)
Constructor.
double Threshold (double falseAcceptanceRate)
Compute the threshold for given false acceptance rate, that is, for a given false positive rate.
double Value (double falseAcceptanceRate)
Value of the ROC curve for given false acceptance rate, that is, for a given false positive rate.
double EqualErrorRate ()
Computes the equal error rate of the classifier.
Protected Attributes
std::vector< double > score_positive
scores of the positive examples
std::vector< double > score_negative
scores of the negative examples
Detailed Description
ROC-Curve - false negatives over false positives.
This class provides the ROC curve of a classifier. All time consuming computations are done in the constructor, such that afterwards fast access to specific values of the curve and the equal error rate is possible.
The ROC class assumes a one dimensional target array and a model producing one dimensional output data. The targets must be the labels +1 and -1 of a binary classification task. The model output is assumed not to be +1 and -1, but real valued instead. Classification in done by thresholding, where different false positive and false negative rates correspond to different thresholds. The ROC curve shows the trade off between the two error types.
Definition at line 71 of file ROC.h.
Constructor & Destructor Documentation
ROC::ROC (Model & model, const Array< double > & input, const Array< double > & target)
Constructor.
Parameters:
model model to use for prediction
input input data
target binary targets for the input data (+1 or -1)
Definition at line 48 of file ROC.cpp.
References Model::model(), score_negative, and score_positive.
Member Function Documentation
double ROC::EqualErrorRate ()
Computes the equal error rate of the classifier.
Definition at line 122 of file ROC.cpp.
References i, score_negative, and score_positive.
double ROC::Threshold (double falseAcceptanceRate)
Compute the threshold for given false acceptance rate, that is, for a given false positive rate.
This threshold, used for classification with the underlying model, results in the given false acceptance rate.
Definition at line 91 of file ROC.cpp.
References i, and score_negative.
Referenced by Value().
double ROC::Value (double falseAcceptanceRate)
Value of the ROC curve for given false acceptance rate, that is, for a given false positive rate.
Definition at line 104 of file ROC.cpp.
References i, score_positive, and Threshold().
Member Data Documentation
std::vector<double> ROC::score_negative [protected]
scores of the negative examples
Definition at line 99 of file ROC.h.
Referenced by EqualErrorRate(), ROC(), and Threshold().
std::vector<double> ROC::score_positive [protected]
scores of the positive examples
Definition at line 96 of file ROC.h.
Referenced by EqualErrorRate(), ROC(), and Value().
The documentation for this class was generated from the following files:
ROC.h
ROC.cpp