ReClaM: GaussianProcessVariance Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
GaussianProcessVariance Class Reference
variance of a Gaussian process
#include <GaussianProcess.h>
Public Member Functions
GaussianProcessVariance ()
Constructor.
~GaussianProcessVariance ()
Destructor.
double error (Model &model, const Array< double > &input, const Array< double > &target)
Computation of the Gaussian process variance.
Detailed Description
variance of a Gaussian process
The GaussianProcessVariance class is an ErrorFunction and can thus be used as an optimization target. Usually it will only be used for monitoring.
Definition at line 139 of file GaussianProcess.h.
Constructor & Destructor Documentation
GaussianProcessVariance::GaussianProcessVariance ()
Constructor.
Definition at line 155 of file GaussianProcess.cpp.
GaussianProcessVariance::~GaussianProcessVariance ()
Destructor.
Definition at line 158 of file GaussianProcess.cpp.
Member Function Documentation
double GaussianProcessVariance::error (Model & model, const Array< double > & input, const Array< double > & target) [virtual]
Computation of the Gaussian process variance.
Parameters:
model A GaussianProcess model must be provided, otherwise an exception will be thrown
Implements ErrorFunction.
Definition at line 162 of file GaussianProcess.cpp.
References GaussianProcess::getCInv(), SVM::getExamples(), SVM::getKernel(), Model::getParameter(), SVM::getPoints(), MetaSVM::getSVM(), and i.
Referenced by GaussianProcess::Variance().
The documentation for this class was generated from the following files:
GaussianProcess.h
GaussianProcess.cpp