ReClaM: SVM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
SVM Class Reference
Support Vector Machine (SVM) as a ReClaM Model.
#include <Svm.h>
Public Member Functions
SVM (KernelFunction *pKernel, bool bSignOutput=false)
Constructor.
SVM (KernelFunction *pKernel, const Array< double > &input, bool bSignOutput=false)
Constructor.
~SVM ()
Destructor.
void setSignOutput (bool bSignOutput=true)
Set the output mode to sign or real mode.
void SetTrainingData (const Array< double > &input, bool copy=false)
void model (const Array< double > &input, Array< double > &output)
compute the SVM prediction on data
double model (const Array< double > &input)
compute the SVM prediction on data
void modelDerivative (const Array< double > &input, Array< double > &derivative)
void modelDerivative (const Array< double > &input, Array< double > &output, Array< double > &derivative)
double getAlpha (int index)
double getOffset ()
KernelFunction * getKernel ()
return the kernel function object
const Array< double > & getPoints ()
return the training data points
unsigned int getExamples ()
return the number of training examples
unsigned int getDimension ()
return the input space dimension
void MakeSparse ()
Discard zero coefficients and corresponding training data.
bool LoadSVMModel (std::istream &is)
bool SaveSVMModel (std::ostream &os)
Static Public Member Functions
static SVM * ImportLibsvmModel (std::istream &is)
static SVM * ImportSvmlightModel (std::istream &is)
Static Protected Member Functions
static int ReadToken (std::istream &is, char *buffer, int maxlength, const char *separators)
Read a token from a stream.
static int DiscardUntil (std::istream &is, const char *separators)
Discard characters with stopping condition.
Protected Attributes
KernelFunction * kernel
kernel function
bool bOwnMemory
true if x and y are allocated by LoadModel
const Array< double > * x
training data points
bool signOutput
true if the SVM outputs the binary label only, false if the SVM outputs the value of the linear feature space function.
unsigned int examples
number of training data points x and labels #y
Friends
class SvmApproximation
Detailed Description
Support Vector Machine (SVM) as a ReClaM Model.
Author:
T. Glasmachers
Date:
2005
The SVM class provides a Support Vector Machine as a
parametric Model, that is, it computes a linear expansion of the kernel function with fixed training examples as one component. It can be viewed as a parametrized family of maps from the input space to the reals.
The parameter array of the SVM class defines the
affine linear solution in feature space, usually described as a vector and a real valued offset b. Note that different SVM training procedures impose constraints on the possible values these parameters are allowed to take.
In ReClaM, the SVM as a model is used for prediction
only. That is, it does not impose any training scheme and could in theory be training using any error measure and any optimizer. In practice, one wants to apply standard SVM training schemes to efficiently find the SVM solution. Therefore, the SVM should be trained with the special optimizer derived class C_SVM. This class implements the so-called C-SVM as a training scheme and uses a quadratic program solver to obtain the optimal solution. However, some other training schemes like basic regularization networks and gaussian process work on the same type of model. Therefore the SVM should be understood as an affine linear model in the kernel induced feature space, rather than being too closely connected to standard SVM training schemes.
Examples:
CrossValidation.cpp, KernelOptimization.cpp, SvmApproximationExample.cpp, SVMclassification-gnuplot.cpp, SVMclassification.cpp, SVMregression-gnuplot.cpp, and SVMregression.cpp.
Definition at line 91 of file Svm.h.
Constructor & Destructor Documentation
SVM::SVM (KernelFunction * pKernel, bool bSignOutput = false)
Constructor.
Parameters:
pKernel kernel function to use for training and prediction
bSignOutput true if the SVM should output binary labels, false if it should output real valued function evaluations
Definition at line 55 of file Svm.cpp.
SVM::SVM (KernelFunction * pKernel, const Array< double > & input, bool bSignOutput = false)
Constructor.
Parameters:
pKernel kernel function to use for training and prediction
input training data points
bSignOutput true if the SVM should output binary labels, false if it should output real valued function evaluations
Definition at line 71 of file Svm.cpp.
SVM::~SVM ()
Destructor.
Definition at line 86 of file Svm.cpp.
Member Function Documentation
int SVM::DiscardUntil (std::istream & is, const char * separators) [static, protected]
Discard characters with stopping condition.
The function reads characters from a stream until one of the terminating characters is found.
Parameters:
is stream to read from
separators termination characters
Returns:
A status code is returned:
terminating char
end of file --> 1001
unrecoverable error --> 1002
Definition at line 683 of file Svm.cpp.
double SVM::getAlpha (int index) [inline]
retrieve one of the coeffitients from the solution vector usually referred to as
Author:
T. Glasmachers
Date:
2006
Examples:
SVMclassification-gnuplot.cpp.
Definition at line 193 of file Svm.h.
References Model::parameter.
Referenced by SvmApproximation::createIndexListWithKMeans(), SvmApproximation::createIndexListWithStochasticUniversalSampling(), SvmApproximation::error(), SpanBound2::error(), SpanBound1::error(), SvmApproximationErrorFunctionGlobal::errorDerivative(), SvmApproximationErrorFunction::errorDerivative(), SpanBound1::errorDerivative(), C_SVM::modelDerivative(), and C_SVM::PrepareDerivative().
unsigned int SVM::getDimension () [inline]
return the input space dimension
Definition at line 229 of file Svm.h.
References Model::inputDimension.
Referenced by SvmApproximationErrorFunctionGlobal::errorDerivative(), and SvmApproximationErrorFunction::errorDerivative().
unsigned int SVM::getExamples () [inline]
return the number of training examples
Definition at line 223 of file Svm.h.
References examples.
Referenced by GaussianProcessEvidence::dEvidenceDTheta(), SpanBound1::error(), GaussianProcessVariance::error(), SvmApproximationErrorFunctionGlobal::errorDerivative(), SvmApproximationErrorFunction::errorDerivative(), SpanBound1::errorDerivative(), GaussianProcessEvidence::evidence(), C_SVM::modelDerivative(), and C_SVM::PrepareDerivative().
KernelFunction* SVM::getKernel () [inline]
return the kernel function object
Definition at line 211 of file Svm.h.
References kernel.
Referenced by SpanBound1::bound(), SpanBound1::boundDerivative(), GaussianProcessEvidence::dEvidenceDTheta(), SpanBoundA::error(), NegativePolarization::error(), LOO::error(), NegativeBKTA::error(), GaussianProcessVariance::error(), SvmApproximationErrorFunctionGlobal::errorDerivative(), SvmApproximationErrorFunction::errorDerivative(), SpanBoundA::errorDerivative(), RadiusMargin::errorDerivative(), NegativePolarization::errorDerivative(), NegativeBKTA::errorDerivative(), MetaSVM::MetaSVM(), SVM_Optimizer::optimize(), RadiusMargin::solveProblems(), and SvmApproximation::SvmApproximation().
double SVM::getOffset () [inline]
retrieve the solution offset, usually referred to as
Author:
T. Glasmachers
Date:
2006
Examples:
SVMclassification-gnuplot.cpp.
Definition at line 205 of file Svm.h.
References examples, and Model::parameter.
Referenced by C_SVM::PrepareDerivative().
const Array<double>& SVM::getPoints () [inline]
return the training data points
Definition at line 217 of file Svm.h.
References x.
Referenced by SvmApproximation::addVecFixPointIteration(), SvmApproximation::calcOffsetForReducedModel(), SvmApproximation::calcOptimalAlphaOfApproximatedSVM(), GaussianProcessEvidence::dEvidenceDTheta(), SvmApproximation::error(), GaussianProcessVariance::error(), SvmApproximationErrorFunctionGlobal::errorDerivative(), SvmApproximationErrorFunction::errorDerivative(), C_SVM::modelDerivative(), and C_SVM::PrepareDerivative().
SVM * SVM::ImportLibsvmModel (std::istream & is) [static]
Import a libsvm 2.81 model file.
Author:
T. Glasmachers
Date:
2006
Returns:
On success a SVM model is returned. A return value of NULL indicates an error.
Definition at line 344 of file Svm.cpp.
References bOwnMemory, examples, i, Model::inputDimension, Model::parameter, Model::setParameter(), PolynomialKernel::setParameter(), and x.
SVM * SVM::ImportSvmlightModel (std::istream & is) [static]
Import an SVM-light model file.
Author:
T. Glasmachers
Date:
2006
Returns:
On success a SVM model is returned. A return value of NULL indicates an error.
Definition at line 501 of file Svm.cpp.
References bOwnMemory, examples, i, Model::inputDimension, Model::parameter, and x.
bool SVM::LoadSVMModel (std::istream & is)
Load the complete SVM model including kernel parameters, alpha, b and the support vectors.
Author:
T. Glasmachers
Date:
2006
Definition at line 219 of file Svm.cpp.
void SVM::MakeSparse ()
Discard zero coefficients and corresponding training data.
If the SVM object onws its training data array, it can make itself sparse after training.
Definition at line 625 of file Svm.cpp.
References i.
Referenced by SVM_Optimizer::optimize().
double SVM::model (const Array< double > & input)
compute the SVM prediction on data
Author:
T. Glasmachers
Date:
2006
Definition at line 157 of file Svm.cpp.
References i.
void SVM::model (const Array< double > & input, Array< double > & output) [virtual]
compute the SVM prediction on data
Author:
T. Glasmachers
Date:
2006
Implements Model.
Definition at line 114 of file Svm.cpp.
References i.
Referenced by SpanBound2::error(), SpanBound1::error(), NoisySvmLikelihood::error(), SpanBound1::errorDerivative(), NoisySvmLikelihood::errorDerivative(), GaussianProcess::operator()(), and Perceptron::optimize().
void SVM::modelDerivative (const Array< double > & input, Array< double > & output, Array< double > & derivative) [virtual]
The modelDerivative member computes the derivative of the SVM function w.r.t. its parameters. Although this information is probably never used, it is easy to compute :)
Of course, the derivative does not make sense after the application of the sign function. Thus, this method always returns the derivative w.r.t. the real valued SVM output.
Author:
T. Glasmachers
Date:
2006
Reimplemented from Model.
Definition at line 197 of file Svm.cpp.
References i.
void SVM::modelDerivative (const Array< double > & input, Array< double > & derivative) [virtual]
The modelDerivative member computes the derivative of the SVM function w.r.t. its parameters. Although this information is probably never used, it is easy to compute :)
Of course, the derivative does not make sense after the application of the sign function. Thus, this method always returns the derivative w.r.t. the real valued SVM output.
Author:
T. Glasmachers
Date:
2006
Reimplemented from Model.
Definition at line 179 of file Svm.cpp.
References i.
int SVM::ReadToken (std::istream & is, char * buffer, int maxlength, const char * separators) [static, protected]
Read a token from a stream.
The function reads a token from a stream. It stores the token into a null terminated string. If the first character read is already a separator the function returns an empty token.
Parameters:
is stream to read from
buffer buffer to store the token
maxlength size of the buffer
separators characters terminating the token
Returns:
A status code is returned:
token read successfully --> terminating char
token read successfully, end of file --> 1001
unrecoverable error --> 1002
buffer overrun, token truncated to size maxlength-1 --> 1003
Definition at line 661 of file Svm.cpp.
References i.
bool SVM::SaveSVMModel (std::ostream & os)
Save the complete SVM model including kernel parameters, alpha, b and the support vectors.
Author:
T. Glasmachers
Date:
2006
Definition at line 293 of file Svm.cpp.
void SVM::setSignOutput (bool bSignOutput = true) [inline]
Set the output mode to sign or real mode.
In sign mode (bSignOutput = true), the machine predicts the class encoded as a +1 or -1. In real number mode, the machine outputs a (non-normalized) confidence score, with positive values indicating class +1.
Definition at line 117 of file Svm.h.
References signOutput.
void SVM::SetTrainingData (const Array< double > & input, bool copy = false)
As the SVM can be constructed without training data points, although these are needed for the computation of the model, this member makes the training data known to the SVM. This method is usually called by the SVM_Optimizer class, but in case a model was loaded from a file it can be necessary to invoke the function manually.
A side effects, the method eventually rescales the parameter vector. In any case, all parameters are reset. The number of examples and the input space dimension are overwritten.
Author:
T. Glasmachers
Date:
2006
Parameters:
input training data points
copy maintain a copy of the input data
Definition at line 92 of file Svm.cpp.
Referenced by LOO::error(), SVM_Optimizer::optimize(), Perceptron::optimize(), SvmApproximation::SvmApproximation(), and GaussianProcess::train().
Friends And Related Function Documentation
friend class SvmApproximation [friend]
Definition at line 285 of file Svm.h.
Member Data Documentation
bool SVM::bOwnMemory [protected]
true if x and y are allocated by LoadModel
Definition at line 331 of file Svm.h.
Referenced by ImportLibsvmModel(), and ImportSvmlightModel().
unsigned int SVM::examples [protected]
number of training data points x and labels #y
Definition at line 341 of file Svm.h.
Referenced by getExamples(), getOffset(), ImportLibsvmModel(), and ImportSvmlightModel().
KernelFunction* SVM::kernel [protected]
kernel function
Definition at line 328 of file Svm.h.
Referenced by getKernel().
bool SVM::signOutput [protected]
true if the SVM outputs the binary label only, false if the SVM outputs the value of the linear feature space function.
Definition at line 338 of file Svm.h.
Referenced by setSignOutput().
const Array<double>* SVM::x [protected]
training data points
Definition at line 334 of file Svm.h.
Referenced by getPoints(), ImportLibsvmModel(), and ImportSvmlightModel().
The documentation for this class was generated from the following files:
Svm.h
Svm.cpp