ReClaM: QpBoxDecomp Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
QpBoxDecomp Class Reference
Quadratic program solver for box constrained problems.
#include <QpBoxDecomp.h>
Public Member Functions
QpBoxDecomp (CachedMatrix &quadraticPart)
Constructor.
virtual ~QpBoxDecomp ()
Destructor.
void Solve (const Array< double > &linearPart, const Array< double > &boxLower, const Array< double > &boxUpper, Array< double > &solutionVector, double eps=0.001)
solve the quadratic program
SharkInt64 iterations ()
Return the number of iterations used to solve the problem.
bool isOptimal ()
Is the solution optimal up to the given epsilon?
void setMaxIterations (SharkInt64 maxiter=-1)
set the maximal number of iterations the solver is allowed to perform
void Set_WSS_Strategy (int i=1)
Protected Member Functions
double StepEdge (double alpha, double g, double Q, double L, double U, double &mu)
Internally used by Solve2D; computes the solution of a one-dimensional sub-problem.
void Solve2D (double alphai, double alphaj, double gi, double gj, double Qii, double Qij, double Qjj, double Li, double Ui, double Lj, double Uj, double &mui, double &muj)
Exact solver for a two-dimensional sub-problem.
void Loop ()
decomposition loop
virtual bool SelectWorkingSet (unsigned int &i)
working set selection in the case of a single variable
virtual bool SelectWorkingSet (unsigned int &i, unsigned int &j)
working set selection in the case of two variables
void Shrink ()
Shrink the problem.
void Unshrink (bool complete=false)
Active all variables.
void FlipCoordinates (unsigned int i, unsigned int j)
exchange two variables via the permutation
Protected Attributes
unsigned int dimension
problem dimension
CachedMatrix & quadratic
representation of the quadratic part of the objective function
Array< double > linear
linear part of the objective function
Array< double > boxMin
box constraint lower bound, that is, minimal variable value
Array< double > boxMax
box constraint upper bound, that is, maximal variable value
unsigned int active
number of currently active variables
Array< unsigned int > permutation
permutation of the variables alpha, gradient, etc.
Array< double > diagonal
diagonal matrix entries The diagonal array is of fixed size and not subject to shrinking.
Array< double > gradient
gradient of the objective function The gradient array is of fixed size and not subject to shrinking.
Array< double > alpha
Solution candidate.
double epsilon
stopping condition - solution accuracy
int WSS_Strategy
number of variables in the working set (1 or 2)
bool bUnshrinked
true if the problem has already been unshrinked
SharkInt64 iter
solution statistics: number of iterations
bool optimal
is the solution found (near) optimal or has the solver stopped due to an interation or time constraint?
SharkInt64 maxIter
maximum number of iterations
Detailed Description
Quadratic program solver for box constrained problems.
This algorithm solves the same problem as QpSvmDecomp but without the equality constraint. For example, this problem corresponds to SVMs without bias. Similar techniques are applied, but this solver solves more complicated sub-problems.
Definition at line 53 of file QpBoxDecomp.h.
Constructor & Destructor Documentation
QpBoxDecomp::QpBoxDecomp (CachedMatrix & quadraticPart)
Constructor.
Parameters:
quadratic quadratic part of the objective function and matrix cache
Definition at line 61 of file QpBoxDecomp.cpp.
References alpha, boxMax, boxMin, diagonal, dimension, CachedMatrix::Entry(), QPMatrix::getMatrixSize(), gradient, i, linear, maxIter, permutation, quadratic, and WSS_Strategy.
QpBoxDecomp::~QpBoxDecomp () [virtual]
Destructor.
Definition at line 87 of file QpBoxDecomp.cpp.
Member Function Documentation
void QpBoxDecomp::FlipCoordinates (unsigned int i, unsigned int j) [protected]
exchange two variables via the permutation
Definition at line 669 of file QpBoxDecomp.cpp.
References alpha, boxMax, boxMin, diagonal, CachedMatrix::FlipColumnsAndRows(), gradient, linear, permutation, quadratic, and XCHG_A.
Referenced by Shrink().
bool QpBoxDecomp::isOptimal () [inline]
Is the solution optimal up to the given epsilon?
Definition at line 85 of file QpBoxDecomp.h.
References optimal.
Referenced by SVM_Optimizer::optimize().
SharkInt64 QpBoxDecomp::iterations () [inline]
Return the number of iterations used to solve the problem.
Definition at line 79 of file QpBoxDecomp.h.
References iter.
void QpBoxDecomp::Loop () [protected]
decomposition loop
Definition at line 294 of file QpBoxDecomp.cpp.
References active, alpha, boxMax, boxMin, bUnshrinked, diagonal, gradient, i, iter, maxIter, optimal, quadratic, CachedMatrix::Row(), SelectWorkingSet(), Shrink(), Solve2D(), Unshrink(), and WSS_Strategy.
Referenced by Solve().
bool QpBoxDecomp::SelectWorkingSet (unsigned int & i) [protected, virtual]
working set selection in the case of a single variable
Definition at line 438 of file QpBoxDecomp.cpp.
References active, alpha, boxMax, boxMin, epsilon, and gradient.
Referenced by Loop().
bool QpBoxDecomp::SelectWorkingSet (unsigned int & i, unsigned int & j) [protected, virtual]
working set selection in the case of two variables
Definition at line 469 of file QpBoxDecomp.cpp.
References active, alpha, boxMax, boxMin, diagonal, epsilon, gradient, quadratic, and CachedMatrix::Row().
void QpBoxDecomp::Set_WSS_Strategy (int i = 1) [inline]
Definition at line 98 of file QpBoxDecomp.h.
References i, and WSS_Strategy.
Referenced by SVM_Optimizer::optimize().
void QpBoxDecomp::setMaxIterations (SharkInt64 maxiter = -1) [inline]
set the maximal number of iterations the solver is allowed to perform
Parameters:
maxiter maximal number of iterations, -1 for infinity
Definition at line 93 of file QpBoxDecomp.h.
References maxIter.
Referenced by SVM_Optimizer::optimize().
void QpBoxDecomp::Shrink () [protected]
Shrink the problem.
Definition at line 569 of file QpBoxDecomp.cpp.
References active, alpha, boxMax, boxMin, bUnshrinked, CachedMatrix::CacheRowRelease(), CachedMatrix::CacheRowResize(), epsilon, FlipCoordinates(), CachedMatrix::getCacheRowSize(), gradient, quadratic, and Unshrink().
Referenced by Loop(), Solve(), and Unshrink().
void QpBoxDecomp::Solve (const Array< double > & linearPart, const Array< double > & boxLower, const Array< double > & boxUpper, Array< double > & solutionVector, double eps = 0.001)
solve the quadratic program
Parameters:
linearPart linear part v of the target function
boxLower vector l of lower bounds
boxUpper vector u of upper bounds
solutionVector input: initial feasible vector ; output: solution
eps solution accuracy, in terms of the maximum KKT violation
Definition at line 92 of file QpBoxDecomp.cpp.
References active, alpha, boxMax, boxMin, dimension, epsilon, gradient, i, linear, Loop(), permutation, quadratic, CachedMatrix::Row(), and Shrink().
Referenced by SVM_Optimizer::optimize().
void QpBoxDecomp::Solve2D (double alphai, double alphaj, double gi, double gj, double Qii, double Qij, double Qjj, double Li, double Ui, double Lj, double Uj, double & mui, double & muj) [protected]
Exact solver for a two-dimensional sub-problem.
Definition at line 178 of file QpBoxDecomp.cpp.
References StepEdge().
Referenced by Loop().
double QpBoxDecomp::StepEdge (double alpha, double g, double Q, double L, double U, double & mu) [protected]
Internally used by Solve2D; computes the solution of a one-dimensional sub-problem.
Definition at line 151 of file QpBoxDecomp.cpp.
References alpha.
Referenced by Solve2D().
void QpBoxDecomp::Unshrink (bool complete = false) [protected]
Active all variables.
Definition at line 646 of file QpBoxDecomp.cpp.
References active, alpha, dimension, gradient, i, linear, quadratic, CachedMatrix::Row(), and Shrink().
Referenced by Loop(), and Shrink().
Member Data Documentation
unsigned int QpBoxDecomp::active [protected]
number of currently active variables
Definition at line 136 of file QpBoxDecomp.h.
Referenced by Loop(), SelectWorkingSet(), Shrink(), Solve(), and Unshrink().
Array<double> QpBoxDecomp::alpha [protected]
Solution candidate.
Definition at line 150 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), Loop(), QpBoxDecomp(), SelectWorkingSet(), Shrink(), Solve(), StepEdge(), and Unshrink().
Array<double> QpBoxDecomp::boxMax [protected]
box constraint upper bound, that is, maximal variable value
Definition at line 133 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), Loop(), QpBoxDecomp(), SelectWorkingSet(), Shrink(), and Solve().
Array<double> QpBoxDecomp::boxMin [protected]
box constraint lower bound, that is, minimal variable value
Definition at line 130 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), Loop(), QpBoxDecomp(), SelectWorkingSet(), Shrink(), and Solve().
bool QpBoxDecomp::bUnshrinked [protected]
true if the problem has already been unshrinked
Definition at line 171 of file QpBoxDecomp.h.
Referenced by Loop(), and Shrink().
Array<double> QpBoxDecomp::diagonal [protected]
diagonal matrix entries The diagonal array is of fixed size and not subject to shrinking.
Definition at line 143 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), Loop(), QpBoxDecomp(), and SelectWorkingSet().
unsigned int QpBoxDecomp::dimension [protected]
problem dimension
Definition at line 121 of file QpBoxDecomp.h.
Referenced by QpBoxDecomp(), Solve(), and Unshrink().
double QpBoxDecomp::epsilon [protected]
stopping condition - solution accuracy
Definition at line 153 of file QpBoxDecomp.h.
Referenced by SelectWorkingSet(), Shrink(), and Solve().
Array<double> QpBoxDecomp::gradient [protected]
gradient of the objective function The gradient array is of fixed size and not subject to shrinking.
Definition at line 147 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), Loop(), QpBoxDecomp(), SelectWorkingSet(), Shrink(), Solve(), and Unshrink().
SharkInt64 QpBoxDecomp::iter [protected]
solution statistics: number of iterations
Definition at line 174 of file QpBoxDecomp.h.
Referenced by iterations(), and Loop().
Array<double> QpBoxDecomp::linear [protected]
linear part of the objective function
Definition at line 127 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), QpBoxDecomp(), Solve(), and Unshrink().
SharkInt64 QpBoxDecomp::maxIter [protected]
maximum number of iterations
Definition at line 182 of file QpBoxDecomp.h.
Referenced by Loop(), QpBoxDecomp(), and setMaxIterations().
bool QpBoxDecomp::optimal [protected]
is the solution found (near) optimal or has the solver stopped due to an interation or time constraint?
Definition at line 179 of file QpBoxDecomp.h.
Referenced by isOptimal(), and Loop().
Array<unsigned int> QpBoxDecomp::permutation [protected]
permutation of the variables alpha, gradient, etc.
Definition at line 139 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), QpBoxDecomp(), and Solve().
CachedMatrix& QpBoxDecomp::quadratic [protected]
representation of the quadratic part of the objective function
Definition at line 124 of file QpBoxDecomp.h.
Referenced by FlipCoordinates(), Loop(), QpBoxDecomp(), SelectWorkingSet(), Shrink(), Solve(), and Unshrink().
int QpBoxDecomp::WSS_Strategy [protected]
number of variables in the working set (1 or 2)
Definition at line 156 of file QpBoxDecomp.h.
Referenced by Loop(), QpBoxDecomp(), and Set_WSS_Strategy().
The documentation for this class was generated from the following files:
QpBoxDecomp.h
QpBoxDecomp.cpp