ReClaM: GridSearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
GridSearch Class Reference
Optimize by trying out a grid of configurations.
#include <GridSearch.h>
Public Member Functions
GridSearch (int verbosity=0)
Constructor.
~GridSearch ()
Destructor.
void init (Model &model)
There is no useful default initialization for this optimizer.
void init (int params, double min, double max, int nodes)
uniform initialization for all parameters
void init (int params, const Array< double > &min, const Array< double > &max, const Array< int > &nodes)
individual definition for every parameter
void init (int params, const Array< double > &values)
uniform definition of the values to test for all parameters
void init (int params, const Array< int > &nodes, const Array< double > &values)
individual definition for every parameter
void init (const Model &model, unsigned max_values)
void assignLinearRange (unsigned index, unsigned no_of_points, double min, double max)
void assignExponentialRange (unsigned index, double base_factor, double exp_base, int min, int max)
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target)
Please note that for the grid search optimizer it does not make sense to call optimize more than once, as the solution does not improve iteratively.
Protected Attributes
Array< int > numberOfValues
The array holds the number of grid values for every parameter axis.
Array< double > nodeValues
The array columns contain the grid values for the corresponding parameter axis.
int verbosity
verbosity level
Detailed Description
Optimize by trying out a grid of configurations.
The GridSearch class allows for the definition of a grid in parameter space. It does a simple one-step optimization over the grid by trying out every possible parameter combination. Please note that the computation effort grows exponentially with the number of parameters.
If you only want to try a subset of the grid, consider using the PointSearch class instead. A more sophisticated (less exhaustive) grid search variant is available with the NestedGridSearch class.
Examples:
CrossValidation.cpp.
Definition at line 71 of file GridSearch.h.
Constructor & Destructor Documentation
GridSearch::GridSearch (int verbosity = 0)
Constructor.
Parameters:
verbosity 0=none, 1=dots, 2=values
Definition at line 51 of file GridSearch.cpp.
References verbosity.
GridSearch::~GridSearch ()
Destructor.
Definition at line 56 of file GridSearch.cpp.
Member Function Documentation
void GridSearch::assignExponentialRange (unsigned index, double base_factor, double exp_base, int min, int max)
Set exponentially progressing grid values for one certain parameter only. This is especially useful in combination with init'ing from a model. The grid points will be filled with values , where i does integer steps between min and max.
Parameters:
index the index of the parameter that gets new grid values
base_factor the value that the exponential base grid should be multiplied by
exp_base the exponential grid will progress on this base (e.g. 2, 10)
min the smallest exponent for #exp_base
max the largest exponent for #exp_base
Definition at line 172 of file GridSearch.cpp.
References nodeValues, and numberOfValues.
void GridSearch::assignLinearRange (unsigned index, unsigned no_of_points, double min, double max)
Assign linearly progressing grid values to one certain parameter only. This is especially useful in combination with init'ing from a model.
Parameters:
index the index of the parameter to which grid values are assigned
no_of_points how many grid points should be assigned to that parameter
min smallest value for that parameter
max largest value for that parameter
Definition at line 157 of file GridSearch.cpp.
References nodeValues, and numberOfValues.
void GridSearch::init (int params, double min, double max, int nodes)
uniform initialization for all parameters
Parameters:
params number of model parameters to optimize
min smallest parameter value
max largest parameter value
nodes total number of values in the interval
Definition at line 66 of file GridSearch.cpp.
References i, nodeValues, and numberOfValues.
void GridSearch::init (int params, const Array< double > & min, const Array< double > & max, const Array< int > & nodes)
individual definition for every parameter
Parameters:
params number of model parameters to optimize
min smallest value for every parameter
max largest value for every parameter
nodes total number of values for every parameter
Definition at line 85 of file GridSearch.cpp.
References i, nodeValues, and numberOfValues.
void GridSearch::init (const Model & model, unsigned max_values)
Construct naive grid with as many dimensions as parameters in the model passed. For each dimension, only one parameter is assigned: the current value of the respective model parameter. To make the grid non-trivial, combine this init routine with the functions assignLinearRange or assignExponentialRange.
Parameters:
model the model from which the trivial grid will be constructed
max_values maximum number of grid values that are later allowed for each dimension of this grid.
Definition at line 140 of file GridSearch.cpp.
References Model::getParameter(), Model::getParameterDimension(), i, Model::isFeasible(), nodeValues, and numberOfValues.
void GridSearch::init (int params, const Array< int > & nodes, const Array< double > & values)
individual definition for every parameter
Parameters:
params number of model parameters to optimize
nodes total number of values for every parameter
values values used. The first dimension is the parameter, the second dimension is the node. Unused entries are ignored.
Definition at line 131 of file GridSearch.cpp.
References nodeValues, and numberOfValues.
void GridSearch::init (int params, const Array< double > & values)
uniform definition of the values to test for all parameters
Parameters:
params number of model parameters to optimize
values values used for every coordinate
Definition at line 115 of file GridSearch.cpp.
References i, nodeValues, and numberOfValues.
void GridSearch::init (Model & model) [virtual]
There is no useful default initialization for this optimizer.
Thus, this member throws an exception.
Implements Optimizer.
Examples:
CrossValidation.cpp.
Definition at line 61 of file GridSearch.cpp.
double GridSearch::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Please note that for the grid search optimizer it does not make sense to call optimize more than once, as the solution does not improve iteratively.
Implements Optimizer.
Examples:
CrossValidation.cpp.
Definition at line 182 of file GridSearch.cpp.
References ErrorFunction::error(), Model::getParameter(), i, Model::isFeasible(), nodeValues, numberOfValues, Model::setParameter(), and verbosity.
Member Data Documentation
Array<double> GridSearch::nodeValues [protected]
The array columns contain the grid values for the corresponding parameter axis.
As all columns have the same size, some values may be meaningless.
Definition at line 151 of file GridSearch.h.
Referenced by assignExponentialRange(), assignLinearRange(), init(), and optimize().
Array<int> GridSearch::numberOfValues [protected]
The array holds the number of grid values for every parameter axis.
Definition at line 147 of file GridSearch.h.
Referenced by assignExponentialRange(), assignLinearRange(), init(), and optimize().
int GridSearch::verbosity [protected]
verbosity level
Definition at line 154 of file GridSearch.h.
Referenced by GridSearch(), and optimize().
The documentation for this class was generated from the following files:
GridSearch.h
GridSearch.cpp