ReClaM: PCA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
PCA Class Reference
"Principal Component Analysis" class for data compression.
#include <PCA.h>
Public Member Functions
PCA ()
~PCA ()
void init (Model &model)
basic initialization with default parameters
void init (bool whitening)
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target)
Performes one optimization step, for example a gradient descent step or an evolution cycle.
double optimize (AffineLinearMap &model, const Array< double > &input)
double optimize (Model &model, ErrorFunction &error, const Array< double > &input, const Array< double > &target, Array< double > &eigenvalues, Array< double > &eigenvectors)
double optimize (AffineLinearMap &model, const Array< double > &input, Array< double > &eigenvalues, Array< double > &eigenvectors)
Protected Member Functions
void MeanAndScatter (const Array< double > &input, Array< double > &mean, Array2D< double > &scatter)
Protected Attributes
bool bWhitening
Detailed Description
"Principal Component Analysis" class for data compression.
The Principal Component Analysis also known as Karhunen-Loeve-Transformation takes a symmetric matrix and uses its decomposition
where is the diagonal matrix of eigenvalues of and is the orthogonal matrix with the corresponding eigenvectors as columns. then defines a successive orthogonal rotation, that maximizes the variances of the coordinates, i.e. the coordinate system is rotated in such a way that the correlation between the new axes becomes zero. If there are axes, the first axis is rotated in a way that the points on the new axis have maximum variance. Then the remaining axes are rotated such that a another axis covers a maximum part of the rest variance, that is not covered by the first axis. After the rotation of axes, the rotation destination of axis no. is fixed. An application for PCA is the reduction of dimensions by skipping the components with the least corresponding eigenvalues/variances.
Examples:
PCAtest.cpp.
Definition at line 93 of file PCA.h.
Constructor & Destructor Documentation
PCA::PCA ()
Definition at line 52 of file PCA.cpp.
References bWhitening.
PCA::~PCA ()
Definition at line 57 of file PCA.cpp.
Member Function Documentation
void PCA::init (Model & model) [virtual]
basic initialization with default parameters
Implements Optimizer.
Examples:
PCAtest.cpp.
Definition at line 62 of file PCA.cpp.
References bWhitening, Model::getInputDimension(), and Model::getOutputDimension().
void PCA::init (bool whitening)
Definition at line 71 of file PCA.cpp.
References bWhitening.
void PCA::MeanAndScatter (const Array< double > & input, Array< double > & mean, Array2D< double > & scatter) [protected]
Definition at line 142 of file PCA.cpp.
References i.
Referenced by optimize().
double PCA::optimize (Model & model, ErrorFunction & error, const Array< double > & input, const Array< double > & target, Array< double > & eigenvalues, Array< double > & eigenvectors)
Definition at line 83 of file PCA.cpp.
References optimize().
double PCA::optimize (AffineLinearMap & model, const Array< double > & input)
Definition at line 90 of file PCA.cpp.
References optimize().
double PCA::optimize (AffineLinearMap & model, const Array< double > & input, Array< double > & eigenvalues, Array< double > & eigenvectors)
Definition at line 97 of file PCA.cpp.
References bWhitening, Model::getInputDimension(), Model::getOutputDimension(), i, MeanAndScatter(), and Model::setParameter().
double PCA::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Performes one optimization step, for example a gradient descent step or an evolution cycle.
Parameters:
model Model to use for the computation.
errorfunction ErrorFunction on which decisions are based.
input Vector of input values.
target Vector of output values.
Returns:
The error E returned by the ErrorFunction.
Implements Optimizer.
Examples:
PCAtest.cpp.
Definition at line 76 of file PCA.cpp.
Referenced by optimize().
Member Data Documentation
bool PCA::bWhitening [protected]
Definition at line 110 of file PCA.h.
Referenced by init(), optimize(), and PCA().
The documentation for this class was generated from the following files:
PCA.h
PCA.cpp