ReClaM: McSvmApproximation Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
McSvmApproximation Class Reference
Approximation of Multi-class Support Vector Machines (SVMs)
#include <McSvmApproximation.h>
Public Member Functions
McSvmApproximation (MultiClassSVM *pSVM, bool verbose=false)
constructor
~McSvmApproximation ()
destructor
float approximate ()
approximate SVM
float gradientDescent ()
perform gradient descent on overall model of approximated SVM (SVs and coefficients)
MultiClassSVM * getApproximatedSVM ()
return pointer to approximated SVM
void setTargetNoVecsForApproximatedSVM (unsigned noVecs)
specify the number of the SVs for the approximated SVM only used if "approximationTarget" is set to "noSVs"
void setNoGradientDescentIterations (unsigned no)
Protected Member Functions
double error ()
determine "difference" between original and approximated SVM
void addVecRprop ()
optimize vector using iRpropPlus
bool calcOptimalAlphaOfApproximatedSVM ()
calculate optimal coefficients for approx. SVM
bool calcOffsetForReducedModel ()
calculate bias "b" for approx. SVM
float getClassificationRateOnSVsCorrectlyClassifiedByOrigSVM ()
determine classification rate of approx. SVM on SVs of original SVM
void determineNoOfVectorsPerClassForApproximation ()
bool chooseVectorForNextIteration (Array< double > &vec)
choose vector from original SVs
Protected Attributes
bool verbose
in verbose mode the algorithm outputs some helpful comments to stdout.
MultiClassSVM * mpSVM
MultiClassSVM * mpApproximatedSVM
double * labels
Array< double > approximatedVectors
unsigned mNoUniqueSVs
Number of examples used as SV somewhere (in one of the machines)
unsigned mNoNonUniqueSVs
Number of SVs taken together all the different machines.
unsigned mNoExamplesOfOrigSVM
unsigned mDimension
unsigned mNoClasses
unsigned * mpNoExamplesOfApproximatedSVM
double mOffsetOfApproximatedSVM
unsigned mTargetNoVecsForApproximatedSVM
unsigned * mpTargetNoVecsPerClass
KernelFunction * mpKernel
double mGamma
bool mbIsApproximatedModelValid
bool mbPerformedGradientDescent
unsigned mNoGradientDescentIterations
unsigned int * mpNoSVsOrigSVM
unsigned int * mpNoVecsDrawn
const char * mOutputDir
std::vector< int > * mpIndexListOfVecsForSelection
Friends
class McSvmApproximationErrorFunction
class McSvmApproximationErrorFunctionGlobal
Detailed Description
Approximation of Multi-class Support Vector Machines (SVMs)
Author:
B. Weghenkel
Date:
2010
The McSvmApproximator class approximates the decision
function of an Multi-class Shark-SVM object
Definition at line 61 of file McSvmApproximation.h.
Constructor & Destructor Documentation
McSvmApproximation::McSvmApproximation (MultiClassSVM * pSVM, bool verbose = false)
constructor
Parameters:
pSVM SVM to be approximated
Definition at line 70 of file McSvmApproximation.cpp.
References MultiClassSVM::getKernel(), Model::getParameter(), and MultiClassSVM::SetTrainingData().
McSvmApproximation::~McSvmApproximation ()
destructor
Definition at line 153 of file McSvmApproximation.cpp.
Member Function Documentation
void McSvmApproximation::addVecRprop () [protected]
optimize vector using iRpropPlus
Definition at line 269 of file McSvmApproximation.cpp.
References Model::getParameter(), IRpropPlus::initUserDefined(), and IRpropPlus::optimize().
float McSvmApproximation::approximate ()
approximate SVM
Definition at line 238 of file McSvmApproximation.cpp.
bool McSvmApproximation::calcOffsetForReducedModel () [protected]
calculate bias "b" for approx. SVM
Definition at line 427 of file McSvmApproximation.cpp.
References MultiClassSVM::getPoints(), and i.
bool McSvmApproximation::calcOptimalAlphaOfApproximatedSVM () [protected]
calculate optimal coefficients for approx. SVM
Definition at line 315 of file McSvmApproximation.cpp.
References MultiClassSVM::getPoints(), and i.
bool McSvmApproximation::chooseVectorForNextIteration (Array< double > & vec) [protected]
choose vector from original SVs
Definition at line 469 of file McSvmApproximation.cpp.
void McSvmApproximation::determineNoOfVectorsPerClassForApproximation () [protected]
Definition at line 497 of file McSvmApproximation.cpp.
double McSvmApproximation::error () [protected]
determine "difference" between original and approximated SVM
MultiClassSVM* McSvmApproximation::getApproximatedSVM () [inline]
return pointer to approximated SVM
Definition at line 80 of file McSvmApproximation.h.
References mpApproximatedSVM.
float McSvmApproximation::getClassificationRateOnSVsCorrectlyClassifiedByOrigSVM () [protected]
determine classification rate of approx. SVM on SVs of original SVM
float McSvmApproximation::gradientDescent ()
perform gradient descent on overall model of approximated SVM (SVs and coefficients)
void McSvmApproximation::setNoGradientDescentIterations (unsigned no) [inline]
Definition at line 88 of file McSvmApproximation.h.
References mNoGradientDescentIterations.
void McSvmApproximation::setTargetNoVecsForApproximatedSVM (unsigned noVecs) [inline]
specify the number of the SVs for the approximated SVM only used if "approximationTarget" is set to "noSVs"
Definition at line 85 of file McSvmApproximation.h.
References mTargetNoVecsForApproximatedSVM.
Friends And Related Function Documentation
friend class McSvmApproximationErrorFunction [friend]
Definition at line 150 of file McSvmApproximation.h.
friend class McSvmApproximationErrorFunctionGlobal [friend]
Definition at line 151 of file McSvmApproximation.h.
Member Data Documentation
Array<double> McSvmApproximation::approximatedVectors [protected]
Definition at line 121 of file McSvmApproximation.h.
double* McSvmApproximation::labels [protected]
Definition at line 119 of file McSvmApproximation.h.
bool McSvmApproximation::mbIsApproximatedModelValid [protected]
Definition at line 138 of file McSvmApproximation.h.
bool McSvmApproximation::mbPerformedGradientDescent [protected]
Definition at line 139 of file McSvmApproximation.h.
unsigned McSvmApproximation::mDimension [protected]
Definition at line 127 of file McSvmApproximation.h.
double McSvmApproximation::mGamma [protected]
Definition at line 136 of file McSvmApproximation.h.
unsigned McSvmApproximation::mNoClasses [protected]
Definition at line 127 of file McSvmApproximation.h.
unsigned McSvmApproximation::mNoExamplesOfOrigSVM [protected]
Definition at line 127 of file McSvmApproximation.h.
unsigned McSvmApproximation::mNoGradientDescentIterations [protected]
Definition at line 141 of file McSvmApproximation.h.
Referenced by setNoGradientDescentIterations().
unsigned McSvmApproximation::mNoNonUniqueSVs [protected]
Number of SVs taken together all the different machines.
Definition at line 126 of file McSvmApproximation.h.
unsigned McSvmApproximation::mNoUniqueSVs [protected]
Number of examples used as SV somewhere (in one of the machines)
Definition at line 124 of file McSvmApproximation.h.
double McSvmApproximation::mOffsetOfApproximatedSVM [protected]
Definition at line 129 of file McSvmApproximation.h.
const char* McSvmApproximation::mOutputDir [protected]
Definition at line 146 of file McSvmApproximation.h.
MultiClassSVM* McSvmApproximation::mpApproximatedSVM [protected]
Definition at line 117 of file McSvmApproximation.h.
Referenced by getApproximatedSVM().
std::vector<int>* McSvmApproximation::mpIndexListOfVecsForSelection [protected]
Definition at line 148 of file McSvmApproximation.h.
KernelFunction* McSvmApproximation::mpKernel [protected]
Definition at line 135 of file McSvmApproximation.h.
unsigned* McSvmApproximation::mpNoExamplesOfApproximatedSVM [protected]
Definition at line 128 of file McSvmApproximation.h.
unsigned int* McSvmApproximation::mpNoSVsOrigSVM [protected]
Definition at line 142 of file McSvmApproximation.h.
unsigned int* McSvmApproximation::mpNoVecsDrawn [protected]
Definition at line 143 of file McSvmApproximation.h.
MultiClassSVM* McSvmApproximation::mpSVM [protected]
Definition at line 116 of file McSvmApproximation.h.
unsigned* McSvmApproximation::mpTargetNoVecsPerClass [protected]
Definition at line 133 of file McSvmApproximation.h.
unsigned McSvmApproximation::mTargetNoVecsForApproximatedSVM [protected]
Definition at line 132 of file McSvmApproximation.h.
Referenced by setTargetNoVecsForApproximatedSVM().
bool McSvmApproximation::verbose [protected]
in verbose mode the algorithm outputs some helpful comments to stdout.
Definition at line 93 of file McSvmApproximation.h.
The documentation for this class was generated from the following files:
McSvmApproximation.h
McSvmApproximation.cpp