ReClaM: BFGS Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
BFGS Class Reference
Offers methods to use the Broyden-Fletcher-Goldfarb-Shanno algorithm for the optimization of models.
#include <BFGS.h>
Public Types
enum LineSearch { Dlinmin, Linmin, Cblnsrch }
Used to specify the type of line search algorithm that is used by the BFGS algorithm:
"Linmin" is the original line search algorithm, "DLinmin" is a line search algorithm that additionally uses derivative information and "Cblnsrch" is a cubic line search.
Public Member Functions
void bfgs (Model &model, ErrorFunction &error, const Array< double > &i, const Array< double > &t, double gtol, unsigned &iter, double &fret, unsigned iterMax)
Updates the weights of the network by using the BFGS optimization algorithm.
void init (Model &model)
Initializes some internal variables used by the BFGS algorithm.
void initBfgs (Model &model, LineSearch ls=Dlinmin, double ax=0., double bx=1., double lambda=0.25)
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target)
Updates the weights of the network by using the BFGS optimization algorithm, that was previously initialized and returns the minimum value by reference.
double optimize (Model &model, ErrorFunction &errorfunction, const Array< double > &input, const Array< double > &target, double gtol, int iterMax)
void bfgs (Model &model, ErrorFunction &errorfunction, const Array< double > &in, const Array< double > &target, double &fret)
Updates the weights of the network by using the BFGS optimization algorithm, that was previously initialized and returns the minimum value by reference.
void bfgs (Model &model, ErrorFunction &errorfunction, const Array< double > &in, const Array< double > &target)
void setAx (double x)
Sets the initial value for the left bracket used by the line search algorithms.
void setBx (double x)
Sets the initial value for the right bracket used by the line search algorithms.
void setLambda (double x)
Sets the initial value for value used by the line search algorithms.
void reset ()
Detailed Description
Offers methods to use the Broyden-Fletcher-Goldfarb-Shanno algorithm for the optimization of models.
Given the error function , that shall be optimized, this function will be square approximated around the last given search point by
where is the Hessian matrix evaluated at with the entries
The derivation is then
At the optimum point holds , so the Newton step (the BFGS algorithm is a quasi-Newton method) is
The new search point is then directly determined from this step with this method used iteratively, because of the approximation.
The inverse Hessian matrix is iteratively estimated with possibility to restrict the number of iterations.
For a more detailed description of the BFGS algorithm refer to "Neural Networks for Pattern Recognition" by Christopher M. Bishop or "Numerical Recipes in C" by Press, Teukolsky, Vetterling and Flannery.
Author:
C. Igel
Date:
1999
Changes:
none
Status:
stable
Definition at line 127 of file BFGS.h.
Member Enumeration Documentation
enum BFGS::LineSearch
Used to specify the type of line search algorithm that is used by the BFGS algorithm:
"Linmin" is the original line search algorithm, "DLinmin" is a line search algorithm that additionally uses derivative information and "Cblnsrch" is a cubic line search.
Enumerator:
Dlinmin
Linmin
Cblnsrch
Definition at line 137 of file BFGS.h.
Member Function Documentation
void BFGS::bfgs (Model & model, ErrorFunction & error, const Array< double > & i, const Array< double > & t, double gtol, unsigned & iter, double & fret, unsigned iterMax)
Updates the weights of the network by using the BFGS optimization algorithm.
Definition at line 140 of file BFGS.cpp.
References Cblnsrch, Dlinmin, ErrorFunction::errorDerivative(), Model::getParameter(), i, Linmin, and Model::setParameter().
Referenced by bfgs(), and optimize().
void BFGS::bfgs (Model & model, ErrorFunction & errorfunction, const Array< double > & in, const Array< double > & target, double & fret)
Updates the weights of the network by using the BFGS optimization algorithm, that was previously initialized and returns the minimum value by reference.
The given input patterns in and their corresponding target values target are used to calculate the error of the currently used model. The resulting error function is then minimized by the BFGS algorithm, the weights of the network are updated.
This method needs far less parameters than the other BFGS method, because it is guessed, that one of the initBfgs methods was called before.
Parameters:
in Input patterns for the currently used model.
target Target values corresponding to the input patterns.
fret Minimum value of the error function.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 404 of file BFGS.cpp.
References Cblnsrch, Dlinmin, ErrorFunction::errorDerivative(), i, Linmin, and Model::setParameter().
void BFGS::bfgs (Model & model, ErrorFunction & errorfunction, const Array< double > & in, const Array< double > & target) [inline]
Definition at line 238 of file BFGS.h.
References bfgs().
void BFGS::init (Model & model) [virtual]
Initializes some internal variables used by the BFGS algorithm.
The given parameters are used to initialize some variables used by the BFGS and the line search algorithms and to allocate memory for internal structures.
Parameters:
model Type of model that uses BFGS.
ls Type of LineSearch algorithm, that is used by the BFGS algorithm. Possible values: "Dlinmin" (default value), "Linmin", "Cblnsrch"
ax Initial left bracket for the line search algorithms, the default bracket is "0".
bx Initial right bracket for the line search algorithms, the default bracket is "1".
lambda The initial value for the searched , that will minimize the function used by the line search algorithm. The default value is "0.25".
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Implements Optimizer.
Definition at line 322 of file BFGS.cpp.
References initBfgs().
void BFGS::initBfgs (Model & model, LineSearch ls = Dlinmin, double ax = 0., double bx = 1., double lambda = 0.25)
Definition at line 328 of file BFGS.cpp.
References Model::getParameter(), Model::getParameterDimension(), i, and Model::setParameter().
Referenced by init().
double BFGS::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target) [virtual]
Updates the weights of the network by using the BFGS optimization algorithm, that was previously initialized and returns the minimum value by reference.
Updates the weights of the network by using the BFGS optimization algorithm.
Updates the weights of the network by using the BFGS optimization algorithm, that was previously initialized.
The given input patterns in and their corresponding target values target are used to calculate the error of the currently used model. The resulting error function is then minimized by the BFGS algorithm, the weights of the network are updated.
This method needs far less parameters than the other BFGS method, because it is guessed, that one of the initBfgs methods was called before.
Parameters:
in Input patterns for the currently used model.
target Target values corresponding to the input patterns.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
The given input patterns in and their corresponding target values target are used to calculate the error of the currently used model. The resulting error function is then minimized by the BFGS algorithm, the weights of the network are updated.
Parameters:
in Input patterns for the currently used model.
target Target values corresponding to the input patterns.
gtol Convergence requirement on zeoring the gradient.
iter Number of iterations that were performed by the function.
fret Minimum value of the error function.
iterMax Max. number of allowed iterations.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
Unstable
Implements Optimizer.
Definition at line 116 of file BFGS.cpp.
References bfgs().
double BFGS::optimize (Model & model, ErrorFunction & errorfunction, const Array< double > & input, const Array< double > & target, double gtol, int iterMax)
Definition at line 126 of file BFGS.cpp.
References bfgs().
void BFGS::reset ()
Definition at line 361 of file BFGS.cpp.
References i.
void BFGS::setAx (double x) [inline]
Sets the initial value for the left bracket used by the line search algorithms.
The line search algorithms used by the BFGS algorithm searches for a minimum value of the error function along a search direction , i.e. it searches for a scalar , that minimizes
The minimum value searched is iteratively bracketed by two points. The left point (i.e. the value that is less than the minimum) can be set by this method.
Parameters:
x The initial value for the left bracket.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 277 of file BFGS.h.
void BFGS::setBx (double x) [inline]
Sets the initial value for the right bracket used by the line search algorithms.
The line search algorithms used by the BFGS algorithm searches for a minimum value of the error function along a search direction , i.e. it searches for a scalar , that minimizes
The minimum value searched is iteratively bracketed by two points. The right point (i.e. the value that is greater than the minimum) can be set by this method.
Parameters:
x The initial value for the right bracket.
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 313 of file BFGS.h.
void BFGS::setLambda (double x) [inline]
Sets the initial value for value used by the line search algorithms.
The line search algorithms used by the BFGS algorithm searches for a minimum value of the error function along a search direction , i.e. it searches for a scalar , that minimizes
can be set by this method.
Parameters:
x The initial value for .
Returns:
none
Author:
C. Igel
Date:
1999
Changes
none
Status
stable
Definition at line 349 of file BFGS.h.
The documentation for this class was generated from the following files:
BFGS.h
BFGS.cpp