ReClaM: VarianceEstimator Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
VarianceEstimator Class Reference
Offers the methods to deal with active learning of a neural network.
#include <VarianceEstimator.h>
Static Public Member Functions
static void estimateFisherInformation (Model &model, const Array< double > &inputA, const Array< double > &outputA, Array< double > &infMatA)
The Fisher information matrix is estimated.
static void estimateInvFisher (Model &model, const Array< double > &inputA, const Array< double > &outputA, Array< double > &invInfMatA, Array< double > &transInvInfMatA, double &s2A)
Estimates the inverse Fisher information matrix and other values used for quantifying changes in variance due to active learning.
static double estimateVariance (Model &model, const Array< double > &inputA, const Array< double > &invInfMatA)
The estimated output variance of the network for one input pattern is returned.
static double estimateVarianceChange (Model &model, const Array< double > &inputA, const Array< double > &invInfMatA, const Array< double > &transInvInfMatA, double s2A)
Estimates the change in the output variance after an active learning step.
static double overallVariance (Model &model, const Array< double > &inputA, const Array< double > &outputA)
The estimated output variance of the network for all input patterns is returned.
Detailed Description
Offers the methods to deal with active learning of a neural network.
Most neural networks are used as passive learners, i.e. they will work on a fixed training set. In natural learning problems, however, the learner can gather new information from its environment to improve the learning process. Using active learning in connection with neural networks, the network is allowed to select a new training input at each time step.
To achieve a real improvement of the learning process, the selected new input is not chosen by random. The goal is to chose an input, that minimizes the expectation of the learner's mean squared error. So you will find methods here, that will estimate the output variance of the network, when adding a new example to the training set.
For more details about active learning in neural networks and the formulas used here for the variance estimations, please refer to David A. Cohn: "Neural Network Exploration Using Optimal Experimental Design."
Example
  // Create own network class using Variance Estimator:
  class MyNet : public FFNet,
                public MeanSquaredError,
                ...,
                public VarianceEstimator
  {
      ...
  }
  void main()
  {
      // Create net:
      MyNet net;
      // Fill net:
      ...
      // Training the net:
      for ( unsigned epoch = 1; epoch < max_epochs; epoch++ )
      {
          // Train net with prefered optimization algorithm:
          ...
          // Estimate current variance of the model:
          currVar = net.overallVariance( inputTrain, targetTrain );
          // Active learning step - choose one of the patterns
          // of the additional set, that will decrease the
          // variance most and add it to the training set:
          //
          // Calculates values "invInfMat", "transInvInfMat" and "s2",
          // that are necessary for the estimation
          // of the variance change:
          net.estimateInvFisher( inputTrain, targetTrain,
                                 invInfMat, transInvInfMat, s2 );
          // Estimate variance change of the model for all patterns
          // of the additional set:
          for ( i = 0; i < no_additionals; i++ )
          {
              varChange =
                  net.estimateVarianceChange( inputAdditional[ i ],
                                              invInfMat,
                                              transInvInfMat, s2    );
              ...
          }
          // Choose pattern which minimizes the model variance:
          ...
          // Monitor variance at the chosen reference point:
          refVar = net.estimateVariance( inputAdditional[ bestIndex ],
                           invInfMat                     );
          // Add chosen pattern to the training set:
          ...
      } // next training epoch
  }
This example shows, how to use the variance estimation.
In addition to your "normal" training set, you also use a set of additional patterns (predefined or random), that can be added one by one to the original training set.
For each active learning step add one pattern to the training set and use the methods of class VarianceEstimator to choose the pattern, that will decrease the variance of the current model at most.
Author:
M. Kreutz
Date:
2001-05-04
Changes:
none
Status:
stable
Definition at line 178 of file VarianceEstimator.h.
Member Function Documentation
void VarianceEstimator::estimateFisherInformation (Model & model, const Array< double > & inputA, const Array< double > & outputA, Array< double > & infMatA) [static]
The Fisher information matrix is estimated.
Given a training set with input patterns with the corresponding target values the current value of the used negative log likelihood measure of the weights (also called a score) is proportional to
where is the output of the used network for the input . After calculating the value of the measure, the Fisher information matrix can be estimated by
where is the learners best guess for mapping inputs to outputs with as the weight vector of the network that minimizes the negative log likelihood measure , i.e. is an estimate of the corresponding .
The Fisher information matrix measures the information contained in the training data set about each parameter (i.e. each weight).
The inverse of the matrix then provides an approximation to the variance of the maximum-likelihood estimator which becomes increasingly accurate as the sample size increases.
Parameters:
inputA The input patterns of the training set.
outputA The target values for the used input patterns.
infMatA The calculated Fisher information matrix .
Returns:
none
Exceptions:
check_exception the type of the exception will be "size mismatch" and indicates that inputA is not 2-dimensional
Author:
M. Kreutz
Date:
2001-05-04
Changes
none
Status
stable
Definition at line 124 of file VarianceEstimator.cpp.
References i, and Model::modelDerivative().
void VarianceEstimator::estimateInvFisher (Model & model, const Array< double > & inputA, const Array< double > & outputA, Array< double > & invInfMatA, Array< double > & transInvInfMatA, double & s2A) [static]
Estimates the inverse Fisher information matrix and other values used for quantifying changes in variance due to active learning.
Given all input patterns of the training set and the corresponding target values three values/matrices are calculated:
the inverse Fisher information matrix ()
the negative log likelihood measure
, where represents the expected value over .
For the definition of , and please refer to method estimateFisherInformation.
The three evaluated values are used for the calculation of the expected change in the output variance (calculated by method estimateVarianceChange), after a new example is added to the training set.
Parameters:
inputA The input patterns of the training set, including the new input pattern .
outputA The target values for the used input patterns.
invInfMatA The calculated inverse Fisher information matrix .
transInvInfMatA The third calculated value as listed above.
s2A The current value of the negative log likelihood measure .
Returns:
none
Exceptions:
check_exception the type of the exception will be "size mismatch" and indicates that inputA is not 2-dimensional
Author:
M. Kreutz
Date:
2001-05-04
Changes
none
Status
stable
See also:
estimateInvFisher
Definition at line 211 of file VarianceEstimator.cpp.
References i, and Model::modelDerivative().
double VarianceEstimator::estimateVariance (Model & model, const Array< double > & inputA, const Array< double > & invInfMatA) [static]
The estimated output variance of the network for one input pattern is returned.
Given one input pattern, the output variance at this reference input can be approximated by
where is the learners best guess for mapping inputs to outputs with as the weight vector of the network that minimizes the negative log likelihood measure and is the inverse Fisher information matrix (see method estimateFisherInformation for details).
Parameters:
inputA The reference input pattern of the training set.
invInfMatA The calculated inverse Fisher information matrix .
Returns:
The estimated output variance .
Author:
M. Kreutz
Date:
2001-05-04
Changes
none
Status
stable
Definition at line 395 of file VarianceEstimator.cpp.
References Model::modelDerivative().
double VarianceEstimator::estimateVarianceChange (Model & model, const Array< double > & inputA, const Array< double > & invInfMatA, const Array< double > & transInvInfMatA, double s2A) [static]
Estimates the change in the output variance after an active learning step.
When active learning takes place, i.e. a chosen input and its corresponding are added to the training set, the variance of the model will change. Then the variance change has to be computed to select optimally.
The expected change in output variance can be estimated by
where represents the expected values over and .
For a definition of , and please refer to method estimateFisherInformation.
The values used for the calculation of the variance change can be calculated by using method estimateInvFisher.
Parameters:
inputA The new input pattern that should be added to the training set.
invInfMatA The inverse Fisher information matrix.
transInvInfMatA A term that is used for the calculation of the variance change. For a definition of this term please refer to method estimateInvFisher.
s2A The current value of the negative log likelihood measure .
Returns:
Author:
M. Kreutz
Date:
2001-05-04
Changes
none
Status
stable
See also:
estimateInvFisher
Definition at line 451 of file VarianceEstimator.cpp.
References Model::modelDerivative().
double VarianceEstimator::overallVariance (Model & model, const Array< double > & inputA, const Array< double > & outputA) [static]
The estimated output variance of the network for all input patterns is returned.
The average variance over all input patterns is calculated by a stochastic estimate based on an average of with a reference point drawn according to the known input distribution (for a calculation of for a single reference point please refer to method estimateVariance).
The overall variance is then estimated by
where is the learners best guess for mapping inputs to outputs with as the weight vector of the network that minimizes the negative log likelihood measure , is the inverse Fisher information matrix (see method estimateFisherInformation for details) and represents the expected value over .
Parameters:
inputA The input patterns of the training set.
outputA The corresponding target values of the input patterns.
Returns:
The estimated output variance .
Exceptions:
check_exception the type of the exception will be "size mismatch" and indicates that inputA is not 2-dimensional
Author:
M. Kreutz
Date:
2001-05-04
Changes
none
Status
stable
Definition at line 315 of file VarianceEstimator.cpp.
References i, and Model::modelDerivative().
The documentation for this class was generated from the following files:
VarianceEstimator.h
VarianceEstimator.cpp