ReClaM: CMACMap Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
CMACMap Class Reference
The CMACMap class represents a simple non-linear function .
#include <CMAC.h>
Public Member Functions
CMACMap ()
CMACMap (size_t inputs, size_t outputs, size_t numberOfTilings, size_t numberOfTiles, double lower=0., double upper=1.)
construct the CMAC
CMACMap (size_t inputs, size_t outputs, size_t numberOfTilings, size_t numberOfTiles, Array< double > const &bounds)
construct the CMAC
void init (bool randomTiles=false)
initialize internal variables
void model (Array< double > const &input, Array< double > &output)
Returns the model's answer #output on the stimulus #input.
void modelDerivative (Array< double > const &input, Array< double > &derivative)
Calculates the derivative of the model output with respect to the parameters.
Array< double > getFeatureVector (Array< double > const &point) const
returns the mapped feature vector
Protected Member Functions
Array< size_t > getIndizes (Array< double > const &point) const
returns an index in the parameter array for each activated feature
Detailed Description
The CMACMap class represents a simple non-linear function .
Definition at line 50 of file CMAC.h.
Constructor & Destructor Documentation
CMACMap::CMACMap ()
Definition at line 35 of file CMAC.cpp.
CMACMap::CMACMap (size_t inputs, size_t outputs, size_t numberOfTilings, size_t numberOfTiles, double lower = 0., double upper = 1.)
construct the CMAC
Parameters:
inputs number of input dimensions
outputs number of output dimensions
numberOfTilings number of Tilings to be created
numberOfTiles amount of tiles per dimension
lower lower bound of input values
upper upper bound of input values
Definition at line 37 of file CMAC.cpp.
References i, Model::inputDimension, Model::outputDimension, and Model::parameter.
CMACMap::CMACMap (size_t inputs, size_t outputs, size_t numberOfTilings, size_t numberOfTiles, Array< double > const & bounds)
construct the CMAC
Parameters:
inputs number of input dimensions
outputs number of output dimensions
numberOfTilings number of Tilings to be created
numberOfTiles amount of tiles per dimension
bounds lower and upper bounts for every input dimension
Definition at line 75 of file CMAC.cpp.
References i, Model::inputDimension, Model::outputDimension, and Model::parameter.
Member Function Documentation
Array< double > CMACMap::getFeatureVector (Array< double > const & point) const
returns the mapped feature vector
Definition at line 163 of file CMAC.cpp.
References getIndizes().
Array< size_t > CMACMap::getIndizes (Array< double > const & point) const [protected]
returns an index in the parameter array for each activated feature
Definition at line 22 of file CMAC.cpp.
Referenced by getFeatureVector(), model(), and modelDerivative().
void CMACMap::init (bool randomTiles = false)
initialize internal variables
Parameters:
randomTiles if this is true, tilings will have a random offset
Definition at line 112 of file CMAC.cpp.
References Model::inputDimension.
void CMACMap::model (Array< double > const & input, Array< double > & output) [virtual]
Returns the model's answer #output on the stimulus #input.
This method calculates the output of the model depending on the #input. The arrays #input and #output can either be one- or two-dimensional, depending on whether one or many patterns should be processed. The number of elements in the last dimension of these arrays must fit the inputDimension and outputDimension, in case of two-dimensional input, the number of elements in the first dimension equals the number of patterns. The method is pure virtual as it has to be implemented by the different models.
Parameters:
input Vector of input values.
output Vector of output values.
Returns:
None.
Implements Model.
Definition at line 127 of file CMAC.cpp.
References getIndizes(), i, Model::outputDimension, and Model::parameter.
void CMACMap::modelDerivative (Array< double > const & input, Array< double > & derivative) [virtual]
Calculates the derivative of the model output with respect to the parameters.
This method performs the calculation of the model output with respect to the model parameters. Sometimes this calculation can only be performed based on a single input pattern; therefore #input must be a onedimensional array. As a default implementation, the derivatives are estimated numerically by using small variations epsilon:
However, to improve the speed, it is adviserable to overload this method by a more sophisticated calculation, depending on the method model. Nevertheless, this default implementation can be used to check new implementations of the derivative of the model with respect to the parameters.
Parameters:
input Vector of input values.
derivative Matrix of partial derivatives.
Reimplemented from Model.
Definition at line 178 of file CMAC.cpp.
References getIndizes(), Model::getParameterDimension(), and Model::outputDimension.
The documentation for this class was generated from the following files:
CMAC.h
CMAC.cpp