LinAlg: eigen.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
eigen.cpp File Reference
eigenvalues of arbitrary matrices
#include <Array/Array.h>
#include <LinAlg/LinAlg.h>
#include <cmath>
Functions
void Exc (Array< double > &A, Array< double > &D, int j, int k, int l, int m)
void Balanc (Array< double > &A, Array< double > &D, int &low, int &hi)
This function balances the elements of a non symmetric square matrix. Given a matrix n x n stored in a table of size n x n, that matrix is replaced by a balanced matrix having the same eigenvalues A symmetric matrix is not affected by this procedure.
void ElmHes (Array< double > &A)
Reduction of a non symmetric real matrix to Hessenberg form by the elimination method. Matrix A (n x n), stored in a table of size Maxc x Maxc, is replaced by a superior Hessenberg matrix having the same eigenvalues. It is recommanded to call previously the Balanc procedure. In output,the Hessenberg matrix has elements A(i, j) with i<=j+1. The elements for i>j+1, that in theory equal zero, are actually filled with random (not used) values.
void eigen (Array< double > amatA, Array< double > &vr, Array< double > &vi)
Calculates the eigenvalues of an arbitrary matrix "amatA" by balancing the elements of the matrix, then reducing it to an upper Hessenberg matrix and finally calculating the eigenvalues ot the reduced form.
Detailed Description
eigenvalues of arbitrary matrices
Copyright (c) 1998-2000:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file eigen.cpp.
Function Documentation
void Balanc (Array< double > & A, Array< double > & D, int & low, int & hi)
This function balances the elements of a non symmetric square matrix. Given a matrix n x n stored in a table of size n x n, that matrix is replaced by a balanced matrix having the same eigenvalues A symmetric matrix is not affected by this procedure.
Parameters:
A matrix
low first nonzero row.
high last nonzero row.
D Vector (1..n) containing enough information to trace the done permutations and the used scale factors.
Exceptions:
SharkException the type of the exception will be "size mismatch" and indicates that amatA is not a square matrix
Changes
previously 'eigensymm', renamed by S. Wiegand 2003/10/01
Status
stable
Definition at line 120 of file eigen.cpp.
References Exc().
Referenced by eigen().
void eigen (Array< double > amatA, Array< double > & vr, Array< double > & vi)
Calculates the eigenvalues of an arbitrary matrix "amatA" by balancing the elements of the matrix, then reducing it to an upper Hessenberg matrix and finally calculating the eigenvalues ot the reduced form.
Given a matrix A, this function calculates the eigenvalues defined as (x is the corresponding but not calculated eigenvector)
where x is a one-column matrix and the matrix multiplication is used for A and x.
Parameters:
amatA matrix.
vr real parts of eigenvalues
vi imaginary parts of eigenvalues
Exceptions:
SharkException the type of the exception will be "size mismatch" and indicates that amatA is not a square matrix
Changes
previously 'eigensymm', renamed by S. Wiegand 2003/10/01
Status
stable
Definition at line 576 of file eigen.cpp.
References Balanc(), and ElmHes().
Referenced by Matrix::eigenvalues().
void ElmHes (Array< double > & A)
Reduction of a non symmetric real matrix to Hessenberg form by the elimination method. Matrix A (n x n), stored in a table of size Maxc x Maxc, is replaced by a superior Hessenberg matrix having the same eigenvalues. It is recommanded to call previously the Balanc procedure. In output,the Hessenberg matrix has elements A(i, j) with i<=j+1. The elements for i>j+1, that in theory equal zero, are actually filled with random (not used) values.
Parameters:
A matrix
Status
stable
Definition at line 252 of file eigen.cpp.
Referenced by eigen().
void Exc (Array< double > & A, Array< double > & D, int j, int k, int l, int m)
Definition at line 43 of file eigen.cpp.
Referenced by Balanc().