LinAlg: eigensymm.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
eigensymm.cpp File Reference
Used to calculate the eigenvalues and the eigenvectors of a symmetric matrix.
#include <cmath>
#include <SharkDefs.h>
#include <LinAlg/LinAlg.h>
Functions
void eigensymm_intermediate (const Array2D< double > &amatA, Array2D< double > &hmatA, Array2D< double > &vmatA, Array< double > &dvecA)
Calculates the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction.
void eigensymm (const Array2D< double > &A, Array2D< double > &G, Array< double > &l)
Used as frontend for eigensymm(const Array2D<double> &amatA,Array2D<double> &vmatA,Array<double> &dvecA,Array<double> &odvecA) for calculating the eigenvalues and the normalized eigenvectors of a symmetric matrix 'amatA' using the Givens and Householder reduction. Each time this frontend is called additional memory is allocated for intermediate results.
void eigensymm (const Array2D< double > &amatA, Array2D< double > &vmatA, Array< double > &dvecA, Array< double > &odvecA)
Calculates the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction without corrupting "amatA" during application.
Detailed Description
Used to calculate the eigenvalues and the eigenvectors of a symmetric matrix.
Here the eigenvectors and eigenvalues are calculated by using Givens and Householder reduction of the matrix to tridiagonal form.
Author:
M. Kreutz
Date:
1998
Copyright (c) 1998-2000:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file eigensymm.cpp.
Function Documentation
void eigensymm (const Array2D< double > & A, Array2D< double > & G, Array< double > & l)
Used as frontend for eigensymm(const Array2D<double> &amatA,Array2D<double> &vmatA,Array<double> &dvecA,Array<double> &odvecA) for calculating the eigenvalues and the normalized eigenvectors of a symmetric matrix 'amatA' using the Givens and Householder reduction. Each time this frontend is called additional memory is allocated for intermediate results.
Used as frontend for eigensymm(const Array2D<double> &amatA,Array2D<double> &vmatA,Array<double> &dvecA,Array<double> &odvecA) for calculating the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction without corrupting "amatA" during application.
Frontend for function eigensymm(const Array2D<double> &amatA,Array2D<double> &vmatA,Array<double> &dvecA,Array<double> &odvecA), when memory for 'odvecA' should be allocated by the call of this frontend.
Parameters:
A matrix, which must be symmetric, so only the bottom triangular matrix must contain values.
G matrix with the calculated normalized eigenvectors, each column will contain one eigenvector.
l n-dimensional vector with the calculated eigenvalues in descending order.
Returns:
none.
Exceptions:
SharkException
Author:
S. Wiegand
Date:
2003
Changes
none
Status
stable
Examples:
eigensymm_test.cpp.
Definition at line 426 of file eigensymm.cpp.
References eigensymm().
Referenced by eigensymm(), and invertSymm().
void eigensymm (const Array2D< double > & amatA, Array2D< double > & vmatA, Array< double > & dvecA, Array< double > & odvecA)
Calculates the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction without corrupting "amatA" during application.
Calculates the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction.
Given a symmetric matrix A, this function calculates the eigenvalues and the eigenvectors x, defined as
where x is a one-column matrix and the matrix multiplication is used for A and x. Here, the Givens reduction as a modification of the Jacobi method (s.a. eigensymmJacobi) is used. Instead of trying to reduce the matrix all the way to diagonal form, we are content to stop when the matrix is tridiagonal. This allows the function to be carried out in a finite number of steps, unlike the Jacobi method, which requires iteration to convergence. So in comparison to the Jacobi method, this function is faster for matrices with an order greater than 10.
Parameters:
amatA matrix, which must be symmetric, so only the bottom triangular matrix must contain values.
vmatA matrix with the calculated normalized eigenvectors, each column will contain an eigenvector.
dvecA n-dimensional vector with the calculated eigenvalues in descending order.
odvecA n-dimensional vector with the calculated offdiagonal of the Householder transformation.
Returns:
none.
Exceptions:
SharkException Please follow the link to view the source code of the example. The example can be executed in the example directory of package LinAlg.
Author:
M. Kreutz
Date:
1998
Changes
2003/09/19 18:55:22 S. Wiegand lower triangular part of 'amatA' will not corrupted anymore
Status
stable
Definition at line 556 of file eigensymm.cpp.
References eigensort().
void eigensymm_intermediate (const Array2D< double > & amatA, Array2D< double > & hmatA, Array2D< double > & vmatA, Array< double > & dvecA)
Calculates the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction.
Calculates the eigenvalues and the normalized eigenvectors of a symmetric matrix "amatA" using the Givens and Householder reduction, however, "hmatA" contains intermediate results after application.
Given a symmetric matrix A, this function calculates the eigenvalues and the eigenvectors x, defined as
where x is a one-column matrix and the matrix multiplication is used for A and x. Here, the Givens reduction as a modification of the Jacobi method (s.a. eigensymmJacobi) is used. Instead of trying to reduce the matrix all the way to diagonal form, we are content to stop when the matrix is tridiagonal. This allows the function to be carried out in a finite number of steps, unlike the Jacobi method, which requires iteration to convergence. So in comparison to the Jacobi method, this function is faster for matrices with an order greater than 10.
Parameters:
amatA matrix, which must be symmetric, so only the bottom triangular matrix must contain values. Values below the diagonal will be destroyed. The method uses this matrix as a buffer for intermediate results.
hmatA matrix, that is used to store intermediate results (other methods like detsymm use these for further calculations)
vmatA matrix with the calculated normalized eigenvectors, each column will contain an eigenvector.
dvecA n-dimensional vector with the calculated eigenvalues in descending order.
Returns:
none.
Exceptions:
SharkException
Author:
M. Kreutz
Date:
1998
Changes
previously 'eigensymm', renamed by S. Wiegand 2003/10/01
Status
stable
Examples:
eigenerr_test.cpp, and rank_test.cpp.
Definition at line 98 of file eigensymm.cpp.
References eigensort().
Referenced by detsymm(), logdetsymm(), and rankDecomp().