LinAlg: eigensort.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
eigensort.cpp File Reference
Used to sort eigenvalues and their corresponding eigenvectors.
#include <cmath>
#include <SharkDefs.h>
#include <LinAlg/LinAlg.h>
Functions
void eigensort (Array2D< double > &vmatA, Array< double > &dvecA)
Sorts the eigenvalues in vector "dvecA" and the corresponding eigenvectors in matrix "vmatA".
Detailed Description
Used to sort eigenvalues and their corresponding eigenvectors.
Author:
M. Kreutz
Date:
1998
Copyright (c) 1998-2000:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file eigensort.cpp.
Function Documentation
void eigensort (Array2D< double > & vmatA, Array< double > & dvecA)
Sorts the eigenvalues in vector "dvecA" and the corresponding eigenvectors in matrix "vmatA".
Sorts the eigenvalues in vector "dvecA" in descending order and the corresponding eigenvectors in matrix "vmatA".
Given the matrix vmatA of eigenvectors and the vector dvecA of corresponding eigenvalues, the values in dvecA will be sorted by descending order and the eigenvectors in vmatA will change their places in a way, that at the end of the function an eigenvalue at position j of vector dvecA will belong to the eigenvector at column j of matrix vmatA. If we've got for example the following result after calling the function:
then eigenvalue has the corresponding eigenvector and .
Parameters:
vmatA matrix with eigenvectors (each column contains an eigenvector, corresponding to one eigenvalue).
dvecA n-dimensional vector with eigenvalues, will contain the eigenvalues in descending order when returning from the function.
Returns:
none.
Exceptions:
SharkException the type of the exception will be "size mismatch" and indicates that dvecA is not one-dimensional or that the number of rows or the number of columns in vmatA is different from the number of values in dvecA
Please follow the link to view the source code of the example. The example can be executed in the example directory of package LinAlg.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Examples:
eigensort_test.cpp.
Definition at line 100 of file eigensort.cpp.
Referenced by eigensymm(), eigensymm_intermediate(), eigensymmJacobi(), and eigensymmJacobi2().