LinAlg: fft.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
fft.cpp File Reference
Functions for performing a fast fourier transformation.
#include "LinAlg/fft.h"
Functions
void fft (Array< std::complex< double > > &data, int isign)
Depending on the value of "isign" the "data" is replaced by its discrete Fourier transform or by its inverse discrete Fourier transform.
void ifft (Array< std::complex< double > > &data)
Replaces the "data" by its inverse discrete Fourier transform.
void fft (Array< std::complex< double > > &data)
Replaces the "data" by its discrete Fourier transform.
Detailed Description
Functions for performing a fast fourier transformation.
The Fourier transformation is often used in the technical sector, e.g. in the communications engineering.
In general a physical process can be described either in the time domain, by the value of some quantity as a function of time , e.g. , or else in the frequency domain, where the process is specified by giving its amplitude (generally a complex number indicating phase also) as a function of frequency , that is , with . It is often useful to think of and as being two different representations of the same function. You can go back and forth between these two representations by means of the Fourier transform equations and .
If the function is given by a finite number of sample points , then the discrete Fourier transform of this function can be calculated by .
The discrete inverse Fourier transform is then given by .
The discrete Fourier transformation has the calculation time of , that can be critical for great .
The "fast" Fourier transformation uses the fact, that a discrete Fourier transform of length can be rewritten as the sum of two discrete Fourier transforms, each of length , where one of the two is formed from the even-numbered points and the other from the odd-numbered points. Then using this splitting recursively we finally have transforms of length 1, which are just the identity operation. By this way the calculation time can be decreased to . To use this algorithm, the number of sample points must be an integer power of two. The following example will show how the functions in this file are used:
You can find, compile and run this example in "$SHARK_ROOTDIR/LinAlg/examples".
Author:
M. Kreutz
Date:
1998
Copyright (c) 1998-2000:
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file fft.cpp.
Function Documentation
void fft (Array< std::complex< double > > & data, int isign)
Depending on the value of "isign" the "data" is replaced by its discrete Fourier transform or by its inverse discrete Fourier transform.
When isign is set to "-1", then is calculated.
When isign is set to "1", then is calculated.
Please notice, that the number of sample points in data must be an integer power of 2. If there are not enough sample points, create the data array with a size equal to the next higher power of 2 and fill the last empty positions of the array with zero values.
Parameters:
data The original sample data (in the time or frequency domain), that will be replaced by its corresponding data of the other domain.
isign Determines the type of transformation.
"-1" = a discrete Fourier transform is performed,
"1" = an inverse Fourier transform is performed
Returns:
none.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Examples:
fft_test.cpp.
Definition at line 118 of file fft.cpp.
Referenced by fft(), and ifft().
void fft (Array< std::complex< double > > & data)
Replaces the "data" by its discrete Fourier transform.
is calculated.
Please notice, that the number of sample points in data must be an integer power of 2. If there are not enough sample points, create the data array with a size equal to the next higher power of 2 and fill the last empty positions of the array with zero values.
Parameters:
data The original sample data of the time domain, that will be replaced by its corresponding data of the frequency domain.
Returns:
none.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 242 of file fft.cpp.
References fft().
void ifft (Array< std::complex< double > > & data)
Replaces the "data" by its inverse discrete Fourier transform.
is calculated.
Please notice, that the number of sample points in data must be an integer power of 2. If there are not enough sample points, create the data array with a size equal to the next higher power of 2 and fill the last empty positions of the array with zero values.
Parameters:
data The original sample data of the frequency domain, that will be replaced by its corresponding data of the time domain.
Returns:
none.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Examples:
fft_test.cpp.
Definition at line 208 of file fft.cpp.
References fft().