FileUtil: FileUtil Namespace Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
FileUtil Namespace Reference
Enumerations
enum iotype { SetDefault, ScanFrom, PrintTo }
Used for the functions "io" and "io_strict" to define the kind of action, that should be performed.
Functions
bool special_character (std::istream &is, char *ch)
Checks, whether the given character "ch" introduces a newline or tabulator.
bool skipLine (std::istream &is, char *ch)
Skips one line while reading from the input stream "is".
unsigned long filesize (std::istream &is)
Returns the number of characters in input stream "is".
unsigned long filesize (std::ostream &os)
Returns the number of characters in output stream "os".
unsigned long filesize (const std::string &name)
Returns the number of characters in file "name".
unsigned long readfile (std::istream &is, std::string &buf)
The whole content of input stream "is" is stored in "buf".
unsigned long readfile (const std::string &name, std::string &buf)
The whole content of file "name" is stored in "buf".
void skipuntil (std::istream &is, const std::string &token)
Reads from input stream "is" until "token" is found.
char gettoken (std::istream &is, std::string &token, const std::string &delim)
Reads the first token from input stream "is".
template<>
bool scanFrom (std::istream &is, const std::string &token, std::string &t, bool rew)
Reads the single value of a token from input stream "is".
template<>
bool scanFrom (std::istream &is, const std::string &token, std::vector< std::string > &t, bool rew)
Reads one or several values of a token from input stream "is".
template<>
bool printTo (std::ostream &os, const std::string &token, const std::string &t)
Writes a token and its single value "t" to output stream "os".
template<>
bool printTo (std::ostream &os, const std::string &token, const std::vector< std::string > &t)
Writes a token and its value(s) "t" to output stream "os".
void rewind (std::istream &is)
The get pointer is set to the beginning of stream "is".
void rewind (std::ostream &os)
The put pointer is set to the beginning of stream "os".
template<class T >
bool scanFrom (std::istream &is, const std::string &token, T &t, bool rew=false)
Reads the single value of a token from input stream "is". Very simple version.
template<class T >
bool printTo (std::ostream &os, const std::string &token, const T &t)
Writes a token and its single value "t" to output stream "os". Very simple version.
template<class T >
void io (std::istream &is, std::ostream &os, const std::string &token, T &val, const T &defval, iotype type)
An easy to use interface to perform the three actions needed for a token.
template<class T >
void io_strict (std::istream &is, std::ostream &os, const std::string &token, T &val, const T &defval, iotype type)
An easy to use interface to perform the three actions needed for a token. A very strict version, used for a special format.
template<class T >
bool scanLine_strict (std::istream &is, const std::string &token, T &t)
Reads the single value of a token from input stream "is". A very strict version, used for a special format.
template<class T >
bool scanFrom_strict (std::istream &is, const std::string &token, T &t, bool rew=false)
Reads the single value of a token from input stream "is". A very strict version, used for a special format. This function is used to offer the same parameter format than #scanFrom(std::istream& is, const std::string& token, T& t, bool rew = false).
template<class T >
bool printTo_strict (std::ostream &os, const std::string &token, const T &t)
Writes a token and its single value "t" to output stream "os". A very strict version, used for a special format.
Enumeration Type Documentation
enum FileUtil::iotype
Used for the functions "io" and "io_strict" to define the kind of action, that should be performed.
SetDefault - The given token value will be initialized by the given default value.
ScanFrom - The value for the given token will be read from the given input stream
PrintTo - The given token and its value are written to the given output stream
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Enumerator:
SetDefault
ScanFrom
PrintTo
Definition at line 297 of file FileUtil.h.
Function Documentation
unsigned long FileUtil::filesize (std::istream & is)
Returns the number of characters in input stream "is".
Given the input stream "is", the number of characters in this file is returned. The position of the get pointer is not finally changed by this function.
Parameters:
is The input stream to count the characters in.
Returns:
The number of characters in the stream.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 179 of file FileUtil.cpp.
Referenced by filesize().
unsigned long FileUtil::filesize (std::ostream & os)
Returns the number of characters in output stream "os".
Given the output stream "os", the number of characters in this file is returned. The position of the put pointer is not finally changed by this function.
Parameters:
os The output stream to count the characters in.
Returns:
The number of characters in the stream.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 217 of file FileUtil.cpp.
unsigned long FileUtil::filesize (const std::string & name)
Returns the number of characters in file "name".
Parameters:
name Name of the file.
Returns:
The number of characters in the file or zero, when the file can't be opened.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 252 of file FileUtil.cpp.
References filesize().
char FileUtil::gettoken (std::istream & is, std::string & token, const std::string & delim)
Reads the first token from input stream "is".
Tokens are separated by delimiters. The string delim is used to enumerate all characters used as delimiters. The delimiters are used then to identify the first token. Any leading delimiters are ignored. An iterative usage of this function will read token after token, because the get pointer is set to the first delimiter after the next token.
Parameters:
is The input stream the token is read from.
token Used to store the token that is read from is.
delim String of characters that are used as delimiters. By default the whitespace character, the tabulator, the carriage return, the newline character, the vertical tabulator and the form feed character are used as delimiters.
Returns:
The first delimiter after the token.
Author:
M. Kreutz
Date:
1998
Changes
2002-01-03, ra: The first character of a token was ignored, when no whitespace followed the leading delimiters - fixed.
Status
stable
Definition at line 432 of file FileUtil.cpp.
template<class T > void FileUtil::io (std::istream & is, std::ostream & os, const std::string & token, T & val, const T & defval, iotype type) [inline]
An easy to use interface to perform the three actions needed for a token.
You can use this function to specify all information for a token once and then initialize it with a default value or read a new value for it from an input stream or write the token and its already given value to an output stream. This can be done by using different values for the action indicator type.
Use this function with caution, if you are using it for reading the value of a token from input stream is, because a string read from the input stream is identified as the searched token when this searched token is a prefix of this string, e.g. if you are searching for a token "a" and one line of the input stream begins with "ab".
This is especially dangerous when using short token names.
If you are using token names of this kind or are not sure, that the scenario above won't occur, use function io_strict instead.
Parameters:
is The input stream used, when reading a token value.
os The output stream used, when writing the token and its value.
token The token used for initializing/reading/writing.
val Used to store the current value of the token.
defval The default value that is used for initialization.
type The action indicator. See iotype definition for the different values and their meanings.
Returns:
None.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 345 of file FileUtil.h.
References printTo(), PrintTo, scanFrom(), ScanFrom, and SetDefault.
template<class T > void FileUtil::io_strict (std::istream & is, std::ostream & os, const std::string & token, T & val, const T & defval, iotype type) [inline]
An easy to use interface to perform the three actions needed for a token. A very strict version, used for a special format.
You can use this function to specify all information for a token once and then initialize it with a default value or read a new value for it from an input stream or write the token and its already given value to an output stream. This can be done by using different values for the action indicator type.
This function here is used to prevent a disadvantage of io, when reading a token value from an input stream. There a string read from the input stream is identified as the searched token when this searched token is a prefix of this string, e.g. if you are searching for a token "a" and one line of the input stream begins with "ab".
This is especially dangerous when using short token names.
Parameters:
is The input stream used, when reading a token value.
os The output stream used, when writing the token and its value.
token The token used for initializing/reading/writing.
val Used to store the current value of the token.
defval The default value that is used for initialization.
type The action indicator. See iotype definition for the different values and their meanings.
Returns:
None.
Author:
R. Alberts
Date:
1999
Changes
2002-01-03, ra
Renamed to from "io2" to "io_strict" for unification, new function "printTo_strict" added.
Status
stable
Examples:
FileUtilClass.cpp.
Definition at line 406 of file FileUtil.h.
References PrintTo, printTo_strict(), ScanFrom, scanFrom_strict(), and SetDefault.
template<class T > bool FileUtil::printTo (std::ostream & os, const std::string & token, const T & t) [inline]
Writes a token and its single value "t" to output stream "os". Very simple version.
If you want to create files that can be used to initialize variables, you can use this function. The value t for a variable with name token will be written to output stream os. The data is written in a formatted manner, i.e. the width of a token-value line is always 40 characters and the token and its value are separated by "_" characters.
Please notice that the formatted output is ignored by older compilers.
In contrast to the other "printTo" functions the token value can not include escape sequences. The disadvantage of the other "printTo" functions is, that the token values must always be stored in strings, independend from their real type. Here you can use a copy of the original value without casting it to string before.
This is the opposite function of #scanFrom(std::istream& is, const std::string& token, T& t, bool rew = false).
Parameters:
os The input stream the token and its value are written to.
token The token that will be written.
t The token value that will be written.
Returns:
"true", if no error occured while writing to os, "false" otherwise.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 238 of file FileUtil.h.
References printTo().
template<> bool FileUtil::printTo (std::ostream & os, const std::string & token, const std::string & t)
Writes a token and its single value "t" to output stream "os".
If you want to create files that can be used to initialize variables, you can use this function. The value t for a variable with name token will be written to output stream os. t can include tabulator characters, carriage returns, newlines, vertical tabulators, alert bells, form feeds, backspaces and escape characters.
This is the opposite function of scanFrom(std::istream& is, const std::string& token, std::string& t, bool rew).
Parameters:
os The input stream the token and its value are written to.
token The token that will be written.
t The token value that will be written.
Returns:
"true", if no error occured while writing to os, "false" otherwise.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 795 of file FileUtil.cpp.
Referenced by io(), and printTo().
template<> bool FileUtil::printTo (std::ostream & os, const std::string & token, const std::vector< std::string > & t)
Writes a token and its value(s) "t" to output stream "os".
If you want to create files that can be used to initialize variables, you can use this function. The value(s) t for a variable with name token will be written to output stream os. Each single value in t can include tabulator characters, carriage returns, newlines, vertical tabulators, alert bells, form feeds, backspaces and escape characters.
This is the opposite function of scanFrom(std::istream& is, const std::string& token, std::vector< std::string >& t, bool rew).
Parameters:
os The input stream the token and its value(s) are written to.
token The token that will be written.
t The value(s) of the token that will be written.
Returns:
"true", if no error occured while writing to os, "false" otherwise.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 835 of file FileUtil.cpp.
template<class T > bool FileUtil::printTo_strict (std::ostream & os, const std::string & token, const T & t) [inline]
Writes a token and its single value "t" to output stream "os". A very strict version, used for a special format.
If you want to create files that can be used to initialize variables, you can use this function. The value t for a variable with name token will be written to output stream os.
Before writing the token name and its value, the token name is checked for the right format:
The first character of a token name must be a letter or an underscore, all further characters must be a letter, a digit or an underscore. If this format is not satisfied, the function will exit with an error message.
This function is the opposite function of scanFrom_strict(std::istream&, const std::string&, T&, bool).
Parameters:
os The input stream the token and its value are written to.
token The token that will be written.
t The token value that will be written.
Returns:
"true", if no error occured while writing to os, "false" otherwise.
Author:
R. Alberts
Date:
2002-01-03
Changes
none
Status
stable
Definition at line 624 of file FileUtil.h.
Referenced by io_strict().
unsigned long FileUtil::readfile (std::istream & is, std::string & buf)
The whole content of input stream "is" is stored in "buf".
All characters in input stream is are read and stored in buffer buf. The current position of the get pointer is not finally changed.
Parameters:
is Input stream from which the content is read.
buf Buffer where the content of is is stored in.
Returns:
The number of characters read from is.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 285 of file FileUtil.cpp.
Referenced by readfile(), and Params::scanFrom().
unsigned long FileUtil::readfile (const std::string & name, std::string & buf)
The whole content of file "name" is stored in "buf".
All characters in the file named name are read and stored in buffer buf. The current position of the get pointer is not finally changed.
Parameters:
name Name of file from which the content is read.
buf Buffer where the content of file name is stored in. If name doesn't exist, the buffer is empty.
Returns:
The number of characters read from name, or "0", when the file doesn't exist.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 332 of file FileUtil.cpp.
References readfile().
void FileUtil::rewind (std::istream & is) [inline]
The get pointer is set to the beginning of stream "is".
Parameters:
is The input stream.
Returns:
None.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 82 of file FileUtil.h.
Referenced by scanFrom(), and scanFrom_strict().
void FileUtil::rewind (std::ostream & os) [inline]
The put pointer is set to the beginning of stream "os".
Parameters:
os The output stream.
Returns:
None.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 104 of file FileUtil.h.
template<> bool FileUtil::scanFrom (std::istream & is, const std::string & token, std::string & t, bool rew)
Reads the single value of a token from input stream "is".
This function is used for files that contain initialization values for variables. The name of the variable is used as search token and the value following these token is stored and can be used as new value for the variable with name token. To identify the token value (and to differentiate it from the token itself) it can be enclosed in quotation marks or inverted commas. The value can include tabulator characters, carriage returns, newlines, vertical tabulators, alert bells, form feeds, backspaces and escape characters, but no whitespaces.
This is the opposite function of printTo(std::ostream& os, const std::string& token, const std::string& t).
Parameters:
is The input stream the token value is read from.
token The token for which the value is read.
t Used to store the token value found. Note, that the value is stored as string, independend from its original type.
rew If set to "true", the search will start at the beginning of the stream; if set to "false" the search will start at the current position of the get pointer.
Returns:
"true", if no error occured while reading from is, "false" otherwise.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 599 of file FileUtil.cpp.
References rewind(), and skipuntil().
Referenced by io(), and scanFrom().
template<class T > bool FileUtil::scanFrom (std::istream & is, const std::string & token, T & t, bool rew = false) [inline]
Reads the single value of a token from input stream "is". Very simple version.
This is the opposite function of printTo(std::ostream& os, const std::string& token, const T& t). and is used for files that contain initialization values for variables. The name of the variable is used as search token and the value following these token is stored and can be used as new value for the variable with name token.
In contrast to the other "scanFrom" functions you can not enclose the token value in quotation marks or inverted commas for a better identification, nor can the token value include escape sequences. The disadvantage of the other "scanFrom" functions is, that the token values are always stored in strings, independend from their real type. Here you can use a buffer t with the right type.
Use this function with caution, because a string read from the input stream is identified as the searched token when this searched token is a prefix of this string, e.g. if you are searching for a token "a" and one line of the input stream begins with "ab".
This is especially dangerous when using short token names.
If you are using token names of this kind or are not sure, that the scenario above won't occur, use function scanFrom_strict(std::istream& is, const std::string& token, T& t, bool rew = false) instead.
Parameters:
is The input stream the token value is read from.
token The token for which the value is read.
t Used to store the token value found.
rew If set to "true", the search will start at the beginning of the stream; if set to "false" (default value) the search will start at the current position of the get pointer.
Returns:
"true", if no error occured while reading from is, "false" otherwise.
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 181 of file FileUtil.h.
References rewind(), scanFrom(), and skipuntil().
template<> bool FileUtil::scanFrom (std::istream & is, const std::string & token, std::vector< std::string > & t, bool rew)
Reads one or several values of a token from input stream "is".
Reads one or several values of a token.
This function is used for files that contain initialization values for variables. The name of the variable is used as search token and the value(s) following these token are stored and can be used as new value(s) for the variable with name token. To identify the token value(s) (and to differentiate it/them from the token itself), each single value can be enclosed in quotation marks or inverted commas. If more than one value is used, the list of all values must be enclosed in parentheses. Values can include tabulator characters, carriage returns, newlines, vertical tabulators, alert bells, form feeds, backspaces and escape characters, but no whitespaces.
This is the opposite function of printTo(std::ostream& os, const std::string& token, const std::vector< std::string >& t).
Parameters:
is The input stream the token value(s) is/are read from.
token The token for which the value(s) is/are read.
t All token values found are stored in this vector. Note, that the value(s) is/are stored as string(s), independend from its/their original type(s).
rew If set to "true", the search will start at the beginning of the stream; if set to "false" the search will start at the current position of the get pointer.
Returns:
"true", if no error occured while reading from is, "false" otherwise.
Example
If you call the function three times for a file with the content shown above it first will read the values , and for a double variable with the name , then the single value for a variable named and finally the value (note, that this value is not enclosed in quotation marks or inverted commas) for an integer variable named .
Author:
M. Kreutz
Date:
1998
Changes
none
Status
stable
Definition at line 667 of file FileUtil.cpp.
References rewind(), and skipuntil().
template<class T > bool FileUtil::scanFrom_strict (std::istream & is, const std::string & token, T & t, bool rew = false) [inline]
Reads the single value of a token from input stream "is". A very strict version, used for a special format. This function is used to offer the same parameter format than #scanFrom(std::istream& is, const std::string& token, T& t, bool rew = false).
See function #scanFrom_strict(std::istream& is, const std::string& token, T& t) for a description of the functioning. This function here is used to prevent a disadvantage of #scanFrom(std::istream& is, const std::string& token, T& t, bool rew = false), where a string read from the input stream is identified as the searched token when this searched token is a prefix of this string, e.g. if you are searching for a token "a" and one line of the input stream begins with "ab".
This is especially dangerous when using short token names.
This function here is the opposite function of printTo_strict.
Parameters:
is The input stream the token value is read from.
token The token for which the value is read.
t Used to store the token value found.
rew If set to "true", the search will start at the beginning of the stream; if set to "false" (default value) the search will start at the current position of the get pointer.
Returns:
"true", if no error occured while reading from is, "false" otherwise.
Author:
R. Alberts
Date:
1999
Changes
Renamed from "scanFrom2" to "scanFrom_strict" for unification.
Status
stable
Examples:
FileUtilSimple.cpp.
Definition at line 571 of file FileUtil.h.
References rewind(), and scanLine_strict().
Referenced by io_strict().
template<class T > bool FileUtil::scanLine_strict (std::istream & is, const std::string & token, T & t)
Reads the single value of a token from input stream "is". A very strict version, used for a special format.
This function is used for files that contain initialization values for variables. The name of the variable is used as search token and the value following these token is stored and can be used as new value for the variable with name token.
In contrast to the other "scanFrom" functions the files used for this function must have a very strict format:
Each line contains the token name AND its corresponding value, it is not allowed to store the token name in one line and its value in the next line. Furthermore, each token name stands at the beginning of a line, no leading whitespaces or tabulators are allowed. The first character of a token name must be a letter or an underscore, all further characters must be a letter, a digit or an underscore. The token name and the token value are separated by whitespaces and/or tabulators, no other delimiters are allowed. The token name read from the stream must match the token name given exactly.
Parameters:
is The input stream the token value is read from.
token The token for which the value is read from is.
t The value of the token.
Returns:
"true", if the token and its value are found; "false", if the token or its value are not found or if an error occured while reading from is.
Author:
R. Alberts
Date:
1999
Changes
2002-01-03, ra:
Renamed from "scanLine" to "scanLine_strict" for unification.
Status
stable
Definition at line 466 of file FileUtil.h.
References skipLine(), and special_character().
Referenced by scanFrom_strict().
bool FileUtil::skipLine (std::istream & is, char * ch)
Skips one line while reading from the input stream "is".
This function reads from the given input stream is, starting at the current position of the get pointer and searches for the next newline character if available. When a newline exists, the whole line was read in and so the position of the get pointer set to the beginning of the next line.
Parameters:
is The input stream from which is read.
ch At the end of the function you can find the last character that was read here (a newline in normal case).
Returns:
"true", when a newline was found, "false" when the end of file was reached before or a character couldn't be read.
Author:
R. Alberts
Date:
1999
Changes
none
Status
stable
Definition at line 144 of file FileUtil.cpp.
References special_character().
Referenced by scanLine_strict().
void FileUtil::skipuntil (std::istream & is, const std::string & token)
Reads from input stream "is" until "token" is found.
Starting at the current position of the get pointer, it is searched for the next occurence of token. If the token is found, the get pointer is set to the first position after the token, otherwise the pointer is set to the end of the file.
Parameters:
is The input stream.
token A string for which is searched in is. If the string is empty, the function returns immediately.
Returns:
None.
Author:
M. Kreutz
Date:
1995
Changes
none
Status
stable
Definition at line 371 of file FileUtil.cpp.
Referenced by scanFrom().
bool FileUtil::special_character (std::istream & is, char * ch)
Checks, whether the given character "ch" introduces a newline or tabulator.
Escape sequences like the tabulator or the newline consist of two characters. The first one is the escape character "\\" that marks the beginning of an escape sequence, the second one is the type of sequence ("t" for tabulator, "n" for newline). This function takes the given character ch, checks, whether this character is an escape character and when this is true, reads in the next character from the given input stream is. If the next character is a "t" or "n", then "true" is returned.
Parameters:
is The input stream from which the first character was taken and the next character can be read.
ch The first character that was read from the input stream and is checked for the escape character.
Returns:
"true", when ch introduces a newline or tabulator, "false" otherwise.
Author:
R. Alberts
Date:
1999
Changes
none
Status
stable
Definition at line 99 of file FileUtil.cpp.
Referenced by scanLine_strict(), and skipLine().