MOO-EALib: Hypervolume.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Hypervolume.h File Reference
Implementation of several algorithms for calculating the hypervolume of a set of points.
Functions
double overmars_yap (double *points, double *referencePoint, unsigned noObjectives, unsigned noPoints)
Implementation of the Overmars-Yap Algorithm, originally provided by N. Beume.
double hypervolume (double *points, double *referencePoint, unsigned int noObjectives, unsigned int noPoints)
computation of the hypervolume
Detailed Description
Implementation of several algorithms for calculating the hypervolume of a set of points.
======================================================================
Author:
Thomas Voß <thomas.voss@rub.de>
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
MOO-EALib
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cam√¢bridge, MA 02139, USA.
======================================================================
Author:
Thomas Voß <thomas.voss@rub.de>
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: Shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
MOO-EALib
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cam‚bridge, MA 02139, USA.
Definition in file Hypervolume.h.
Function Documentation
double hypervolume (double * points, double * referencePoint, unsigned int noObjectives, unsigned int noPoints)
computation of the hypervolume
This function acts as a frontend to various algorithms for the computation of the hypervolume.
Parameters:
points the list containes the coordinates of all points in a single array
referencePoint the reference or nadir point
noObjectives number of coordinates per point
noPoints number of points in the list
Returns:
dominated hypervolume
Definition at line 495 of file Hypervolume.cpp.
References LastObjectiveComparator::compare(), h(), LastObjectiveComparator::NO_OBJECTIVES, and overmars_yap().
double overmars_yap (double * points, double * referencePoint, unsigned noObjectives, unsigned noPoints)
Implementation of the Overmars-Yap Algorithm, originally provided by N. Beume.
Applicable to points of dimension d >= 3. It is assumed that the array of points is sorted according to the 'last' objective.
 author = {Nicola Beume and G"unther Rudolph},
 title = {Faster {S}-Metric Calculation By Considering Dominated Hypervolume as {Klee}'s Measure Problem},
 booktitle = {IASTED International Conference on Computational Intelligence},
 publisher = {ACTA Press},
 pages = {231-236},
 year = {2006},
Definition at line 82 of file Hypervolume.cpp.
References stream().
Referenced by hypervolume(), and HypervolumeIndicator::operator()().