MOO-EALib: Hypervolume.cpp File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
Hypervolume.cpp File Reference
#include <SharkDefs.h>
#include <MOO-EALib/Hypervolume.h>
#include <algorithm>
#include <cmath>
#include <vector>
#include <errno.h>
Classes
struct LastObjectiveComparator
Comparison of the last component of two fitness vectors.
Functions
int compare (const void *a, const void *b)
int covers (double *cuboid, double *regionLow)
int partCovers (double *cuboid, double *regionUp)
int containsBoundary (double *cub, double *regLow, int split)
double getMeasure (double *regionLow, double *regionUp)
int isPile (double *cuboid, double *regionLow, double *regionUp)
int binaryToInt (int *bs)
void intToBinary (int i, int *result)
double computeTrellis (double *regLow, double *regUp, double *trellis)
double getMedian (double *bounds, int length)
double stream (double *regionLow, double *regionUp, double *points, unsigned noPoints, int split, double cover)
double overmars_yap (double *points, double *referencePoint, unsigned noObjectives, unsigned noPoints)
Implementation of the Overmars-Yap Algorithm, originally provided by N. Beume.
int double_compare (const void *p1, const void *p2)
int cmp (const void *p1, const void *p2)
void sortByLastObjective (double *points, unsigned int noObjectives, unsigned int noPoints)
double hypervolume (double *points, double *referencePoint, unsigned int noObjectives, unsigned int noPoints)
computation of the hypervolume
Function Documentation
int binaryToInt (int * bs)
Definition at line 171 of file Hypervolume.cpp.
Referenced by computeTrellis().
int cmp (const void * p1, const void * p2)
Definition at line 450 of file Hypervolume.cpp.
Referenced by sortByLastObjective().
int compare (const void * a, const void * b)
Definition at line 54 of file Hypervolume.cpp.
double computeTrellis (double * regLow, double * regUp, double * trellis)
Definition at line 201 of file Hypervolume.cpp.
References binaryToInt(), and intToBinary().
Referenced by stream().
int containsBoundary (double * cub, double * regLow, int split)
Definition at line 125 of file Hypervolume.cpp.
Referenced by stream().
int covers (double * cuboid, double * regionLow)
Definition at line 105 of file Hypervolume.cpp.
Referenced by stream().
int double_compare (const void * p1, const void * p2)
Definition at line 240 of file Hypervolume.cpp.
Referenced by getMedian().
double getMeasure (double * regionLow, double * regionUp)
Definition at line 139 of file Hypervolume.cpp.
Referenced by stream().
double getMedian (double * bounds, int length)
Definition at line 252 of file Hypervolume.cpp.
References double_compare().
Referenced by stream().
double hypervolume (double * points, double * referencePoint, unsigned int noObjectives, unsigned int noPoints)
computation of the hypervolume
This function acts as a frontend to various algorithms for the computation of the hypervolume.
Parameters:
points the list containes the coordinates of all points in a single array
referencePoint the reference or nadir point
noObjectives number of coordinates per point
noPoints number of points in the list
Returns:
dominated hypervolume
Definition at line 495 of file Hypervolume.cpp.
References LastObjectiveComparator::compare(), h(), LastObjectiveComparator::NO_OBJECTIVES, and overmars_yap().
void intToBinary (int i, int * result)
Definition at line 183 of file Hypervolume.cpp.
Referenced by computeTrellis().
int isPile (double * cuboid, double * regionLow, double * regionUp)
Definition at line 151 of file Hypervolume.cpp.
Referenced by stream().
double overmars_yap (double * points, double * referencePoint, unsigned noObjectives, unsigned noPoints)
Implementation of the Overmars-Yap Algorithm, originally provided by N. Beume.
Applicable to points of dimension d >= 3. It is assumed that the array of points is sorted according to the 'last' objective.
 author = {Nicola Beume and G"unther Rudolph},
 title = {Faster {S}-Metric Calculation By Considering Dominated Hypervolume as {Klee}'s Measure Problem},
 booktitle = {IASTED International Conference on Computational Intelligence},
 publisher = {ACTA Press},
 pages = {231-236},
 year = {2006},
Examples:
HypervolumeBenchmark.cpp.
Definition at line 82 of file Hypervolume.cpp.
References stream().
Referenced by hypervolume(), and HypervolumeIndicator::operator()().
int partCovers (double * cuboid, double * regionUp)
Definition at line 116 of file Hypervolume.cpp.
Referenced by stream().
void sortByLastObjective (double * points, unsigned int noObjectives, unsigned int noPoints)
Definition at line 459 of file Hypervolume.cpp.
References cmp().
double stream (double * regionLow, double * regionUp, double * points, unsigned noPoints, int split, double cover)
Definition at line 268 of file Hypervolume.cpp.
References computeTrellis(), containsBoundary(), covers(), getMeasure(), getMedian(), isPile(), and partCovers().
Referenced by overmars_yap().