MOO-EALib: MOOMeasures.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
MOOMeasures.h File Reference
Distance and diversity measurement for pareto sets.
#include <SharkDefs.h>
#include <Array/ArraySort.h>
#include <vector>
#include <algorithm>
Functions
bool cmpDelta (IndividualMOO *a, IndividualMOO *b)
double delta (ArchiveMOO &q, Array< double > &pf)
double upsilonDistanceElement (IndividualMOO &i, Array< double > &pf)
double upsilonDistanceFront (ArchiveMOO &q, Array< double > &pf, double &stdv)
double bosmanDistanceElement (Array< double > &fitness, Array< double > &pf)
double bosmanDistanceFront (ArchiveMOO &q, Array< double > &pf, double &stdv)
void minmax (Array< double > &pf, double &min1, double &max1, double &min2, double &max2, bool init=false)
void minmax (ArchiveMOO &q, double &min1, double &max1, double &min2, double &max2, bool init=false)
double hyperVolumeElement (double x1, double x2, double y, double bound)
double hyperVolumeValue (Array< double > &pf, double min1, double max1, double min2, double max2, bool minimizeall)
double hyperVolumeValue (ArchiveMOO &q, double min1, double max1, double min2, double max2, bool minimizeall)
double aggregationElement (Array< double > &pf, double tradeoff)
double aggregationValue (Array< double > &pf, unsigned resolution)
double aggregationValue (ArchiveMOO &q, unsigned resolution)
Detailed Description
Distance and diversity measurement for pareto sets.
Author:
Stefan Roth
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file MOOMeasures.h.
Function Documentation
double aggregationElement (Array< double > & pf, double tradeoff)
Definition at line 314 of file MOOMeasures.h.
Referenced by aggregationValue().
double aggregationValue (Array< double > & pf, unsigned resolution)
Definition at line 330 of file MOOMeasures.h.
References aggregationElement().
Referenced by aggregationValue().
double aggregationValue (ArchiveMOO & q, unsigned resolution)
Definition at line 347 of file MOOMeasures.h.
References aggregationValue(), IndividualMOO::getMOOFitness(), ArchiveMOO::readArchive(), and ArchiveMOO::size().
double bosmanDistanceElement (Array< double > & fitness, Array< double > & pf)
Definition at line 160 of file MOOMeasures.h.
Referenced by bosmanDistanceFront().
double bosmanDistanceFront (ArchiveMOO & q, Array< double > & pf, double & stdv)
Definition at line 176 of file MOOMeasures.h.
References bosmanDistanceElement(), IndividualMOO::getMOOFitness(), ArchiveMOO::readArchive(), and ArchiveMOO::size().
bool cmpDelta (IndividualMOO * a, IndividualMOO * b)
Definition at line 50 of file MOOMeasures.h.
References IndividualMOO::getMOOFitness().
Referenced by delta().
double delta (ArchiveMOO & q, Array< double > & pf)
Definition at line 56 of file MOOMeasures.h.
References cmpDelta(), ArchiveMOO::readArchive(), and ArchiveMOO::size().
double hyperVolumeElement (double x1, double x2, double y, double bound)
Definition at line 252 of file MOOMeasures.h.
Referenced by hyperVolumeValue().
double hyperVolumeValue (Array< double > & pf, double min1, double max1, double min2, double max2, bool minimizeall)
Definition at line 257 of file MOOMeasures.h.
References hyperVolumeElement().
Referenced by hyperVolumeValue().
double hyperVolumeValue (ArchiveMOO & q, double min1, double max1, double min2, double max2, bool minimizeall)
Definition at line 291 of file MOOMeasures.h.
References IndividualMOO::getMOOFitness(), hyperVolumeValue(), ArchiveMOO::readArchive(), and ArchiveMOO::size().
void minmax (Array< double > & pf, double & min1, double & max1, double & min2, double & max2, bool init = false)
Definition at line 217 of file MOOMeasures.h.
References MAX.
Referenced by minmax().
void minmax (ArchiveMOO & q, double & min1, double & max1, double & min2, double & max2, bool init = false)
Definition at line 236 of file MOOMeasures.h.
References IndividualMOO::getMOOFitness(), minmax(), ArchiveMOO::readArchive(), and ArchiveMOO::size().
double upsilonDistanceElement (IndividualMOO & i, Array< double > & pf)
Definition at line 114 of file MOOMeasures.h.
References IndividualMOO::getMOOFitness().
Referenced by upsilonDistanceFront().
double upsilonDistanceFront (ArchiveMOO & q, Array< double > & pf, double & stdv)
Definition at line 130 of file MOOMeasures.h.
References ArchiveMOO::readArchive(), ArchiveMOO::size(), and upsilonDistanceElement().