MOO-EALib: MOOTestFunctions.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
MOOTestFunctions.h File Reference
Several Benchmark functions for algorithm analysis.
#include <SharkDefs.h>
#include <Array/ArraySort.h>
#include <Array/ArrayIo.h>
#include <Array/Array.h>
#include <Array/Array2D.h>
#include <Array/ArrayOp.h>
#include <Rng/Uniform.h>
Classes
class Linkage_2< DTLZ_T >
Renders a fitness function unseparable.
class Linkage_3< DTLZ_T >
Renders a fitness function unseparable.
struct DTLZ1
DTLZ-1 test function for algorithm analysis.
struct DTLZ2
DTLZ-2 test function for algorithm analysis.
struct DTLZ3
DTLZ-3 test function for algorithm analysis.
struct DTLZ4
DTLZ-4 test function for algorithm analysis.
struct DTLZ5
DTLZ-5 test function for algorithm analysis.
struct DTLZ6
DTLZ-6 test function for algorithm analysis.
struct DTLZ7
DTLZ-7 test function for algorithm analysis.
struct Igel1
Igel-1 test function for algorithm analysis.
struct Igel2
Igel-2 test function for algorithm analysis.
struct Igel3
Igel-3 test function for algorithm analysis.
struct Igel4
Igel-4 test function for algorithm analysis.
Typedefs
typedef Linkage_2< DTLZ2 > L_2_DTLZ2
typedef Linkage_3< DTLZ2 > L_3_DTLZ2
typedef Linkage_2< DTLZ3 > L_2_DTLZ3
typedef Linkage_3< DTLZ3 > L_3_DTLZ3
Functions
unsigned approxEquidistantFrontDoIt (Array< double > &v, Array< double > &w, unsigned n, double d)
void approxEquidistantFront (Array< double > &v, Array< double > &w, unsigned n=500, double eps=0.000001)
double SphereF1 (const std::vector< double > &x)
double SphereF2 (const std::vector< double > &x)
double DebConvexF1 (const std::vector< double > &x)
double DebConvexF2 (const std::vector< double > &x)
double DebConcaveF1 (const std::vector< double > &x)
double DebConcaveF2 (const std::vector< double > &x)
double DebDiscreteF1 (const std::vector< double > &x)
double DebDiscreteF2 (const std::vector< double > &x)
double FonsecaConcaveF1 (const std::vector< double > &x)
double FonsecaConcaveF2 (const std::vector< double > &x)
void FonsecaConcaveSampleFront (Array< double > &pf, unsigned dimension, unsigned n=500)
void FonsecaConcaveSample (Array< double > &pf, unsigned dimension, unsigned n=500)
double MessacConcaveF1 (const std::vector< double > &x)
double MessacConcaveF2 (const std::vector< double > &x)
void MessacConcaveSampleFront (Array< double > &pf, unsigned dimension, double lower, double upper, unsigned n=500)
void MessacConcaveSample (Array< double > &pf, unsigned dimension, double lower, double upper)
double norm (const Array< double > &a)
double scalarprod (const Array< double > &a, const Array< double > &b)
double scalarprod (const Array< double > &a, const std::vector< double > &b)
void generateBasis (unsigned d, Array< double > &B)
double RotParF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotParF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotParF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotParF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotParSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=100000)
void RotParSample (Array< double > &pf, unsigned dimension, double cond, double cond2=2)
double RotCigarF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotCigarF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotCigarF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotCigarF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotCigarSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=100000)
double RotCigTabF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotCigTabF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotCigTabF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotCigTabF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotCigTabSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=100000)
double RotTabletF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotTabletF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotTabletF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotTabletF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotTabletSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=100000)
double RotFonsecaConcaveF1 (const std::vector< double > &x, Array< double > &coord, double cond)
double RotFonsecaConcaveF2 (const std::vector< double > &x, Array< double > &coord, double cond)
double DebRotatedF1 (const std::vector< double > &x, Array< double > &coord)
double DebRotatedF2 (const std::vector< double > &x, Array< double > &coord)
void DebRotatedSampleFront (Array< double > &pf, unsigned dimension, unsigned n=500)
double CI1F1 (const std::vector< double > &x)
double CI1F2 (const std::vector< double > &x)
double CI2F1 (const std::vector< double > &x)
double CI2F2 (const std::vector< double > &x)
double ZDT1F1 (const std::vector< double > &x)
double ZDT1G (const std::vector< double > &x)
double ZDT1F2 (const std::vector< double > &x)
void ZDT1SampleFront (Array< double > &pf, unsigned n=500)
double ZDT2F1 (const std::vector< double > &x)
double ZDT2G (const std::vector< double > &x)
double ZDT2F2 (const std::vector< double > &x)
void ZDT2SampleFront (Array< double > &pf, unsigned n=500)
double ZDT3F1 (const std::vector< double > &x)
double ZDT3G (const std::vector< double > &x)
double ZDT3F2 (const std::vector< double > &x)
void ZDT3SampleFront (Array< double > &pf, unsigned n=500)
double ZDT4F1 (const std::vector< double > &x)
double ZDT4G (const std::vector< double > &x)
double ZDT4F2 (const std::vector< double > &x)
double ZDT4PrimeF2 (const std::vector< double > &x, const Array< double > &coord)
double ZDT4FII1 (const std::vector< double > &x)
double ZDT4GII (const std::vector< double > &x)
double ZDT4FII2 (const std::vector< double > &x)
double ZDT4FG (const std::vector< double > &x)
double ZDT4FF2 (const std::vector< double > &x)
double ZDT4FF1 (const std::vector< double > &x)
void ZDT4SampleFront (Array< double > &pf, unsigned n=500)
double ZDT6F1 (const std::vector< double > &x)
double ZDT6G (const std::vector< double > &x)
double ZDT6F2 (const std::vector< double > &x)
void ZDT6SampleFront (Array< double > &pf, unsigned n=500)
double sphere (const std::vector< double > &x)
double DeJongF2 (const std::vector< double > &x)
double DeJongF3 (const std::vector< double > &x)
double SchafferF7 (const std::vector< double > &x)
double SchwefelF1 (const std::vector< double > &x)
double SchwefelF2 (const std::vector< double > &x)
double rastrigin (const std::vector< double > &x)
double rosenbrock (const std::vector< double > &x)
double ackley (const std::vector< double > &x)
double func1 (const std::vector< double > &x)
double h (double x, double n)
double hf (double x, double y0, double ymax)
double hg (double x)
double IHR1F1 (const std::vector< double > &x, const Array< double > &coord)
double IHR1F2 (const std::vector< double > &x, const Array< double > &coord)
double IHR2F1 (const std::vector< double > &x, Array< double > &coord)
double IHR2F2 (const std::vector< double > &x, Array< double > &coord)
double IHR3F1 (const std::vector< double > &x, Array< double > &coord)
double IHR3F2 (const std::vector< double > &x, Array< double > &coord)
double IHR4F1 (const std::vector< double > &x, Array< double > &coord)
double IHR4F2 (const std::vector< double > &x, Array< double > &coord)
double IHR6F1 (const std::vector< double > &x, Array< double > &coord)
double IHR6F2 (const std::vector< double > &x, Array< double > &coord)
Detailed Description
Several Benchmark functions for algorithm analysis.
Author:
Tatsuya Okabe
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
MOO-EALib
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file MOOTestFunctions.h.
Typedef Documentation
typedef Linkage_2<DTLZ2> L_2_DTLZ2
Definition at line 2094 of file MOOTestFunctions.h.
typedef Linkage_2<DTLZ3> L_2_DTLZ3
Definition at line 2138 of file MOOTestFunctions.h.
typedef Linkage_3<DTLZ2> L_3_DTLZ2
Definition at line 2095 of file MOOTestFunctions.h.
typedef Linkage_3<DTLZ3> L_3_DTLZ3
Definition at line 2139 of file MOOTestFunctions.h.
Function Documentation
double ackley (const std::vector< double > & x)
Definition at line 1748 of file MOOTestFunctions.h.
void approxEquidistantFront (Array< double > & v, Array< double > & w, unsigned n = 500, double eps = 0.000001)
Definition at line 131 of file MOOTestFunctions.h.
References approxEquidistantFrontDoIt().
Referenced by DebRotatedSampleFront(), FonsecaConcaveSampleFront(), RotCigarSampleFront(), RotCigTabSampleFront(), RotParSampleFront(), RotTabletSampleFront(), ZDT1SampleFront(), ZDT2SampleFront(), ZDT3SampleFront(), ZDT4SampleFront(), and ZDT6SampleFront().
unsigned approxEquidistantFrontDoIt (Array< double > & v, Array< double > & w, unsigned n, double d)
Definition at line 87 of file MOOTestFunctions.h.
Referenced by approxEquidistantFront().
double CI1F1 (const std::vector< double > & x)
Definition at line 1235 of file MOOTestFunctions.h.
double CI1F2 (const std::vector< double > & x)
Definition at line 1240 of file MOOTestFunctions.h.
double CI2F1 (const std::vector< double > & x)
Definition at line 1245 of file MOOTestFunctions.h.
double CI2F2 (const std::vector< double > & x)
Definition at line 1250 of file MOOTestFunctions.h.
double DebConcaveF1 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 269 of file MOOTestFunctions.h.
double DebConcaveF2 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 286 of file MOOTestFunctions.h.
double DebConvexF1 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 225 of file MOOTestFunctions.h.
double DebConvexF2 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 240 of file MOOTestFunctions.h.
double DebDiscreteF1 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 315 of file MOOTestFunctions.h.
double DebDiscreteF2 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 332 of file MOOTestFunctions.h.
double DebRotatedF1 (const std::vector< double > & x, Array< double > & coord)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1143 of file MOOTestFunctions.h.
References scalarprod().
Referenced by DebRotatedSampleFront().
double DebRotatedF2 (const std::vector< double > & x, Array< double > & coord)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1158 of file MOOTestFunctions.h.
References scalarprod().
Referenced by DebRotatedSampleFront().
void DebRotatedSampleFront (Array< double > & pf, unsigned dimension, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1190 of file MOOTestFunctions.h.
References approxEquidistantFront(), DebRotatedF1(), and DebRotatedF2().
double DeJongF2 (const std::vector< double > & x)
Definition at line 1631 of file MOOTestFunctions.h.
double DeJongF3 (const std::vector< double > & x)
Definition at line 1647 of file MOOTestFunctions.h.
double FonsecaConcaveF1 (const std::vector< double > & x)
Examples:
fonMO-CMA.cpp, fonSteadyStateMO-CMA.cpp, MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, realcoded-NSGA2.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 361 of file MOOTestFunctions.h.
Referenced by FonsecaConcaveSample(), and FonsecaConcaveSampleFront().
double FonsecaConcaveF2 (const std::vector< double > & x)
Examples:
fonMO-CMA.cpp, fonSteadyStateMO-CMA.cpp, MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, realcoded-NSGA2.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 377 of file MOOTestFunctions.h.
Referenced by FonsecaConcaveSample(), and FonsecaConcaveSampleFront().
void FonsecaConcaveSample (Array< double > & pf, unsigned dimension, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 423 of file MOOTestFunctions.h.
References FonsecaConcaveF1(), and FonsecaConcaveF2().
void FonsecaConcaveSampleFront (Array< double > & pf, unsigned dimension, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 391 of file MOOTestFunctions.h.
References approxEquidistantFront(), FonsecaConcaveF1(), and FonsecaConcaveF2().
double func1 (const std::vector< double > & x)
Definition at line 1766 of file MOOTestFunctions.h.
void generateBasis (unsigned d, Array< double > & B)
Examples:
realcoded-NSGA2.cpp.
Definition at line 621 of file MOOTestFunctions.h.
References norm(), and scalarprod().
double h (double x, double n) [inline]
Definition at line 1794 of file MOOTestFunctions.h.
Referenced by hypervolume(), IHR1F2(), IHR3F2(), IHR4F2(), FastNonDominatedSort::operator()(), DTLZ7::operator()(), and az::alg::Matrix::tred2().
double hf (double x, double y0, double ymax) [inline]
Definition at line 1799 of file MOOTestFunctions.h.
double hg (double x) [inline]
Definition at line 1805 of file MOOTestFunctions.h.
Referenced by IHR1F2(), IHR2F2(), IHR3F2(), and IHR6F2().
double IHR1F1 (const std::vector< double > & x, const Array< double > & coord)
Definition at line 1810 of file MOOTestFunctions.h.
References scalarprod().
double IHR1F2 (const std::vector< double > & x, const Array< double > & coord)
Definition at line 1815 of file MOOTestFunctions.h.
References h(), hg(), and scalarprod().
double IHR2F1 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1838 of file MOOTestFunctions.h.
References scalarprod().
double IHR2F2 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1843 of file MOOTestFunctions.h.
References hg(), and scalarprod().
double IHR3F1 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1867 of file MOOTestFunctions.h.
References scalarprod().
double IHR3F2 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1872 of file MOOTestFunctions.h.
References h(), hg(), and scalarprod().
double IHR4F1 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1897 of file MOOTestFunctions.h.
References scalarprod().
double IHR4F2 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1902 of file MOOTestFunctions.h.
References h(), and scalarprod().
double IHR6F1 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1927 of file MOOTestFunctions.h.
References scalarprod().
Referenced by IHR6F2().
double IHR6F2 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1933 of file MOOTestFunctions.h.
References hg(), IHR6F1(), and scalarprod().
double MessacConcaveF1 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 470 of file MOOTestFunctions.h.
Referenced by MessacConcaveSample(), and MessacConcaveSampleFront().
double MessacConcaveF2 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 484 of file MOOTestFunctions.h.
Referenced by MessacConcaveSample(), and MessacConcaveSampleFront().
void MessacConcaveSample (Array< double > & pf, unsigned dimension, double lower, double upper)
Examples:
realcoded-NSGA2.cpp.
Definition at line 527 of file MOOTestFunctions.h.
References MessacConcaveF1(), and MessacConcaveF2().
void MessacConcaveSampleFront (Array< double > & pf, unsigned dimension, double lower, double upper, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 498 of file MOOTestFunctions.h.
References MessacConcaveF1(), and MessacConcaveF2().
double norm (const Array< double > & a)
Definition at line 588 of file MOOTestFunctions.h.
Referenced by generateBasis(), and MOCMASearch::init().
double rastrigin (const std::vector< double > & x)
Definition at line 1715 of file MOOTestFunctions.h.
double rosenbrock (const std::vector< double > & x)
Definition at line 1732 of file MOOTestFunctions.h.
double RotCigarF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Examples:
realcoded-NSGA2.cpp.
Definition at line 796 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotCigarF1(), and RotCigarSampleFront().
double RotCigarF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 834 of file MOOTestFunctions.h.
References RotCigarF1().
double RotCigarF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 849 of file MOOTestFunctions.h.
References RotCigarF2().
double RotCigarF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Examples:
realcoded-NSGA2.cpp.
Definition at line 815 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotCigarF2(), and RotCigarSampleFront().
void RotCigarSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 100000)
Examples:
realcoded-NSGA2.cpp.
Definition at line 863 of file MOOTestFunctions.h.
References approxEquidistantFront(), RotCigarF1(), and RotCigarF2().
double RotCigTabF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Definition at line 899 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotCigTabF1(), and RotCigTabSampleFront().
double RotCigTabF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 945 of file MOOTestFunctions.h.
References RotCigTabF1().
double RotCigTabF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Definition at line 922 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotCigTabF2(), and RotCigTabSampleFront().
double RotCigTabF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 960 of file MOOTestFunctions.h.
References RotCigTabF2().
void RotCigTabSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 100000)
Definition at line 974 of file MOOTestFunctions.h.
References approxEquidistantFront(), RotCigTabF1(), and RotCigTabF2().
double RotFonsecaConcaveF1 (const std::vector< double > & x, Array< double > & coord, double cond)
Definition at line 1111 of file MOOTestFunctions.h.
References scalarprod().
double RotFonsecaConcaveF2 (const std::vector< double > & x, Array< double > & coord, double cond)
Definition at line 1125 of file MOOTestFunctions.h.
References scalarprod().
double RotParF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Examples:
realcoded-NSGA2.cpp.
Definition at line 649 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotParF1(), RotParSample(), and RotParSampleFront().
double RotParF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 681 of file MOOTestFunctions.h.
References RotParF1().
double RotParF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Examples:
realcoded-NSGA2.cpp.
Definition at line 665 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotParF2(), RotParSample(), and RotParSampleFront().
double RotParF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 696 of file MOOTestFunctions.h.
References RotParF2().
void RotParSample (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2)
Examples:
realcoded-NSGA2.cpp.
Definition at line 741 of file MOOTestFunctions.h.
References RotParF1(), and RotParF2().
void RotParSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 100000)
Examples:
realcoded-NSGA2.cpp.
Definition at line 710 of file MOOTestFunctions.h.
References approxEquidistantFront(), RotParF1(), and RotParF2().
double RotTabletF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1010 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotTabletF1(), and RotTabletSampleFront().
double RotTabletF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 1048 of file MOOTestFunctions.h.
References RotTabletF1().
double RotTabletF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 1063 of file MOOTestFunctions.h.
References RotTabletF2().
double RotTabletF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1029 of file MOOTestFunctions.h.
References scalarprod().
Referenced by RotTabletF2(), and RotTabletSampleFront().
void RotTabletSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 100000)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1077 of file MOOTestFunctions.h.
References approxEquidistantFront(), RotTabletF1(), and RotTabletF2().
double scalarprod (const Array< double > & a, const std::vector< double > & b)
Definition at line 605 of file MOOTestFunctions.h.
double scalarprod (const Array< double > & a, const Array< double > & b)
Definition at line 596 of file MOOTestFunctions.h.
Referenced by DebRotatedF1(), DebRotatedF2(), generateBasis(), IHR1F1(), IHR1F2(), IHR2F1(), IHR2F2(), IHR3F1(), IHR3F2(), IHR4F1(), IHR4F2(), IHR6F1(), IHR6F2(), Igel4::operator()(), Igel3::operator()(), Igel2::operator()(), Igel1::operator()(), Linkage_3< DTLZ_T >::operator()(), Linkage_2< DTLZ_T >::operator()(), RotCigarF1(), RotCigarF2(), RotCigTabF1(), RotCigTabF2(), RotFonsecaConcaveF1(), RotFonsecaConcaveF2(), RotParF1(), RotParF2(), RotTabletF1(), and RotTabletF2().
double SchafferF7 (const std::vector< double > & x)
Definition at line 1663 of file MOOTestFunctions.h.
double SchwefelF1 (const std::vector< double > & x)
Definition at line 1680 of file MOOTestFunctions.h.
double SchwefelF2 (const std::vector< double > & x)
Definition at line 1696 of file MOOTestFunctions.h.
double sphere (const std::vector< double > & x)
Definition at line 1617 of file MOOTestFunctions.h.
double SphereF1 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 194 of file MOOTestFunctions.h.
double SphereF2 (const std::vector< double > & x)
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, PAES-SCAT.cpp, PAES.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 208 of file MOOTestFunctions.h.
double ZDT1F1 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1259 of file MOOTestFunctions.h.
Referenced by ZDT1SampleFront().
double ZDT1F2 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1274 of file MOOTestFunctions.h.
References ZDT1G().
Referenced by ZDT1SampleFront().
double ZDT1G (const std::vector< double > & x)
Definition at line 1264 of file MOOTestFunctions.h.
Referenced by ZDT1F2().
void ZDT1SampleFront (Array< double > & pf, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1279 of file MOOTestFunctions.h.
References approxEquidistantFront(), ZDT1F1(), and ZDT1F2().
double ZDT2F1 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1315 of file MOOTestFunctions.h.
Referenced by ZDT2SampleFront().
double ZDT2F2 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1330 of file MOOTestFunctions.h.
References ZDT2G().
Referenced by ZDT2SampleFront().
double ZDT2G (const std::vector< double > & x)
Definition at line 1320 of file MOOTestFunctions.h.
Referenced by ZDT2F2().
void ZDT2SampleFront (Array< double > & pf, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1335 of file MOOTestFunctions.h.
References approxEquidistantFront(), ZDT2F1(), and ZDT2F2().
double ZDT3F1 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1369 of file MOOTestFunctions.h.
Referenced by ZDT3SampleFront().
double ZDT3F2 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1384 of file MOOTestFunctions.h.
References ZDT3G().
Referenced by ZDT3SampleFront().
double ZDT3G (const std::vector< double > & x)
Definition at line 1374 of file MOOTestFunctions.h.
Referenced by ZDT3F2().
void ZDT3SampleFront (Array< double > & pf, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1390 of file MOOTestFunctions.h.
References approxEquidistantFront(), ZDT3F1(), and ZDT3F2().
double ZDT4F1 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1432 of file MOOTestFunctions.h.
double ZDT4F2 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1451 of file MOOTestFunctions.h.
References ZDT4G().
double ZDT4FF1 (const std::vector< double > & x)
Definition at line 1508 of file MOOTestFunctions.h.
Referenced by ZDT4SampleFront().
double ZDT4FF2 (const std::vector< double > & x)
Definition at line 1503 of file MOOTestFunctions.h.
References ZDT4FG().
Referenced by ZDT4SampleFront().
double ZDT4FG (const std::vector< double > & x)
Definition at line 1493 of file MOOTestFunctions.h.
Referenced by ZDT4FF2().
double ZDT4FII1 (const std::vector< double > & x)
Definition at line 1472 of file MOOTestFunctions.h.
double ZDT4FII2 (const std::vector< double > & x)
Definition at line 1487 of file MOOTestFunctions.h.
References ZDT4G().
double ZDT4G (const std::vector< double > & x)
Definition at line 1441 of file MOOTestFunctions.h.
Referenced by ZDT4F2(), ZDT4FII2(), and ZDT4PrimeF2().
double ZDT4GII (const std::vector< double > & x)
Definition at line 1477 of file MOOTestFunctions.h.
double ZDT4PrimeF2 (const std::vector< double > & x, const Array< double > & coord)
Definition at line 1456 of file MOOTestFunctions.h.
References ZDT4G().
void ZDT4SampleFront (Array< double > & pf, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1514 of file MOOTestFunctions.h.
References approxEquidistantFront(), ZDT4FF1(), and ZDT4FF2().
double ZDT6F1 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1548 of file MOOTestFunctions.h.
Referenced by ZDT6F2(), and ZDT6SampleFront().
double ZDT6F2 (const std::vector< double > & x)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1567 of file MOOTestFunctions.h.
References ZDT6F1(), and ZDT6G().
Referenced by ZDT6SampleFront().
double ZDT6G (const std::vector< double > & x)
Definition at line 1553 of file MOOTestFunctions.h.
Referenced by ZDT6F2().
void ZDT6SampleFront (Array< double > & pf, unsigned n = 500)
Examples:
realcoded-NSGA2.cpp.
Definition at line 1572 of file MOOTestFunctions.h.
References approxEquidistantFront(), ZDT6F1(), and ZDT6F2().