MOO-EALib: TestFunction.h File Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
TestFunction.h File Reference
Collection of benchmark fitness functions for algorithm analysis.
#include <SharkDefs.h>
#include <Array/ArraySort.h>
#include <Rng/GlobalRng.h>
Defines
#define __TESTFUNCTIONMOO_H
Functions
unsigned approxEquidistantFrontDoIt (Array< double > &v, Array< double > &w, unsigned n, double d)
void approxEquidistantFront (Array< double > &v, Array< double > &w, unsigned n=500, double eps=0.000001)
double SphereF1 (const std::vector< double > &x)
double SphereF2 (const std::vector< double > &x)
double DebConvexF1 (const std::vector< double > &x)
double DebConvexF2 (const std::vector< double > &x)
double DebConcaveF1 (const std::vector< double > &x)
double DebConcaveF2 (const std::vector< double > &x)
double DebDiscreteF1 (const std::vector< double > &x)
double DebDiscreteF2 (const std::vector< double > &x)
double FonsecaConcaveF1 (const std::vector< double > &x)
double FonsecaConcaveF2 (const std::vector< double > &x)
void FonsecaConcaveSampleFront (Array< double > &pf, unsigned dimension, unsigned n=500)
void FonsecaConcaveSample (Array< double > &pf, unsigned dimension, unsigned n=500)
double MessacConcaveF1 (const std::vector< double > &x)
double MessacConcaveF2 (const std::vector< double > &x)
void MessacConcaveSampleFront (Array< double > &pf, unsigned dimension, double lower, double upper, unsigned n=500)
void MessacConcaveSample (Array< double > &pf, unsigned dimension, double lower, double upper)
double norm (const Array< double > &a)
double scalarprod (const Array< double > &a, const Array< double > &b)
double scalarprod (const Array< double > &a, const std::vector< double > &b)
void generateBasis (unsigned d, Array< double > &B)
double RotParF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotParF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotParF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotParF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotParSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=500)
void RotParSample (Array< double > &pf, unsigned dimension, double cond, double cond2=2)
double RotCigarF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotCigarF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotCigarF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotCigarF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotCigarSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=500)
double RotTabletF1 (const std::vector< double > &_v, Array< double > &coord, double cond)
double RotTabletF2 (const std::vector< double > &_v, Array< double > &coord, double cond1, double cond2=2)
double RotTabletF1 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond)
double RotTabletF2 (const std::vector< double > &_v, Array< double > &coord, const std::vector< double > &lower, const std::vector< double > &upper, double cond1, double cond2=2)
void RotTabletSampleFront (Array< double > &pf, unsigned dimension, double cond, double cond2=2, unsigned n=500)
double DebRotatedF1 (const std::vector< double > &x, Array< double > &coord)
double DebRotatedF2 (const std::vector< double > &x, Array< double > &coord)
void DebRotatedSampleFront (Array< double > &pf, unsigned dimension, unsigned n=500)
double CI1F1 (const std::vector< double > &x)
double CI1F2 (const std::vector< double > &x)
double CI2F1 (const std::vector< double > &x)
double CI2F2 (const std::vector< double > &x)
double ZDT1F1 (const std::vector< double > &x)
double ZDT1G (const std::vector< double > &x)
double ZDT1F2 (const std::vector< double > &x)
void ZDT1SampleFront (Array< double > &pf, unsigned n=500)
double ZDT2F1 (const std::vector< double > &x)
double ZDT2G (const std::vector< double > &x)
double ZDT2F2 (const std::vector< double > &x)
void ZDT2SampleFront (Array< double > &pf, unsigned n=500)
double ZDT3F1 (const std::vector< double > &x)
double ZDT3G (const std::vector< double > &x)
double ZDT3F2 (const std::vector< double > &x)
void ZDT3SampleFront (Array< double > &pf, unsigned n=500)
double ZDT4F1 (const std::vector< double > &x)
double ZDT4G (const std::vector< double > &x)
double ZDT4F2 (const std::vector< double > &x)
double ZDT4FII1 (const std::vector< double > &x)
double ZDT4GII (const std::vector< double > &x)
double ZDT4FII2 (const std::vector< double > &x)
double ZDT4FG (const std::vector< double > &x)
double ZDT4FF2 (const std::vector< double > &x)
double ZDT4FF1 (const std::vector< double > &x)
void ZDT4SampleFront (Array< double > &pf, unsigned n=500)
double ZDT6F1 (const std::vector< double > &x)
double ZDT6G (const std::vector< double > &x)
double ZDT6F2 (const std::vector< double > &x)
void ZDT6SampleFront (Array< double > &pf, unsigned n=500)
double sphere (const std::vector< double > &x)
double DeJongF2 (const std::vector< double > &x)
double DeJongF3 (const std::vector< double > &x)
double SchafferF7 (const std::vector< double > &x)
double SchwefelF1 (const std::vector< double > &x)
double SchwefelF2 (const std::vector< double > &x)
double rastrigin (const std::vector< double > &x)
double rosenbrock (const std::vector< double > &x)
double ackley (const std::vector< double > &x)
double func1 (const std::vector< double > &x)
Detailed Description
Collection of benchmark fitness functions for algorithm analysis.
Author:
Tatsuya Okabe
Institut für Neuroinformatik
Ruhr-Universität Bochum
D-44780 Bochum, Germany
Phone: +49-234-32-25558
Fax: +49-234-32-14209
eMail: shark-admin@neuroinformatik.ruhr-uni-bochum.de
www: http://www.neuroinformatik.ruhr-uni-bochum.de
Project:
MOO-EALib
This file is part of Shark. This library is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
Definition in file TestFunction.h.
Define Documentation
#define __TESTFUNCTIONMOO_H
Definition at line 74 of file TestFunction.h.
Function Documentation
double ackley (const std::vector< double > & x)
Definition at line 1590 of file TestFunction.h.
void approxEquidistantFront (Array< double > & v, Array< double > & w, unsigned n = 500, double eps = 0.000001)
Definition at line 131 of file TestFunction.h.
References approxEquidistantFrontDoIt().
unsigned approxEquidistantFrontDoIt (Array< double > & v, Array< double > & w, unsigned n, double d)
Definition at line 87 of file TestFunction.h.
double CI1F1 (const std::vector< double > & x)
Definition at line 1096 of file TestFunction.h.
double CI1F2 (const std::vector< double > & x)
Definition at line 1101 of file TestFunction.h.
double CI2F1 (const std::vector< double > & x)
Definition at line 1106 of file TestFunction.h.
double CI2F2 (const std::vector< double > & x)
Definition at line 1111 of file TestFunction.h.
double DebConcaveF1 (const std::vector< double > & x)
Definition at line 266 of file TestFunction.h.
double DebConcaveF2 (const std::vector< double > & x)
Definition at line 283 of file TestFunction.h.
double DebConvexF1 (const std::vector< double > & x)
Definition at line 222 of file TestFunction.h.
double DebConvexF2 (const std::vector< double > & x)
Definition at line 237 of file TestFunction.h.
double DebDiscreteF1 (const std::vector< double > & x)
Definition at line 312 of file TestFunction.h.
double DebDiscreteF2 (const std::vector< double > & x)
Definition at line 329 of file TestFunction.h.
double DebRotatedF1 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1004 of file TestFunction.h.
References scalarprod().
double DebRotatedF2 (const std::vector< double > & x, Array< double > & coord)
Definition at line 1019 of file TestFunction.h.
References scalarprod().
void DebRotatedSampleFront (Array< double > & pf, unsigned dimension, unsigned n = 500)
Definition at line 1051 of file TestFunction.h.
References approxEquidistantFront(), DebRotatedF1(), and DebRotatedF2().
double DeJongF2 (const std::vector< double > & x)
Definition at line 1473 of file TestFunction.h.
double DeJongF3 (const std::vector< double > & x)
Definition at line 1489 of file TestFunction.h.
double FonsecaConcaveF1 (const std::vector< double > & x)
Definition at line 358 of file TestFunction.h.
double FonsecaConcaveF2 (const std::vector< double > & x)
Definition at line 372 of file TestFunction.h.
void FonsecaConcaveSample (Array< double > & pf, unsigned dimension, unsigned n = 500)
Definition at line 418 of file TestFunction.h.
References FonsecaConcaveF1(), and FonsecaConcaveF2().
void FonsecaConcaveSampleFront (Array< double > & pf, unsigned dimension, unsigned n = 500)
Definition at line 386 of file TestFunction.h.
References approxEquidistantFront(), FonsecaConcaveF1(), and FonsecaConcaveF2().
double func1 (const std::vector< double > & x)
Definition at line 1608 of file TestFunction.h.
void generateBasis (unsigned d, Array< double > & B)
Definition at line 616 of file TestFunction.h.
References norm(), and scalarprod().
double MessacConcaveF1 (const std::vector< double > & x)
Definition at line 465 of file TestFunction.h.
double MessacConcaveF2 (const std::vector< double > & x)
Definition at line 479 of file TestFunction.h.
void MessacConcaveSample (Array< double > & pf, unsigned dimension, double lower, double upper)
Definition at line 522 of file TestFunction.h.
References MessacConcaveF1(), and MessacConcaveF2().
void MessacConcaveSampleFront (Array< double > & pf, unsigned dimension, double lower, double upper, unsigned n = 500)
Definition at line 493 of file TestFunction.h.
References MessacConcaveF1(), and MessacConcaveF2().
double norm (const Array< double > & a)
Definition at line 583 of file TestFunction.h.
double rastrigin (const std::vector< double > & x)
Definition at line 1557 of file TestFunction.h.
double rosenbrock (const std::vector< double > & x)
Definition at line 1574 of file TestFunction.h.
double RotCigarF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Definition at line 799 of file TestFunction.h.
References scalarprod().
double RotCigarF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 837 of file TestFunction.h.
References RotCigarF1().
double RotCigarF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 852 of file TestFunction.h.
References RotCigarF2().
double RotCigarF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Definition at line 818 of file TestFunction.h.
References scalarprod().
void RotCigarSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 500)
Definition at line 866 of file TestFunction.h.
References approxEquidistantFront(), RotCigarF1(), and RotCigarF2().
double RotParF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Definition at line 652 of file TestFunction.h.
References scalarprod().
double RotParF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 684 of file TestFunction.h.
References RotParF1().
double RotParF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Definition at line 668 of file TestFunction.h.
References scalarprod().
double RotParF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 699 of file TestFunction.h.
References RotParF2().
void RotParSample (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2)
Definition at line 744 of file TestFunction.h.
References RotParF1(), and RotParF2().
void RotParSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 500)
Definition at line 713 of file TestFunction.h.
References approxEquidistantFront(), RotParF1(), and RotParF2().
double RotTabletF1 (const std::vector< double > & _v, Array< double > & coord, double cond)
Definition at line 902 of file TestFunction.h.
References scalarprod().
double RotTabletF1 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond)
Definition at line 940 of file TestFunction.h.
References RotTabletF1().
double RotTabletF2 (const std::vector< double > & _v, Array< double > & coord, double cond1, double cond2 = 2)
Definition at line 921 of file TestFunction.h.
References scalarprod().
double RotTabletF2 (const std::vector< double > & _v, Array< double > & coord, const std::vector< double > & lower, const std::vector< double > & upper, double cond1, double cond2 = 2)
Definition at line 955 of file TestFunction.h.
References RotTabletF2().
void RotTabletSampleFront (Array< double > & pf, unsigned dimension, double cond, double cond2 = 2, unsigned n = 500)
Definition at line 969 of file TestFunction.h.
References approxEquidistantFront(), RotTabletF1(), and RotTabletF2().
double scalarprod (const Array< double > & a, const std::vector< double > & b)
Definition at line 600 of file TestFunction.h.
double scalarprod (const Array< double > & a, const Array< double > & b)
Definition at line 591 of file TestFunction.h.
double SchafferF7 (const std::vector< double > & x)
Definition at line 1505 of file TestFunction.h.
double SchwefelF1 (const std::vector< double > & x)
Definition at line 1522 of file TestFunction.h.
double SchwefelF2 (const std::vector< double > & x)
Definition at line 1538 of file TestFunction.h.
double sphere (const std::vector< double > & x)
Definition at line 1459 of file TestFunction.h.
double SphereF1 (const std::vector< double > & x)
Definition at line 191 of file TestFunction.h.
double SphereF2 (const std::vector< double > & x)
Definition at line 205 of file TestFunction.h.
double ZDT1F1 (const std::vector< double > & x)
Definition at line 1120 of file TestFunction.h.
double ZDT1F2 (const std::vector< double > & x)
Definition at line 1135 of file TestFunction.h.
References ZDT1G().
double ZDT1G (const std::vector< double > & x)
Definition at line 1125 of file TestFunction.h.
void ZDT1SampleFront (Array< double > & pf, unsigned n = 500)
Definition at line 1140 of file TestFunction.h.
References approxEquidistantFront(), ZDT1F1(), and ZDT1F2().
double ZDT2F1 (const std::vector< double > & x)
Definition at line 1176 of file TestFunction.h.
double ZDT2F2 (const std::vector< double > & x)
Definition at line 1191 of file TestFunction.h.
References ZDT2G().
double ZDT2G (const std::vector< double > & x)
Definition at line 1181 of file TestFunction.h.
void ZDT2SampleFront (Array< double > & pf, unsigned n = 500)
Definition at line 1196 of file TestFunction.h.
References approxEquidistantFront(), ZDT2F1(), and ZDT2F2().
double ZDT3F1 (const std::vector< double > & x)
Definition at line 1230 of file TestFunction.h.
double ZDT3F2 (const std::vector< double > & x)
Definition at line 1245 of file TestFunction.h.
References ZDT3G().
double ZDT3G (const std::vector< double > & x)
Definition at line 1235 of file TestFunction.h.
void ZDT3SampleFront (Array< double > & pf, unsigned n = 500)
Definition at line 1251 of file TestFunction.h.
References approxEquidistantFront(), ZDT3F1(), and ZDT3F2().
double ZDT4F1 (const std::vector< double > & x)
Definition at line 1293 of file TestFunction.h.
double ZDT4F2 (const std::vector< double > & x)
Definition at line 1308 of file TestFunction.h.
References ZDT4G().
double ZDT4FF1 (const std::vector< double > & x)
Definition at line 1350 of file TestFunction.h.
double ZDT4FF2 (const std::vector< double > & x)
Definition at line 1345 of file TestFunction.h.
References ZDT4FG().
double ZDT4FG (const std::vector< double > & x)
Definition at line 1335 of file TestFunction.h.
double ZDT4FII1 (const std::vector< double > & x)
Definition at line 1314 of file TestFunction.h.
double ZDT4FII2 (const std::vector< double > & x)
Definition at line 1329 of file TestFunction.h.
References ZDT4G().
double ZDT4G (const std::vector< double > & x)
Definition at line 1298 of file TestFunction.h.
double ZDT4GII (const std::vector< double > & x)
Definition at line 1319 of file TestFunction.h.
void ZDT4SampleFront (Array< double > & pf, unsigned n = 500)
Definition at line 1356 of file TestFunction.h.
References approxEquidistantFront(), ZDT4FF1(), and ZDT4FF2().
double ZDT6F1 (const std::vector< double > & x)
Definition at line 1390 of file TestFunction.h.
double ZDT6F2 (const std::vector< double > & x)
Definition at line 1409 of file TestFunction.h.
References ZDT6F1(), and ZDT6G().
double ZDT6G (const std::vector< double > & x)
Definition at line 1395 of file TestFunction.h.
void ZDT6SampleFront (Array< double > & pf, unsigned n = 500)
Definition at line 1414 of file TestFunction.h.
References approxEquidistantFront(), ZDT6F1(), and ZDT6F2().