MOO-EALib: az::alg::Matrix Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
az::alg::Matrix Class Reference
Matrix class.
#include <RMMEDA.h>
Public Member Functions
Matrix (unsigned int row=0, unsigned int col=0)
constructor
Matrix (const Matrix &mat)
constructor
~Matrix ()
destructor
Matrix & Resize (unsigned int row, unsigned int col)
reset the matrix size
Matrix & Identity (unsigned int size)
create an identity matrix
unsigned int RowSize ()
get the row size
unsigned int ColSize ()
get the column size
double * operator() ()
get the pointer to the data
double & operator() (unsigned int row, unsigned int col)
get an element
Matrix & operator= (const Matrix &mat)
reset to another matrix
FVECTOR & Row (unsigned int row, FVECTOR &value)
get a row
FVECTOR & Column (unsigned int col, FVECTOR &value)
get a column
Matrix & Sub (unsigned int row, unsigned int col, Matrix &mat)
get a sub-matrix except a row and a column
double Det ()
calculate the determinant of a square matrix
Matrix & Trans ()
translate the matrix
Matrix & Inv ()
inverse the matrix
void Eig (FVECTOR &eigvalue, Matrix &eigvector)
calculate the eigenvalue and egienvectors
Matrix & Multiply (Matrix &mat, Matrix &result)
multiply a matrix
FVECTOR & LeftMultiply (FVECTOR &vec, FVECTOR &result)
left multiply a vector
FVECTOR & RightMultiply (FVECTOR &vec, FVECTOR &result)
right multiply a vector
Matrix & Divide (double sca)
divide a scalar
FVECTOR & ColMean (FVECTOR &mean)
get the mean of all columns
FVECTOR & RowMean (FVECTOR &mean)
get the mean of all rows
FVECTOR & ColStd (FVECTOR &std)
get standard variation of all columns
FVECTOR & RowStd (FVECTOR &std)
get standard variation of all rows
Matrix & RowSub (FVECTOR &value)
subtract a row vector
Matrix & ColSub (FVECTOR &value)
subtract a column vector
Protected Member Functions
void tred2 (FVECTOR &eigenvalue, FVECTOR &interm, Matrix &eigenvector)
Householder reduction of Matrix a to tridiagonal form.
void tqli (FVECTOR &eigenvalue, FVECTOR &interm, Matrix &eigenvector)
Tridiagonal QL algorithm -- Implicit.
void Sort (FVECTOR &eigenvalue, Matrix &eigenvector)
sort the eigenvalue by decreasing order
Protected Attributes
unsigned int mRow
row size
unsigned int mCol
column size
double * pData
pointer to the data
Friends
std::istream & operator>> (std::istream &is, Matrix &mat)
read a matrix
std::ostream & operator<< (std::ostream &os, Matrix &mat)
write a matrix
void LUbksb (Matrix &mat, std::vector< unsigned int > &indx, std::vector< double > &b)
solve A X = b(Numerical Recipes in C++ pp.50-51)
void LUdcmp (Matrix &mat, std::vector< unsigned int > &indx, double &d)
LU decompostion of a rowwise permutation(Numerical Recipes in C++ pp.49-50)
Detailed Description
Matrix class.
Definition at line 257 of file RMMEDA.h.
Constructor & Destructor Documentation
az::alg::Matrix::Matrix (unsigned int row = 0, unsigned int col = 0)
constructor
Parameters:
row row size
col column size
Returns:
void
Definition at line 654 of file RMMEDA.cpp.
References mCol, mRow, and pData.
az::alg::Matrix::Matrix (const Matrix & mat)
constructor
mat reference matrix
Returns:
void
Definition at line 667 of file RMMEDA.cpp.
References mCol, mRow, and pData.
az::alg::Matrix::~Matrix ()
destructor
Returns:
void
Definition at line 680 of file RMMEDA.cpp.
References pData.
Member Function Documentation
FVECTOR & az::alg::Matrix::ColMean (FVECTOR & mean)
get the mean of all columns
Parameters:
mean the mean vector
Returns:
mean vector
Definition at line 913 of file RMMEDA.cpp.
Referenced by ColStd().
unsigned int az::alg::Matrix::ColSize () [inline]
get the column size
Returns:
column size
Definition at line 296 of file RMMEDA.h.
References mCol.
Referenced by az::alg::Cholesky(), az::alg::CholeskySolve(), Multiply(), az::alg::operator<<(), az::alg::pinv(), Sub(), and az::alg::SVD().
FVECTOR & az::alg::Matrix::ColStd (FVECTOR & std)
get standard variation of all columns
Parameters:
std the std vector
Returns:
std vector
Definition at line 943 of file RMMEDA.cpp.
References ColMean().
Matrix & az::alg::Matrix::ColSub (FVECTOR & value)
subtract a column vector
Parameters:
value row vector
Returns:
reference to the matrix
Definition at line 989 of file RMMEDA.cpp.
Referenced by az::alg::PCA::Train().
FVECTOR & az::alg::Matrix::Column (unsigned int col, FVECTOR & value)
get a column
Parameters:
col column number
value a vector to store the column
Returns:
reference to value
Definition at line 732 of file RMMEDA.cpp.
References CHECK, mCol, and mRow.
double az::alg::Matrix::Det ()
calculate the determinant of a square matrix
Returns:
the deterministic
Definition at line 760 of file RMMEDA.cpp.
References CHECK, LUdcmp, mCol, and mRow.
Matrix & az::alg::Matrix::Divide (double sca)
divide a scalar
Parameters:
sca scalar
Returns:
reference to the matrix
Definition at line 903 of file RMMEDA.cpp.
Referenced by az::alg::PCA::Train().
void az::alg::Matrix::Eig (FVECTOR & eigvalue, Matrix & eigvector)
calculate the eigenvalue and egienvectors
Parameters:
eigvalue eigenvalue
eigvector eigenvector
Returns:
void
Definition at line 841 of file RMMEDA.cpp.
References CHECK, mCol, mRow, Sort(), tqli(), and tred2().
Referenced by az::alg::PCA::Train().
Matrix & az::alg::Matrix::Identity (unsigned int size)
create an identity matrix
Parameters:
size row and column size
Returns:
reference of the matrix
Definition at line 700 of file RMMEDA.cpp.
References Resize().
Referenced by az::alg::PCA::Initialize().
Matrix & az::alg::Matrix::Inv ()
inverse the matrix
Returns:
reference to the matrix
Definition at line 808 of file RMMEDA.cpp.
References CHECK, LUbksb, LUdcmp, mCol, and mRow.
FVECTOR & az::alg::Matrix::LeftMultiply (FVECTOR & vec, FVECTOR & result)
left multiply a vector
Parameters:
vec vector
result reuslt vector
Returns:
reuslt vector
Definition at line 875 of file RMMEDA.cpp.
References CHECK, and mRow.
Matrix & az::alg::Matrix::Multiply (Matrix & mat, Matrix & result)
multiply a matrix
Parameters:
mat another matrix
result reuslt matrix
Returns:
reuslt matrix
Definition at line 856 of file RMMEDA.cpp.
References CHECK, ColSize(), mCol, Resize(), and RowSize().
Referenced by az::alg::pinv(), and az::alg::PCA::Train().
double* az::alg::Matrix::operator() () [inline]
get the pointer to the data
Returns:
the pointer to the data
Definition at line 300 of file RMMEDA.h.
References pData.
double & az::alg::Matrix::operator() (unsigned int row, unsigned int col)
get an element
Parameters:
row row number
col column number
Returns:
reference to the element
Definition at line 708 of file RMMEDA.cpp.
References CHECK, mCol, mRow, and pData.
Matrix & az::alg::Matrix::operator= (const Matrix & mat)
reset to another matrix
Parameters:
mat matrix reference
Returns:
reference of the matrix
Definition at line 715 of file RMMEDA.cpp.
References mCol, mRow, pData, and Resize().
Matrix & az::alg::Matrix::Resize (unsigned int row, unsigned int col)
reset the matrix size
Parameters:
row row size
col column size
Returns:
reference of the matrix
Definition at line 686 of file RMMEDA.cpp.
References mCol, mRow, and pData.
Referenced by az::alg::Cholesky(), az::alg::CholeskySolve(), Identity(), Multiply(), operator=(), az::alg::operator>>(), Sub(), and az::alg::SVD().
FVECTOR & az::alg::Matrix::RightMultiply (FVECTOR & vec, FVECTOR & result)
right multiply a vector
Parameters:
vec vector
result reuslt vector
Returns:
reuslt vector
Definition at line 889 of file RMMEDA.cpp.
References CHECK, and mCol.
FVECTOR & az::alg::Matrix::Row (unsigned int row, FVECTOR & value)
get a row
Parameters:
row row number
value a vector to store the row
Returns:
reference to value
Definition at line 723 of file RMMEDA.cpp.
References CHECK, mCol, and mRow.
FVECTOR & az::alg::Matrix::RowMean (FVECTOR & mean)
get the mean of all rows
Parameters:
mean the mean vector
Returns:
mean vector
Definition at line 928 of file RMMEDA.cpp.
Referenced by RowStd().
unsigned int az::alg::Matrix::RowSize () [inline]
get the row size
Returns:
row size
Definition at line 292 of file RMMEDA.h.
References mRow.
Referenced by az::alg::Cholesky(), az::alg::CholeskySolve(), az::alg::LUbksb(), az::alg::LUdcmp(), Multiply(), az::alg::operator<<(), Sub(), and az::alg::SVD().
FVECTOR & az::alg::Matrix::RowStd (FVECTOR & std)
get standard variation of all rows
Parameters:
std the std vector
Returns:
std vector
Definition at line 961 of file RMMEDA.cpp.
References RowMean().
Matrix & az::alg::Matrix::RowSub (FVECTOR & value)
subtract a row vector
Parameters:
value row vector
Returns:
reference to the matrix
Definition at line 979 of file RMMEDA.cpp.
void az::alg::Matrix::Sort (FVECTOR & eigenvalue, Matrix & eigenvector) [protected]
sort the eigenvalue by decreasing order
Parameters:
eigenvalue eigenvalue
eigenvector eigenvector
Returns:
void
Definition at line 1259 of file RMMEDA.cpp.
References wxFinite.
Referenced by Eig().
Matrix & az::alg::Matrix::Sub (unsigned int row, unsigned int col, Matrix & mat)
get a sub-matrix except a row and a column
Parameters:
row row number
col column number
mat a matrix to store the sub-matrix
Returns:
sub-matrix
Definition at line 741 of file RMMEDA.cpp.
References CHECK, ColSize(), mCol, mRow, Resize(), and RowSize().
void az::alg::Matrix::tqli (FVECTOR & eigenvalue, FVECTOR & interm, Matrix & eigenvector) [protected]
Tridiagonal QL algorithm -- Implicit.
Parameters:
eigenvalue eigenvalue
interm temporal variable
eigenvector eigenvector
Returns:
void
Definition at line 1192 of file RMMEDA.cpp.
References mRow, SIGN, and wxFinite.
Referenced by Eig().
Matrix & az::alg::Matrix::Trans ()
translate the matrix
Returns:
reference to the matrix
Definition at line 792 of file RMMEDA.cpp.
References mCol, and mRow.
Referenced by az::alg::pinv(), and az::alg::PCA::Train().
void az::alg::Matrix::tred2 (FVECTOR & eigenvalue, FVECTOR & interm, Matrix & eigenvector) [protected]
Householder reduction of Matrix a to tridiagonal form.
Algorithm: Martin et al., Num. Math. 11, 181-195, 1968. Ref: Smith et al., Matrix Eigensystem Routines -- EISPACK Guide Springer-Verlag, 1976, pp. 489-494. W H Press et al., Numerical Recipes in C, Cambridge U P, 1988, pp. 373-374.
Parameters:
eigenvalue eigenvalue
interm temporal variable
eigenvector eigenvector
Returns:
void
Definition at line 1114 of file RMMEDA.cpp.
References h(), and mRow.
Referenced by Eig().
Friends And Related Function Documentation
void LUbksb (Matrix & mat, std::vector< unsigned int > & indx, std::vector< double > & b) [friend]
solve A X = b(Numerical Recipes in C++ pp.50-51)
Parameters:
mat LU docomposition of A
indx input vector that records the row permutation by LUdcmp
b right hand of equation
Returns:
void
Definition at line 1026 of file RMMEDA.cpp.
Referenced by Inv().
void LUdcmp (Matrix & mat, std::vector< unsigned int > & indx, double & d) [friend]
LU decompostion of a rowwise permutation(Numerical Recipes in C++ pp.49-50)
Parameters:
mat input and output matrix
indx output vector that records the row permutation
d +-1 depending on whether the number of row interchanges was even or odd
Returns:
void
Definition at line 1051 of file RMMEDA.cpp.
Referenced by Det(), and Inv().
std::ostream& operator<< (std::ostream & os, Matrix & mat) [friend]
write a matrix
Parameters:
os output stream
mat matrix
Returns:
reference to output stream
Definition at line 1011 of file RMMEDA.cpp.
std::istream& operator>> (std::istream & is, Matrix & mat) [friend]
read a matrix
Parameters:
is input stream
mat matrix
Returns:
reference to input stream
Definition at line 999 of file RMMEDA.cpp.
Member Data Documentation
unsigned int az::alg::Matrix::mCol [protected]
column size
Definition at line 260 of file RMMEDA.h.
Referenced by ColSize(), Column(), Det(), Eig(), Inv(), Matrix(), Multiply(), operator()(), az::alg::operator<<(), operator=(), az::alg::operator>>(), Resize(), RightMultiply(), Row(), Sub(), and Trans().
unsigned int az::alg::Matrix::mRow [protected]
row size
Definition at line 260 of file RMMEDA.h.
Referenced by Column(), Det(), Eig(), Inv(), LeftMultiply(), Matrix(), operator()(), az::alg::operator<<(), operator=(), az::alg::operator>>(), Resize(), Row(), RowSize(), Sub(), tqli(), Trans(), and tred2().
double* az::alg::Matrix::pData [protected]
pointer to the data
Definition at line 262 of file RMMEDA.h.
Referenced by Matrix(), operator()(), operator=(), Resize(), and ~Matrix().
The documentation for this class was generated from the following files:
RMMEDA.h
RMMEDA.cpp