MOO-EALib: az::alg::LocalPCA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
az::alg::LocalPCA Class Reference
Local PCA, partion data into clusters.
#include <RMMEDA.h>
Public Member Functions
void Train ()
train process
Protected Member Functions
double Distance (unsigned int m, unsigned int c)
calculate the distance between data m to cluster c
Protected Attributes
std::vector< std::vector
< std::vector< double > > > mvPI
matrix PI to each cluster
Detailed Description
Local PCA, partion data into clusters.
Definition at line 715 of file RMMEDA.h.
Member Function Documentation
double az::alg::LocalPCA::Distance (unsigned int m, unsigned int c) [protected]
calculate the distance between data m to cluster c
Parameters:
m datat index
c cluster index
Returns:
distance
Definition at line 1553 of file RMMEDA.cpp.
References az::alg::ModelRM::mDX, az::alg::ModelRM::mvMean, mvPI, and az::alg::ModelRM::mvX.
Referenced by Train().
void az::alg::LocalPCA::Train ()
train process
Returns:
void
Definition at line 1437 of file RMMEDA.cpp.
References Distance(), az::alg::ModelRM::Eigen(), az::alg::ModelRM::mDLat, az::alg::ModelRM::mDX, az::alg::ModelRM::mErrTol, az::alg::ModelRM::mIter, az::alg::ModelRM::mMaxIter, az::alg::ModelRM::mNClu, az::alg::ModelRM::mNX, az::alg::ModelRM::mvEigenvalue, az::alg::ModelRM::mvEigenvector, az::alg::ModelRM::mvIndex, az::alg::ModelRM::mvMean, az::alg::ModelRM::mvNo, mvPI, az::alg::ModelRM::mvProMax, az::alg::ModelRM::mvProMin, and az::alg::ModelRM::mvX.
Referenced by az::mea::gen::mod::RM::Generate().
Member Data Documentation
std::vector< std::vector< std::vector<double> > > az::alg::LocalPCA::mvPI [protected]
matrix PI to each cluster
Definition at line 718 of file RMMEDA.h.
Referenced by Distance(), and Train().
The documentation for this class was generated from the following files:
RMMEDA.h
RMMEDA.cpp