MOO-EALib: az::alg::PCA Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
az::alg::PCA Class Reference
PCA class.
#include <RMMEDA.h>
Public Member Functions
PCA ()
constructor
PCA (alg::Matrix &data)
constructor
~PCA ()
destructor
alg::Matrix & Data (alg::Matrix &data)
set data
alg::Matrix & Data ()
get data matrix reference
alg::FVECTOR & Mean ()
get data mean vector
alg::Matrix & Eigenvector ()
get eigenvectors
alg::FVECTOR & Eigenvalue ()
get eigenvalue vector
void Initialize (unsigned int dim)
initialize colvariance matrix to be an identity
void PrimaryRange (unsigned int dim, double &min, double &max)
get the range of the projections in a dimension
void Train ()
calculate the mean, eigenvalue and eigenvectors
void Write (std::ostream &os)
write results into a stream
void Write (std::string &name)
write results into a file
void Write (const char *name)
write results into a file
Protected Attributes
alg::Matrix * pData
data matrix
alg::Matrix mCov
colvariance matrix
alg::Matrix mEigenvector
eigenvectors
alg::FVECTOR mMean
data mean
alg::FVECTOR mEigenvalue
eigenvalue
Friends
std::ostream & operator<< (std::ostream &os, PCA &pca)
write results into a stream
Detailed Description
PCA class.
Warning:
the data must be stored in a column matrix
Definition at line 516 of file RMMEDA.h.
Constructor & Destructor Documentation
az::alg::PCA::PCA ()
constructor
Returns:
void
Definition at line 1305 of file RMMEDA.cpp.
References pData.
az::alg::PCA::PCA (alg::Matrix & data)
constructor
Parameters:
data data matrix
Returns:
void
Definition at line 1311 of file RMMEDA.cpp.
References pData.
az::alg::PCA::~PCA ()
destructor
Returns:
void
Definition at line 1317 of file RMMEDA.cpp.
References pData.
Member Function Documentation
alg::Matrix& az::alg::PCA::Data (alg::Matrix & data) [inline]
set data
Parameters:
data data matrix
Returns:
data matrix reference
Definition at line 541 of file RMMEDA.h.
References pData.
alg::Matrix& az::alg::PCA::Data () [inline]
get data matrix reference
Returns:
data matrix reference
Definition at line 545 of file RMMEDA.h.
References pData.
alg::FVECTOR& az::alg::PCA::Eigenvalue () [inline]
get eigenvalue vector
Returns:
eigenvalue vector
Definition at line 557 of file RMMEDA.h.
References mEigenvalue.
alg::Matrix& az::alg::PCA::Eigenvector () [inline]
get eigenvectors
Returns:
eigenvector matrix
Definition at line 553 of file RMMEDA.h.
References mEigenvector.
void az::alg::PCA::Initialize (unsigned int dim)
initialize colvariance matrix to be an identity
Parameters:
dim data dimension
Returns:
void
Definition at line 1323 of file RMMEDA.cpp.
References az::alg::Matrix::Identity(), mCov, mEigenvalue, and mEigenvector.
alg::FVECTOR& az::alg::PCA::Mean () [inline]
get data mean vector
Returns:
mean vector
Definition at line 549 of file RMMEDA.h.
References mMean.
void az::alg::PCA::PrimaryRange (unsigned int dim, double & min, double & max)
get the range of the projections in a dimension
Parameters:
dim data dimension
min minimum projection
max maximum projection
Returns:
void
Definition at line 1332 of file RMMEDA.cpp.
References mEigenvector, mMean, and pData.
Referenced by Write().
void az::alg::PCA::Train ()
calculate the mean, eigenvalue and eigenvectors
Returns:
void
Definition at line 1347 of file RMMEDA.cpp.
References az::alg::Matrix::ColSub(), az::alg::Matrix::Divide(), az::alg::Matrix::Eig(), mCov, mEigenvalue, mEigenvector, mMean, az::alg::Matrix::Multiply(), and az::alg::Matrix::Trans().
void az::alg::PCA::Write (std::ostream & os)
write results into a stream
Returns:
void
Definition at line 1372 of file RMMEDA.cpp.
References mCov, mEigenvalue, mEigenvector, mMean, and PrimaryRange().
Referenced by az::alg::operator<<(), and Write().
void az::alg::PCA::Write (std::string & name)
write results into a file
Parameters:
name filename
Returns:
void
Definition at line 1402 of file RMMEDA.cpp.
References Write().
void az::alg::PCA::Write (const char * name)
write results into a file
Parameters:
name filename
Returns:
void
Definition at line 1413 of file RMMEDA.cpp.
References Write().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, PCA & pca) [friend]
write results into a stream
Parameters:
os output stream
pca PCA object
Returns:
output stream
Definition at line 1365 of file RMMEDA.cpp.
Member Data Documentation
alg::Matrix az::alg::PCA::mCov [protected]
colvariance matrix
Definition at line 519 of file RMMEDA.h.
Referenced by Initialize(), Train(), and Write().
alg::FVECTOR az::alg::PCA::mEigenvalue [protected]
eigenvalue
Definition at line 522 of file RMMEDA.h.
Referenced by Eigenvalue(), Initialize(), Train(), and Write().
alg::Matrix az::alg::PCA::mEigenvector [protected]
eigenvectors
Definition at line 519 of file RMMEDA.h.
Referenced by Eigenvector(), Initialize(), PrimaryRange(), Train(), and Write().
alg::FVECTOR az::alg::PCA::mMean [protected]
data mean
Definition at line 522 of file RMMEDA.h.
Referenced by Mean(), PrimaryRange(), Train(), and Write().
alg::Matrix* az::alg::PCA::pData [protected]
data matrix
Definition at line 519 of file RMMEDA.h.
Referenced by Data(), PCA(), PrimaryRange(), and ~PCA().
The documentation for this class was generated from the following files:
RMMEDA.h
RMMEDA.cpp