MOO-EALib: az::mea::sel::NDS Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
az::mea::sel::NDS Class Reference
MIDEA.
#include <RMMEDA.h>
Public Member Functions
void Select (unsigned int size, std::vector< std::vector< double > > &of, std::vector< std::vector< double > > &ox, std::vector< std::vector< double > > &pf, std::vector< std::vector< double > > &px)
ND-selector.
void Select (unsigned int size, std::vector< unsigned int > &ids, std::vector< std::vector< double > > &pf, std::vector< std::vector< double > > &px)
ND-selector.
void Select (unsigned int size, unsigned int numberOfObjectives, PopulationMOO &offspring, PopulationMOO &total)
Protected Member Functions
int Dominate (int iA, int iB)
void SortRank ()
double FDen (double dis)
void SortDensity (int iS, int iE)
Protected Attributes
int XDim
int FDim
int NData
int SData
double ** pX
double ** pF
std::vector< int > rankV
std::vector< int > id
Detailed Description
MIDEA.
Definition at line 151 of file RMMEDA.h.
Member Function Documentation
int az::mea::sel::NDS::Dominate (int iA, int iB) [protected]
Definition at line 331 of file RMMEDA.cpp.
References FDim, and pF.
Referenced by SortRank().
double az::mea::sel::NDS::FDen (double dis) [protected]
Definition at line 416 of file RMMEDA.cpp.
void az::mea::sel::NDS::Select (unsigned int size, std::vector< unsigned int > & ids, std::vector< std::vector< double > > & pf, std::vector< std::vector< double > > & px)
ND-selector.
Parameters:
size number of offspring
ids selected id in original order
pf parent objective vectors
px parent decision vectors
Definition at line 566 of file RMMEDA.cpp.
References FDim, NData, pF, pX, rankV, SData, SortDensity(), SortRank(), and XDim.
void az::mea::sel::NDS::Select (unsigned int size, std::vector< std::vector< double > > & of, std::vector< std::vector< double > > & ox, std::vector< std::vector< double > > & pf, std::vector< std::vector< double > > & px)
ND-selector.
Parameters:
size number of offspring
of offspring objective vectors
ox offspring decision vectors
pf parent objective vectors
px parent decision vectors
Definition at line 467 of file RMMEDA.cpp.
References FDim, NData, pF, pX, rankV, SData, SortDensity(), SortRank(), and XDim.
Referenced by Select(), and PopulationMOO::SelectPop().
void az::mea::sel::NDS::Select (unsigned int size, unsigned int numberOfObjectives, PopulationMOO & offspring, PopulationMOO & total)
Definition at line 534 of file RMMEDA.cpp.
References PopulationMOO::resize(), Select(), and PopulationMOO::size().
void az::mea::sel::NDS::SortDensity (int iS, int iE) [protected]
Definition at line 423 of file RMMEDA.cpp.
References FDim, pF, pX, and SData.
Referenced by Select().
void az::mea::sel::NDS::SortRank () [protected]
Definition at line 360 of file RMMEDA.cpp.
References Dominate(), NData, pF, pX, and rankV.
Referenced by Select().
Member Data Documentation
int az::mea::sel::NDS::FDim [protected]
Definition at line 154 of file RMMEDA.h.
Referenced by Dominate(), Select(), and SortDensity().
std::vector<int> az::mea::sel::NDS::id [protected]
Definition at line 161 of file RMMEDA.h.
int az::mea::sel::NDS::NData [protected]
Definition at line 154 of file RMMEDA.h.
Referenced by Select(), and SortRank().
double ** az::mea::sel::NDS::pF [protected]
Definition at line 158 of file RMMEDA.h.
Referenced by Dominate(), Select(), SortDensity(), and SortRank().
double** az::mea::sel::NDS::pX [protected]
Definition at line 158 of file RMMEDA.h.
Referenced by Select(), SortDensity(), and SortRank().
std::vector<int> az::mea::sel::NDS::rankV [protected]
Definition at line 160 of file RMMEDA.h.
Referenced by Select(), and SortRank().
int az::mea::sel::NDS::SData [protected]
Definition at line 154 of file RMMEDA.h.
Referenced by Select(), and SortDensity().
int az::mea::sel::NDS::XDim [protected]
Definition at line 154 of file RMMEDA.h.
Referenced by Select().
The documentation for this class was generated from the following files:
RMMEDA.h
RMMEDA.cpp