MOO-EALib: PopulationMOO Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
PopulationMOO Class Reference
Population of individuals with vector-valued fitness.
#include <PopulationMOO.h>
Public Member Functions
PopulationMOO ()
PopulationMOO (unsigned)
PopulationMOO (const IndividualMOO &)
PopulationMOO (unsigned, const IndividualMOO &)
PopulationMOO (unsigned, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
PopulationMOO (unsigned, const std::vector< Chromosome * > &)
PopulationMOO (const PopulationMOO &)
PopulationMOO (const Population &)
~PopulationMOO ()
unsigned size () const
std::vector< Individual * >
::iterator begin ()
std::vector< Individual * >
::iterator end ()
void resize (unsigned)
IndividualMOO & operator[] (unsigned)
const IndividualMOO & operator[] (unsigned) const
PopulationMOO & operator= (const IndividualMOO &)
PopulationMOO & operator= (const Individual &)
PopulationMOO & operator= (const PopulationMOO &)
PopulationMOO & operator= (const Population &)
bool operator== (const PopulationMOO &) const
void setAscending (bool)
void setSpinOnce (bool)
void replace (unsigned, const Individual &)
void replace (unsigned, const IndividualMOO &)
void replace (unsigned, const Population &)
void replace (unsigned, const PopulationMOO &)
void insert (unsigned, const Individual &)
void insert (unsigned, const IndividualMOO &)
void insert (unsigned, const Population &)
void insert (unsigned, const PopulationMOO &)
void append (const Individual &)
void append (const IndividualMOO &)
void append (const Population &)
void append (const PopulationMOO &)
void remove (unsigned)
void remove (unsigned, unsigned)
void sortIndividuals (std::vector< IndividualMOO * > &)
void sort ()
void shuffle ()
void exchange (Population &)
void exchange (PopulationMOO &)
IndividualMOO & oneOfBest ()
const IndividualMOO & oneOfBest () const
IndividualMOO & best ()
const IndividualMOO & best () const
IndividualMOO & worst ()
const IndividualMOO & worst () const
IndividualMOO & random ()
const IndividualMOO & random () const
IndividualMOO & best (IndividualMOO &, IndividualMOO &) const
IndividualMOO & best (unsigned, unsigned)
IndividualMOO & worst (IndividualMOO &, IndividualMOO &) const
IndividualMOO & worst (unsigned, unsigned)
void getNonDominated (PopulationMOO &nondom, bool unpenalized=false)
fill population nondom with the non-dominated individuals according to either penalized or unpenalized fitness
void setNoOfObj (unsigned)
void setMOOFitness (double)
void setMOORank (unsigned)
void setMOOShare (double)
int Dominate (unsigned i, unsigned j, bool unpenalized=false)
void MOGAFonsecaRank ()
void MOGAGoldbergRank ()
void NSGAIIRank ()
void MOORankToFitness ()
void aggregation (const std::vector< double > &)
void simpleSum ()
void simpleTransferFitness (unsigned)
void selectInit ()
void selectElitists (PopulationMOO &, unsigned)
void selectRouletteWheel (PopulationMOO &, unsigned)
void linearDynamicScaling (std::vector< double > &, unsigned long)
void selectMuLambda (PopulationMOO &, unsigned)
void selectMuLambdaKappa (PopulationMOO &, unsigned, unsigned)
void selectProportional (PopulationMOO &, unsigned)
IndividualMOO & selectOneIndividual ()
void selectTournament (PopulationMOO &, unsigned, unsigned)
void selectEPTournament (PopulationMOO &, unsigned)
void selectLinearRanking (PopulationMOO &, double, unsigned)
void selectLinearRankingWhitley (PopulationMOO &, double, unsigned)
void selectElitistsMOO (PopulationMOO &offspring, unsigned numElitists)
void NormalizeSelectProb ()
void SelectProbMichalewicz (double=0.075)
void printPM ()
double PhenoFitDisN1 (unsigned, unsigned)
double PhenoFitDisN2 (unsigned, unsigned)
double PhenoFitDisNM (unsigned, unsigned)
unsigned NicheCountPFN1 (unsigned, double)
unsigned NicheCountPFN2 (unsigned, double)
unsigned NicheCountPFNM (unsigned, double)
void NicheCountPFN1 (double)
void NicheCountPFN2 (double)
void NicheCountPFNM (double)
double SharingTriPFN1 (unsigned, double)
double SharingTriPFN2 (unsigned, double)
double SharingTriPFNM (unsigned, double)
void SharingTriPFN1 (double)
void SharingTriPFN2 (double)
void SharingTriPFNM (double)
double SharingPowPFN1 (unsigned, double, double)
double SharingPowPFN2 (unsigned, double, double)
double SharingPowPFNM (unsigned, double, double)
void SharingPowPFN1 (double, double)
void SharingPowPFN2 (double, double)
void SharingPowPFNM (double, double)
void SharingSelProb ()
void SharingFitness ()
void SharingMOOFitness ()
void SelectByRoulette (PopulationMOO &, unsigned=0)
void SelectTournamentNCPFN1 (PopulationMOO &, double, unsigned=0)
void SelectTournamentNCPFN2 (PopulationMOO &, double, unsigned=0)
void SelectTournamentNCPFNM (PopulationMOO &, double, unsigned=0)
void SelectTournamentSTPFN1 (PopulationMOO &, double, unsigned=0)
void SelectTournamentSTPFN2 (PopulationMOO &, double, unsigned=0)
void SelectTournamentSTPFNM (PopulationMOO &, double, unsigned=0)
void SelectTournamentSPPFN1 (PopulationMOO &, double, double, unsigned=0)
void SelectTournamentSPPFN2 (PopulationMOO &, double, double, unsigned=0)
void SelectTournamentSPPFNM (PopulationMOO &, double, double, unsigned=0)
void SelectComparisonNCPFN1 (PopulationMOO &, unsigned, double, unsigned=0)
void SelectComparisonNCPFN2 (PopulationMOO &, unsigned, double, unsigned=0)
void SelectComparisonNCPFNM (PopulationMOO &, unsigned, double, unsigned=0)
void SelectComparisonSTPFN1 (PopulationMOO &, unsigned, double, unsigned=0)
void SelectComparisonSTPFN2 (PopulationMOO &, unsigned, double, unsigned=0)
void SelectComparisonSTPFNM (PopulationMOO &, unsigned, double, unsigned=0)
void SelectComparisonSPPFN1 (PopulationMOO &, unsigned, double, double, unsigned=0)
void SelectComparisonSPPFN2 (PopulationMOO &, unsigned, double, double, unsigned=0)
void SelectComparisonSPPFNM (PopulationMOO &, unsigned, double, double, unsigned=0)
bool EvaluationMOOElitists (unsigned)
unsigned getNoOfRankOne ()
unsigned SelectMOOElitists (PopulationMOO &, unsigned, unsigned, double, double=1)
unsigned SelectMOOElitistsSub (PopulationMOO &, unsigned, unsigned, double, double=1)
unsigned SelectMOOElitistsFromRankOne (PopulationMOO &, unsigned, unsigned, double, double=1)
void crowdedTournamentSelection (PopulationMOO &offsprings)
void crowdedDistance (bool UnpenalizedFitness=false)
void crowdingDistance (bool UnpenalizedFitness=false)
void EpsilonMeasure (bool UnpenalizedFitness=false)
void SMeasure (bool UnpenalizedFitness=false)
void SMeasureTwoObjectives (bool UnpenalizedFitness=false)
unsigned maxMOORank ()
unsigned numberOfMOORank (unsigned rank)
void SPEA2Strengthen (ArchiveMOO &archive)
void SPEA2Density (ArchiveMOO &archive)
void SPEA2BinaryTournamentSelection (ArchiveMOO &archive)
double kthDistance (unsigned i, unsigned k)
void SPEA2Sort ()
void environmentalSelection (PopulationMOO &pop, ArchiveMOO &archive)
unsigned SPEA2NoOfNonDominated ()
void selectCrowdedEPTournament (PopulationMOO &offsprings, unsigned q)
void nichedComparisonRank (PopulationMOO &pop, Array< unsigned > &nichedRanks)
PopulationMOO & combinePopulationMOO (PopulationMOO &p1, PopulationMOO &p2)
PopulationMOO & combinePopulationMOO (PopulationMOO &p1, ArchiveMOO &a1)
int checkData (PopulationMOO &offsprings)
void selectCrowdedMuPlusLambda (PopulationMOO &offsprings, bool unpenalized=false)
void selectCrowdedMuCommaLambda (PopulationMOO &offsprings, bool unpenalized=false)
void selectBinaryTournamentMOO (PopulationMOO &offspring)
void SelectPop (std::vector< std::vector< double > > &PopX, std::vector< std::vector< double > > &PopF, std::vector< std::vector< double > > &OffX, std::vector< std::vector< double > > &OffF)
void selectRMMuPlusLambda (PopulationMOO &offspring)
int pvm_pkpop ()
int pvm_upkpop ()
Static Public Member Functions
static bool compareFitnessAscending (Individual *const &pInd1, Individual *const &pInd2)
static bool compareFitnessDescending (Individual *const &pInd1, Individual *const &pInd2)
static bool compareRankShare (Individual *const &pInd1, Individual *const &pInd2)
static bool compareScaledFitnessRankShare (Individual *const &pInd1, Individual *const &pInd2)
Public Attributes
FastNonDominatedSort m_fastNonDominatedSort
CrowdingDistance m_crowdingDistance
IndicatorBasedSelectionStrategy
< AdditiveEpsilonIndicator > m_epsilonMeasure
IndicatorBasedSelectionStrategy
< HypervolumeIndicator > m_sMeasure
Friends
std::ostream & operator<< (std::ostream &os, const PopulationMOO &pop)
std::istream & operator>> (std::istream &is, PopulationMOO &pop)
Detailed Description
Population of individuals with vector-valued fitness.
Examples:
fonMO-CMA.cpp, fonSteadyStateMO-CMA.cpp, MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, NSGA2example.cpp, PAES-SCAT.cpp, PAES.cpp, and realcoded-NSGA2.cpp.
Definition at line 81 of file PopulationMOO.h.
Constructor & Destructor Documentation
PopulationMOO::PopulationMOO ()
Definition at line 83 of file PopulationMOO.cpp.
PopulationMOO::PopulationMOO (unsigned n)
Definition at line 90 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (const IndividualMOO & indmoo)
Definition at line 104 of file PopulationMOO.cpp.
PopulationMOO::PopulationMOO (unsigned n, const IndividualMOO & indmoo)
Definition at line 116 of file PopulationMOO.cpp.
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0)
Definition at line 131 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1)
Definition at line 146 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1, const Chromosome & chrom2)
Definition at line 161 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3)
Definition at line 177 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4)
Definition at line 194 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5)
Definition at line 213 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5, const Chromosome & chrom6)
Definition at line 233 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const Chromosome & chrom0, const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5, const Chromosome & chrom6, const Chromosome & chrom7)
Definition at line 254 of file PopulationMOO.cpp.
References begin().
PopulationMOO::PopulationMOO (unsigned n, const std::vector< Chromosome * > & chrom)
Definition at line 277 of file PopulationMOO.cpp.
PopulationMOO::PopulationMOO (const PopulationMOO & popmoo)
Definition at line 294 of file PopulationMOO.cpp.
References size().
PopulationMOO::PopulationMOO (const Population & pop)
Definition at line 313 of file PopulationMOO.cpp.
References begin().
PopulationMOO::~PopulationMOO ()
Definition at line 331 of file PopulationMOO.cpp.
Member Function Documentation
void PopulationMOO::aggregation (const std::vector< double > & weight)
Definition at line 938 of file IndividualMOO.cpp.
References IndividualMOO::getMOOFitness(), and IndividualMOO::MOOFitness.
void PopulationMOO::append (const IndividualMOO & indmoo)
Definition at line 648 of file PopulationMOO.cpp.
void PopulationMOO::append (const Individual & ind)
Definition at line 640 of file PopulationMOO.cpp.
void PopulationMOO::append (const Population & pop)
Definition at line 656 of file PopulationMOO.cpp.
References insert(), and size().
void PopulationMOO::append (const PopulationMOO & popmoo)
Definition at line 665 of file PopulationMOO.cpp.
References insert(), and size().
vector< Individual * >::iterator PopulationMOO::begin ()
Definition at line 347 of file PopulationMOO.cpp.
Referenced by combinePopulationMOO(), insert(), ArchiveMOO::nonDominatedSolutions(), IndicatorBasedSelectionStrategy< Indicator_T >::operator()(), PopulationMOO(), remove(), replace(), resize(), MOCMASearch::run(), selectCrowdedMuCommaLambda(), and sort().
IndividualMOO & PopulationMOO::best ()
Definition at line 818 of file PopulationMOO.cpp.
Referenced by oneOfBest().
const IndividualMOO & PopulationMOO::best () const
Definition at line 826 of file PopulationMOO.cpp.
IndividualMOO & PopulationMOO::best (IndividualMOO & i1, IndividualMOO & i2) const
Definition at line 866 of file PopulationMOO.cpp.
IndividualMOO & PopulationMOO::best (unsigned i, unsigned j)
Definition at line 882 of file PopulationMOO.cpp.
int PopulationMOO::checkData (PopulationMOO & offsprings)
Definition at line 2199 of file PopulationMOO.cpp.
Referenced by combinePopulationMOO().
PopulationMOO & PopulationMOO::combinePopulationMOO (PopulationMOO & p1, PopulationMOO & p2)
Definition at line 2145 of file PopulationMOO.cpp.
References begin(), checkData(), setAscending(), setNoOfObj(), and size().
Referenced by crowdedTournamentSelection(), nichedComparisonRank(), selectCrowdedEPTournament(), and selectCrowdedMuPlusLambda().
PopulationMOO & PopulationMOO::combinePopulationMOO (PopulationMOO & p1, ArchiveMOO & a1)
Definition at line 2175 of file PopulationMOO.cpp.
References begin(), ArchiveMOO::readArchive(), setAscending(), setNoOfObj(), ArchiveMOO::size(), and size().
bool PopulationMOO::compareFitnessAscending (Individual *const & pInd1, Individual *const & pInd2) [static]
Definition at line 698 of file PopulationMOO.cpp.
Referenced by sort(), and sortIndividuals().
bool PopulationMOO::compareFitnessDescending (Individual *const & pInd1, Individual *const & pInd2) [static]
Definition at line 704 of file PopulationMOO.cpp.
Referenced by sort(), and sortIndividuals().
bool PopulationMOO::compareRankShare (Individual *const & pInd1, Individual *const & pInd2) [static]
Examples:
fonMO-CMA.cpp, and fonSteadyStateMO-CMA.cpp.
Definition at line 1745 of file PopulationMOO.cpp.
References IndividualMOO::getMOORank(), and IndividualMOO::getMOOShare().
Referenced by crowdedTournamentSelection(), IndexComparator::operator()(), MOCMASearch::run(), selectBinaryTournamentMOO(), selectCrowdedMuCommaLambda(), and selectCrowdedMuPlusLambda().
bool PopulationMOO::compareScaledFitnessRankShare (Individual *const & pInd1, Individual *const & pInd2) [static]
Definition at line 2064 of file PopulationMOO.cpp.
References IndividualMOO::getMOORank(), and IndividualMOO::getMOOShare().
Referenced by selectCrowdedEPTournament().
void PopulationMOO::crowdedDistance (bool UnpenalizedFitness = false)
Definition at line 1798 of file PopulationMOO.cpp.
References maxMOORank(), NSGAIIRank(), setMOOShare(), size(), SortMOO_CD::sort(), and sort().
Referenced by crowdedTournamentSelection(), NSGA2Search::init(), selectCrowdedMuCommaLambda(), and selectCrowdedMuPlusLambda().
void PopulationMOO::crowdedTournamentSelection (PopulationMOO & offsprings)
Examples:
NSGA2-SCAT.cpp.
Definition at line 1761 of file PopulationMOO.cpp.
References combinePopulationMOO(), compareRankShare(), crowdedDistance(), size(), and sort().
void PopulationMOO::crowdingDistance (bool UnpenalizedFitness = false)
Definition at line 1784 of file PopulationMOO.cpp.
References CrowdingDistance::m_bUnpenalizedFitness, m_crowdingDistance, and m_fastNonDominatedSort.
int PopulationMOO::Dominate (unsigned i, unsigned j, bool unpenalized = false)
Definition at line 1026 of file PopulationMOO.cpp.
Referenced by FastNonDominatedSort::operator()().
vector< Individual * >::iterator PopulationMOO::end ()
Definition at line 355 of file PopulationMOO.cpp.
Referenced by IndicatorBasedSelectionStrategy< Indicator_T >::operator()(), resize(), MOCMASearch::run(), selectCrowdedMuCommaLambda(), and sort().
void PopulationMOO::environmentalSelection (PopulationMOO & pop, ArchiveMOO & archive)
void PopulationMOO::EpsilonMeasure (bool UnpenalizedFitness = false)
Definition at line 1791 of file PopulationMOO.cpp.
References IndicatorBasedSelectionStrategy< Indicator_T >::m_bUnpenalizedFitness, m_epsilonMeasure, and m_fastNonDominatedSort.
bool PopulationMOO::EvaluationMOOElitists (unsigned)
void PopulationMOO::exchange (PopulationMOO & popmoo)
Definition at line 754 of file PopulationMOO.cpp.
References size().
void PopulationMOO::exchange (Population &)
void PopulationMOO::getNonDominated (PopulationMOO & nondom, bool unpenalized = false)
fill population nondom with the non-dominated individuals according to either penalized or unpenalized fitness
Definition at line 929 of file PopulationMOO.cpp.
References resize(), and size().
Referenced by NSGA2Search::bestSolutions(), MOCMASearch::bestSolutions(), NSGA2Search::bestSolutionsFitness(), and MOCMASearch::bestSolutionsFitness().
unsigned PopulationMOO::getNoOfRankOne ()
void PopulationMOO::insert (unsigned i, const IndividualMOO & indmoo)
Definition at line 606 of file PopulationMOO.cpp.
References begin(), insert(), and size().
void PopulationMOO::insert (unsigned i, const PopulationMOO & popmoo)
Definition at line 627 of file PopulationMOO.cpp.
References begin(), insert(), and size().
void PopulationMOO::insert (unsigned i, const Individual & ind)
Definition at line 597 of file PopulationMOO.cpp.
References begin(), and size().
Referenced by append(), and insert().
void PopulationMOO::insert (unsigned i, const Population & pop)
Definition at line 615 of file PopulationMOO.cpp.
References begin(), insert(), and size().
double PopulationMOO::kthDistance (unsigned i, unsigned k)
void PopulationMOO::linearDynamicScaling (std::vector< double > & window, unsigned long t)
Definition at line 1448 of file PopulationMOO.cpp.
unsigned PopulationMOO::maxMOORank ()
Definition at line 2034 of file PopulationMOO.cpp.
References size().
Referenced by crowdedDistance(), CrowdingDistance::operator()(), IndicatorBasedSelectionStrategy< Indicator_T >::operator()(), and SMeasureTwoObjectives().
void PopulationMOO::MOGAFonsecaRank ()
Examples:
MOGA-SCAT.cpp.
Definition at line 1117 of file PopulationMOO.cpp.
References setMOORank(), and size().
void PopulationMOO::MOGAGoldbergRank ()
Examples:
MOGA-SCAT.cpp.
Definition at line 1142 of file PopulationMOO.cpp.
References setMOORank(), and size().
void PopulationMOO::MOORankToFitness ()
Examples:
MOGA-SCAT.cpp.
Definition at line 1277 of file PopulationMOO.cpp.
References size().
unsigned PopulationMOO::NicheCountPFN1 (unsigned , double)
void PopulationMOO::NicheCountPFN1 (double)
unsigned PopulationMOO::NicheCountPFN2 (unsigned , double)
Examples:
MOGA-SCAT.cpp.
void PopulationMOO::NicheCountPFN2 (double sr)
Definition at line 1650 of file PopulationMOO.cpp.
References PhenoFitDisN2().
unsigned PopulationMOO::NicheCountPFNM (unsigned , double)
void PopulationMOO::NicheCountPFNM (double)
void PopulationMOO::nichedComparisonRank (PopulationMOO & pop, Array< unsigned > & nichedRanks)
Definition at line 2116 of file PopulationMOO.cpp.
References combinePopulationMOO(), resize(), size(), and SortMOO_NCR::sort().
void PopulationMOO::NormalizeSelectProb ()
Definition at line 1577 of file PopulationMOO.cpp.
References size().
Referenced by SelectByRoulette().
void PopulationMOO::NSGAIIRank ()
Definition at line 1192 of file PopulationMOO.cpp.
References setMOORank(), and size().
Referenced by crowdedDistance(), and SMeasureTwoObjectives().
unsigned PopulationMOO::numberOfMOORank (unsigned rank)
Definition at line 2049 of file PopulationMOO.cpp.
References size().
IndividualMOO & PopulationMOO::oneOfBest ()
Definition at line 774 of file PopulationMOO.cpp.
References best(), and size().
const IndividualMOO & PopulationMOO::oneOfBest () const
Definition at line 796 of file PopulationMOO.cpp.
References best(), and size().
PopulationMOO & PopulationMOO::operator= (const PopulationMOO & popmoo)
Definition at line 449 of file PopulationMOO.cpp.
References size().
PopulationMOO & PopulationMOO::operator= (const Population & pop)
Definition at line 472 of file PopulationMOO.cpp.
References size().
PopulationMOO & PopulationMOO::operator= (const Individual & ind)
Definition at line 437 of file PopulationMOO.cpp.
References size().
PopulationMOO & PopulationMOO::operator= (const IndividualMOO & indmoo)
Definition at line 425 of file PopulationMOO.cpp.
References size().
bool PopulationMOO::operator== (const PopulationMOO & popmoo) const
Definition at line 497 of file PopulationMOO.cpp.
References size().
IndividualMOO & PopulationMOO::operator[] (unsigned i)
Definition at line 403 of file PopulationMOO.cpp.
References size().
Referenced by operator[]().
const IndividualMOO & PopulationMOO::operator[] (unsigned i) const
Definition at line 414 of file PopulationMOO.cpp.
References operator[](), and size().
double PopulationMOO::PhenoFitDisN1 (unsigned , unsigned)
double PopulationMOO::PhenoFitDisN2 (unsigned i1, unsigned i2)
Definition at line 1635 of file PopulationMOO.cpp.
Referenced by NicheCountPFN2().
double PopulationMOO::PhenoFitDisNM (unsigned , unsigned)
void PopulationMOO::printPM ()
Definition at line 1621 of file PopulationMOO.cpp.
int PopulationMOO::pvm_pkpop ()
Part of PVM-send routine for MOO-populations
Definition at line 2209 of file PopulationMOO.cpp.
References IndividualMOO::pvm_pkind(), and size().
int PopulationMOO::pvm_upkpop ()
Part of PVM-receive routine for MOO-populations
Definition at line 2235 of file PopulationMOO.cpp.
References IndividualMOO::pvm_upkind(), and size().
IndividualMOO & PopulationMOO::random ()
Definition at line 850 of file PopulationMOO.cpp.
References size().
const IndividualMOO & PopulationMOO::random () const
Definition at line 858 of file PopulationMOO.cpp.
References size().
void PopulationMOO::remove (unsigned i)
Definition at line 673 of file PopulationMOO.cpp.
References begin(), and size().
void PopulationMOO::remove (unsigned i, unsigned k)
Definition at line 683 of file PopulationMOO.cpp.
References begin(), and size().
void PopulationMOO::replace (unsigned i, const Population & pop)
Definition at line 572 of file PopulationMOO.cpp.
References size().
void PopulationMOO::replace (unsigned i, const PopulationMOO & popmoo)
Definition at line 585 of file PopulationMOO.cpp.
References size().
void PopulationMOO::replace (unsigned i, const Individual & ind)
Definition at line 552 of file PopulationMOO.cpp.
References begin(), and size().
void PopulationMOO::replace (unsigned i, const IndividualMOO & indmoo)
Definition at line 562 of file PopulationMOO.cpp.
References begin(), and size().
void PopulationMOO::resize (unsigned n)
Definition at line 363 of file PopulationMOO.cpp.
References begin(), end(), and size().
Referenced by getNonDominated(), nichedComparisonRank(), MOCMASearch::parents(), and az::mea::sel::NDS::Select().
void PopulationMOO::selectBinaryTournamentMOO (PopulationMOO & offspring)
Definition at line 2301 of file PopulationMOO.cpp.
References compareRankShare(), and size().
Referenced by NSGA2Search::run().
void PopulationMOO::SelectByRoulette (PopulationMOO & offsprings, unsigned elit = 0)
Examples:
MOGA-SCAT.cpp.
Definition at line 1692 of file PopulationMOO.cpp.
References NormalizeSelectProb(), selectInit(), and size().
void PopulationMOO::SelectComparisonNCPFN1 (PopulationMOO & , unsigned , double , unsigned = 0)
void PopulationMOO::SelectComparisonNCPFN2 (PopulationMOO & , unsigned , double , unsigned = 0)
void PopulationMOO::SelectComparisonNCPFNM (PopulationMOO & , unsigned , double , unsigned = 0)
void PopulationMOO::SelectComparisonSPPFN1 (PopulationMOO & , unsigned , double , double , unsigned = 0)
void PopulationMOO::SelectComparisonSPPFN2 (PopulationMOO & , unsigned , double , double , unsigned = 0)
void PopulationMOO::SelectComparisonSPPFNM (PopulationMOO & , unsigned , double , double , unsigned = 0)
void PopulationMOO::SelectComparisonSTPFN1 (PopulationMOO & , unsigned , double , unsigned = 0)
void PopulationMOO::SelectComparisonSTPFN2 (PopulationMOO & , unsigned , double , unsigned = 0)
void PopulationMOO::SelectComparisonSTPFNM (PopulationMOO & , unsigned , double , unsigned = 0)
void PopulationMOO::selectCrowdedEPTournament (PopulationMOO & offsprings, unsigned q)
EP-tournament style crowding distance based selection
Definition at line 2080 of file PopulationMOO.cpp.
References combinePopulationMOO(), compareScaledFitnessRankShare(), size(), and sort().
void PopulationMOO::selectCrowdedMuCommaLambda (PopulationMOO & offsprings, bool unpenalized = false)
Definition at line 2283 of file PopulationMOO.cpp.
References begin(), compareRankShare(), crowdedDistance(), end(), size(), and sort().
void PopulationMOO::selectCrowdedMuPlusLambda (PopulationMOO & offsprings, bool unpenalized = false)
Definition at line 2261 of file PopulationMOO.cpp.
References combinePopulationMOO(), compareRankShare(), crowdedDistance(), size(), and sort().
Referenced by NSGA2Search::run().
void PopulationMOO::selectElitists (PopulationMOO & offspring, unsigned numElitists)
Examples:
MOGA-SCAT.cpp.
Definition at line 1358 of file PopulationMOO.cpp.
References size(), and sortIndividuals().
Referenced by selectMuLambda(), and selectProportional().
void PopulationMOO::selectElitistsMOO (PopulationMOO & offspring, unsigned numElitists)
void PopulationMOO::selectEPTournament (PopulationMOO & , unsigned)
void PopulationMOO::selectInit ()
Definition at line 1350 of file PopulationMOO.cpp.
Referenced by SelectByRoulette(), selectMuLambda(), and selectProportional().
void PopulationMOO::selectLinearRanking (PopulationMOO & , double , unsigned)
void PopulationMOO::selectLinearRankingWhitley (PopulationMOO & , double , unsigned)
unsigned PopulationMOO::SelectMOOElitists (PopulationMOO & , unsigned , unsigned , double , double = 1)
unsigned PopulationMOO::SelectMOOElitistsFromRankOne (PopulationMOO & , unsigned , unsigned , double , double = 1)
unsigned PopulationMOO::SelectMOOElitistsSub (PopulationMOO & , unsigned , unsigned , double , double = 1)
void PopulationMOO::selectMuLambda (PopulationMOO & offspring, unsigned numElitists)
Definition at line 1458 of file PopulationMOO.cpp.
References selectElitists(), selectInit(), size(), and sortIndividuals().
void PopulationMOO::selectMuLambdaKappa (PopulationMOO & , unsigned , unsigned)
IndividualMOO & PopulationMOO::selectOneIndividual ()
Definition at line 1533 of file PopulationMOO.cpp.
References size().
void PopulationMOO::SelectPop (std::vector< std::vector< double > > & PopX, std::vector< std::vector< double > > & PopF, std::vector< std::vector< double > > & OffX, std::vector< std::vector< double > > & OffF)
Definition at line 2320 of file PopulationMOO.cpp.
References az::mea::sel::NDS::Select().
Referenced by selectRMMuPlusLambda().
void PopulationMOO::SelectProbMichalewicz (double c = 0.075)
Examples:
MOGA-SCAT.cpp.
Definition at line 1601 of file PopulationMOO.cpp.
References size().
void PopulationMOO::selectProportional (PopulationMOO & popmoo, unsigned numElitists)
Definition at line 1497 of file PopulationMOO.cpp.
References selectElitists(), selectInit(), selectRouletteWheel(), and size().
void PopulationMOO::selectRMMuPlusLambda (PopulationMOO & offspring)
Definition at line 2330 of file PopulationMOO.cpp.
References SelectPop(), setMOOFitness(), and size().
void PopulationMOO::selectRouletteWheel (PopulationMOO & popmoo, unsigned numElitists)
Definition at line 1407 of file PopulationMOO.cpp.
References size().
Referenced by selectProportional().
void PopulationMOO::selectTournament (PopulationMOO & , unsigned , unsigned)
void PopulationMOO::SelectTournamentNCPFN1 (PopulationMOO & , double , unsigned = 0)
void PopulationMOO::SelectTournamentNCPFN2 (PopulationMOO & , double , unsigned = 0)
void PopulationMOO::SelectTournamentNCPFNM (PopulationMOO & , double , unsigned = 0)
void PopulationMOO::SelectTournamentSPPFN1 (PopulationMOO & , double , double , unsigned = 0)
void PopulationMOO::SelectTournamentSPPFN2 (PopulationMOO & , double , double , unsigned = 0)
void PopulationMOO::SelectTournamentSPPFNM (PopulationMOO & , double , double , unsigned = 0)
void PopulationMOO::SelectTournamentSTPFN1 (PopulationMOO & , double , unsigned = 0)
void PopulationMOO::SelectTournamentSTPFN2 (PopulationMOO & , double , unsigned = 0)
void PopulationMOO::SelectTournamentSTPFNM (PopulationMOO & , double , unsigned = 0)
void PopulationMOO::setAscending (bool strategy)
Definition at line 521 of file PopulationMOO.cpp.
Referenced by combinePopulationMOO().
void PopulationMOO::setMOOFitness (double obj)
Definition at line 990 of file PopulationMOO.cpp.
References size().
Referenced by selectRMMuPlusLambda().
void PopulationMOO::setMOORank (unsigned MOOR)
Definition at line 1004 of file PopulationMOO.cpp.
References size().
Referenced by MOGAFonsecaRank(), MOGAGoldbergRank(), NSGAIIRank(), and FastNonDominatedSort::operator()().
void PopulationMOO::setMOOShare (double MOOS)
Definition at line 1015 of file PopulationMOO.cpp.
References size().
Referenced by crowdedDistance(), CrowdingDistance::operator()(), IndicatorBasedSelectionStrategy< Indicator_T >::operator()(), and SMeasureTwoObjectives().
void PopulationMOO::setNoOfObj (unsigned NOO)
Examples:
MOGA-SCAT.cpp, NSGA2-SCAT.cpp, and PAES-SCAT.cpp.
Definition at line 977 of file PopulationMOO.cpp.
References IndicatorBasedSelectionStrategy< Indicator_T >::m_binaryQualityIndicator, HypervolumeIndicator::m_noObjectives, m_sMeasure, and size().
Referenced by combinePopulationMOO(), NSGA2Search::init(), and MOCMASearch::init().
void PopulationMOO::setSpinOnce (bool spin)
Definition at line 537 of file PopulationMOO.cpp.
void PopulationMOO::SharingFitness ()
void PopulationMOO::SharingMOOFitness ()
double PopulationMOO::SharingPowPFN1 (unsigned , double , double)
void PopulationMOO::SharingPowPFN1 (double , double)
void PopulationMOO::SharingPowPFN2 (double , double)
double PopulationMOO::SharingPowPFN2 (unsigned , double , double)
void PopulationMOO::SharingPowPFNM (double , double)
double PopulationMOO::SharingPowPFNM (unsigned , double , double)
void PopulationMOO::SharingSelProb ()
Examples:
MOGA-SCAT.cpp.
Definition at line 1672 of file PopulationMOO.cpp.
References size().
double PopulationMOO::SharingTriPFN1 (unsigned , double)
void PopulationMOO::SharingTriPFN1 (double)
double PopulationMOO::SharingTriPFN2 (unsigned , double)
void PopulationMOO::SharingTriPFN2 (double)
double PopulationMOO::SharingTriPFNM (unsigned , double)
void PopulationMOO::SharingTriPFNM (double)
void PopulationMOO::shuffle ()
Definition at line 744 of file PopulationMOO.cpp.
void PopulationMOO::simpleSum ()
Definition at line 1324 of file PopulationMOO.cpp.
References size().
void PopulationMOO::simpleTransferFitness (unsigned i)
Definition at line 1337 of file PopulationMOO.cpp.
References size().
unsigned PopulationMOO::size () const
Examples:
MOGA-SCAT.cpp, and NSGA2-SCAT.cpp.
Definition at line 338 of file PopulationMOO.cpp.
Referenced by append(), NSGA2Search::bestSolutions(), MOCMASearch::bestSolutions(), NSGA2Search::bestSolutionsFitness(), MOCMASearch::bestSolutionsFitness(), combinePopulationMOO(), crowdedDistance(), crowdedTournamentSelection(), exchange(), az::mea::gen::mod::RM::Generate(), getNonDominated(), insert(), maxMOORank(), MOGAFonsecaRank(), MOGAGoldbergRank(), MOORankToFitness(), nichedComparisonRank(), NormalizeSelectProb(), NSGAIIRank(), numberOfMOORank(), oneOfBest(), CrowdingDistance::operator()(), FastNonDominatedSort::operator()(), IndicatorBasedSelectionStrategy< Indicator_T >::operator()(), operator=(), operator==(), operator[](), PopulationMOO(), pvm_pkpop(), pvm_upkpop(), random(), remove(), replace(), resize(), NSGA2Search::run(), MOCMASearch::run(), az::mea::sel::NDS::Select(), selectBinaryTournamentMOO(), SelectByRoulette(), selectCrowdedEPTournament(), selectCrowdedMuCommaLambda(), selectCrowdedMuPlusLambda(), selectElitists(), selectMuLambda(), selectOneIndividual(), SelectProbMichalewicz(), selectProportional(), selectRMMuPlusLambda(), selectRouletteWheel(), setMOOFitness(), setMOORank(), setMOOShare(), setNoOfObj(), SharingSelProb(), simpleSum(), simpleTransferFitness(), SMeasure(), and SMeasureTwoObjectives().
void PopulationMOO::SMeasure (bool UnpenalizedFitness = false)
Definition at line 1893 of file PopulationMOO.cpp.
References IndicatorBasedSelectionStrategy< Indicator_T >::m_bUnpenalizedFitness, m_fastNonDominatedSort, m_sMeasure, size(), and SMeasureTwoObjectives().
Referenced by MOCMASearch::run().
void PopulationMOO::SMeasureTwoObjectives (bool UnpenalizedFitness = false)
Definition at line 1908 of file PopulationMOO.cpp.
References maxMOORank(), NSGAIIRank(), setMOOShare(), size(), and sort().
Referenced by SMeasure().
void PopulationMOO::sort ()
Definition at line 727 of file PopulationMOO.cpp.
References begin(), compareFitnessAscending(), compareFitnessDescending(), and end().
Referenced by crowdedDistance(), crowdedTournamentSelection(), selectCrowdedEPTournament(), selectCrowdedMuCommaLambda(), selectCrowdedMuPlusLambda(), SMeasureTwoObjectives(), and sortIndividuals().
void PopulationMOO::sortIndividuals (std::vector< IndividualMOO * > & indvec)
Definition at line 711 of file PopulationMOO.cpp.
References compareFitnessAscending(), compareFitnessDescending(), and sort().
Referenced by selectElitists(), and selectMuLambda().
void PopulationMOO::SPEA2BinaryTournamentSelection (ArchiveMOO & archive)
void PopulationMOO::SPEA2Density (ArchiveMOO & archive)
unsigned PopulationMOO::SPEA2NoOfNonDominated ()
void PopulationMOO::SPEA2Sort ()
void PopulationMOO::SPEA2Strengthen (ArchiveMOO & archive)
IndividualMOO & PopulationMOO::worst (IndividualMOO & i1, IndividualMOO & i2) const
Definition at line 898 of file PopulationMOO.cpp.
IndividualMOO & PopulationMOO::worst ()
Definition at line 834 of file PopulationMOO.cpp.
IndividualMOO & PopulationMOO::worst (unsigned i, unsigned j)
Definition at line 914 of file PopulationMOO.cpp.
const IndividualMOO & PopulationMOO::worst () const
Definition at line 842 of file PopulationMOO.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const PopulationMOO & pop) [friend]
Definition at line 587 of file PopulationMOO.h.
std::istream& operator>> (std::istream & is, PopulationMOO & pop) [friend]
Definition at line 599 of file PopulationMOO.h.
Member Data Documentation
CrowdingDistance PopulationMOO::m_crowdingDistance
Definition at line 632 of file PopulationMOO.h.
Referenced by crowdingDistance().
IndicatorBasedSelectionStrategy<AdditiveEpsilonIndicator> PopulationMOO::m_epsilonMeasure
Definition at line 633 of file PopulationMOO.h.
Referenced by EpsilonMeasure().
FastNonDominatedSort PopulationMOO::m_fastNonDominatedSort
Definition at line 631 of file PopulationMOO.h.
Referenced by crowdingDistance(), EpsilonMeasure(), and SMeasure().
IndicatorBasedSelectionStrategy<HypervolumeIndicator> PopulationMOO::m_sMeasure
Definition at line 634 of file PopulationMOO.h.
Referenced by setNoOfObj(), and SMeasure().
The documentation for this class was generated from the following files:
PopulationMOO.h
IndividualMOO.cpp
PopulationMOO.cpp