MOO-EALib: ArchiveMOO Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
ArchiveMOO Class Reference
Archive of candidates for pareto optimality.
#include <ArchiveMOO.h>
Public Member Functions
ArchiveMOO ()
ArchiveMOO (bool strategy)
ArchiveMOO (unsigned max)
ArchiveMOO (unsigned max, bool strategy)
~ArchiveMOO ()
unsigned getMaxArchive ()
void setMaxArchive (unsigned max)
unsigned getCapacity ()
unsigned size ()
bool getStrategy ()
void setStrategy (bool strategy)
void minimize ()
void maximize ()
void addArchive (IndividualMOO &indmoo)
IndividualMOO & readArchive (unsigned i)
void delArchive (unsigned i)
void delArchive (std::vector< unsigned > &v)
void delArchive (Array< unsigned > &a)
void cleanArchive ()
void delSharingWorst ()
void delSharingWorst (double div)
IndividualMOO & readBestArchive ()
void nonDominatedSolutions ()
int Dominate (IndividualMOO &im1, IndividualMOO &im2)
int Dominate (IndividualMOO &im1)
void delDominateArchive (IndividualMOO &im1)
double distanceOnFitness (unsigned i1, unsigned i2)
double distanceOnFitness (IndividualMOO &im1)
Array< double > distanceDataOnFitness ()
unsigned sharingWorst ()
unsigned sharingWorst (double div)
unsigned sharingBest ()
double minDistanceOnFitness ()
double minDistanceOnFitness (unsigned i1)
unsigned crowded (IndividualMOO &im, double div)
void saveArchive (char *filename)
void saveArchiveGPT (char *filename)
Protected Attributes
unsigned MaxArchive
bool Strategy
Detailed Description
Archive of candidates for pareto optimality.
Examples:
MOGA-SCAT.cpp, MOGA.cpp, NSGA2-SCAT.cpp, NSGA2.cpp, NSGA2example.cpp, PAES-SCAT.cpp, PAES.cpp, realcoded-NSGA2.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 86 of file ArchiveMOO.h.
Constructor & Destructor Documentation
ArchiveMOO::ArchiveMOO ()
Definition at line 85 of file ArchiveMOO.cpp.
ArchiveMOO::ArchiveMOO (bool strategy)
Definition at line 89 of file ArchiveMOO.cpp.
References setStrategy().
ArchiveMOO::ArchiveMOO (unsigned max)
Definition at line 95 of file ArchiveMOO.cpp.
References setMaxArchive().
ArchiveMOO::ArchiveMOO (unsigned max, bool strategy)
Definition at line 101 of file ArchiveMOO.cpp.
References setMaxArchive(), and setStrategy().
ArchiveMOO::~ArchiveMOO ()
Definition at line 112 of file ArchiveMOO.cpp.
References size().
Member Function Documentation
void ArchiveMOO::addArchive (IndividualMOO & indmoo)
Examples:
MOGA-SCAT.cpp, NSGA2-SCAT.cpp, PAES-SCAT.cpp, and VEGA-SCAT.cpp.
Definition at line 178 of file ArchiveMOO.cpp.
References getMaxArchive(), and size().
Referenced by nonDominatedSolutions().
void ArchiveMOO::cleanArchive ()
Examples:
MOGA-SCAT.cpp, and VEGA-SCAT.cpp.
Definition at line 253 of file ArchiveMOO.cpp.
References delArchive(), and size().
Referenced by nonDominatedSolutions().
unsigned ArchiveMOO::crowded (IndividualMOO & im, double div)
Examples:
PAES-SCAT.cpp.
Definition at line 876 of file ArchiveMOO.cpp.
References IndividualMOO::getMOOFitness(), IndividualMOO::getNoOfObj(), readArchive(), and size().
void ArchiveMOO::delArchive (unsigned i)
Definition at line 206 of file ArchiveMOO.cpp.
References size().
Referenced by cleanArchive(), delArchive(), delDominateArchive(), and delSharingWorst().
void ArchiveMOO::delArchive (Array< unsigned > & a)
Definition at line 237 of file ArchiveMOO.cpp.
References delArchive(), and size().
void ArchiveMOO::delArchive (std::vector< unsigned > & v)
Definition at line 221 of file ArchiveMOO.cpp.
References delArchive(), and size().
void ArchiveMOO::delDominateArchive (IndividualMOO & im1)
Examples:
MOGA-SCAT.cpp, and PAES-SCAT.cpp.
Definition at line 473 of file ArchiveMOO.cpp.
References delArchive(), Dominate(), readArchive(), and size().
Referenced by nonDominatedSolutions().
void ArchiveMOO::delSharingWorst (double div)
Definition at line 271 of file ArchiveMOO.cpp.
References delArchive(), and sharingWorst().
void ArchiveMOO::delSharingWorst ()
Examples:
MOGA-SCAT.cpp, and PAES-SCAT.cpp.
Definition at line 263 of file ArchiveMOO.cpp.
References delArchive(), and sharingWorst().
Array< double > ArchiveMOO::distanceDataOnFitness ()
Definition at line 547 of file ArchiveMOO.cpp.
References distanceOnFitness(), and size().
Referenced by minDistanceOnFitness(), sharingBest(), and sharingWorst().
double ArchiveMOO::distanceOnFitness (unsigned i1, unsigned i2)
Examples:
MOGA-SCAT.cpp.
Definition at line 493 of file ArchiveMOO.cpp.
References IndividualMOO::getNoOfObj(), readArchive(), and size().
Referenced by distanceDataOnFitness().
double ArchiveMOO::distanceOnFitness (IndividualMOO & im1)
Definition at line 511 of file ArchiveMOO.cpp.
References IndividualMOO::getMOOFitness(), IndividualMOO::getNoOfObj(), readArchive(), and size().
int ArchiveMOO::Dominate (IndividualMOO & im1, IndividualMOO & im2)
Examples:
MOGA-SCAT.cpp, and PAES-SCAT.cpp.
Definition at line 325 of file ArchiveMOO.cpp.
References IndividualMOO::getMOOFitness(), IndividualMOO::getNoOfObj(), getStrategy(), and minimize().
Referenced by delDominateArchive(), Dominate(), and nonDominatedSolutions().
int ArchiveMOO::Dominate (IndividualMOO & im1)
Definition at line 396 of file ArchiveMOO.cpp.
References Dominate(), readArchive(), and size().
unsigned ArchiveMOO::getCapacity ()
Examples:
MOGA-SCAT.cpp, and PAES-SCAT.cpp.
Definition at line 138 of file ArchiveMOO.cpp.
References getMaxArchive(), and size().
unsigned ArchiveMOO::getMaxArchive ()
Examples:
PAES-SCAT.cpp.
Definition at line 126 of file ArchiveMOO.cpp.
References MaxArchive.
Referenced by addArchive(), and getCapacity().
bool ArchiveMOO::getStrategy ()
Definition at line 151 of file ArchiveMOO.cpp.
References Strategy.
Referenced by Dominate().
void ArchiveMOO::maximize ()
Definition at line 169 of file ArchiveMOO.cpp.
References Strategy.
double ArchiveMOO::minDistanceOnFitness ()
Examples:
MOGA-SCAT.cpp.
Definition at line 824 of file ArchiveMOO.cpp.
References distanceDataOnFitness(), and size().
double ArchiveMOO::minDistanceOnFitness (unsigned i1)
Definition at line 851 of file ArchiveMOO.cpp.
References distanceDataOnFitness(), and size().
void ArchiveMOO::minimize ()
Examples:
MOGA-SCAT.cpp, NSGA2-SCAT.cpp, PAES-SCAT.cpp, and VEGA-SCAT.cpp.
Definition at line 163 of file ArchiveMOO.cpp.
References Strategy.
Referenced by Dominate().
void ArchiveMOO::nonDominatedSolutions ()
Examples:
NSGA2-SCAT.cpp, and VEGA-SCAT.cpp.
Definition at line 293 of file ArchiveMOO.cpp.
References addArchive(), PopulationMOO::begin(), cleanArchive(), delDominateArchive(), Dominate(), readArchive(), and size().
IndividualMOO & ArchiveMOO::readArchive (unsigned i)
Examples:
PAES-SCAT.cpp.
Definition at line 193 of file ArchiveMOO.cpp.
References size().
Referenced by aggregationValue(), bosmanDistanceFront(), PopulationMOO::combinePopulationMOO(), crowded(), delDominateArchive(), delta(), distanceOnFitness(), Dominate(), hyperVolumeValue(), minmax(), nonDominatedSolutions(), saveArchive(), saveArchiveGPT(), sharingWorst(), and upsilonDistanceFront().
IndividualMOO & ArchiveMOO::readBestArchive ()
Definition at line 279 of file ArchiveMOO.cpp.
References sharingBest(), and size().
void ArchiveMOO::saveArchive (char * filename)
Examples:
MOGA-SCAT.cpp, NSGA2-SCAT.cpp, PAES-SCAT.cpp, and VEGA-SCAT.cpp.
Definition at line 910 of file ArchiveMOO.cpp.
References IndividualMOO::getMOOFitness(), IndividualMOO::getNoOfObj(), readArchive(), and size().
void ArchiveMOO::saveArchiveGPT (char * filename)
Definition at line 939 of file ArchiveMOO.cpp.
References IndividualMOO::getMOOFitness(), IndividualMOO::getNoOfObj(), readArchive(), and size().
void ArchiveMOO::setMaxArchive (unsigned max)
Definition at line 132 of file ArchiveMOO.cpp.
References MaxArchive.
Referenced by ArchiveMOO().
void ArchiveMOO::setStrategy (bool strategy)
Definition at line 157 of file ArchiveMOO.cpp.
References Strategy.
Referenced by ArchiveMOO().
unsigned ArchiveMOO::sharingBest ()
Definition at line 734 of file ArchiveMOO.cpp.
References distanceDataOnFitness(), and size().
Referenced by readBestArchive().
unsigned ArchiveMOO::sharingWorst ()
Examples:
PAES-SCAT.cpp.
Definition at line 565 of file ArchiveMOO.cpp.
References distanceDataOnFitness(), and size().
Referenced by delSharingWorst().
unsigned ArchiveMOO::sharingWorst (double div)
Definition at line 654 of file ArchiveMOO.cpp.
References IndividualMOO::getMOOFitness(), IndividualMOO::getNoOfObj(), readArchive(), and size().
unsigned ArchiveMOO::size ()
Examples:
MOGA-SCAT.cpp, and PAES-SCAT.cpp.
Definition at line 144 of file ArchiveMOO.cpp.
Referenced by addArchive(), aggregationValue(), bosmanDistanceFront(), cleanArchive(), PopulationMOO::combinePopulationMOO(), crowded(), delArchive(), delDominateArchive(), delta(), distanceDataOnFitness(), distanceOnFitness(), Dominate(), getCapacity(), hyperVolumeValue(), minDistanceOnFitness(), minmax(), nonDominatedSolutions(), readArchive(), readBestArchive(), saveArchive(), saveArchiveGPT(), sharingBest(), sharingWorst(), upsilonDistanceFront(), and ~ArchiveMOO().
Member Data Documentation
unsigned ArchiveMOO::MaxArchive [protected]
Definition at line 203 of file ArchiveMOO.h.
Referenced by getMaxArchive(), and setMaxArchive().
bool ArchiveMOO::Strategy [protected]
Definition at line 204 of file ArchiveMOO.h.
Referenced by getStrategy(), maximize(), minimize(), and setStrategy().
The documentation for this class was generated from the following files:
ArchiveMOO.h
ArchiveMOO.cpp