MOO-EALib: IndicatorBasedSelectionStrategy< Indicator_T > Class Template Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
IndicatorBasedSelectionStrategy< Indicator_T > Class Template Reference
Abstract selection based on binary indicators.
#include <SelectionMOO.h>
Public Member Functions
IndicatorBasedSelectionStrategy (bool unpenalizedFitness=false, bool ascending=true)
void operator() (PopulationMOO &pop)
Public Attributes
bool m_bUnpenalizedFitness
If true, the unpenalized fitness is used for calculation.
bool m_bAscending
If true, a minimization goal is assumed.
Indicator_T m_binaryQualityIndicator
The indicator that is used for the selection of individuals.
Detailed Description
template<typename Indicator_T>
class IndicatorBasedSelectionStrategy< Indicator_T >
Abstract selection based on binary indicators.
This class models the indicator based selection strategy proposed by Zitzler, Brockhoff and Thiele (2007) in
 author = {Eckart Zitzler and Dimo Brockhoff and Lothar Thiele},
 title = {The Hypervolume Indicator Revisited: {O}n The Design of {Pareto}-Compliant Indicators Via Weighted Integration},
 year = {2007},
 booktitle = {Fourth International Conference on Evolutionary Multi-Criterion Optimization (EMO 2007)},
 publisher = {Springer-Verlag},
 volume = 4403,
 series = {LNCS}
Definition at line 243 of file SelectionMOO.h.
Constructor & Destructor Documentation
template<typename Indicator_T> IndicatorBasedSelectionStrategy< Indicator_T >::IndicatorBasedSelectionStrategy (bool unpenalizedFitness = false, bool ascending = true) [inline]
Definition at line 246 of file SelectionMOO.h.
Member Function Documentation
template<typename Indicator_T > void IndicatorBasedSelectionStrategy< Indicator_T >::operator() (PopulationMOO & pop)
Definition at line 47 of file SelectionMOO-Impl.h.
References PopulationMOO::begin(), calc_boundary_elements(), PopulationMOO::end(), PopulationMOO::maxMOORank(), PopulationMOO::setMOOShare(), and PopulationMOO::size().
Member Data Documentation
template<typename Indicator_T> bool IndicatorBasedSelectionStrategy< Indicator_T >::m_bAscending
If true, a minimization goal is assumed.
Otherwise, a maximization goal is assumed.
Definition at line 256 of file SelectionMOO.h.
template<typename Indicator_T> Indicator_T IndicatorBasedSelectionStrategy< Indicator_T >::m_binaryQualityIndicator
The indicator that is used for the selection of individuals.
Definition at line 258 of file SelectionMOO.h.
Referenced by IndicatorBasedSelectionStrategy< HypervolumeIndicator >::IndicatorBasedSelectionStrategy(), and PopulationMOO::setNoOfObj().
template<typename Indicator_T> bool IndicatorBasedSelectionStrategy< Indicator_T >::m_bUnpenalizedFitness
If true, the unpenalized fitness is used for calculation.
Otherwise, the penalized fitness is used.
Definition at line 255 of file SelectionMOO.h.
Referenced by PopulationMOO::EpsilonMeasure(), IndicatorBasedSelectionStrategy< HypervolumeIndicator >::IndicatorBasedSelectionStrategy(), and PopulationMOO::SMeasure().
The documentation for this class was generated from the following files:
SelectionMOO.h
SelectionMOO-Impl.h