MOO-EALib: IndividualMOO Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
IndividualMOO Class Reference
Multi objective version of an individual consisting of chromosomes.
#include <IndividualMOO.h>
Public Member Functions
IndividualMOO ()
IndividualMOO (unsigned)
IndividualMOO (unsigned, const Chromosome &)
IndividualMOO (const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &, const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
IndividualMOO (const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &, const Chromosome &)
IndividualMOO (const std::vector< Chromosome * > &)
IndividualMOO (const Individual &)
IndividualMOO (const IndividualMOO &)
~IndividualMOO ()
unsigned totalSize () const
void setEvalFlg (bool)
void setLearnTime (unsigned lt=0)
unsigned getLearnTime () const
void setNoOfObj (unsigned)
unsigned getNoOfObj () const
void setMOORank (unsigned)
unsigned getMOORank () const
void setMOOShare (double)
double getMOOShare () const
const std::vector< double > & getMOOFitnessValues (bool unpenalized) const
std::vector< double > & getMOOFitnessValues (bool unpenalized)
void setMOOFitness (unsigned, double)
double getMOOFitness (unsigned)
void setMOOFitnessValues (double)
void setMOOFitnessValues (double, double)
void setMOOFitnessValues (double, double, double)
void setMOOFitnessValues (double, double, double, double)
void setMOOFitnessValues (double, double, double, double, double)
void setMOOFitnessValues (double, double, double, double, double, double)
void setMOOFitnessValues (double, double, double, double, double, double, double)
void setMOOFitnessValues (double, double, double, double, double, double, double, double)
void setMOOFitnessValues (std::vector< double > &)
const std::vector< double > & getMOOFitnessValues () const
std::vector< double > & getMOOFitnessValues ()
void initializeMOOFitness (double=0.0)
void setUnpenalizedMOOFitness (unsigned, double)
double getUnpenalizedMOOFitness (unsigned)
void setUnpenalizedMOOFitnessValues (double)
void setUnpenalizedMOOFitnessValues (double, double)
void setUnpenalizedMOOFitnessValues (double, double, double)
void setUnpenalizedMOOFitnessValues (double, double, double, double)
void setUnpenalizedMOOFitnessValues (double, double, double, double, double)
void setUnpenalizedMOOFitnessValues (double, double, double, double, double, double)
void setUnpenalizedMOOFitnessValues (double, double, double, double, double, double, double)
void setUnpenalizedMOOFitnessValues (double, double, double, double, double, double, double, double)
void setUnpenalizedMOOFitnessValues (std::vector< double > &)
const std::vector< double > & getUnpenalizedMOOFitnessValues () const
std::vector< double > & getUnpenalizedMOOFitnessValues ()
void initializeUnpenalizedMOOFitness (double=0.0)
Chromosome & operator[] (unsigned)
const Chromosome & operator[] (unsigned) const
IndividualMOO & operator= (const IndividualMOO &)
bool operator== (const IndividualMOO &) const
IndividualMOO & operator= (const Individual &)
void replace (unsigned, const Chromosome &)
void insert (unsigned, const Chromosome &)
void append (const Chromosome &)
void remove (unsigned)
void remove (unsigned, unsigned)
double aggregation (const std::vector< double > &)
double simplesum ()
void printIM ()
int pvm_pkind ()
int pvm_upkind ()
Protected Attributes
std::vector< double > MOOFitness
std::vector< double > UnpenalizedMOOFitness
unsigned MOORank
double MOOShare
Friends
std::ostream & operator<< (std::ostream &os, const IndividualMOO &ind)
std::istream & operator>> (std::istream &is, IndividualMOO &ind)
Detailed Description
Multi objective version of an individual consisting of chromosomes.
Examples:
fonMO-CMA.cpp, fonSteadyStateMO-CMA.cpp, NSGA2example.cpp, realcoded-NSGA2.cpp, VEGA-SCAT.cpp, and VEGA.cpp.
Definition at line 78 of file IndividualMOO.h.
Constructor & Destructor Documentation
IndividualMOO::IndividualMOO ()
Definition at line 81 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (unsigned n)
Definition at line 93 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (unsigned n, const Chromosome & chrom1)
Definition at line 105 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1)
Definition at line 117 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2)
Definition at line 129 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3)
Definition at line 142 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4)
Definition at line 156 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5)
Definition at line 171 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5, const Chromosome & chrom6)
Definition at line 187 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5, const Chromosome & chrom6, const Chromosome & chrom7)
Definition at line 204 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const Chromosome & chrom1, const Chromosome & chrom2, const Chromosome & chrom3, const Chromosome & chrom4, const Chromosome & chrom5, const Chromosome & chrom6, const Chromosome & chrom7, const Chromosome & chrom8)
Definition at line 222 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const std::vector< Chromosome * > &)
IndividualMOO::IndividualMOO (const Individual & indiv1)
Definition at line 253 of file IndividualMOO.cpp.
References MOOFitness, setMOORank(), setMOOShare(), and UnpenalizedMOOFitness.
IndividualMOO::IndividualMOO (const IndividualMOO & indmoo)
Definition at line 265 of file IndividualMOO.cpp.
References MOOFitness, MOORank, MOOShare, setMOOFitness(), setMOORank(), setMOOShare(), setUnpenalizedMOOFitness(), and UnpenalizedMOOFitness.
IndividualMOO::~IndividualMOO ()
Definition at line 295 of file IndividualMOO.cpp.
Member Function Documentation
double IndividualMOO::aggregation (const std::vector< double > &)
void IndividualMOO::append (const Chromosome & chrom)
Definition at line 913 of file IndividualMOO.cpp.
unsigned IndividualMOO::getLearnTime () const
Definition at line 334 of file IndividualMOO.cpp.
Referenced by operator=().
double IndividualMOO::getMOOFitness (unsigned nof)
Examples:
PAES-SCAT.cpp.
Definition at line 412 of file IndividualMOO.cpp.
References MOOFitness.
Referenced by PopulationMOO::aggregation(), aggregationValue(), bosmanDistanceFront(), cmpDelta(), ArchiveMOO::crowded(), ArchiveMOO::distanceOnFitness(), ArchiveMOO::Dominate(), hyperVolumeValue(), minmax(), ArchiveMOO::saveArchive(), ArchiveMOO::saveArchiveGPT(), ArchiveMOO::sharingWorst(), simplesum(), and upsilonDistanceElement().
const std::vector< double > & IndividualMOO::getMOOFitnessValues (bool unpenalized) const
Definition at line 393 of file IndividualMOO.cpp.
References getMOOFitnessValues(), and getUnpenalizedMOOFitnessValues().
Referenced by LastObjectiveSort::operator()(), and ObjectiveSort::operator()().
vector< double > & IndividualMOO::getMOOFitnessValues ()
Definition at line 549 of file IndividualMOO.cpp.
References MOOFitness.
const vector< double > & IndividualMOO::getMOOFitnessValues () const
Definition at line 545 of file IndividualMOO.cpp.
References MOOFitness.
Referenced by getMOOFitnessValues().
std::vector< double > & IndividualMOO::getMOOFitnessValues (bool unpenalized)
Definition at line 397 of file IndividualMOO.cpp.
References getMOOFitnessValues(), and getUnpenalizedMOOFitnessValues().
unsigned IndividualMOO::getMOORank () const
Definition at line 369 of file IndividualMOO.cpp.
References MOORank.
Referenced by PopulationMOO::compareRankShare(), and PopulationMOO::compareScaledFitnessRankShare().
double IndividualMOO::getMOOShare () const
Definition at line 385 of file IndividualMOO.cpp.
References MOOShare.
Referenced by PopulationMOO::compareRankShare(), and PopulationMOO::compareScaledFitnessRankShare().
unsigned IndividualMOO::getNoOfObj () const
Examples:
PAES-SCAT.cpp.
Definition at line 353 of file IndividualMOO.cpp.
References MOOFitness.
Referenced by ArchiveMOO::crowded(), ArchiveMOO::distanceOnFitness(), ArchiveMOO::Dominate(), operator=(), pvm_pkind(), pvm_upkind(), ArchiveMOO::saveArchive(), ArchiveMOO::saveArchiveGPT(), and ArchiveMOO::sharingWorst().
double IndividualMOO::getUnpenalizedMOOFitness (unsigned nof)
Definition at line 576 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
const vector< double > & IndividualMOO::getUnpenalizedMOOFitnessValues () const
Definition at line 709 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
Referenced by getMOOFitnessValues().
vector< double > & IndividualMOO::getUnpenalizedMOOFitnessValues ()
Definition at line 713 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::initializeMOOFitness (double x = 0.0)
Definition at line 556 of file IndividualMOO.cpp.
References MOOFitness.
Referenced by operator=(), and setNoOfObj().
void IndividualMOO::initializeUnpenalizedMOOFitness (double x = 0.0)
Definition at line 720 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
Referenced by operator=(), and setNoOfObj().
void IndividualMOO::insert (unsigned i, const Chromosome & chrom)
Definition at line 905 of file IndividualMOO.cpp.
IndividualMOO & IndividualMOO::operator= (const IndividualMOO & indmoo)
Definition at line 747 of file IndividualMOO.cpp.
References getLearnTime(), getNoOfObj(), MOOFitness, MOORank, MOOShare, setNoOfObj(), and UnpenalizedMOOFitness.
Referenced by operator=().
IndividualMOO & IndividualMOO::operator= (const Individual & ind)
Definition at line 854 of file IndividualMOO.cpp.
References initializeMOOFitness(), initializeUnpenalizedMOOFitness(), MOORank, MOOShare, operator=(), and setNoOfObj().
bool IndividualMOO::operator== (const IndividualMOO & indmoo) const
Definition at line 798 of file IndividualMOO.cpp.
References MOOFitness, MOORank, MOOShare, and UnpenalizedMOOFitness.
Chromosome & IndividualMOO::operator[] (unsigned i)
Definition at line 731 of file IndividualMOO.cpp.
Referenced by operator[]().
const Chromosome & IndividualMOO::operator[] (unsigned i) const
Definition at line 739 of file IndividualMOO.cpp.
References operator[]().
void IndividualMOO::printIM ()
Definition at line 971 of file IndividualMOO.cpp.
References MOOFitness, MOORank, MOOShare, and UnpenalizedMOOFitness.
int IndividualMOO::pvm_pkind ()
Part of PVM-send routine for MOO-individuals
Definition at line 1014 of file IndividualMOO.cpp.
References getNoOfObj(), MOOFitness, MOORank, MOOShare, and UnpenalizedMOOFitness.
Referenced by PopulationMOO::pvm_pkpop().
int IndividualMOO::pvm_upkind ()
Part of PVM-receive routine for MOO-individuals
Definition at line 1061 of file IndividualMOO.cpp.
References getNoOfObj(), MOOFitness, MOORank, MOOShare, setNoOfObj(), and UnpenalizedMOOFitness.
Referenced by PopulationMOO::pvm_upkpop().
void IndividualMOO::remove (unsigned i)
Definition at line 922 of file IndividualMOO.cpp.
Referenced by remove().
void IndividualMOO::remove (unsigned i, unsigned j)
Definition at line 930 of file IndividualMOO.cpp.
References remove().
void IndividualMOO::replace (unsigned i, const Chromosome & chrom)
Definition at line 897 of file IndividualMOO.cpp.
void IndividualMOO::setEvalFlg (bool flg)
Definition at line 310 of file IndividualMOO.cpp.
void IndividualMOO::setLearnTime (unsigned lt = 0)
Definition at line 326 of file IndividualMOO.cpp.
void IndividualMOO::setMOOFitness (unsigned nof, double fit)
Definition at line 403 of file IndividualMOO.cpp.
References MOOFitness.
Referenced by IndividualMOO().
void IndividualMOO::setMOOFitnessValues (double f0, double f1)
Definition at line 430 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (double f0, double f1, double f2)
Definition at line 440 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (double f0, double f1, double f2, double f3, double f4, double f5, double f6, double f7)
Definition at line 514 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (double f0, double f1, double f2, double f3, double f4)
Definition at line 465 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (double f0, double f1, double f2, double f3, double f4, double f5)
Definition at line 480 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (double f0, double f1, double f2, double f3)
Definition at line 452 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (double f0, double f1, double f2, double f3, double f4, double f5, double f6)
Definition at line 496 of file IndividualMOO.cpp.
References MOOFitness.
void IndividualMOO::setMOOFitnessValues (std::vector< double > &)
void IndividualMOO::setMOOFitnessValues (double f0)
Examples:
fonMO-CMA.cpp, fonSteadyStateMO-CMA.cpp, NSGA2example.cpp, realcoded-NSGA2.cpp, and VEGA-SCAT.cpp.
Definition at line 421 of file IndividualMOO.cpp.
References MOOFitness.
Referenced by NSGA2Search::eval(), and MOCMASearch::eval().
void IndividualMOO::setMOORank (unsigned n)
Definition at line 361 of file IndividualMOO.cpp.
References MOORank.
Referenced by IndividualMOO().
void IndividualMOO::setMOOShare (double n)
Definition at line 377 of file IndividualMOO.cpp.
References MOOShare.
Referenced by IndividualMOO().
void IndividualMOO::setNoOfObj (unsigned n)
Examples:
VEGA-SCAT.cpp.
Definition at line 342 of file IndividualMOO.cpp.
References initializeMOOFitness(), initializeUnpenalizedMOOFitness(), MOOFitness, and UnpenalizedMOOFitness.
Referenced by operator=(), and pvm_upkind().
void IndividualMOO::setUnpenalizedMOOFitness (unsigned nof, double fit)
Definition at line 567 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
Referenced by IndividualMOO().
void IndividualMOO::setUnpenalizedMOOFitnessValues (std::vector< double > &)
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1)
Definition at line 594 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1, double f2, double f3, double f4, double f5, double f6, double f7)
Definition at line 678 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1, double f2, double f3)
Definition at line 616 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1, double f2, double f3, double f4, double f5, double f6)
Definition at line 660 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0)
Definition at line 585 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
Referenced by MOCMASearch::eval().
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1, double f2, double f3, double f4, double f5)
Definition at line 644 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1, double f2, double f3, double f4)
Definition at line 629 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
void IndividualMOO::setUnpenalizedMOOFitnessValues (double f0, double f1, double f2)
Definition at line 604 of file IndividualMOO.cpp.
References UnpenalizedMOOFitness.
double IndividualMOO::simplesum ()
Definition at line 957 of file IndividualMOO.cpp.
References getMOOFitness(), and MOOFitness.
unsigned IndividualMOO::totalSize () const
Definition at line 302 of file IndividualMOO.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const IndividualMOO & ind) [friend]
Definition at line 325 of file IndividualMOO.h.
std::istream& operator>> (std::istream & is, IndividualMOO & ind) [friend]
Definition at line 361 of file IndividualMOO.h.
Member Data Documentation
std::vector< double > IndividualMOO::MOOFitness [protected]
Definition at line 425 of file IndividualMOO.h.
Referenced by PopulationMOO::aggregation(), getMOOFitness(), getMOOFitnessValues(), getNoOfObj(), IndividualMOO(), initializeMOOFitness(), operator=(), operator==(), printIM(), pvm_pkind(), pvm_upkind(), setMOOFitness(), setMOOFitnessValues(), setNoOfObj(), and simplesum().
unsigned IndividualMOO::MOORank [protected]
Definition at line 427 of file IndividualMOO.h.
Referenced by getMOORank(), IndividualMOO(), operator=(), operator==(), printIM(), pvm_pkind(), pvm_upkind(), and setMOORank().
double IndividualMOO::MOOShare [protected]
Definition at line 428 of file IndividualMOO.h.
Referenced by getMOOShare(), IndividualMOO(), operator=(), operator==(), printIM(), pvm_pkind(), pvm_upkind(), and setMOOShare().
std::vector< double > IndividualMOO::UnpenalizedMOOFitness [protected]
Definition at line 426 of file IndividualMOO.h.
Referenced by getUnpenalizedMOOFitness(), getUnpenalizedMOOFitnessValues(), IndividualMOO(), initializeUnpenalizedMOOFitness(), operator=(), operator==(), printIM(), pvm_pkind(), pvm_upkind(), setNoOfObj(), setUnpenalizedMOOFitness(), and setUnpenalizedMOOFitnessValues().
The documentation for this class was generated from the following files:
IndividualMOO.h
IndividualMOO.cpp