MOO-EALib: MOCMASearch Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
MOCMASearch Class Reference
CMA-ES for multi-objective optimization.
#include <MO-CMA.h>
Public Member Functions
MOCMASearch ()
~MOCMASearch ()
void init (ObjectiveFunctionVS< double > &fitness, unsigned int mu, unsigned int lambda)
void init (ObjectiveFunctionVS< double > &fitness, double stepsize, unsigned int mu, unsigned int lambda)
void run ()
void bestSolutions (std::vector< double * > &points)
void bestSolutionsFitness (Array< double > &fitness)
double penaltyFactor () const
void setPenaltyFactor (double factor)
void parents (PopulationMOO &parents) const
Protected Member Functions
void eval (IndividualMOO &ind)
Protected Attributes
ObjectiveFunctionVS< double > * m_fitness
unsigned int m_objectives
PopulationMOO * m_pop
double m_penaltyFactor
Detailed Description
CMA-ES for multi-objective optimization.
Definition at line 46 of file MO-CMA.h.
Constructor & Destructor Documentation
MOCMASearch::MOCMASearch ()
Definition at line 53 of file MO-CMA.cpp.
References m_penaltyFactor, and m_pop.
MOCMASearch::~MOCMASearch ()
Definition at line 59 of file MO-CMA.cpp.
References m_pop.
Member Function Documentation
void MOCMASearch::bestSolutions (std::vector< double * > & points)
Definition at line 239 of file MO-CMA.cpp.
References PopulationMOO::getNonDominated(), m_pop, and PopulationMOO::size().
void MOCMASearch::bestSolutionsFitness (Array< double > & fitness)
Definition at line 249 of file MO-CMA.cpp.
References PopulationMOO::getNonDominated(), m_objectives, m_pop, and PopulationMOO::size().
void MOCMASearch::eval (IndividualMOO & ind) [protected]
Definition at line 272 of file MO-CMA.cpp.
References m_fitness, m_objectives, m_penaltyFactor, IndividualMOO::setMOOFitnessValues(), and IndividualMOO::setUnpenalizedMOOFitnessValues().
Referenced by init(), and run().
void MOCMASearch::init (ObjectiveFunctionVS< double > & fitness, double stepsize, unsigned int mu, unsigned int lambda)
Definition at line 142 of file MO-CMA.cpp.
References eval(), m_fitness, m_objectives, m_pop, and PopulationMOO::setNoOfObj().
void MOCMASearch::init (ObjectiveFunctionVS< double > & fitness, unsigned int mu, unsigned int lambda)
Definition at line 65 of file MO-CMA.cpp.
References eval(), m_fitness, m_objectives, m_pop, norm(), and PopulationMOO::setNoOfObj().
void MOCMASearch::parents (PopulationMOO & parents) const
Definition at line 263 of file MO-CMA.cpp.
References m_pop, and PopulationMOO::resize().
double MOCMASearch::penaltyFactor () const [inline]
Definition at line 58 of file MO-CMA.h.
References m_penaltyFactor.
void MOCMASearch::run ()
Definition at line 173 of file MO-CMA.cpp.
References PopulationMOO::begin(), PopulationMOO::compareRankShare(), PopulationMOO::end(), eval(), m_fitness, m_pop, PopulationMOO::size(), and PopulationMOO::SMeasure().
void MOCMASearch::setPenaltyFactor (double factor) [inline]
Definition at line 59 of file MO-CMA.h.
References m_penaltyFactor.
Member Data Documentation
ObjectiveFunctionVS<double>* MOCMASearch::m_fitness [protected]
Definition at line 66 of file MO-CMA.h.
Referenced by eval(), init(), and run().
unsigned int MOCMASearch::m_objectives [protected]
Definition at line 67 of file MO-CMA.h.
Referenced by bestSolutionsFitness(), eval(), and init().
double MOCMASearch::m_penaltyFactor [protected]
Definition at line 69 of file MO-CMA.h.
Referenced by eval(), MOCMASearch(), penaltyFactor(), and setPenaltyFactor().
PopulationMOO* MOCMASearch::m_pop [protected]
Definition at line 68 of file MO-CMA.h.
Referenced by bestSolutions(), bestSolutionsFitness(), init(), MOCMASearch(), parents(), run(), and ~MOCMASearch().
The documentation for this class was generated from the following files:
MO-CMA.h
MO-CMA.cpp