MOO-EALib: az::mea::gen::mod::RM Class Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
az::mea::gen::mod::RM Class Reference
Local PCA based EDA generator.
#include <RMMEDA.h>
Public Member Functions
RM ()
constructor
~RM ()
destructor
void Generate (unsigned int latent, unsigned int cluster, unsigned int trainsteps, double extension, Array< double > &xlow, Array< double > &xupp, unsigned int sizenew, PopulationMOO &popnew, PopulationMOO &popref)
Generator.
void Generate (unsigned int latent, unsigned int cluster, unsigned int trainsteps, double extension, std::vector< double > &xlow, std::vector< double > &xupp, unsigned int sizenew, std::vector< std::vector< double > > &popnew, std::vector< std::vector< double > > &popref)
Protected Member Functions
void Clear ()
clear data pool
Protected Attributes
double ** pData
pointer to data
double mExtension
Principal Curve(Surface) extension ratio.
unsigned int mDataSize
data number
unsigned int mDataDim
data dimension
unsigned int mTrainSteps
inner train steps
unsigned int mLatentDim
latent dimension
unsigned int mMaxCluster
maximum cluster number
Detailed Description
Local PCA based EDA generator.
Definition at line 63 of file RMMEDA.h.
Constructor & Destructor Documentation
az::mea::gen::mod::RM::RM ()
constructor
Returns:
void
Definition at line 103 of file RMMEDA.cpp.
References mDataDim, mDataSize, mExtension, mLatentDim, mMaxCluster, and pData.
az::mea::gen::mod::RM::~RM ()
destructor
Returns:
void
Definition at line 112 of file RMMEDA.cpp.
References Clear().
Member Function Documentation
void az::mea::gen::mod::RM::Clear () [protected]
clear data pool
Returns:
void
Definition at line 118 of file RMMEDA.cpp.
References mDataSize, and pData.
Referenced by Generate(), and ~RM().
void az::mea::gen::mod::RM::Generate (unsigned int latent, unsigned int cluster, unsigned int trainsteps, double extension, std::vector< double > & xlow, std::vector< double > & xupp, unsigned int sizenew, std::vector< std::vector< double > > & popnew, std::vector< std::vector< double > > & popref)
Definition at line 174 of file RMMEDA.cpp.
References Clear(), az::alg::LHC(), mDataDim, mDataSize, mExtension, mLatentDim, mMaxCluster, mTrainSteps, az::alg::ModelRM::mvEigenvalue, az::alg::ModelRM::mvEigenvector, az::alg::ModelRM::mvIndex, az::alg::ModelRM::mvMean, az::alg::ModelRM::mvNo, az::alg::ModelRM::mvProMax, az::alg::ModelRM::mvProMin, az::alg::ModelRM::mvX, pData, az::alg::ModelRM::Set(), az::alg::LocalPCA::Train(), and wxFinite.
void az::mea::gen::mod::RM::Generate (unsigned int latent, unsigned int cluster, unsigned int trainsteps, double extension, Array< double > & xlow, Array< double > & xupp, unsigned int sizenew, PopulationMOO & popnew, PopulationMOO & popref)
Generator.
Parameters:
latent latent dimension
cluster maximum cluster number
trainsteps Local PCA train steps
extension extension ratio
sizenew number of new trial solutions
popnew offspring population
popref reference population(current population)
Returns:
void
Definition at line 131 of file RMMEDA.cpp.
References PopulationMOO::size().
Member Data Documentation
unsigned int az::mea::gen::mod::RM::mDataDim [protected]
data dimension
Definition at line 68 of file RMMEDA.h.
Referenced by Generate(), and RM().
unsigned int az::mea::gen::mod::RM::mDataSize [protected]
data number
Definition at line 68 of file RMMEDA.h.
Referenced by Clear(), Generate(), and RM().
double az::mea::gen::mod::RM::mExtension [protected]
Principal Curve(Surface) extension ratio.
Definition at line 66 of file RMMEDA.h.
Referenced by Generate(), and RM().
unsigned int az::mea::gen::mod::RM::mLatentDim [protected]
latent dimension
Definition at line 68 of file RMMEDA.h.
Referenced by Generate(), and RM().
unsigned int az::mea::gen::mod::RM::mMaxCluster [protected]
maximum cluster number
Definition at line 68 of file RMMEDA.h.
Referenced by Generate(), and RM().
unsigned int az::mea::gen::mod::RM::mTrainSteps [protected]
inner train steps
Definition at line 68 of file RMMEDA.h.
Referenced by Generate().
double** az::mea::gen::mod::RM::pData [protected]
pointer to data
Definition at line 66 of file RMMEDA.h.
Referenced by Clear(), Generate(), and RM().
The documentation for this class was generated from the following files:
RMMEDA.h
RMMEDA.cpp