MOO-EALib: az::alg Namespace Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
az::alg Namespace Reference
alg namespace, contains algorithms
Classes
class error
error process for DATA namespace
class Matrix
Matrix class.
class PCA
PCA class.
class ModelRM
Model structure, used to store data.
class LocalPCA
Local PCA, partion data into clusters.
Typedefs
typedef std::vector< double > FVECTOR
real vector
typedef std::list< unsigned int > LINDEX
index structure based on list
typedef std::vector< unsigned int > VINDEX
index structure based on vector
Functions
void LHC (std::vector< std::vector< double > > &rand, std::vector< double > &low, std::vector< double > &upp)
void Uniform (std::vector< std::vector< double > > &rand, std::vector< double > &low, std::vector< double > &upp)
std::istream & operator>> (std::istream &is, Matrix &mat)
std::ostream & operator<< (std::ostream &os, Matrix &mat)
void LUbksb (Matrix &mat, std::vector< unsigned int > &indx, std::vector< double > &b)
void LUdcmp (Matrix &mat, std::vector< unsigned int > &indx, double &d)
std::ostream & operator<< (std::ostream &os, PCA &pca)
void Eigen (std::vector< double > &eva, std::vector< std::vector< double > > &eve, unsigned int no, std::vector< std::vector< double > > &cov)
calcualte the eigenvalues and eigenvectors of a covariance matrix
bool Cholesky (Matrix &L, Matrix &A1)
cholesky factorization of A1: L*L'
bool CholeskySolve (Matrix &X, Matrix &A1, Matrix &B)
Solve a linear system A1*X=B, using cholesky factorization of A1: L*L'.
double hypot (const double &a, const double &b)
void SVD (Matrix &U, Matrix &S, Matrix &V, Matrix &A)
For an m-by-n matrix A with m >= n, so that A = U*S*V'.
void pinv (Matrix &inA, Matrix &A)
find Pseudo inverse matrix by SVD
Detailed Description
alg namespace, contains algorithms
Typedef Documentation
typedef std::vector<double> az::alg::FVECTOR
real vector
Definition at line 248 of file RMMEDA.h.
typedef std::list< unsigned int > az::alg::LINDEX
index structure based on list
Definition at line 251 of file RMMEDA.h.
typedef std::vector< unsigned int > az::alg::VINDEX
index structure based on vector
Definition at line 254 of file RMMEDA.h.
Function Documentation
bool az::alg::Cholesky (Matrix & L, Matrix & A)
cholesky factorization of A1: L*L'
linear algebra functions
cholesky factorization of A: L*L'
Parameters:
L factorization matrix(output)
A a square matrix(input)
Returns:
success or not
Definition at line 1753 of file RMMEDA.cpp.
References az::alg::Matrix::ColSize(), az::alg::Matrix::Resize(), and az::alg::Matrix::RowSize().
Referenced by CholeskySolve().
bool az::alg::CholeskySolve (Matrix & X, Matrix & A, Matrix & B)
Solve a linear system A1*X=B, using cholesky factorization of A1: L*L'.
Solve a linear system A*X = B, using cholesky factorization of A: L*L'.
Parameters:
X a matrix so that L*L'*X = B(output)
A a square matrix(input)
B righthand matrix(input)
Returns:
success or not
Definition at line 1787 of file RMMEDA.cpp.
References Cholesky(), az::alg::Matrix::ColSize(), az::alg::Matrix::Resize(), and az::alg::Matrix::RowSize().
void az::alg::Eigen (std::vector< double > & eva, std::vector< std::vector< double > > & eve, unsigned int no, std::vector< std::vector< double > > & cov)
calcualte the eigenvalues and eigenvectors of a covariance matrix
Parameters:
eva sorted eigenvalues
eve sorted eigenvectors
no the main no-eigens are stored
cov the covariance matrix
Returns:
void
Definition at line 1691 of file RMMEDA.cpp.
double az::alg::hypot (const double & a, const double & b)
Definition at line 1826 of file RMMEDA.cpp.
Referenced by SVD().
void az::alg::LHC (std::vector< std::vector< double > > & rand, std::vector< double > & low, std::vector< double > & upp)
Definition at line 68 of file RMMEDA.cpp.
Referenced by az::mea::gen::mod::RM::Generate().
void az::alg::LUbksb (Matrix & mat, std::vector< unsigned int > & indx, std::vector< double > & b)
Parameters:
mat LU docomposition of A
indx input vector that records the row permutation by LUdcmp
b right hand of equation
Returns:
void
Definition at line 1026 of file RMMEDA.cpp.
References az::alg::Matrix::RowSize().
void az::alg::LUdcmp (Matrix & mat, std::vector< unsigned int > & indx, double & d)
Parameters:
mat input and output matrix
indx output vector that records the row permutation
d +-1 depending on whether the number of row interchanges was even or odd
Returns:
void
Definition at line 1051 of file RMMEDA.cpp.
References az::alg::Matrix::RowSize().
std::ostream& az::alg::operator<< (std::ostream & os, Matrix & mat)
Parameters:
os output stream
mat matrix
Returns:
reference to output stream
Definition at line 1011 of file RMMEDA.cpp.
References az::alg::Matrix::ColSize(), az::alg::Matrix::mCol, az::alg::Matrix::mRow, and az::alg::Matrix::RowSize().
std::ostream& az::alg::operator<< (std::ostream & os, PCA & pca)
Parameters:
os output stream
pca PCA object
Returns:
output stream
Definition at line 1365 of file RMMEDA.cpp.
References az::alg::PCA::Write().
std::istream& az::alg::operator>> (std::istream & is, Matrix & mat)
Parameters:
is input stream
mat matrix
Returns:
reference to input stream
Definition at line 999 of file RMMEDA.cpp.
References az::alg::Matrix::mCol, az::alg::Matrix::mRow, and az::alg::Matrix::Resize().
void az::alg::pinv (Matrix & inA, Matrix & A)
find Pseudo inverse matrix by SVD
Parameters:
inA inverse A(output)
A m-by-n matrix(input)
no
Definition at line 2323 of file RMMEDA.cpp.
References az::alg::Matrix::ColSize(), az::alg::Matrix::Multiply(), SVD(), and az::alg::Matrix::Trans().
void az::alg::SVD (Matrix & U, Matrix & S, Matrix & V, Matrix & A)
For an m-by-n matrix A with m >= n, so that A = U*S*V'.
Parameters:
U m-by-n orthogonal matrix(output)
S n-by-n diagonal matrix(output)
V n-by-n orthogonal matrix V(output)
A m-by-n matrix(input)
no
Definition at line 1838 of file RMMEDA.cpp.
References az::alg::Matrix::ColSize(), hypot(), MAX, MIN, az::alg::Matrix::Resize(), and az::alg::Matrix::RowSize().
Referenced by pinv().
void az::alg::Uniform (std::vector< std::vector< double > > & rand, std::vector< double > & low, std::vector< double > & upp)
Definition at line 78 of file RMMEDA.cpp.