MOO-EALib: FastNonDominatedSort Struct Reference
Shark Machine Learning Library
About Shark
Sourceforge
Project Summary
Downloads
Subversion Repository
Getting Started
Tutorials
FAQ
Main Modules
ReClaM
EALib
MOO-EALib
Fuzzy
Tools
Mixture
Array
Rng
LinAlg
FileUtil
FastNonDominatedSort Struct Reference
Level of non-dominance.
#include <SelectionMOO.h>
Public Member Functions
FastNonDominatedSort (bool unpenalizedFitness=false)
void operator() (PopulationMOO &pop)
Public Attributes
bool m_bUnpenalizedFitness
Detailed Description
Level of non-dominance.
Calculates the level of non-dominance of each member of the population pop.
Definition at line 88 of file SelectionMOO.h.
Constructor & Destructor Documentation
FastNonDominatedSort::FastNonDominatedSort (bool unpenalizedFitness = false) [inline]
Definition at line 90 of file SelectionMOO.h.
Member Function Documentation
void FastNonDominatedSort::operator() (PopulationMOO & pop)
Definition at line 69 of file SelectionMOO.cpp.
References PopulationMOO::Dominate(), h(), m_bUnpenalizedFitness, PopulationMOO::setMOORank(), and PopulationMOO::size().
Member Data Documentation
bool FastNonDominatedSort::m_bUnpenalizedFitness
Definition at line 96 of file SelectionMOO.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
SelectionMOO.h
SelectionMOO.cpp